unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/HCP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HCP_Contact__c</fullName>
    <label>HCP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HCP&#39;s Study Sites</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>HCP Status per clinical trial by PI</description>
    <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
    <label>HCP Status</label>

    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>On Hold (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending Orientation</fullName>
            </value>
            <value>
                <fullName>Declined (Approval)</fullName>
            </value>
            <value>
                <fullName>On Hold (Approval)</fullName>
            </value>
            <value>
                <fullName>Declined (Activation)</fullName>
            </value>
            <value>
                <fullName>On Hold (Activation)</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Activated (Admin)</fullName>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
            </value>
            <value>
                <fullName>Declined (Admin)</fullName>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hospital of rainbow</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Referring HCPs</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Healthcare_Provider__c/Healthcare_Provider__c.object-meta.xml
<CustomObject>
    <label>Healthcare Provider</label>
    <nameField>
        <displayFormat>PROVIDERID{00000}</displayFormat>
        <label>Healthcare Provider Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Healthcare Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Healthcare_Provider__c/fields/HCP_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>HCP_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HCP Enrollment</label>
    <referenceTo>HCP_Enrollment__c</referenceTo>
    <relationshipLabel>Healthcare Providers</relationshipLabel>
    <relationshipName>Healthcare_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Healthcare_Provider__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>No Sharing</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/providers/classes/EmailTemplateInitialHCP.cls
/**
 * Created by Igor Malyuta on 31.03.2020.
 */
public with sharing class EmailTemplateInitialHCP extends EmailTemplateInitialAbstract{

    private List<HCP_Enrollment__c> enrollments;

    public EmailTemplateInitialHCP(Map<String, String> templateLabels, Id recipientId, String outputMode) {
        super(templateLabels, recipientId, outputMode, null);
        headerLabel = LABEL_HEADER_INITIAL_HCP;
        greetingLabel = LABEL_GREETING_VALUE_PI_HCP;
        bodyLabel = LABEL_BODY_INITIAL_HCP;

        if (!getHealthCareProviders().isEmpty()) {
            bodyLabel = LABEL_BODY_INITIAL_PI_PT_HCP;
            headerLabel = LABEL_HEADER_INITIAL_PI_PT_HCP;
        } else if (hasEnrollments()) {
            bodyLabel = LABEL_BODY_INITIAL_PI_HCP;
            headerLabel = LABEL_HEADER_INITIAL_PI_HCP;
        }

//        if (isSameInvestigator()) parameters.put('PIName', getMultiplePINames(recipientId));
    }

    private List<Healthcare_Provider__c> getHealthCareProviders() {
            return [
                    SELECT Id, HCP_Enrollment__c
                    FROM Healthcare_Provider__c
                    WHERE HCP_Enrollment__c IN (
                            SELECT Id
                            FROM HCP_Enrollment__c
                            WHERE HCP_Contact__c = :recipientId
                    )
            ];
    }

    private List<HCP_Enrollment__c> getEnrollments() {
        if(enrollments == null) {
            enrollments = [
                    SELECT Id, Study_Site__r.Principal_Investigator__c
                    FROM HCP_Enrollment__c
                    WHERE HCP_Contact__c = :recipientId
                    AND (Status__c = :HCPEnrollmentService.HCP_S_ACTIVATION_PENDING_O
                    OR Status__c = :HCPEnrollmentService.HCP_S_ACTIVATED )
                    ORDER BY CreatedDate DESC
            ];
        }
        return enrollments;
    }

    private Boolean hasEnrollments() {
        return !getEnrollments().isEmpty();
    }

    private Boolean isSameInvestigator() {
        List<HCP_Enrollment__c> hcpEnrollments = getEnrollments();
        if (!hasEnrollments()) return false;

        Map<Id, List<HCP_Enrollment__c>> hcpEnrollmentsByPI = new Map<Id, List<HCP_Enrollment__c>>();
        for (HCP_Enrollment__c hcpe : hcpEnrollments) {
            if (!hcpEnrollmentsByPI.containsKey(hcpe.Study_Site__r.Principal_Investigator__c)) {
                hcpEnrollmentsByPI.put(hcpe.Study_Site__r.Principal_Investigator__c, new List<HCP_Enrollment__c>());
            }
            hcpEnrollmentsByPI.get(hcpe.Study_Site__r.Principal_Investigator__c).add(hcpe);
        }
        if (hcpEnrollmentsByPI.keySet().size() > 1) return true;

        return false;
    }

    private String getMultiplePINames(Id hcpContId) {
        List<HCP_Enrollment__c> hcpEnrollments = [
                SELECT
                        Study_Site__r.Principal_Investigator__r.Name,
                        Study_Site__r.Principal_Investigator__r.Salutation
                FROM HCP_Enrollment__c
                WHERE HCP_Contact__c = :hcpContId
        ];

        String piNames = '';
        for (HCP_Enrollment__c hcpE : hcpEnrollments) {
//            piNames += getFullContactName(hcpE.Study_Site__r.Principal_Investigator__r) + ', ';
        }
        return piNames.removeEnd(', ');
    }
}