unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hospital of rainbow</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Referring HCPs</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referring_HCP_Staff__c/Referring_HCP_Staff__c.object-meta.xml
<CustomObject>

    <label>Referring HCP Staff</label>
    <nameField>
        <displayFormat>HCPS-{000000}</displayFormat>
        <label>Referring HCP Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referring HCP Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Referring_HCP_Staff__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referring HCP Staffs</relationshipLabel>
    <relationshipName>Referring_HCP_Staffs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Referring_HCP_Staff__c/fields/Delegate_Level__c.field-meta.xml
<CustomField>
    <fullName>Delegate_Level__c</fullName>
    <label>Delegate Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referring_HCP_Staff__c/fields/HCP_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>HCP_Enrollment__c</fullName>
    <label>HCP Enrollment</label>
    <referenceTo>HCP_Enrollment__c</referenceTo>
    <relationshipLabel>Referring HCP Staffs</relationshipLabel>
    <relationshipName>Referring_HCP_Staffs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/Site_Staff__c.object-meta.xml
<CustomObject>
    <description>Used to connect Contacts with Study Sites to represent a Principal Investigator&#39;s team</description>

    <label>Site Staff</label>
    <nameField>
        <displayFormat>Staff #{0000}</displayFormat>
        <label>Site Staff</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Staff__c/fields/Delegate_Level__c.field-meta.xml
<CustomField>
    <fullName>Delegate_Level__c</fullName>
    <label>Delegate Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact__c</fullName>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staff&#39;s Study Sites</relationshipLabel>
    <relationshipName>PI_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <formula>if(is_Site_and_Staff_Same_Country__c == false,  HYPERLINK(&quot;/&quot;&amp; Id , Name ) , &apos;-&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Staff</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Site Staff</relationshipLabel>
    <relationshipName>Site_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to study site delegate</description>
    <label>Site Staff</label>
    <referenceTo>Site_Staff__c</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendEmailTemplate.cls
public without sharing class SendEmailTemplate {
    
    public static final String EMAIL_TEMPLATE_PATIENT1_NEW = 'Patient1_New_Study';
    public static final String EMAIL_TEMPLATE_PATIENT2_NEW = 'Patient2_New_Study';
    
    public class SendEmailTemplateException extends Exception{}
    public static final Id ORGWIDE_EMAIL_ADDRESS_ID = getOrgwideEmailAddress().Id;
    
    public static void sendEmailNotification(String templateName, Map<Id, String> whatIdMap){
        //prepare emails list:
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
        List<Contact> contacts = [SELECT Id, HasOptedOutOfEmail FROM Contact WHERE Id IN : whatIdMap.values()];
        Map<Id, Boolean> contactsOptedOutEmailMap = new Map<Id, Boolean>();
        for(Contact c: contacts) contactsOptedOutEmailMap.put(c.Id, c.HasOptedOutOfEmail);
        
        for(Id whatId : whatIdMap.keySet()){
            if(contactsOptedOutEmailMap.get(whatIdMap.get(whatId))!= null && !contactsOptedOutEmailMap.get(whatIdMap.get(whatId))){
                emailMessages.add(createEmail(getEmailTemplateId(templateName), whatIdMap.get(whatId), whatId));
            }
        }
        //send emails:
        sendEmailMessages(emailMessages);
    }
    
    public static void sendShareEmail(Id whatId, Id fromId,  String emailAddr) {
        Id shareStudyEmailTemplateId = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: CommunityService.COMMUNITY_ET_SHARE_STUDY LIMIT 1].Id;
        List<Messaging.SingleEmailMessage> msgList = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
        msg.setTemplateId(shareStudyEmailTemplateId);
        msg.setWhatId(whatId);
        msg.setTargetObjectId(fromId);
        msg.setToAddresses(new List<String>{emailAddr});
        msgList.add(msg);
        // Send the emails in a transaction, then roll it back
        Savepoint sp = Database.setSavepoint();
        Messaging.sendEmail(msgList); // Dummy email send
        Database.rollback(sp); // Email will not send as it is rolled Back
        // Send Actual email
        List<Messaging.SingleEmailMessage> msgListToBeSend = new List<Messaging.SingleEmailMessage>();
        for (Messaging.SingleEmailMessage email : msgList) {
            Messaging.SingleEmailMessage emailToSend = new Messaging.SingleEmailMessage();
            emailToSend.setToAddresses(email.getToAddresses());
            emailToSend.setPlainTextBody(email.getPlainTextBody());
            emailToSend.setHTMLBody(email.getHTMLBody());
            emailToSend.setPlainTextBody(email.getPlainTextBody());
            emailToSend.setSubject(email.getSubject());
            emailToSend.setOrgWideEmailAddressId(ORGWIDE_EMAIL_ADDRESS_Id);
            msgListToBeSend.add(emailToSend);
        }
        Messaging.sendEmail(msgListToBeSend);
    }
    @InvocableMethod(Label='Send Emails')
    public static void sendEmailNotificationWithDelegates(List<emailNotification> variables){
        //prepare emails list:
        System.debug(variables);
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
        emailMessages.add(createEmail(getEmailTemplateId(variables[0].templateName), variables[0].contactId, variables[0].whatId, variables[0].studyId, true, variables[0].userMode));
        System.debug(emailMessages);
        //send emails:
        sendEmailMessages(emailMessages);
    }
    public class emailNotification {
        @InvocableVariable
        public String templateName;
        @InvocableVariable
        public Id contactId;
        @InvocableVariable
        public Id whatId;
        @InvocableVariable
        public Id studyId;
        @InvocableVariable
        public String userMode;
    }


    
    public static Messaging.SingleEmailMessage createEmail(String templateDeveloperName, Id contactId, Id whatId){
        return createEmail(getEmailTemplateId(templateDeveloperName), contactId, whatId);
    }
    
    public static Messaging.SingleEmailMessage createEmail(Id emailTemplateId, Id contactId, Id whatId){

        return createEmail(emailTemplateId, contactId, whatId, null, false,'');
    }

    public static Messaging.SingleEmailMessage createEmail(Id emailTemplateId, Id contactId, Id whatId, Id studyId, Boolean ccDelegates, String userMode){
        Messaging.SingleEmailMessage newEmail = new Messaging.SingleEmailMessage();
        newEmail.setTemplateId(emailTemplateId);
        newEmail.setTargetObjectId(contactId);
        newEmail.setSaveAsActivity(false);
        newEmail.setOrgWideEmailAddressId(ORGWIDE_EMAIL_ADDRESS_Id);
        //newEmail.setToAddresses(new List<String>{toAddress});
        //newEmail.setWhatId(whatId);
        if(ccDelegates && userMode == CommunityService.USER_MODE_PI){
            List<String> delegateAddresses = new List<String>();
            for(Site_Staff__c delegate : [
                    SELECT Id, Site_Contact__r.Email
                    FROM Site_Staff__c
                    WHERE
                    Delegate_Level__c =: DelegateService.DELEGATE_LEVEL_1
                    AND Study_Site__c = :studyId]){
                delegateAddresses.add(delegate.Site_Contact__r.Email);
            }
            newEmail.setCcAddresses(delegateAddresses);
        }
        else if(ccDelegates && userMode == CommunityService.USER_MODE_HCP){
            List<String> delegateAddresses = new List<String>();
            for(Referring_HCP_Staff__c delegate : [
                    SELECT Id, Contact__r.Email
                    FROM Referring_HCP_Staff__c
                    WHERE
                    Delegate_Level__c =: DelegateService.DELEGATE_LEVEL_1
                    AND HCP_Enrollment__r.Study_Site__c = :studyId]){
                delegateAddresses.add(delegate.Contact__r.Email);
            }
            newEmail.setCcAddresses(delegateAddresses);
        }

        return newEmail;
    }
    
    private static final Map<String, Id> templateNameIdMap = new Map<String, Id>();
    
    private static Id getEmailTemplateId(String templateName) {
        Id templateId = templateNameIdMap.get(templateName);
        if(templateId != null) return templateId;
        List<EmailTemplate> templates = [
                SELECT Id
                FROM EmailTemplate
                WHERE DeveloperName = :templateName
                LIMIT 1
        ];
        if(templates.isEmpty()) throw new SendEmailTemplateException('Email template: "' + templateName + '" not found');
        templateNameIdMap.put(templateName, templates[0].Id);
        return templates[0].Id;
    }
    
    private static OrgwideEmailAddress getOrgwideEmailAddress() {
        List<OrgWideEmailAddress> orgwideEmailAddresses = [
                SELECT Id
                FROM OrgwideEmailAddress
                WHERE displayname = :CommunityService.COMMUNITY_ORG_WIDE_ADDRESS_NAME
                LIMIT 1
        ];
        if(orgwideEmailAddresses.isEmpty()){
            Organization org = [SELECT Id, IsSandbox FROM Organization LIMIT 1];
            if(org.IsSandbox){
                orgwideEmailAddresses = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
                if(!orgwideEmailAddresses.isEmpty()){
                    return orgwideEmailAddresses[0];
                }
            }
            throw new SendEmailTemplateException('Org Wide Email Address: "' + CommunityService.COMMUNITY_ORG_WIDE_ADDRESS_NAME + '" not found');
        }
        return orgwideEmailAddresses[0];
    }
    
    public static void sendEmailMessages(List<Messaging.SingleEmailMessage> emailMessages){
        System.debug(emailMessages);
        for(Messaging.SendEmailResult result : Messaging.sendEmail(emailMessages, false)){
            if (result.success) {
                System.debug('The email was sent successfully.');
            } else {
                System.debug('The email failed to send: ' + result.errors[0].message);
            }
        }
    }

}