unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hospital of rainbow</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Referring HCPs</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Override_PI_Referral_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_PI_Referral_Status__c</fullName>
    <label>PI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Accepted (Admin)</fullName>
                <isActive>false</isActive>
                <label>Accepted (Admin)</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Active (Admin)</fullName>
                <isActive>false</isActive>
                <label>Active (Admin)</label>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
                <isActive>false</isActive>
                <label>Deactivated (Admin)</label>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
                <isActive>false</isActive>
                <label>Declined (Acceptance)</label>
            </value>
            <value>
                <fullName>No Response</fullName>
                <isActive>false</isActive>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
                <isActive>false</isActive>
                <label>Non-Responsive (Admin)</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
                <isActive>false</isActive>
                <label>On Hold (Admin)</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NoTanksModalController.cls
/**
 * Created by D.Yasinskyi on 29.03.2018
 */
public without sharing class NoTanksModalController {

    @AuraEnabled
    public static void deactivateTrial(Id trialId, String userMode, String ssId) {
        try{
            if(String.isEmpty(ssId)) {
                if (userMode == CommunityService.USER_MODE_HCP) {
                    deactivateHCPEnrollment(trialId, userMode);
                } else if (userMode == CommunityService.USER_MODE_PI) {
                    deactivateStudySite(trialId, userMode);
                }
            }
            else{
                deactivateStudySiteById(ssId, userMode);
            }
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    private static void deactivateHCPEnrollment(Id trialId, String userMode) {
        HCP_Enrollment__c hcpEnrollment = HCPEnrollmentService.getHCPEnrollmentForHCPByTrial(trialId);
        HCPEnrollmentService.changeStatus(hcpEnrollment.Id, userMode, StudyActions.ACT_HCP_DECLINE);
    }

    private static void deactivateStudySite(Id trialId, String userMode) {
        List<Study_Site__c> studySites = StudySiteService.getStudySiteForPIByTrialId(trialId);
        Set<Id> ssIdSet = new Set<Id>();
        if(studySites.isEmpty()) throw new AuraHandledException('incorrect Data');
        for (Integer i = 0; i <studySites.size(); i++) {
            if(studySites[i].Override_PI_Referral_Status__c == StudySiteService.PI_S_INVITATION_SENT) {
                ssIdSet.add(studySites[i].Id);
            }
        }
        StudySiteService.changeStatus(ssIdSet, userMode, 'decline');
    }

    private static void deactivateStudySiteById(Id ssId, String userMode) {
        Study_Site__c studySites = StudySiteService.getStudySiteForHCPById(ssId);
        if(studySites==null) throw new AuraHandledException('incorrect Data');
        StudySiteService.changeStatus(studySites.Id, userMode, 'decline');
    }
}