force-app/main/community-template/objects/Community_Template__mdt/Community_Template__mdt.object-meta.xml
<CustomObject>
    <label>Community Template</label>
    <pluralLabel>Community Templates</pluralLabel>
</CustomObject>

force-app/main/community-template/objects/Community_Template__mdt/fields/Community_Template__c.field-meta.xml
<CustomField>
    <fullName>Community_Template__c</fullName>
        <label>Community Template</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                    <default>true</default>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>GSK</fullName>
                </value>
                <value>
                    <fullName>Covid_19</fullName>
                </value>
                <value>
                    <fullName>Janssen</fullName>
                </value>
                <value>
                    <fullName>PatientPortal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
</CustomField>

force-app/main/community-template/objects/Community_Template_Selector__c/Community_Template_Selector__c.object-meta.xml
<CustomObject>
    <label>Community Template Selector</label>
    <nameField>
        <displayFormat>CTS-{0000}</displayFormat>
        <label>Community Template Selector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Template Selectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/community-template/objects/Community_Template_Selector__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Community Template Selectors</relationshipLabel>
    <relationshipName>Community_Template_Selectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/community-template/objects/Community_Template_Selector__c/fields/Template_Selector_Formula__c.field-meta.xml
<CustomField>
    <fullName>Template_Selector_Formula__c</fullName>
    <formula>IF( CONTAINS(Participant_Enrollment__r.Clinical_Trial_Profile__r.Study_Code_Name__c, &#39;GSK&#39;), &#39;GSK&#39;, &#39;Default&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Template Selector Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/community-template/objects/CommunityTemplate_Property__mdt/CommunityTemplate_Property__mdt.object-meta.xml
<CustomObject>
    <label>Community Template Property</label>
    <pluralLabel>Community_Template Properties</pluralLabel>
</CustomObject>

force-app/main/community-template/objects/CommunityTemplate_Property__mdt/fields/Community_Template__c.field-meta.xml
<CustomField>
    <fullName>Community_Template__c</fullName>
    <label>Community Template</label>
    <referenceTo>Community_Template__mdt</referenceTo>
    <relationshipName>CommunityTemplate_Properties</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/community-template/objects/CommunityTemplate_Property__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>

</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/community-template/classes/CommunityTemplateService.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class CommunityTemplateService {
    
    public static final String TEMPLATE_DEFAULT = 'Default';
    
    public static Map<String, String> getTemplateProperties(Id peId){
        System.debug('XXX_PE ID: ' + peId);
        Community_Template_Selector__c selector = new Community_Template_Selector__c();
        if(peId != null){
            selector = new Community_Template_Selector__c(Participant_Enrollment__c = peId);
            insert selector;
            selector = [SELECT Template_Selector_Formula__c FROM Community_Template_Selector__c WHERE Id =: selector.Id];
        }
        List<String> templateNames = new List<String>{'Default'};
        String templateName = selector.Template_Selector_Formula__c;
        if(!String.isEmpty(templateName)) templateNames.add(selector.Template_Selector_Formula__c);
        List<CommunityTemplate_Property__mdt> templatePropertis = [
                SELECT Id, Value__c, Label, Community_Template__r.Label
                FROM CommunityTemplate_Property__mdt
                WHERE Community_Template__r.Label IN: templateNames];
        Map<String, String> resMap = new Map<String, String>();
        //Set default properties
        for(CommunityTemplate_Property__mdt property : templatePropertis){
            if(property.Community_Template__r.Label == 'Default'){
                resMap.put(property.Label, property.Value__c);
            }
        }
        //Set specified properties:
        for(CommunityTemplate_Property__mdt property : templatePropertis){
            if(!String.isEmpty(templateName) && property.Community_Template__r.Label == templateName){
                resMap.put(property.Label, property.Value__c);
            }
        }
        Map<String, String> resourcesURLMap = getResourceURLMap();
        for(String resourceName : resourcesURLMap.keySet()){
            for(String propertyName : resMap.keySet()){
                String value = resMap.get(propertyName);
                value = value.replace(resourceName, resourcesURLMap.get(resourceName));
                resMap.put(propertyName, value);
            }
        }
        if(selector.Id != null) delete selector;
        return resMap;
    }
    
    public static Map<String, String> getResourceURLMap() {
        List<StaticResource> resourceList = [
                SELECT Name, NamespacePrefix, SystemModStamp
                FROM StaticResource];
        Map<String, String> resourcesMap = new Map<String, String>();
        for(StaticResource resource : resourceList){
            String namespace = resource.NamespacePrefix;
            String resourceURL = '/resource/' + resource.SystemModStamp.getTime() +
                    '/' + (namespace != null && namespace != '' ? namespace + '__' : '') + resource.Name;
            resourcesMap.put('$Resource/' + resource.Name, resourceURL);
        }
        return resourcesMap;
    }

}