force-app/main/default/objects/Case/fields/CommunityName__c.field-meta.xml
<CustomField>
    <fullName>CommunityName__c</fullName>
    <label>CommunityName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/CommunityTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommunityTemplate__c</fullName>
    <label>Community Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>IQVIA Patient Portal</label>
            </value>
            <value>
                <fullName>GSK</fullName>
                <label>GSK Pan Oncology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/community-template/objects/Community_Template__mdt/Community_Template__mdt.object-meta.xml
<CustomObject>
    <label>Community Template</label>
    <pluralLabel>Community Templates</pluralLabel>
</CustomObject>

force-app/main/community-template/objects/Community_Template__mdt/fields/Community_Name__c.field-meta.xml
<CustomField>
    <fullName>Community_Name__c</fullName>
    <label>Community Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/classes/TemplatePropertiesService.cls
/**
 * Created by Olga Skrynnikova on 2/26/2020.
 */

public with sharing class TemplatePropertiesService {

    private Map<String, String> properties;
    
    public TemplatePropertiesService(String templateName){
        properties = CommunityTemplateService.getTemplate(templateName).properties;
    }

    public TemplatePropertiesService() {
        properties = CommunityTemplateService.getDefaultTemplate().properties;
    }

    public TemplatePropertiesService(Id resourceId, Id recipientId, String userMode, Boolean isDelegate) {
        String templateName = getTemplateName(resourceId, recipientId, userMode, isDelegate);
        properties = !String.isEmpty(templateName) ?
                CommunityTemplateService.getTemplate(templateName).properties :
                CommunityTemplateService.getDefaultTemplate().properties;
    }

    public String getPropertyValue(String key) {
        return properties.get(key);
    }

    private String getTemplateName(Id resourceId, Id recipientId, String userMode, Boolean isDelegate) {
        if(userMode != CommunityModeService.USER_MODE_PARTICIPANT) return CommunityTemplateService.TEMPLATE_DEFAULT;
        String templateName;
        try {
            if (recipientId.getSobjectType() == User.getSObjectType()) {
                recipientId = [
                        SELECT Id, ContactId
                        FROM User
                        WHERE Id = :recipientId
                ].ContactId;
            }
            Id partConId = recipientId;

            if (isDelegate && userMode == CommunityService.USER_MODE_PARTICIPANT) {
                partConId = PatientDelegateService.getParticipantByDelegateContactId(partConId).Contact__c;
            }
            if(partConId == null) return templateName;

            String filter;
            Id enrollmentId;
            if (resourceId.getSobjectType() == Participant_Enrollment__c.getSObjectType()) {
                filter = DatabaseService.fieldEqual('Id', resourceId);
            } else if (resourceId.getSobjectType() == User.getSObjectType() && userMode == CommunityService.USER_MODE_PARTICIPANT) {
                filter = DatabaseService.fieldEqual('Participant_Contact__c', partConId);
            } else if (resourceId.getSobjectType() == Case.getSObjectType()) {
                Case cs = [SELECT Id, CommunityName__c FROM Case WHERE Id = :resourceId];
                if (cs != null) {
                    Community_Template__mdt commTemplate = [
                            SELECT Id, DeveloperName, Community_Name__c
                            FROM Community_Template__mdt
                            WHERE Community_Name__c = :cs.CommunityName__c
                    ];
                    return commTemplate.DeveloperName;
                }
            } else if (resourceId.getSobjectType() == Task.getSObjectType()) {
                Task task = [SELECT Id, Community_Template_Name__c, WhatId FROM Task WHERE Id = :resourceId];
                if(task.Community_Template_Name__c != null) {
                    return task.Community_Template_Name__c;
                } else if (task.WhatId != null && task.WhatId.getSobjectType() == Participant_Enrollment__c.getSObjectType()) {
                    filter = DatabaseService.fieldEqual('Id', task.WhatId);
                } else {
                    Participant_Enrollment__c currentPE = ContactService.getCurrentPE(partConId);
                    enrollmentId = currentPE != null ? currentPE.Id : PatientDelegateService.getPastPEIdsForContact(partConId)[0];
                    filter = DatabaseService.fieldEqual('Id', enrollmentId);
                }
            } else if (resourceId.getSobjectType() == SurveyInvitation.getSObjectType()) {
                SurveyInvitation invitation = [SELECT Id, Participant_Enrollment__c FROM SurveyInvitation WHERE Id = :resourceId];
                enrollmentId = invitation.Participant_Enrollment__c;
            }  else if (resourceId.getSobjectType() == Clinical_Trial_Profile__c.getSObjectType()) {
                filter = DatabaseService.fieldEqual('Clinical_Trial_Profile__c', resourceId);
            }

            if (filter == null) {
                if (enrollmentId == null) {
                    Participant_Enrollment__c currentPE = ContactService.getCurrentPE(partConId);
                    enrollmentId = currentPE != null ? currentPE.Id : PatientDelegateService.getPastPEIdsForContact(partConId)[0];
                }
                filter = DatabaseService.fieldEqual('Id', enrollmentId);
            }
            if (templateName == null && filter != null) {
                List<Participant_Enrollment__c> enrollments = (List<Participant_Enrollment__c>) DatabaseService.query(
                        new List<String>{
                                'Clinical_Trial_Profile__r.CommunityTemplate__c'
                        },
                        Participant_Enrollment__c.getSObjectType(),
                        filter
                );
                if (enrollments != null && !enrollments.isEmpty()) {
                    templateName = CommunityTemplateService.getTemplate(
                            enrollments.get(0).Clinical_Trial_Profile__r.CommunityTemplate__c).templateName;
                }
            }
        } catch (Exception e) {
            EmailService.sendException(e, null);
        }

        return templateName;
    }
}