force-app/libs/action-queue/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/libs/action-queue/objects/Execution_History__c/Execution_History__c.object-meta.xml
<CustomObject>
    <label>Execution History</label>
    <nameField>
        <displayFormat>EH-{000000}</displayFormat>
        <label>Execution Time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/libs/action-queue/objects/Execution_History__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Execution Histories</relationshipLabel>
    <relationshipName>Execution_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/integration-framework/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/deprecated/classes/Action_GetCardDetails.cls
/**
 * Created by Nargiz Mamedova on 1/21/2020.
 */

public with sharing class Action_GetCardDetails implements Action{

    public class Action_GetCardDetails_Exception extends Exception{}
    private String protocolId;
    private String patientId;
    private Participant__c participant;
    public Id integrationLogId;
    transient public IntegrationLog__c log;
    transient public List<RemoteCall_GetCardDetails.Card> result;

    public Action_GetCardDetails(String protocolId, String patientId, Participant__c participant) {
        this.protocolId = protocolId;
        this.patientId = patientId;
        this.participant = participant;
    }

    public void execute() {
    }

    public Type getType() {
        return Action_GetCardDetails.class;
    }
    
    public Boolean isDMLWithSetupObjects() {
        return false;
    }
    
    public void postDML(Action__c dbAction, Execution_History__c executionHistory) {
    }
}