force-app/libs/action-queue/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/libs/action-queue/objects/Action__c/fields/DML_With_Setup_Objects__c.field-meta.xml
<CustomField>
    <fullName>DML_With_Setup_Objects__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DML With Setup Objects</label>
    <type>Checkbox</type>
</CustomField>

force-app/libs/action-queue/objects/Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/libs/action-queue/objects/Action_Execution_Setting__c/Action_Execution_Setting__c.object-meta.xml
<CustomObject>
    <label>Action Execution Setting</label>
    <nameField>
        <displayFormat>AES-{000000}</displayFormat>
        <label>Action Execution Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Execution Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/libs/action-queue/objects/Action_Execution_Setting__c/fields/Relaunch_Interval__c.field-meta.xml
<CustomField>
    <fullName>Relaunch_Interval__c</fullName>
    <label>Relaunch Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/libs/action-queue/objects/Action_Execution_Setting__c/fields/Remove_After_Complete__c.field-meta.xml
<CustomField>
    <fullName>Remove_After_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remove After Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/action-queue/objects/Action_Execution_Setting__c/fields/Repetitions_Count__c.field-meta.xml
<CustomField>
    <fullName>Repetitions_Count__c</fullName>
    <label>Repetitions Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/libs/action-queue/objects/Execution_History__c/Execution_History__c.object-meta.xml
<CustomObject>
    <label>Execution History</label>
    <nameField>
        <displayFormat>EH-{000000}</displayFormat>
        <label>Execution Time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/libs/action-queue/objects/Execution_History__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Execution Histories</relationshipLabel>
    <relationshipName>Execution_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/libs/action-queue/objects/Execution_History__c/fields/Is_Success__c.field-meta.xml
<CustomField>
    <fullName>Is_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/libs/action-queue/classes/ActionExecutor.cls
/**
 * Created by Nargiz Mamedova on 12/3/2019.
 */

public with sharing class ActionExecutor {

    public static String ACTION_STATUS_PENDING = 'Pending';
    public static String ACTION_STATUS_COMPLETED = 'Completed';
    public static String ACTION_STATUS_FAILED = 'Failed';
    public static String ACTION_STATUS_SCHEDULED = 'Scheduled';
    
    public class ExecutionResult{
        public Action action;
        public Action__c dbAction;
        public Execution_History__c executionHistory;
        
        public ExecutionResult(Action action, Action__c dbAction, Execution_History__c executionHistory){
            this.action = action;
            this.dbAction = dbAction;
            this.executionHistory = executionHistory;
        }
        
        public void complete(){
            if(action != null) action.postDML(dbAction, executionHistory);
        }
    }
    
    private static Map<String, Action_Execution_Setting__c> actionSettingsMap = new Map<String, Action_Execution_Setting__c>();
    private static Action_Execution_Setting__c orgDefaultSetting = new Action_Execution_Setting__c(
            Relaunch_Interval__c = 5,
            Repetitions_Count__c = 3,
            Remove_After_Complete__c = true
    );

    static {
        List<Action_Execution_Setting__c> actionExecutionSettings = [
                SELECT Id, Type__c, Relaunch_Interval__c, Repetitions_Count__c, Remove_After_Complete__c
                FROM Action_Execution_Setting__c
        ];
        for(Action_Execution_Setting__c act : actionExecutionSettings) {
            if(act.Type__c == null){
                orgDefaultSetting = act;
            } else {
                actionSettingsMap.put(act.Type__c + '', act);
            }
        }
    }

    private static Action_Execution_Setting__c getSetting(String actionType){
        Action_Execution_Setting__c actionSetting = actionSettingsMap.get(actionType);
        if(actionSetting == null) actionSetting = orgDefaultSetting;
        return actionSetting;
    }
    
    public static String generateCodeExecutionForAnonymous(Action action){
        String actionJSON = JSON.serialize(action);
        return 'ActionExecutor.execute(\'' + actionJSON + '\', ' + action.getType() + '.class).complete();';
    }
    
    public static ExecutionResult execute(String actionJSON, Type actionType){
        Action action = (Action)JSON.deserialize(actionJSON, actionType);
        return execute(action);
    }
    
    public static ExecutionResult execute(Action action){
        Action__c act = new Action__c(
                Type__c = action.getType().toString(),
                Body__c = JSON.serializePretty(action),
                DML_With_Setup_Objects__c = action.isDMLWithSetupObjects()
        );
        Execution_History__c history = new Execution_History__c();
        Action_Execution_Setting__c actionSetting = getSetting(act.Type__c);
        try {
            action.execute();
            act.Status__c = ACTION_STATUS_COMPLETED;
            history.Is_Success__c = true;
        } catch (Exception e) {
            act.Status__c = ACTION_STATUS_PENDING;
            Datetime nextExecutionDatetime = Datetime.now().addMinutes(actionSetting.Relaunch_Interval__c.intValue());
            act.Execution_Time__c = nextExecutionDatetime;
            history.Error_Message__c = e.getMessage();
            history.Stack_Trace__c = e.getStackTraceString();
            history.Is_Success__c = false;
        } finally {
            act.Body__c = JSON.serializePretty(action);
            if(!actionSetting.Remove_After_Complete__c || act.Status__c != ACTION_STATUS_COMPLETED) {
                DMLService.insertRecord(act);
                DMLService.setLookup(history, 'Action__c', act);
                DMLService.insertRecord(history);
                DMLService.resetLookup();
            }
        }
        return new ExecutionResult(action, act, history);
    }

    public static ExecutionResult execute(Action__c act){
        Execution_History__c history = new Execution_History__c();
        Action_Execution_Setting__c actionSetting = getSetting(act.Type__c);
        Type actionType = Type.forName(act.Type__c);
        Action action = (Action) JSON.deserialize(act.Body__c, actionType);
        try{
            action.execute();
            act.Status__c = ACTION_STATUS_COMPLETED;
            history.Is_Success__c = true;
        } catch (Exception e) {
            Datetime nextExecutionDatetime = Datetime.now().addMinutes(actionSetting.Relaunch_Interval__c.intValue());
            history.Error_Message__c = e.getMessage();
            history.Stack_Trace__c = e.getStackTraceString();
            history.Is_Success__c = false;

            if(act.Execution_Histories__r.size() < actionSetting.Repetitions_Count__c - 1) {
                act.Status__c = ACTION_STATUS_PENDING;
                act.Execution_Time__c = nextExecutionDatetime;
            } else {
                act.Status__c = ACTION_STATUS_FAILED;
                act.Execution_Time__c = null;
            }
        } finally {
            act.Body__c = JSON.serializePretty(action);
            if(!actionSetting.Remove_After_Complete__c || act.Status__c != ACTION_STATUS_COMPLETED) {
                DMLService.updateRecord(act);
                DMLService.setLookup(history, 'Action__c', act);
                DMLService.insertRecord(history);
                DMLService.resetLookup();
            } else {
                DMLService.deleteRecord(act);
            }
        }
        return new ExecutionResult(action, act, history);
    }

    public static void executeAsync(Action action, Datetime executeTime){
        Action__c act = new Action__c(
                Type__c = action.getType().toString(),
                Body__c = JSON.serializePretty(action),
                Execution_Time__c = executeTime,
                DML_With_Setup_Objects__c = action.isDMLWithSetupObjects(),
                Status__c = ACTION_STATUS_PENDING
        );
        DMLService.insertRecord(act);
    }

     public static void executeAsync(Action action){
        executeAsyncImpl(JSON.serialize(action), action.getType().toString());
    }

     public static void executeAsync(Action__c act){
        executeAsyncImpl(JSON.serialize(act));
    }

    @Future(Callout=true)
    private static void executeAsyncImpl(String actionJSON, String actionTypeStr){
        Type actionType = Type.forName(actionTypeStr);
        Action action = (Action) JSON.deserialize(actionJSON, actionType);
        execute(action);
    }

    @Future(Callout=true)
    private static void executeAsyncImpl(String actionJSON){
        execute((Action__c) JSON.deserialize(actionJSON, Action__c.class));
    }
}