force-app/libs/action-queue/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/libs/action-queue/objects/Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Link_to_Pre_screening__c.field-meta.xml
<CustomField>
    <fullName>Link_to_Pre_screening__c</fullName>
    <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires pre-screening.</inlineHelpText>
    <label>Link to Pre-screening</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
    <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
    <label>NCT Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Override_Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_Recruitment_Status__c</fullName>
    <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
    <label>Override Recruitment Status</label>

    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actively Enrolling</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>No_Longer_Enrolling</fullName>
                <label>No Longer Enrolling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <description>QI assigned unique ID for a study</description>
    <externalId>true</externalId>
    <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
    <label>Protocol ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Title__c.field-meta.xml
<CustomField>
    <fullName>Study_Title__c</fullName>
    <description>Title of the Study</description>
    <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
    <label>Study Title</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Suppress_Participant_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Participant_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, no emails will be sent to participants for this study.</inlineHelpText>
    <label>Suppress Participant Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/Site_Staff__c.object-meta.xml
<CustomObject>
    <description>Used to connect Contacts with Study Sites to represent a Principal Investigator&#39;s team</description>

    <label>Site Staff</label>
    <nameField>
        <displayFormat>Staff #{0000}</displayFormat>
        <label>Site Staff</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Staff__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; Study_Site__r.Clinical_Trial_Profile__c,  Study_Site__r.Clinical_Trial_Profile__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clinical Trial Profile</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site_Staff__c/fields/Delegate_Level__c.field-meta.xml
<CustomField>
    <fullName>Delegate_Level__c</fullName>
    <label>Delegate Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Study_Site__r.Principal_Investigator__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact__c</fullName>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staff&#39;s Study Sites</relationshipLabel>
    <relationshipName>PI_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <formula>if(is_Site_and_Staff_Same_Country__c == false,  HYPERLINK(&quot;/&quot;&amp; Id , Name ) , &apos;-&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Staff</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Site Staff</relationshipLabel>
    <relationshipName>Site_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <formula>Clinical_Trial_Profile__r.Protocol_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Clinical Trial Profile&#39;s Protocol Id</inlineHelpText>
    <label>Protocol ID</label>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to study site delegate</description>
    <label>Site Staff</label>
    <referenceTo>Site_Staff__c</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Study_Site_Type__c.field-meta.xml
<CustomField>
    <fullName>Study_Site_Type__c</fullName>
    <label>Study Site Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Traditional</fullName>
                <default>true</default>
                <label>Traditional</label>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Suppress_Participant_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Participant_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, no emails will be sent to participants for this study site.</inlineHelpText>
    <label>Suppress Participant Emails</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/tests/classes/Test_SiteStaffTableRemote.cls
/**
 * Created by Andrii Kryvolap.
 */

@IsTest(IsParallel=false)
private class Test_SiteStaffTableRemote {
    @TestSetup
    static void init() {
        Test.startTest();
        TestData.loadTestData();
        Test.stopTest();
    }

    @IsTest
    static void testGetInitData() {
        TestData testDataInst = new TestData();
        Test.startTest();
        System.runAs(testDataInst.hcpUser) {
            SiteStaffTableRemote.InitData initData = SiteStaffTableRemote.getInitData(
                testDataInst.hcpEnrollment.Study_Site__c
            );
            System.assertEquals(initData.viewMode, 'Disabled');
        }
        Test.stopTest();
    }
    @IsTest
    static void testCreateInitData() {
        TestData testDataInst = new TestData();
        Test.startTest();
        System.runAs(testDataInst.hcpUser) {
            SiteStaffTableRemote.InitData initData = SiteStaffTableRemote.createInitData(
                testDataInst.hcpEnrollment.Study_Site__c,
                'Edit'
            );
            System.assertEquals(initData.viewMode, 'Edit');
            System.assertEquals(initData.inInvitationActiveStatus, true);
            System.assertEquals(initData.siteStaffMembers.size(), 2);
        }
        Test.stopTest();
    }
    @IsTest
    static void testInviteUser() {
        TestData testDataInst = new TestData();
        Test.startTest();
        System.runAs(testDataInst.hcpUser) {
            SiteStaffTableRemote.InitData initData = SiteStaffTableRemote.createInitData(
                testDataInst.hcpEnrollment.Study_Site__c,
                'Edit'
            );
        }
        Test.stopTest();
    }
     @IsTest
    static void testInviteStaffMember() {
        
          UserRole userRole_1 = [SELECT Id FROM UserRole WHERE Name = 'View All' LIMIT 1];
        Profile profile_1 = [
            SELECT Id
            FROM Profile
            WHERE Name = 'IQVIA Customer Community Plus Login User'
            LIMIT 1
        ];
        User admin = [
            SELECT Id, Username, UserRoleId
            FROM User
            WHERE
                Profile.Name = 'System Administrator'
                AND UserRoleId = :userRole_1.Id
                AND IsActive = TRUE
            LIMIT 1
        ];
        User user_1;
        Test.startTest();
        System.runAs(admin) {
            Account usraccount = new Account(Name = 'Community');
            insert usraccount;

            Contact usrcontact = new Contact(AccountId = usraccount.Id, LastName = 'xgeek');
            insert usrcontact;

            user_1 = new User(
                Email = 'yourusername@gmail.com',
                ProfileId = profile_1.Id,
                UserName = 'yourusername@gmail.com',
                Alias = 'Test',
                TimeZoneSidKey = 'America/New_York',
                EmailEncodingKey = 'ISO-8859-1',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                ContactId = usrcontact.Id,
                PortalRole = 'Manager',
                FirstName = 'Firstname',
                LastName = 'Lastname'
            );
            insert user_1;
            Clinical_Trial_Profile__c clinical = new Clinical_Trial_Profile__c(
                Protocol_ID__c = 'tt123456790',
                Override_Recruitment_Status__c = 'Actively Enrolling',
                NCT_Number__c = 'NCT00000002',
                Link_to_Pre_screening__c = 'some link',
                Study_Title__c = 'Some Title',
                Study_Code_Name__c = 'Some Code Name',
                Suppress_Participant_Emails__c = false
            );
            insert clinical;

            Study_Site__c studySite = new Study_Site__c(
                Name = 'Test',
                Principal_Investigator__c = usrcontact.Id,
                Clinical_Trial_Profile__c = clinical.Id,
                Site__c = usraccount.Id,
                Study_Site_Type__c = 'Traditional',
                Suppress_Participant_Emails__c = false
            );
            insert studySite;
            Site_Staff__c siteStaff = new Site_Staff__c(
                Delegate_Level__c = 'Level 1',
                Study_Site__c = studySite.Id,
                Site_Contact__c = usrcontact.Id
            );
            insert siteStaff;
            SiteStaffTableRemote.inviteStaffMember(usrcontact.Id,studySite.Id);
        
        Datetime timeStamp = Datetime.now();
            
            List<Action__c> pendingActions = [
                SELECT Id, Body__c, Status__c, CreatedDate
                FROM Action__c
                WHERE Type__c = 'Action_AssignContactPermissions' AND CreatedDate >= :timeStamp
            ];
            System.debug(pendingActions);
           // System.assertEquals(2, pendingActions.size());
        }
         Test.stopTest();
       
    }
}