force-app/libs/action-queue/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/libs/action-queue/objects/Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/deprecated/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log Old</label>
    <nameField>
        <displayFormat>IL-{00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/integration-framework/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Notification__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/messaging/objects/Send_Result__c/Send_Result__c.object-meta.xml
<CustomObject>
    <label>Send Result</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Send Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Send Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Send_Result__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action</label>
    <referenceTo>Action__c</referenceTo>
    <relationshipLabel>Send Results</relationshipLabel>
    <relationshipName>Send_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/objects/Send_Result__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/messaging/objects/Send_Result__c/fields/Integration_Log__c.field-meta.xml
<CustomField>
    <fullName>Integration_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integration Log</label>
    <referenceTo>IntegrationLog__c</referenceTo>
    <relationshipLabel>Send Results</relationshipLabel>
    <relationshipName>Send_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/objects/Send_Result__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Send Results</relationshipLabel>
    <relationshipName>Send_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/messaging/objects/Send_Result__c/fields/NotificationId__c.field-meta.xml
<CustomField>
    <fullName>NotificationId__c</fullName>
    <label>NotificationId</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Send Results</relationshipLabel>
    <relationshipName>Send_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/messaging/objects/Send_Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/messaging/objects/Send_Result__c/fields/Target_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Type__c</fullName>
    <label>Target Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/messaging/classes/NotificationResultService.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class NotificationResultService {
    
    public static final String SEND_RESULT_STATUS_SKIPPED = 'Skipped';
    public static final String SEND_RESULT_STATUS_IN_PROGRESS = 'In Progress';
    public static final String SEND_RESULT_STATUS_FAILED = 'Failed';
    public static final String SEND_RESULT_STATUS_SENT = 'Sent';
    
    private Map<Id, List<Send_Result__c>> sendResultsMap;
    
    
    public NotificationResultService(List<Notification__c> notifications){
        List<Notification__c> notificationsWithResults = [
                SELECT Id, (SELECT Id, Target_Type__c, Status__c FROM Send_Results__r)
                FROM Notification__c
                WHERE Id IN: notifications
        ];
        sendResultsMap = new Map<Id, List<Send_Result__c>>();
        for(Notification__c n : notificationsWithResults){
            sendResultsMap.put(n.Id, n.Send_Results__r);
        }
    }
    
    public void setSkipped(Id notificationId, String targetType){
        setResultStatus(notificationId, targetType, SEND_RESULT_STATUS_SKIPPED, null);
    }
    
    public void setInProgress(Id notificationId, String targetType){
        setResultStatus(notificationId, targetType, SEND_RESULT_STATUS_IN_PROGRESS, null);
    }
    
    public void setFailed(Id notificationId, String targetType, String errorMessage){
        setResultStatus(notificationId, targetType, SEND_RESULT_STATUS_FAILED, errorMessage);
    }
    
    public void setSent(Id notificationId, String targetType){
        setResultStatus(notificationId, targetType, SEND_RESULT_STATUS_SENT, null);
    }
    
    public Send_Result__c getSendResult(Id notificationId, String targetType){
        List<Send_Result__c> sendResults = sendResultsMap.get(notificationId);
        if(sendResultsMap == null) sendResults = new List<Send_Result__c>();
        Send_Result__c result;
        for(Send_Result__c sendResult : sendResults){
            if(sendResult.Target_Type__c == targetType){
                result = sendResult;
                break;
            }
        }
        if(result == null) {
            result = new Send_Result__c(
                    Notification__c = notificationId,
                    Target_Type__c = targetType
            );
            sendResults.add(result);
        }
        return result;
    }
    
    public void updateResults(){
        updateResults(null);
    }
    
    public void updateResults(IntegrationLog__c log){
        List<Send_Result__c> results = new List<Send_Result__c>();
        for(List<Send_Result__c> nResults : sendResultsMap.values()){
            for(Send_Result__c sr : nResults) {
                if(log != null && sr.Target_Type__c == NotificationService.NOTIFICATION_TARGET_TYPE_SMS) {
                    sr.Integration_Log__c = log.Id;
                }
            }
            results.addAll(nResults);
        }
        upsert results;
        updateNotificationsStatus();
    }
    
    public void setAction(Action__c action){
        List<Send_Result__c> results = new List<Send_Result__c>();
        for(List<Send_Result__c> nResults : sendResultsMap.values()){
            for(Send_Result__c sr : nResults) {
                sr.Action__c = action.Id;
            }
            results.addAll(nResults);
        }
    }
    
    private void setResultStatus(Id notificationId, String targetType, String status, String errorMessage){
        Send_Result__c result = getSendResult(notificationId, targetType);
        result.Status__c = status;
        result.Error__c = SObjectHelper.trimForField(errorMessage, Send_Result__c.Error__c);
    }
    
    private void updateNotificationsStatus(){
        List<Notification__c> notifications = [
                SELECT Id, (SELECT Id, Status__c FROM Send_Results__r)
                FROM Notification__c
                WHERE Id IN: sendResultsMap.keySet()
        ];
        for(Notification__c n : notifications){
            if(n.Send_Results__r.isEmpty()) continue;
        
            Boolean hasFailed = false;
            Boolean hasInProgress = false;
            for(Send_Result__c sr : n.Send_Results__r){
                if(sr.Status__c == SEND_RESULT_STATUS_IN_PROGRESS) hasInProgress = true;
                if(sr.Status__c == SEND_RESULT_STATUS_FAILED) hasFailed = true;
            }
            if(hasFailed){
                n.Status__c = NotificationService.NOTIFICATION_STATUS_FAILED;
            } else if(hasInProgress){
                n.Status__c = NotificationService.NOTIFICATION_STATUS_IN_PROGRESS;
            } else{
                n.Status__c = NotificationService.NOTIFICATION_STATUS_PROCESSED;
            }
        }
        update notifications;
    }

}