force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Override_PI_Referral_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_PI_Referral_Status__c</fullName>
    <label>PI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Accepted (Admin)</fullName>
                <isActive>false</isActive>
                <label>Accepted (Admin)</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Active (Admin)</fullName>
                <isActive>false</isActive>
                <label>Active (Admin)</label>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
                <isActive>false</isActive>
                <label>Deactivated (Admin)</label>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
                <isActive>false</isActive>
                <label>Declined (Acceptance)</label>
            </value>
            <value>
                <fullName>No Response</fullName>
                <isActive>false</isActive>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
                <isActive>false</isActive>
                <label>Non-Responsive (Admin)</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
                <isActive>false</isActive>
                <label>On Hold (Admin)</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site_Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Activation_Status__c</fullName>
    <label>Site Activation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Activated (Admin)</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
                <default>true</default>
                <label>Deactivated</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_UpdateSiteActivationField.cls
public class Batch_UpdateSiteActivationField implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        List<String> referralsStatus = new List<String>{'Accepted','Accepted (Admin)','Deactivated (Admin)','Deactivated','Invitation Sent','On Hold (Admin)','On Hold'};
        return Database.getQueryLocator('select Id,Site_Activation_Status__c, Override_PI_Referral_Status__c  from Study_Site__c '
                                        +'where Site_Activation_Status__c !=null and (Override_PI_Referral_Status__c  IN :referralsStatus or Override_PI_Referral_Status__c =null) ');
    }
    public void execute(Database.BatchableContext BC, List<Study_Site__c> scope){
        for(Study_Site__c ss : scope){
            system.debug('ss.Override_PI_Referral_Status__c :: '+ss.Override_PI_Referral_Status__c);
            if(ss.Override_PI_Referral_Status__c == 'Accepted' || ss.Override_PI_Referral_Status__c =='Accepted (Admin)'){
                ss.Site_Activation_Status__c = 'Activated (Admin)';
            }
            else if(ss.Override_PI_Referral_Status__c =='Deactivated (Admin)'
               || ss.Override_PI_Referral_Status__c =='Deactivated'
               || ss.Override_PI_Referral_Status__c == 'Invitation Sent'){
                ss.Site_Activation_Status__c = 'Deactivated';
            }
            else if(ss.Override_PI_Referral_Status__c == 'On Hold (Admin)'
               || ss.Override_PI_Referral_Status__c == 'On Hold'){
                ss.Site_Activation_Status__c = 'On Hold';
            }
            else if(ss.Override_PI_Referral_Status__c ==null || ss.Override_PI_Referral_Status__c =='' ){
                ss.Site_Activation_Status__c = 'Deactivated (Admin)';
            }
        }
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.PrepareAdditionalFieldsHandler.class);
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.DeleteStatusHistoryOnDeleteHandler.class);
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.CreatePIOrSendNotificationHandler.class);
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.SwitchContactUserModeHandler.class);
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.CreateStatusHistoryHandler.class);
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.CreateHCPEnrollmentsForRPInWhiteListHandler.class);
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.SetSuppressEmailsFieldAccordingToStudy.class);
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.AssignCommunityPermissionsForUser.class);
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.SetEnableCCSupportFieldAccordingToStudy.class);
        update scope;
    }
    public void finish(Database.BatchableContext BC){
        
    }
}