force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/First_Reminder__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder__c</fullName>
    <defaultValue>24</defaultValue>
    <label>First Reminder</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Second_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Second_Reminder__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Second Reminder</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/onetime-scripts/classes/Batch_Updatereminderdefaultvalues.cls
global without sharing class Batch_Updatereminderdefaultvalues implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query  = 'Select id,First_Reminder__c,Second_Reminder__c from Study_Site__c where Second_Reminder__c = null or First_Reminder__c = null';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<Sobject> records){
        List<Study_Site__c> lst_Studysite = (List<Study_Site__c>)records;
        List<Study_Site__c> toupdatestudysite = new List<Study_Site__c>();
        for(Study_Site__c ss:lst_Studysite){
            Study_Site__c sstoupdate = new Study_Site__c();
            sstoupdate.Id = ss.Id;
            if(ss.Second_Reminder__c == null){
                sstoupdate.Second_Reminder__c = 1;
            }
            if(ss.First_Reminder__c == null){
                sstoupdate.First_Reminder__c = 24;
            } 
            toupdatestudysite.add(sstoupdate);
        }
        if(!toupdatestudysite.isEmpty()){
            TriggerHandlerExecutor.bypassHandler(StudySiteTriggerHandler.PrepareAdditionalFieldsHandler.class);
            TriggerHandlerExecutor.bypassHandler(StudySiteTriggerHandler.CreatePIOrSendNotificationHandler.class);
            TriggerHandlerExecutor.bypassHandler(StudySiteTriggerHandler.SwitchContactUserModeHandler.class);
            TriggerHandlerExecutor.bypassHandler(StudySiteTriggerHandler.CreateStatusHistoryHandler.class);
            TriggerHandlerExecutor.bypassHandler(StudySiteTriggerHandler.CreateHCPEnrollmentsForRPInWhiteListHandler.class);
            TriggerHandlerExecutor.bypassHandler(StudySiteTriggerHandler.SetSuppressEmailsFieldAccordingToStudy.class);
            TriggerHandlerExecutor.bypassHandler(StudySiteTriggerHandler.AssignCommunityPermissionsForUser.class);
            TriggerHandlerExecutor.bypassHandler(StudySiteTriggerHandler.SetEnableCCSupportFieldAccordingToStudy.class );
            TriggerHandlerExecutor.bypassHandler(StudySiteTriggerHandler.DeleteStatusHistoryOnDeleteHandler.class);
            update toupdatestudysite;
        }
        
    }    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}