force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Alert</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/Viewed__c.field-meta.xml
<CustomField>
    <fullName>Viewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Viewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/alerts/classes/AlertsRemote.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class AlertsRemote {
    
    @AuraEnabled
    public static String getPPAlerts(String userMode) { // Changes for PEH -8551 - Anitha
        try {
            List<Alert> alerts = Alert.getContactPPAlerts( 
                CommunityService.getUserContact().Id,
                userMode
            );
            return JSON.serialize(alerts);
        } catch (Exception e) {
            return (String) AuraHelper.throwException(e);
        }
    }

    @AuraEnabled
    public static String getAlerts(String userMode) {
        try {
            List<Alert> alerts = Alert.getContactAlerts(
                CommunityService.getUserContact().Id,
                userMode
            );
            return JSON.serialize(alerts);
        } catch (Exception e) {
            return (String) AuraHelper.throwException(e);
        }
    }

    @AuraEnabled
    public static void setAlertViewed(Id alertId) {
        try {
            Alert__c alert = new Alert__c(Id = alertId, Viewed__c = true);
            update alert;
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
    }
}