force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Alert</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/Viewed__c.field-meta.xml
<CustomField>
    <fullName>Viewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Viewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AlertsRemote.cls
/**
 * Created by Leonid Bartenev
 */

public class AlertsRemote {
    
    @AuraEnabled
    public static String getAlerts(String userMode){
        List<Alert> alerts = Alert.getContactAlerts(CommunityService.getUserContact().Id);
        return JSON.serialize(alerts);
    }
    
    @AuraEnabled
    public static void setAlertViewed(Id alertId){
        try{
            Alert__c alert = new Alert__c(Id = alertId, Viewed__c = true);
            update alert;
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

}