force-app/main/integration/objects/Integration_Patient__c/Integration_Patient__c.object-meta.xml
<CustomObject>
    <label>Integration Patient</label>
    <nameField>
        <displayFormat>IP-{00000000}</displayFormat>
        <label>Integration Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Patient__c/fields/STUDYID__c.field-meta.xml
<CustomField>
    <fullName>STUDYID__c</fullName>
    <label>STUDYID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationPatientBatchDeletion.cls
global class IntegrationPatientBatchDeletion implements Database.Batchable<sObject>{
	private String ctpId;
    global IntegrationPatientBatchDeletion(String ctpId){
        this.ctpId = ctpId;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query='SELECT Id, Name, STUDYID__c FROM Integration_Patient__c WHERE STUDYID__c = :ctpId';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC,List<Integration_Patient__c> intPatientLst){
        List<Integration_Patient__c> recordToBeDeletedIP = [SELECT Id, Name, STUDYID__c FROM Integration_Patient__c WHERE Id IN :intPatientLst];
        if(!recordToBeDeletedIP.isEmpty()){
            delete recordToBeDeletedIP;
        }
    }
    global void finish(Database.BatchableContext BC){
        
    }
}