force-app/main/integration/objects/Integration_Patient__c/Integration_Patient__c.object-meta.xml
<CustomObject>
    <label>Integration Patient</label>
    <nameField>
        <displayFormat>IP-{00000000}</displayFormat>
        <label>Integration Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/integration/objects/Integration_Patient__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient__c/fields/IsDeletedInSDH__c.field-meta.xml
<CustomField>
    <fullName>IsDeletedInSDH__c</fullName>
    <label>IsDeletedInSDH</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient__c/fields/Subject_Status__c.field-meta.xml
<CustomField>
    <fullName>Subject_Status__c</fullName>
    <label>Subject Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Study_Enrollment__c/Participant_Study_Enrollment__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Participant Study Enrollment</label>
    <nameField>
        <displayFormat>PSE{00000000}</displayFormat>
        <label>Participant Study Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Study Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <formula>Study_ID__c + &quot;~&quot; + Study_Site__r.Study_Site_Number__c + &quot;~&quot; + Screening_ID__c</formula>
    <label>External Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/IsSubjectIDverifiedInSDH__c.field-meta.xml
<CustomField>
    <fullName>IsSubjectIDverifiedInSDH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSubjectIDverifiedInSDH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SDH_Status__mdt/SDH_Status__mdt.object-meta.xml
<CustomObject>
    <label>SDH Status</label>
    <pluralLabel>SDH Statuses</pluralLabel>
</CustomObject>

force-app/main/default/classes/IntegrationPatientTriggerHandler.cls
/**
 * Created by Denis Z on 17-Jun-19.
 */

public with sharing class IntegrationPatientTriggerHandler {

    public class UpdatePatientsHandler extends TriggerHandler{

        public override void afterInsert(List<SObject> newList) {
            updatePatients(newList);
        }

        public override void afterUpdate(List<SObject> newList, Map<Id, SObject> oldMap) {
            updatePatients(newList);
        }
    }

    @TestVisible
    private static void updatePatients(List<Integration_Patient__c> newList){
        List<String> externalKeys = new List<String>();
        for(Integration_Patient__c patient : newList){
            externalKeys.add(patient.External_ID__c);
        }
        List<Participant_Study_Enrollment__c> pseList = PSEService.getPSEListByExternalIds(externalKeys);
        List<SDH_Status__mdt> sdhStatuses = [
            SELECT
                    Label,
                    Salesforce_Status__c,
                    Salesforce_Object__c
            FROM    SDH_Status__mdt
        ];
        Map<String, SDH_Status__mdt> sdhStatusMap = new Map<String, SDH_Status__mdt>();
        for(SDH_Status__mdt sdhStatus : sdhStatuses){
            sdhStatusMap.put(sdhStatus.Label.remove(' '), sdhStatus);
        }
        Map<String, Participant_Study_Enrollment__c> pseMap = new Map<String, Participant_Study_Enrollment__c>();
        for(Participant_Study_Enrollment__c pse : pseList){
            pseMap.put(pse.External_Key__c, pse);
        }
        for(Integration_Patient__c patient : newList){
            if(pseMap.containsKey(patient.External_ID__c)) {
                pseMap.get(patient.External_ID__c).Status__c = getPSEStatus(sdhStatusMap, patient);
                if (patient.IsDeletedInSDH__c == 'N') {
                    pseMap.get(patient.External_ID__c).IsSubjectIDverifiedInSDH__c = true;
                } else {
                    pseMap.get(patient.External_ID__c).IsSubjectIDverifiedInSDH__c = false;
                }
            }
        }
        update pseMap.values();
    }

    private static String getPSEStatus(Map<String, SDH_Status__mdt> sdhStatusMap, Integration_Patient__c patient){
        if(sdhStatusMap.containsKey(patient.Subject_Status__c.remove(' ')) && sdhStatusMap.get(patient.Subject_Status__c.remove(' ')).Salesforce_Object__c == 'Participant Study Enrollment'){
            return sdhStatusMap.get(patient.Subject_Status__c.remove(' ')).Salesforce_Status__c;
        }
        return null;
    }

}