force-app/main/resources/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object contains Video/Articles</description>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/Therapeutic_Area_Patient__c.object-meta.xml
<CustomObject>
    <label>Therapeutic Area Patient</label>
    <nameField>
        <displayFormat>TAP - {00000000}</displayFormat>
        <label>Therapeutic Area Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Therapeutic Area Patients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Therapeutic Area Patients</relationshipLabel>
    <relationshipName>Therapeutic_Area_Patients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/resources/classes/ResourceArticleVideoService.cls
public virtual inherited sharing class ResourceArticleVideoService extends ResourceService {
    private static ResourceArticleVideoService instance;

    public static ResourceArticleVideoService getInstance() {
        if (instance == null)
            instance = new ResourceArticleVideoService();
        return instance;
    }

    public override virtual List<Resource__c> getResources() {
        List<Resource__c> sortedResources = new List<Resource__c>();
        if (
            pState.value == ParticipantService.ParticipantStates.REFERRAL ||
            pState.value == ParticipantService.ParticipantStates.PARTICIPANT
        ) {
            sortedResources.addAll(
                ResourceStudyRelatedService.getInstance()
                    .init(resourceType, resourceId, ResourceService.RESOURCE_SOURCE_STUDY)
                    .getResources()
            );
        }
        String contentClass = ResourceService.RESOURCE_SOURCE_PLATFORM;
        if (pState.value == ParticipantService.ParticipantStates.ALUMNI)
            contentClass = ResourceService.RESOURCE_SOURCE_THIRD_PARTY;

        if (pState.value == ParticipantService.ParticipantStates.ALUMNI) {
            List<String> therapeuticAreas = new List<String>();
            for (
                Therapeutic_Area_Patient__c tap : ParticipantDecoupler.getTherapeuticAreaPatients()
            ) {
                therapeuticAreas.add(tap.Therapeutic_Area__c);
            }
            sortedResources.addAll(
                ResourceTARelatedService.getInstance()
                    .init(resourceType, resourceId, contentClass, therapeuticAreas)
                    .getResources()
            );
        }
        return sortedResources;
    }

    protected override virtual ResourceService.ResourceWrapperContainer getErrorNoResources() {
        return resourceType == ResourceService.RESOURCE_TYPE_ARTICLE
            ? ResourceService.getErrorNoArticles(false)
            : ResourceService.getErrorNoVideos(false);
    }

    protected override virtual Boolean isObjectsToFilterMissing() {
        return ParticipantDecoupler.getTherapeuticAreaPatients().isEmpty() && pState.ctp == null;
    }
}