force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Mailing Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <label>Mailing Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Permit_IQVIA_to_contact_about_study__c.field-meta.xml
<CustomField>
    <fullName>Permit_IQVIA_to_contact_about_study__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked when share the above information with IQVIA and its affiliates checkbox is checked in the front end</inlineHelpText>
    <label>Permit personal information storage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Permit_Mail_Email_contact_for_this_study__c.field-meta.xml
<CustomField>
    <fullName>Permit_Mail_Email_contact_for_this_study__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permit Mail-Email contact for this study</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Permit_SMS_Text_for_this_study__c.field-meta.xml
<CustomField>
    <fullName>Permit_SMS_Text_for_this_study__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permit SMS/Text for this study</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Permit_Voice_Text_contact_for_this_study__c.field-meta.xml
<CustomField>
    <fullName>Permit_Voice_Text_contact_for_this_study__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permit voice call for this study</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Email_Consent_Time__c.field-meta.xml
<CustomField>
    <fullName>Study_Email_Consent_Time__c</fullName>
    <label>Study Email Consent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Phone_Consent_Time__c.field-meta.xml
<CustomField>
    <fullName>Study_Phone_Consent_Time__c</fullName>
    <label>Study Phone Consent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_PI_Storage_Consent_Time__c.field-meta.xml
<CustomField>
    <fullName>Study_PI_Storage_Consent_Time__c</fullName>
    <label>Study PI Storage Consent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_SMS_Consent_Time__c.field-meta.xml
<CustomField>
    <fullName>Study_SMS_Consent_Time__c</fullName>
    <label>Study SMS Consent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Batch_UpdatetimestampsforexistingPERTest.cls
@isTest
public with sharing class Batch_UpdatetimestampsforexistingPERTest {
    @isTest
    public static void test(){
        Test.startTest();
        TestData.loadTestData();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = new Participant_Enrollment__c();
        pe.id = testData.pe.Id;
        pe.Permit_Mail_Email_contact_for_this_study__c = true;
        pe.Permit_Voice_Text_contact_for_this_study__c = true;
        pe.Permit_SMS_Text_for_this_study__c = true;
        pe.Permit_IQVIA_to_contact_about_study__c = true;
        pe.Study_Email_Consent_Time__c = null;
        pe.Study_Phone_Consent_Time__c = null;
        pe.Study_SMS_Consent_Time__c = null;
        pe.Study_PI_Storage_Consent_Time__c = null;
        TriggerHandlerExecutor.bypassHandler(ParticipantEnrollmentTriggerHandler.StudyConsentTimestamps.class);
        update pe;
        Participant_Enrollment__c pe1 = [select Id,Participant__c from Participant_Enrollment__c limit 1];
        Participant__c part = new Participant__c();
        part.Id = pe1.Participant__c;
        part.Mailing_Country__c = 'United Kingdom';
        part.Mailing_Country_Code__c = 'GB';
        update part;
        List<String> perIds = new List<String>();
		List<String> perExcludeIds = new List<String>();
        Batch_UpdatetimestampsforexistingPER batch = new Batch_UpdatetimestampsforexistingPER(perIds,perExcludeIds);
        database.executeBatch(batch, 2000);
        Test.stopTest();
    }
    @isTest
    public static void test_ExcludeId(){
        Test.startTest();
        TestData.loadTestData();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = new Participant_Enrollment__c();
        pe.id = testData.pe.Id;
        pe.Permit_Mail_Email_contact_for_this_study__c = true;
        pe.Permit_Voice_Text_contact_for_this_study__c = true;
        pe.Permit_SMS_Text_for_this_study__c = true;
        pe.Permit_IQVIA_to_contact_about_study__c = true;
        pe.Study_Email_Consent_Time__c = null;
        pe.Study_Phone_Consent_Time__c = null;
        pe.Study_SMS_Consent_Time__c = null;
        pe.Study_PI_Storage_Consent_Time__c = null;
        TriggerHandlerExecutor.bypassHandler(ParticipantEnrollmentTriggerHandler.StudyConsentTimestamps.class);
        update pe;
        Participant_Enrollment__c pe1 = [select Id,Participant__c from Participant_Enrollment__c limit 1];
        Participant__c part = new Participant__c();
        part.Id = pe1.Participant__c;
        part.Mailing_Country__c = 'United Kingdom';
        part.Mailing_Country_Code__c = 'GB';
        update part;
        List<String> perIds = new List<String>();
		List<String> perExcludeIds = new List<String>();
        perExcludeIds.add(pe.Id);
        Batch_UpdatetimestampsforexistingPER batch = new Batch_UpdatetimestampsforexistingPER(perIds,perExcludeIds);
        database.executeBatch(batch, 2000);
        Test.stopTest();
    }
    @isTest
    public static void test_Include(){
        Test.startTest();
        TestData.loadTestData();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = new Participant_Enrollment__c();
        pe.id = testData.pe.Id;
        pe.Permit_Mail_Email_contact_for_this_study__c = true;
        pe.Permit_Voice_Text_contact_for_this_study__c = true;
        pe.Permit_SMS_Text_for_this_study__c = true;
        pe.Permit_IQVIA_to_contact_about_study__c = true;
        pe.Study_Email_Consent_Time__c = null;
        pe.Study_Phone_Consent_Time__c = null;
        pe.Study_SMS_Consent_Time__c = null;
        pe.Study_PI_Storage_Consent_Time__c = null;
        TriggerHandlerExecutor.bypassHandler(ParticipantEnrollmentTriggerHandler.StudyConsentTimestamps.class);
        update pe;
        Participant_Enrollment__c pe1 = [select Id,Participant__c from Participant_Enrollment__c limit 1];
        Participant__c part = new Participant__c();
        part.Id = pe1.Participant__c;
        part.Mailing_Country__c = 'United Kingdom';
        part.Mailing_Country_Code__c = 'GB';
        update part;
        List<String> perIds = new List<String>();
		List<String> perExcludeIds = new List<String>();
        perIds.add(pe.Id);
        Batch_UpdatetimestampsforexistingPER batch = new Batch_UpdatetimestampsforexistingPER(perIds,perExcludeIds);
        database.executeBatch(batch, 2000);
        Test.stopTest();
    }
    @isTest
    public static void test_MultiInputs(){
        Test.startTest();
        TestData.loadTestData();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = new Participant_Enrollment__c();
        pe.id = testData.pe.Id;
        pe.Permit_Mail_Email_contact_for_this_study__c = true;
        pe.Permit_Voice_Text_contact_for_this_study__c = true;
        pe.Permit_SMS_Text_for_this_study__c = true;
        pe.Permit_IQVIA_to_contact_about_study__c = true;
        pe.Study_Email_Consent_Time__c = null;
        pe.Study_Phone_Consent_Time__c = null;
        pe.Study_SMS_Consent_Time__c = null;
        pe.Study_PI_Storage_Consent_Time__c = null;
        TriggerHandlerExecutor.bypassHandler(ParticipantEnrollmentTriggerHandler.StudyConsentTimestamps.class);
        update pe;
        List<Participant_Enrollment__c> peList = [select Id,Participant__c from Participant_Enrollment__c limit 2];
        Participant__c part = new Participant__c();
        part.Id = peList[0].Participant__c;
        part.Mailing_Country__c = 'United Kingdom';
        part.Mailing_Country_Code__c = 'GB';
        update part;
        List<String> perIds = new List<String>();
		List<String> perExcludeIds = new List<String>();
        perIds.add(peList[0].Id);
        perExcludeIds.add(peList[1].Id);
        Batch_UpdatetimestampsforexistingPER batch = new Batch_UpdatetimestampsforexistingPER(perIds,perExcludeIds);
        database.executeBatch(batch, 2000);
        Test.stopTest();
    }
    
    
    
}