force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Email</label>

    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Participant&#39;s First Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s First Name</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Mailing City</label>
    <length>80</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Phone</label>

    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/Patient_Delegate__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate</label>
    <nameField>
        <displayFormat>PD-{00000000}</displayFormat>
        <label>Patient Delegate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/scheduled-batch-implementation/classes/Batch_CreateParticipantForDelegate.cls
/**
 * Created by Olga Skrynnikova on 4/16/2020.
 */

public without sharing class Batch_CreateParticipantForDelegate implements Database.Batchable<SObject>{

    public Database.QueryLocator start(Database.BatchableContext param1) {
        return Database.getQueryLocator([
                SELECT
                        Id,
                        Contact__c,
                        Participant__c
                FROM Patient_Delegate__c
        ]);
    }

    public void execute(Database.BatchableContext param1, List<Patient_Delegate__c> patientDelegates) {
        List<Id> delegateConList = new List<Id>();
        for(Patient_Delegate__c pd: patientDelegates) if (!delegateConList.contains(pd.Contact__c)) delegateConList.add(pd.Contact__c);

        List<Participant__c> delegateWithParticipant = [SELECT Id, Contact__c FROM Participant__c WHERE Contact__c IN: delegateConList];
        System.debug('>>>delegateWithParticipant' + delegateWithParticipant);
        List<Id> delegateConIdsWithParticipants = new List<Id>();
        for(Participant__c p: delegateWithParticipant) if (p.Contact__c != null && !delegateConIdsWithParticipants.contains(p.Contact__c)) delegateConIdsWithParticipants.add(p.Contact__c);
        List<Contact> contacts = [
                SELECT Id, FirstName, LastName, Phone, Email, MailingCity, MailingCountryCode, MailingStateCode
                FROM Contact
                WHERE Id IN:delegateConList
        ];
        System.debug('>>>contacts' + contacts);

        List<Participant__c> participantsForInsert = new List<Participant__c>();
        for (Contact contact : contacts) {

            if (!delegateConIdsWithParticipants.contains(contact.Id)) {
                participantsForInsert.add(new Participant__c(
                        Contact__c = contact.Id,
                        First_Name__c = contact.FirstName,
                        Last_Name__c = contact.LastName,
                        Email__c = contact.Email,
                        Phone__c = contact.Phone,
                        Mailing_City__c = contact.MailingCity,
                        Mailing_Country_Code__c = contact.MailingCountryCode,
                        Mailing_State_Code__c = contact.MailingStateCode

                ));
            }
        }
        System.debug('>>>participantsForInsert' + participantsForInsert);
        if (participantsForInsert.size() > 0) insert participantsForInsert;
    }
    public void finish(Database.BatchableContext param1) {
    }

}