force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Email</label>

    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Participant&#39;s First Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s First Name</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Phone</label>

    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/HCP__c.field-meta.xml
<CustomField>
    <fullName>HCP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HCP</label>
    <referenceTo>HCP_Enrollment__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <label>Mailing Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Patient_ID__c.field-meta.xml
<CustomField>
    <fullName>Patient_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Patient ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source__c</fullName>
    <description>HCP/Physician Participant Referral Source</description>
    <inlineHelpText>HCP/Physician Participant Referral Source</inlineHelpText>
    <label>Referral Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>HCP Prescreen Log</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>ePR</fullName>
            </value>
            <value>
                <fullName>ACOE</fullName>
            </value>
            <value>
                <fullName>3rd_Party</fullName>
                <label>3rd Party</label>
            </value>
            <value>
                <fullName>Autocruitment</fullName>
            </value>
            <value>
                <fullName>23andMe</fullName>
            </value>
            <value>
                <fullName>IQVIA registry</fullName>
            </value>
            <value>
			 <fullName>Ciitizen</fullName>
                </value>
            <value>
                <fullName>MassiveBio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Screening_ID__c.field-meta.xml
<CustomField>
    <fullName>Screening_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Obtain the Interactive Voice Response System (IVRS) Number/ Interactive Web Response System (IWRS) Number for the  participant</inlineHelpText>
    <label>Screening ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/tests/classes/Test_ReferringRemote.cls
/**
 * Created by Denis on 15.04.2019.
 */

@IsTest
private without sharing class Test_ReferringRemote {
    
    @IsTest
    static void saveParticipant() {
        TestData.loadTestData();
        Test.startTest();
        TestData testDataInstance = new TestData();
        System.runAs(testDataInstance.hcpUser){
            Participant_Enrollment__c pe = new Participant_Enrollment__c(
                    HCP__c = testDataInstance.hcpEnrollment.Id,
                    Study_Site__c = testDataInstance.ss.Id,
                    Patient_ID__c = 'SomePatientId1',
                    Referral_Source__c = 'HCP',
                    Screening_ID__c = 'TestScrId12345'
            );
            Participant__c participant = new Participant__c(
                    First_Name__c = 'PTest',
                    Last_Name__c = 'PTest',
                    Phone__c = '13413223',
                    Date_of_Birth__c = '1990-11-11',
                    Email__c = 'partTest@email.com',
                    Mailing_Country_Code__c = 'US',
                    Mailing_State_Code__c = 'AL'
            );
            Participant__c participantDelegate = new Participant__c(
                    First_Name__c = 'PTestDelegate',
                    Last_Name__c = 'PTestDelegate',
                    Phone__c = '13413123',
                    Email__c = 'PTestDelegate@email.com',
                    Mailing_Country_Code__c = 'US',
                    Mailing_State_Code__c = 'AL'
            );
            ReferringRemote.checkNeedsGuardian(JSON.serialize(participant));
            ReferringRemote.saveParticipant(testDataInstance.hcpEnrollment.Id, JSON.serialize(pe), JSON.serialize(participant), JSON.serialize(participantDelegate), null, null);
            ReferringRemote.setfailedReferral(JSON.serialize(pe), ParticipantEnrollmentService.NON_REF_REASON_STATUS_FAILED_PE_SCREENING);
        }
        Test.stopTest();
    }
    
    @IsTest
    static void getInitData() {
        TestData.loadTestData();
        Test.startTest();
        TestData testDataInstance = new TestData();
        System.runAs(testDataInstance.hcpUser){
            String initDataStr = ReferringRemote.getInitData(testDataInstance.ctp.Id, testDataInstance.pe.Id, testDataInstance.hcpEnrollment.Id, CommunityService.USER_MODE_HCP, null);
        }
        Test.stopTest();
    }

}