force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Pending_Payments__c.field-meta.xml
<CustomField>
    <fullName>Pending_Payments__c</fullName>
    <label>Pending Payments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Vendor__c/Payment_Vendor__c.object-meta.xml
<CustomObject>
    <label>Payment Vendor</label>
    <nameField>
        <label>Payment Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Vendor__c/fields/Link_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Link_Vendor__c</fullName>
    <label>Link Vendor</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PaymentVendorSettings__c/PaymentVendorSettings__c.object-meta.xml
<CustomObject>
    <label>PaymentVendorSettings</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>PaymentVendorSettings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PaymentVendorSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentVendorSettings__c/fields/Payment_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Vendor</label>
    <referenceTo>Payment_Vendor__c</referenceTo>
    <relationshipLabel>PaymentVendorSettings</relationshipLabel>
    <relationshipName>PaymentVendorSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PaymentVendorSettings__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>PaymentVendorSettings</relationshipLabel>
    <relationshipName>PaymentVendorSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentsRemote.cls
/**
 * Created by Olga Skrynnikova on 12/20/2019.
 */

public without sharing class PaymentsRemote {
    public class InitData{
        @AuraEnabled public Participant__c participant;
        @AuraEnabled public String pendingPayments;
        @AuraEnabled public String href;
        @AuraEnabled public Boolean informationAvailable;
    }

    @AuraEnabled
    public static InitData getPaymentData() {
        try {
            InitData initData = new InitData();
            ParticipantService.ParticipantState ps = ParticipantService.getInstance().getState();
            initData.participant = ps.participant;
            initData.informationAvailable = true;

            if(String.isEmpty(initData.participant.Pending_Payments__c)) initData.pendingPayments = '0.00';
            else initData.pendingPayments = initData.participant.Pending_Payments__c;

            List<PaymentVendorSettings__c> pvs = [
                    SELECT Id, Study_Site__c, Payment_Vendor__r.Link_Vendor__c
                    FROM PaymentVendorSettings__c
                    WHERE Study_Site__c =: ps.pe.Study_Site__c
            ];
            if(String.isEmpty(initData.participant.Status__c)) initData.informationAvailable = false;

            if(!pvs.isEmpty()) initData.href = pvs[0].Payment_Vendor__r.Link_Vendor__c;
            else initData.href = 'none';

            return initData;
        } catch (Exception e) {
            return (InitData) AuraHelper.throwException(e);
        }
    }
}