force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit__c/Televisit__c.object-meta.xml
<CustomObject>
    <label>Televisit</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Televisit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Televisits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Call will be ended after the planned duration time</inlineHelpText>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>15 minutes</fullName>
            </value>
            <value>
                <fullName>30 minutes</fullName>
            </value>
            <value>
                <fullName>45 minutes</fullName>
            </value>
            <value>
                <fullName>60 minutes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Televisits</relationshipLabel>
    <relationshipName>Televisits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Source_Community__c.field-meta.xml
<CustomField>
    <fullName>Source_Community__c</fullName>
    <label>Source Community</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IQVIA Referral Hub</fullName>
            </value>
            <value>
                <fullName>Janssen Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Visit Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Visit_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_End_Date_Time__c</fullName>
    <label>Visit End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/Televisit_Attendee__c.object-meta.xml
<CustomObject>
    <label>Televisit Attendee</label>
    <nameField>
        <label>Televisit Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Televisit Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit_Attendee__c/fields/Attendee_Email__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Email__c</fullName>
    <label>Attendee Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Type__c</fullName>
    <label>Attendee Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Televisit__c.field-meta.xml
<CustomField>
    <fullName>Televisit__c</fullName>
    <label>Televisit</label>
    <referenceTo>Televisit__c</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_TelevisitMeetBannerController.cls
@IsTest
public class Test_TelevisitMeetBannerController {
	@TestSetup
    static void init() {
        Test.startTest();
        TestData.loadTestData();
        Test.stopTest();
    }
    @IsTest
    static void testTelevisitBanner() {
        Participant_Enrollment__c  enroll = [select Id,Participant__c from Participant_Enrollment__c limit 1];
        Contact con = [select Id from Contact limit 1];
        
        Participant__c participant = new Participant__c(id=enroll.Participant__c);
        participant.Contact__c = con.id;
        update participant;
        
        TriggerHandlerExecutor.bypassHandler(
                                TelevisitTriggerHandler.TelevisitEventTrigger.class
                            );
        TriggerHandlerExecutor.bypassHandler(
                                TelevisitTriggerHandler.NotifyAttendees.class
                            );
        Televisit__c visit = new Televisit__c();
        visit.Title__c = 'Test Class Meet';
        visit.Duration__c = '15 minutes';
        visit.Source_Community__c = 'IQVIA Referral Hub';
        visit.Visit_Date_Time__c = Datetime.now();
        visit.Visit_End_Date_Time__c = Datetime.now().addMinutes(15);
        visit.Participant_Enrollment__c = enroll.Id;
        visit.Status__c = 'Scheduled';
        insert visit;
        Televisit_Attendee__c attendee = new Televisit_Attendee__c ();
        attendee.Attendee_Type__c = 'PI';
        attendee.Televisit__c = visit.Id;
        attendee.User__c = UserInfo.getUserId();
        
        Televisit_Attendee__c attendee2 = new Televisit_Attendee__c ();
        attendee2.Attendee_Type__c = 'Participant';
        attendee2.Televisit__c = visit.Id;
        attendee2.Attendee_Email__c = 'melisha.dsa@iqvia.com';
        attendee2.Contact__c = con.Id;
        
        List<Televisit_Attendee__c> attendeeLst = new List<Televisit_Attendee__c>();
        attendeeLst.add(attendee);
        attendeeLst.add(attendee2);
        insert attendeeLst;
        TelevisitMeetBannerController.getSessionId();
        TelevisitMeetBannerController.getVisits('IQVIA Referral Hub','PI');
    }
}