force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>First_Name__c + &#39; &#39; + Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/Patient_Visit__c.object-meta.xml
<CustomObject>
    <label>Patient Visit</label>
    <nameField>
        <displayFormat>PV-{000000}</displayFormat>
        <label>Patient Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Visit__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/visits/objects/Patient_Visit__c/fields/Visit_Number__c.field-meta.xml
<CustomField>
    <fullName>Visit_Number__c</fullName>
    <label>Visit Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/Visit_Result__c.object-meta.xml
<CustomObject>
    <label>Visit_Result</label>
    <nameField>
        <displayFormat>VR-{0000000}</displayFormat>
        <label>Visit_Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit_Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Result__c/fields/Actual_Value__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value__c</fullName>
    <label>Actual Result</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Max_Value__c</fullName>
    <label>Max Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/visits/objects/Visit_Result__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Min_Value__c.field-meta.xml
<CustomField>
    <fullName>Min_Value__c</fullName>
    <label>Min Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Patient_Visit__c.field-meta.xml
<CustomField>
    <fullName>Patient_Visit__c</fullName>
    <label>Patient Visit</label>
    <referenceTo>Patient_Visit__c</referenceTo>
    <relationshipLabel>Visit_Results</relationshipLabel>
    <relationshipName>Visit_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Result_Type__c.field-meta.xml
<CustomField>
    <fullName>Result_Type__c</fullName>
    <description>.</description>
    <label>Result Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Visit_Result_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Result_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Result Type</label>
    <referenceTo>Visit_Result_Type__c</referenceTo>
    <relationshipLabel>Visit_Results</relationshipLabel>
    <relationshipName>Visit_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/recordTypes/Vitals.recordType-meta.xml
<RecordType>
    <fullName>Vitals</fullName>
    <active>true</active>
    <label>Vitals</label>
</RecordType>

force-app/main/default/objects/Visit_Result_Type__c/Visit_Result_Type__c.object-meta.xml
<CustomObject>
    <label>Visit Result Type</label>
    <nameField>
        <displayFormat>VRT-{000000}</displayFormat>
        <label>Visit Result Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Result Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/visits/objects/Visit_Result_Type_Sharing__c/Visit_Result_Type_Sharing__c.object-meta.xml
<CustomObject>
    <label>Visit Result Type Sharing</label>
    <nameField>
        <displayFormat>VRTS-{000000}</displayFormat>
        <label>Visit Result Type Sharing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Result Type Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/visits/objects/Visit_Result_TypeM__mdt/Visit_Result_TypeM__mdt.object-meta.xml
<CustomObject>
    <label>Visit Result Type</label>
    <pluralLabel>Visit Result Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Visit_Result_TypeM__mdt/fields/Description_Label_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Description_Label_Api_Name__c</fullName>
    <description>Label Api Name</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/visits/objects/Visit_Result_TypeM__mdt/fields/Visit_Result_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Result_Type__c</fullName>
    <label>Visit Result Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lab</fullName>
                <default>true</default>
                <label>Lab</label>
            </value>
            <value>
                <fullName>Vital</fullName>
            </value>
            <value>
                <fullName>Biomarkers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Result_TypeM_Dashboard_Config__mdt/Visit_Result_TypeM_Dashboard_Config__mdt.object-meta.xml
<CustomObject>
    <label>Visit Result Type Dashboard Config</label>
    <pluralLabel>Visit Result Types Dashboard Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Visit_Result_TypeM_Dashboard_Config__mdt/fields/Dashboard_Name__c.field-meta.xml
<CustomField>
    <fullName>Dashboard_Name__c</fullName>
    <label>Dashboard Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/visits/objects/Visit_Result_TypeM_Dashboard_Config__mdt/fields/Visit_Result_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Result_Type__c</fullName>
    <label>Visit Result Type</label>
    <referenceTo>Visit_Result_TypeM__mdt</referenceTo>
    <relationshipLabel>Visit Result Types Dashboard Config</relationshipLabel>
    <relationshipName>Visit_Result_Types_Dashboard_Config</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/visits/classes/VisitResultsService.cls
public inherited sharing class VisitResultsService {

    public static final String DASHBOARD_TYPE_HOME_PAGE = 'Home Page';

    private VisitResultMService metadataService;
    private Map<String, String> visitResultsMeasurementNamesMap;

    public VisitResultsService() {
        this.metadataService = (VisitResultMService) ClassFactory.newInstance(VisitResultMService.class);
        this.visitResultsMeasurementNamesMap = metadataService.getVisitResultsMeasurementNamesMap();
    }

    public List<String> getVisitResultsGroupNames(String visitResultsMode) {
        return this.metadataService.getVisitResultGroupNames(visitResultsMode);
    }

    public List<VisitResultWrapper> getVisitResultWrappersForDashboard() {

        List<Visit_Result_TypeM_Dashboard_Config__mdt> configs = metadataService.getVisitResultTypeDashboardConfigs();
        List<String> configNames = new List<String>();
        for (Visit_Result_TypeM_Dashboard_Config__mdt visitResultTypeMDashboardConfig : configs) {
            configNames.add(visitResultTypeMDashboardConfig.Visit_Result_Type__r.DeveloperName);
        }

        List<String> ctpAvailableNames = new List<String>();
        List<Visit_Result_Type_Sharing__c> ctpAvailable = [SELECT Id,Type__c FROM Visit_Result_Type_Sharing__c];
        for (Visit_Result_Type_Sharing__c visitResultTypeSharing : ctpAvailable) {
            ctpAvailableNames.add(visitResultTypeSharing.Type__c);
        }

        List<String> filteredVisitResults = new List<String>();
        for (String configName : configNames) {
            if (ctpAvailableNames.contains(configName)) filteredVisitResults.add(configName);
        }

        List<Visit_Result_TypeM_Dashboard_Config__mdt> filteredConfigs = new List<Visit_Result_TypeM_Dashboard_Config__mdt>();
        for (Visit_Result_TypeM_Dashboard_Config__mdt visitResultTypeMDashboardConfig : configs) {
            if (filteredVisitResults.contains(visitResultTypeMDashboardConfig.Visit_Result_Type__r.DeveloperName)) filteredConfigs.add(visitResultTypeMDashboardConfig);
        }


        List<Visit_Result__c> visitResults = VisitResultSharingService.processResults('Vitals',filteredVisitResults);
        if (visitResults.isEmpty() || filteredConfigs.isEmpty()) {
            return new List<VisitResultWrapper>();
        }

        Map<String, Visit_Result__c> visitResultValuesByNames = new Map<String, Visit_Result__c>();
        List<VisitResultWrapper> wrappers = new List<VisitResultWrapper>();
        Boolean listIsNotEmpty = false;

        for (Visit_Result__c singleVisitResult : visitResults) {
            visitResultValuesByNames.put(singleVisitResult.Result_Type__c, singleVisitResult);
        }

        //String languageToTranslate = IRBParticipantService.getSuitableLanguageForIRBTranslation(ParticipantService.getParticipantState().pe.Id);
        for (Visit_Result_TypeM_Dashboard_Config__mdt singleConfig : filteredConfigs) {
            Visit_Result__c visitResult = visitResultValuesByNames.get(singleConfig.Visit_Result_Type__r.DeveloperName);
            if (visitResult != null && visitResult.Actual_Value__c != null) {
                listIsNotEmpty = true;
            }
            wrappers.add(new VisitResultWrapper(visitResult, TranslateHelper.getLabelValue(singleConfig.Dashboard_Name__c), this.visitResultsMeasurementNamesMap));
        }
        return listIsNotEmpty ? wrappers : new List<VisitResultWrapper>();
    }

    public List<Patient_Visit__c> getPatientVisitsForReport(Participant_Enrollment__c pe) {
        String visitsQuery = 'SELECT ' +
                'Name, ' +
                'Completed_Date__c, ' +
                'Participant_Enrollment__r.Participant__r.Full_Name__c, ' +
                'Participant_Enrollment__r.Participant__r.Last_Name__c, ' +
                '(SELECT Name, Actual_Value__c, Min_Value__c, Max_Value__c, Measurement__c, Result_Type__c, Patient_Visit__r.Visit_Number__c FROM Visit_Results__r) ' +
                'FROM Patient_Visit__c ' +
                'WHERE Participant_Enrollment__c = \'' + pe.Id + '\'' +
                ' AND Status__c = \'Completed\'' +
                ' ORDER BY Completed_Date__c NULLS LAST';
        return ((DatabaseProxy) ClassFactory.newInstance(DatabaseProxy.class)).query(visitsQuery, true);
    }

    public VisitResultsContainer getVisitResultsContainer(String visitResultsGroupName,  Map<String,List<String>> visitResultSharings) {
        List<Visit_Result_TypeM__mdt> visitResultTypes = this.metadataService.getVisitResultTypes(visitResultsGroupName);
        List<String> availableVisitResults = visitResultSharings.get(visitResultsGroupName);
        List<Visit_Result_TypeM__mdt> filteredVisitResultTypesIfAvailable = new List<Visit_Result_TypeM__mdt>();
        for (Visit_Result_TypeM__mdt visitResultTypeM : visitResultTypes) {
            if (availableVisitResults.contains(visitResultTypeM.DeveloperName)) filteredVisitResultTypesIfAvailable.add(visitResultTypeM);
        }
        String visitResultMode = this.metadataService.getVisitResultModeByGroupName(visitResultsGroupName);
        List<Visit_Result__c> visitResults = VisitResultSharingService.processResults(visitResultMode, visitResultSharings.get(visitResultsGroupName));

        //String languageToTranslate = IRBParticipantService.getSuitableLanguageForIRBTranslation(ParticipantService.getParticipantState().pe.Id);
        return visitResults.isEmpty()
                ? null
                : new VisitResultsContainer(
                        visitResults[0].Patient_Visit__r,
                        this.getVisitResultWrappers(visitResults, filteredVisitResultTypesIfAvailable),
                        TranslateHelper.getLabelValue(visitResultsGroupName)
                );
    }


    private List<VisitResultWrapper> getVisitResultWrappers(List<Visit_Result__c> visitResults, List<Visit_Result_TypeM__mdt> visitResultTypes) {

        Map<String, Visit_Result__c> visitResultsByTypeDeveloperNames = this.getVisitResultsByTypeDeveloperNames(visitResults);
        List<VisitResultWrapper> wrappers = new List<VisitResultWrapper>();
        for (Visit_Result_TypeM__mdt singleVRT : visitResultTypes) {
            wrappers.add(new VisitResultWrapper(
                    visitResultsByTypeDeveloperNames.get(singleVRT.DeveloperName),
                    TranslateHelper.getLabelValue(singleVRT.DeveloperName),
                    TranslateHelper.getLabelValue(singleVRT.Description_Label_Api_Name__c),
                    this.visitResultsMeasurementNamesMap
            ));
        }
        return wrappers;
    }

    private Map<String, Visit_Result__c> getVisitResultsByTypeDeveloperNames(List<Visit_Result__c> visitResults) {
        Map<String, Visit_Result__c> result = new Map<String, Visit_Result__c>();
        for (Visit_Result__c singleResult : visitResults) {
            result.put(singleResult.Result_Type__c, singleResult);
        }
        return result;
    }

    public class VisitResultsContainer {

        @AuraEnabled
        public List<VisitResultsService.VisitResultWrapper> wrappers;
        @AuraEnabled
        public String visitDate;
        @AuraEnabled
        public String groupName;

        public VisitResultsContainer(Patient_Visit__c visit, List<VisitResultWrapper> wrappers, String groupName) {
            this.wrappers = wrappers;
            if (visit.Completed_Date__c != null) {
                Datetime dt = Datetime.newInstance(visit.Completed_Date__c.year(), visit.Completed_Date__c.month(), visit.Completed_Date__c.day(), 0, 0, 0);
                this.visitDate = dt.format('dd-MMM-yyyy');
            } else this.visitDate = Label.StudyVisit_Information_Not_Available;
            this.groupName = groupName;
        }
    }

    public class VisitResultWrapper {

        @AuraEnabled
        public Double value;
        @AuraEnabled
        public Double minValue;
        @AuraEnabled
        public Double maxValue;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String measurement;
        @AuraEnabled
        public String description;

        public VisitResultWrapper(Visit_Result__c visitResult, String name, String description) {
            this(visitResult, name, description, null);
        }

        public VisitResultWrapper(Visit_Result__c visitResult, String name, String description, Map<String, String> measurementNamesMap) {

            this.name = name;
            this.description = description;
            if (visitResult != null) {
                this.value = visitResult.Actual_Value__c;
                this.minValue = visitResult.Min_Value__c;
                this.maxValue = visitResult.Max_Value__c;
                if (visitResult.Measurement__c != null) {
                    String measurementLowerCase = visitResult.Measurement__c.toLowerCase();
                    if (measurementNamesMap != null && measurementNamesMap.containsKey(measurementLowerCase)) {
                        this.measurement = measurementNamesMap.get(measurementLowerCase).replace('/', ' / ');
                    } else {
                        this.measurement = visitResult.Measurement__c.replace('/', ' / ');
                    }
                }
            }
        }

        public VisitResultWrapper(Visit_Result__c visitResult, String name) {
            this(visitResult, name, new Map<String, String>());
        }

        public VisitResultWrapper(Visit_Result__c visitResult, String name, Map<String, String> measurementNamesMap) {
            this.name = name;
            if (visitResult != null) {
                this.value = visitResult.Actual_Value__c;
                String measurementLowerCase = visitResult.Measurement__c.toLowerCase();
                if (measurementNamesMap != null && measurementNamesMap.containsKey(measurementLowerCase)) {
                    this.measurement = measurementNamesMap.get(measurementLowerCase).replace('/', ' / ');
                } else {
                    this.measurement = visitResult.Measurement__c.replace('/', ' / ');
                }
            }
        }
    }
}