force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Conditions__c.field-meta.xml
<CustomField>
    <fullName>Conditions__c</fullName>
    <description>If Conditions exist for this Participant, then this field &gt;0</description>
    <label>Conditions</label>
    <summaryFilterItems>
        <field>Therapeutic_Area_Patient__c.Condition_Of_Interest_Order__c</field>
        <operation>notEqual</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Therapeutic_Area_Patient__c.Participant__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/recordTypes/Condition_of_Interests.recordType-meta.xml
<RecordType>
    <fullName>Condition_of_Interests</fullName>
    <active>true</active>
    <label>Condition of Interests</label>
</RecordType>

force-app/main/default/objects/Therapeutic_Area_Patient__c/Therapeutic_Area_Patient__c.object-meta.xml
<CustomObject>
    <label>Therapeutic Area Patient</label>
    <nameField>
        <displayFormat>TAP - {00000000}</displayFormat>
        <label>Therapeutic Area Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Therapeutic Area Patients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Condition_Of_Interest_Order__c.field-meta.xml
<CustomField>
    <fullName>Condition_Of_Interest_Order__c</fullName>
    <label>Condition Of Interest Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/IsRelatedToStudy__c.field-meta.xml
<CustomField>
    <fullName>IsRelatedToStudy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRelatedToStudy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Therapeutic Areas</relationshipLabel>
    <relationshipName>Therapeutic_Area_Patients</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Therapeutic Area Patients</relationshipLabel>
    <relationshipName>Therapeutic_Area_Patients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ConditionOfInterestRemote.cls
/**
 * Created by AlexKetch on 3/21/2019.
 */

public with sharing class ConditionOfInterestRemote {
    public static final String COI = 'Condition_of_Interests';

    @AuraEnabled
    public static List<ConditionOfInterestRemote.CAWrapper> getConditionOfInterest() {
        try {
            Participant__c participant = getParticipant();
            List<ConditionOfInterestRemote.CAWrapper> caWrappers = new List<ConditionOfInterestRemote.CAWrapper>();
            if (!participant.Therapeutic_Area_Patients__r.isEmpty()) {
                for (Therapeutic_Area_Patient__c coi : participant.Therapeutic_Area_Patients__r) {
                    ConditionOfInterestRemote.CAWrapper caWrapper = new ConditionOfInterestRemote.CAWrapper ();
                    caWrapper.isSelected = true;
                    caWrapper.coi = coi;
                    caWrappers.add(caWrapper);
                }
            }
            return caWrappers;
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
        return null;
    }

    @AuraEnabled
    public static List<Therapeutic_Area_Patient__c> upsertListCoi(List<Therapeutic_Area_Patient__c> cois) {
        try {
            upsert cois;
            return cois;
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
        return null;
    }

    @AuraEnabled
    public static void deleteCOI(List<Id> coiIds) {
        try {
            Database.delete(coiIds);
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
    }

    private static Participant__c getParticipant() {
        DatabaseProxy databaseProxy = (DatabaseProxy) ClassFactory.newInstance(DatabaseProxy.class);
        CommunityService cService = (CommunityService) ClassFactory.newInstance(CommunityService.class);
        String participantId = cService.getParticipantId();
        String participantQuery =
                'SELECT Id, ' +
                        'Conditions__c, ' +
                        '(SELECT Id, Therapeutic_Area__c, Therapeutic_Area__r.Name, Therapeutic_Area__r.RecordType.DeveloperName, IsRelatedToStudy__c, Condition_Of_Interest_Order__c ' +
                        'FROM Therapeutic_Area_Patients__r ' +
                        'WHERE Condition_Of_Interest_Order__c > 0 ' +
                        'AND Therapeutic_Area__r.RecordType.DeveloperName = \'' + COI + '\' ' +
                        'ORDER BY Condition_Of_Interest_Order__c) ' +
                        'FROM Participant__c ' +
                        'WHERE Id = \'' + participantId + '\'';
        return ((List<Participant__c>) databaseProxy.query(participantQuery))[0];
    }

    public class CAWrapper {
        @AuraEnabled
        public Boolean isSelected;
        @AuraEnabled
        public Therapeutic_Area_Patient__c coi;
    }

}