force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>7</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Birth_Day__c.field-meta.xml
<CustomField>
    <fullName>Birth_Day__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>		
    <label>Birth Day</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Birth_Month__c.field-meta.xml
<CustomField>
    <fullName>Birth_Month__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>		
    <label>Birth Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Birth_Year__c.field-meta.xml
<CustomField>
    <fullName>Birth_Year__c</fullName>
    <label>Birth Year</label>
    <length>4</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/libs/scheduled-batch/classes/Test_Batch_UpdateAgePartBDayToday.cls
@isTest
public class Test_Batch_UpdateAgePartBDayToday {
    @testSetup static void testSetupMethod() {
        TestData.loadTestData();
    }
    @IsTest
    static void testAge(){
        list<participant__c> plist = [select id from participant__c limit 3];
        
        
        plist[0].Birth_Year__c = '2000';
        plist[0].Birth_Month__c = '12' ;
        plist[0].Birth_Day__c = '31';
        
        plist[1].Birth_Year__c = '2001';
        plist[1].Birth_Month__c = '12' ;
        
        plist[2].Birth_Year__c = '2002';
        
        update plist;
        
        system.debug([Select Age__c from participant__c where id =:plist]);
        Test.startTest();
        Database.executeBatch(new Batch_UpdateAgeOfParticipantsBDayToday());
        Test.stopTest();
        
        system.debug([Select Age__c from participant__c where id =:plist]);
    }
}