force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Participant&#39;s First Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s First Name</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <label>Mailing Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/PI_Contact__c.field-meta.xml
<CustomField>
    <fullName>PI_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PI Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (PI)</relationshipLabel>
    <relationshipName>Participant_Profile2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/Participant_Enrollment_Status_History__c.object-meta.xml
<CustomObject>

    <label>Participant Enrollment Status History</label>
    <nameField>
        <displayFormat>PESH-{0000000}</displayFormat>
        <label>Participant Enrollment Status History Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollment Status History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Participant_Enrollment_Status_History__c/fields/ParticipantEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ParticipantEnrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Participant Enrollment Status History</relationshipLabel>
    <relationshipName>Participant_Enrollment_Status_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Participant Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Participant_Statuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/PI_Contact__c.field-meta.xml
<CustomField>
    <fullName>PI_Contact__c</fullName>
    <formula>HYPERLINK( &quot;/&quot;&amp;Principal_Investigator__c , Principal_Investigator__r.FirstName&amp;&quot; &quot; &amp;Principal_Investigator__r.LastName )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PI Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Participant_Statuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Failed Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Failed Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded from Referring</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Success</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-Up Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Participation Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Trial Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Drop Out</fullName>
    </customValue>
    <customValue>
        <fullName>Deceased</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Successfully Contacted</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Reach</fullName>
    </customValue>
    <customValue>
        <fullName>Contacted - Not Suitable</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Success</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress - Wash Out Period</fullName>
        <label>In Wash Out Period</label>
    </customValue>
    <customValue>
        <fullName>Ready to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Declined Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent After Screening</fullName>
    </customValue>
    <masterLabel>Participant Statuses</masterLabel>
</GlobalValueSet>

force-app/main/deprecated/classes/Test_PSEStatusHistoryRemote.cls
/**
 * Created by Leonid Bartenev
 */

@IsTest
private class Test_PSEStatusHistoryRemote {
    public static list<Participant_Enrollment__c> peList = new List<Participant_Enrollment__c>();
    @isTest
    static void test1() {

        Test.startTest();
        TestData.loadTestData();
        Test.stopTest();

        Participant__c participant = new Participant__c(
                First_Name__c = 'newParticipant',
                Last_Name__c = 'newParticipant',
                Mailing_Country_Code__c = 'US',
                Mailing_State_Code__c = 'MS'
        );
        insert participant;

        Study_Site__c studySite = [
                SELECT Id
                FROM Study_Site__c
        ];
        Contact piContact = [
                SELECT Id
                FROM Contact
                WHERE Email = 'pi@emil.com'
        ];

        Participant_Enrollment__c pe = new Participant_Enrollment__c(
                Study_Site__c = studySite.Id,
                Participant__c = participant.Id,
                PI_Contact__c = piContact.Id
        );
        insert pe;
		Participant_Enrollment_Status_History__c peHistory = new Participant_Enrollment_Status_History__c(
            Date__c = Date.today(),
            ParticipantEnrollment__c = pe.Id,
            Status__c = PEStatusState.PE_STATUS_ENROLLMENT_SUCCESS
        );
        insert peHistory;
         PSEStatusHistoryRemote.getParticipationStatusHistory(pe.id);
    }
     
}