force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Email</label>

    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Participant&#39;s First Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s First Name</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Phone</label>

    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <label>Mailing Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Patient_ID__c.field-meta.xml
<CustomField>
    <fullName>Patient_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Patient ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_AddPatientByPIRemote.cls
/**
 * Created by Leonid Bartenev
 */

@IsTest
private class Test_AddPatientByPIRemote {
    
    @IsTest
    static void testGetInitData() {
        TestData.loadTestData();
        Test.startTest();
        TestData testData = new TestData();
        System.runAs(testData.piUser){
            AddPatientByPIRemote.getInitData(testData.ctp.Id);
        }
        Test.stopTest();
    }
    
    @IsTest
    static void testSaveParticipant() {
        TestData.loadTestData();
        Test.startTest();
        TestData testData = new TestData();
        System.debug('CTP: ' + testData.ctp);
        System.debug('PARTICIPANTS: ' + [SELECT Name FROM Participant__c]);
        System.runAs(testData.piUser){
            Participant__c participant = new Participant__c(
                    First_Name__c = 'NewP',
                    Last_Name__c = 'NewP',
                    Phone__c = '11213232',
                    Email__c = 'NewP@email.com',
                    Mailing_Country_Code__c = 'US',
                    Mailing_State_Code__c = 'NY'

            );
            Participant_Enrollment__c pe = new Participant_Enrollment__c(
                    Study_Site__c = testData.ss.Id,
                    Patient_ID__c = '12345678',
                    Participant_Status__c = PEStatusState.PE_STATUS_ENROLLMENT_SUCCESS
            );
            AddPatientByPIRemote.saveParticipant(JSON.serialize(participant), JSON.serialize(pe));
        }
        Test.stopTest();
    }
}