force-app/main/default/objects/CC_Staff__c/CC_Staff__c.object-meta.xml
<CustomObject>
    <label>CC Staff</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>CC Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Staff__c/fields/CC_Staff_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Staff_Status__c</fullName>
    <label>CC Staff Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Not Invited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Staff__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CC Staff Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.userCommunityMode__c</field>
            <operation>equals</operation>
            <value>CC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CC Staff</relationshipLabel>
    <relationshipName>CC_Staffs_Contact</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Staff_Status__c.field-meta.xml
<CustomField>
    <fullName>CC_Staff_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for the status of call center staff</description>
    <label>CC Staff Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunytyType__c.field-meta.xml
<CustomField>
    <fullName>userCommunytyType__c</fullName>
    <description>User types for community - HCP / PI / Participant</description>
    <inlineHelpText>Select user types for community</inlineHelpText>
    <label>User Community Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CCStaffTriggerHandler.cls
/**
* Created by Akanksha on 18.06.20
*/
public class CCStaffTriggerHandler {

    // Handlers: -------------------------------------------------------------------------------------------------------
        
    public class UpdateContactOnStatusChange extends TriggerHandler {
        
        public override void afterInsert(List<SObject> newList) {
            UpdateContactCCStaffStatus(newList);
        }
        public override void afterUpdate(List<SObject> newList,Map<Id, SObject> oldMap) {
            UpdateContactCCStaffStatus(newList);
        }
    }
    
    // Logic: ----------------------------------------------------------------------------------------------------------
    
    @TestVisible
    private static void UpdateContactCCStaffStatus(List<CC_Staff__c> newList) {
        List<Contact> conList = new List<Contact>();
        List<CC_Staff__c> ccList = [SELECT Id,CC_Staff_Status__c,
                                    Contact__r.userCommunityMode__c,
                                    Contact__r.userCommunytyType__c,
                                    Contact__r.CC_Staff_Status__c
                                    FROM CC_Staff__c
                                    WHERE ID IN: newList AND
                                   Contact__r.userCommunityMode__c = 'CC'];
        For(CC_Staff__c c: ccList){
                    c.Contact__r.userCommunytyType__c = 'CC';
                if(c.CC_Staff_Status__c == 'Invited')
                    c.Contact__r.CC_Staff_Status__c = True;  
                else
                    c.Contact__r.CC_Staff_Status__c = False; 
            
            conList.add(c.Contact__r);
        }
        update conList;
    }
}