force-app/main/integration-framework/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Opt_Out__e/SMS_Opt_Out__e.object-meta.xml
<CustomObject>
    <label>SMS Opt Out</label>
    <pluralLabel>SMS Opt Out</pluralLabel>
</CustomObject>

force-app/main/default/objects/SMS_Opt_Out__e/fields/optout__c.field-meta.xml
<CustomField>
    <fullName>optout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>optout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS_Opt_Out__e/fields/PreviousPublishedMessageId__c.field-meta.xml
<CustomField>
    <fullName>PreviousPublishedMessageId__c</fullName>
    <label>PreviousPublishedMessageId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/triggers-implementation/classes/SMSOptOutTriggerHandler.cls
public without sharing class SMSOptOutTriggerHandler {
    public class optOutSMS extends TriggerHandler {
        public override void afterInsert(List<SObject> newList) {
            optOutForSMS((List<SMS_Opt_Out__e>) newList);
        }
    }

    /**
     * @description: This Method will process the OPT Out for SMS.
     *
     * @author: Krishna Mahto
     * @param: smsOptOutPEventList
     * @return:
     **/
    @TestVisible
    private static void optOutForSMS(List<SMS_Opt_Out__e> smsOptOutPEventList) {
        Set<String> messageIdSet = new Set<String>();
        List<IntegrationLog__c> listIL = new List<IntegrationLog__c>();
        //Get the List of PreviousPublishedMessageId__c from platform event record.
        for (SMS_Opt_Out__e smsOptOut : smsOptOutPEventList) {
            listIL.add(smsOptOut.createIntegrationLog());
            if (smsOptOut.optout__c) {
                messageIdSet.Add(smsOptOut.PreviousPublishedMessageId__c);
            }
        }
        if (listIL.size() > 0) {
            insert listIL;
        }
        //Process Opt out for SMS.
        SMSOptOutService.processOptOUTForSMS(messageIdSet);
    }
}