force-app/main/messaging/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Notification__c/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <label>Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/messaging/objects/Notification_Target__mdt/Notification_Target__mdt.object-meta.xml
<CustomObject>
    <label>Notification Target</label>
    <pluralLabel>Notification Targets</pluralLabel>
</CustomObject>

force-app/main/messaging/objects/Notification_Target__mdt/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <label>Notification Type</label>
    <referenceTo>Notification_Type__mdt</referenceTo>
    <relationshipLabel>Notification Targets</relationshipLabel>
    <relationshipName>Notification_Targets</relationshipName>
    <type>MetadataRelationship</type>

</CustomField>

force-app/main/messaging/classes/EmailService.cls
/**
 * Created by Olga Skrynnikova on 11/28/2019.
 */

public without sharing class EmailService {
    public class SendEmailTemplateException extends Exception {
    }

    private static final Map<String, Id> templateNameIdMap = new Map<String, Id>();
    private static final Map<String, Id> orgWideEmailAddressesMap = new Map<String, Id>();

    static {
        List<OrgWideEmailAddress> listAddresses = [
                SELECT Id, DisplayName
                FROM OrgWideEmailAddress
        ];
        for (OrgWideEmailAddress address : listAddresses) {
            orgWideEmailAddressesMap.put(address.DisplayName, address.Id);
        }
        List<EmailTemplate> templates = [
                SELECT Id, DeveloperName
                FROM EmailTemplate
        ];
        for (EmailTemplate temp : templates) {
            templateNameIdMap.put(temp.DeveloperName, temp.Id);
        }
    }

    public static Id getEmailTemplateId(String templateName) {
        if (templateName != null) return templateNameIdMap.get(templateName);
        return null;
    }

    public static Id getOrgWideEmailAddressId(String orgWideEmailAddress) {
        if (orgWideEmailAddress != null) return orgWideEmailAddressesMap.get(orgWideEmailAddress);
        return null;
    }

    public static Messaging.SingleEmailMessage createEmail(Id emailTemplateId, Id recipientId, Id whatId, List<String> ccAddresses, String orgWideEmAddress) {
        Messaging.SingleEmailMessage newEmail = new Messaging.SingleEmailMessage();
        newEmail.setTemplateId(emailTemplateId);
        newEmail.setTargetObjectId(recipientId);
        newEmail.setSaveAsActivity(false);
        newEmail.setWhatId(whatId);
        Id orgWideEmailAddressId = getOrgWideEmailAddressId(orgWideEmAddress);
        if (orgWideEmailAddressId != null) newEmail.setOrgWideEmailAddressId(orgWideEmailAddressId);
        if (ccAddresses != null) newEmail.setCcAddresses(ccAddresses);
        return newEmail;
    }

    public static void send(List<Notification__c> notifications) {
        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
        for (Notification__c n : notifications) {
            Notification_Target__mdt currentTarget = NotificationService.getTargetByNotification(n.Notification_Type__c, NotificationService.NOTIFICATION_TARGET_TYPE_EMAIL);
            emailMessages.add(createEmail(getEmailTemplateId(currentTarget.Email_Template__c), n.Recipient__c, n.WhatId__c));
        }
        List<Messaging.SendEmailResult> resultList = Messaging.sendEmail(emailMessages, false);
        List<Notification__c> notificationList = new List<Notification__c>(notifications);
        for (Integer i = 0; i < notificationList.size(); i++) {
            if (!resultList[i].success) {
                notificationList[i].Email_Status__c = NotificationService.EMAIL_STATUS_FAILED;
            }
        }
    }
    public static Messaging.SingleEmailMessage createEmail(String templateDeveloperName, Id contactId, Id whatId) {
        return createEmail(getEmailTemplateId(templateDeveloperName), contactId, whatId);
    }


}