force-app/main/messaging/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Notification__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Televisit__c/Televisit__c.object-meta.xml
<CustomObject>
    <label>Televisit</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Televisit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Televisits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Visit Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/Televisit_Attendee__c.object-meta.xml
<CustomObject>
    <label>Televisit Attendee</label>
    <nameField>
        <label>Televisit Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Televisit Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit_Attendee__c/fields/Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Type__c</fullName>
    <label>Attendee Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Is_First_Reminder_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_First_Reminder_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is First Reminder Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Is_Second_Reminder_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Second_Reminder_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Second Reminder Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Lastname__c.field-meta.xml
<CustomField>
    <fullName>Lastname__c</fullName>
    <label>Lastname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Televisit__c.field-meta.xml
<CustomField>
    <fullName>Televisit__c</fullName>
    <label>Televisit</label>
    <referenceTo>Televisit__c</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Televisit_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Televisit_Scheduled_Date__c</fullName>
    <label>Televisit Scheduled Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/scheduled-batch-implementation/classes/Batch_TelevisitReminder.cls
public without sharing class Batch_TelevisitReminder extends Batch_ScheduledAbstract {
    public Database.QueryLocator start(Database.BatchableContext param1) {
        return Database.getQueryLocator(
            [
                SELECT
                Id,
                Attendee_Type__c,
                Contact__c,
                Firstname__c,
                Lastname__c,
                Televisit_Scheduled_Date__c,
                User__c,
                Televisit__r.Visit_Date_Time__c,
                Televisit__r.Status__c,
                Televisit__r.Title__c,
                Is_Second_Reminder_Sent__c,
                Is_First_Reminder_Sent__c
                FROM Televisit_Attendee__c
                WHERE
                (Attendee_Type__c = 'PI' OR Attendee_Type__c = 'Site Staff') AND
                Televisit__r.Status__c = 'Scheduled' AND Is_Second_Reminder_Sent__c = false AND 
                (
                    (
                        Is_First_Reminder_Sent__c = false AND 
                        Televisit__r.Visit_Date_Time__c >= :Datetime.now().addDays(1) AND 
                        Televisit__r.Visit_Date_Time__c <=:Datetime.now().addDays(1).addMinutes(2)
                    ) OR 
                    (
                        Televisit__r.Visit_Date_Time__c >= :Datetime.now().addHours(1) AND 
                        Televisit__r.Visit_Date_Time__c <= :Datetime.now().addHours(1).addMinutes(2)
                    )
                )
                
            ]
        );
    }
    public void execute(Database.BatchableContext param1, List<SObject> attendeeList) {
        sendRemindersParticipantTeam(attendeeList);
        checkReminder(attendeeList);
        update attendeeList;
    }
    
    private void sendRemindersParticipantTeam(List<Televisit_Attendee__c> attendeeList) {
        
        List<Notification__c> notifications = new List<Notification__c>();
        for (Televisit_Attendee__c attendee : attendeeList) {
            Notification__c notification = new Notification__c();
            notification.Recipient__c = attendee.Contact__c;
            notification.WhatId__c = attendee.Id;
            if(
                attendee.Televisit__r.Visit_Date_Time__c >= Datetime.now().addHours(1) &&
                attendee.Televisit__r.Visit_Date_Time__c <= Datetime.now().addHours(1).addMinutes(2)
            ){
                notification.Notification_Type__c = 'Message_to_PI_Televisit_Reminder_Two';
            }else{
                notification.Notification_Type__c = 'Message_To_PI_Televisit_Reminder'; 
            }
            
            notifications.add(notification);
        }
        
        if (!notifications.isEmpty()){
            insert notifications;
        }
    }
    
    private void checkReminder(List<Televisit_Attendee__c> attendeeList) {
        
        for (Televisit_Attendee__c t : attendeeList) {
            if( t.Televisit__r.Visit_Date_Time__c >= Datetime.now().addHours(1) &&
               t.Televisit__r.Visit_Date_Time__c <= Datetime.now().addHours(1).addMinutes(2)
              ){
                  t.Is_Second_Reminder_Sent__c = true;
              }else{
                  t.Is_First_Reminder_Sent__c = true;
              }
        }
    }
    
    public override Type getType() {
        return Batch_PatientTaskReminder.class;
    }

    public override String getBatchDescription() {
        return 'Sends Email Reminders about upcoming televisits';
    }

    public override String getRecommendedIntervalMode() {
        return Batch_ScheduledAbstract.INTERVAL_DAYS;
    }

    public override Integer getRecommendedRelaunchInterval() {
        return 1;
    }
}