force-app/main/integration/objects/Integration_Patient_Referral__c/Integration_Patient_Referral__c.object-meta.xml
<CustomObject>
    <label>Integration Patient Referral</label>
    <nameField>
        <label>Integration Patient Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Patient Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/acceptedTermsAndConditions__c.field-meta.xml
<CustomField>
    <fullName>acceptedTermsAndConditions__c</fullName>
    <label>acceptedTermsAndConditions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Address_Country__c</fullName>
    <label>Address_Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Address_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>Address_ZipCode__c</fullName>
    <label>Address_ZipCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <label>Data_Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <label>firstName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language_Preference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <label>lastName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Integration Patient Referrals</relationshipLabel>
    <relationshipName>Integration_Patient_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/protocolId__c.field-meta.xml
<CustomField>
    <fullName>protocolId__c</fullName>
    <label>protocolId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/referralID__c.field-meta.xml
<CustomField>
    <fullName>referralID__c</fullName>
    <label>referralID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Referred_Date__c.field-meta.xml
<CustomField>
    <fullName>Referred_Date__c</fullName>
    <label>Referred_Date</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/siteSelected__c.field-meta.xml
<CustomField>
    <fullName>siteSelected__c</fullName>
    <label>siteSelected</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Referred_Date__c.field-meta.xml
<CustomField>
    <fullName>Referred_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date Potential Participant referred to a Site / PI</inlineHelpText>
    <label>Referred Date</label>
    <type>Date</type>
</CustomField>

force-app/main/tests/classes/Test_SendEmailTemplate.cls
@IsTest
private class Test_SendEmailTemplate {
    @testSetup
    static void setup() {
        TestData.loadTestData();
    }
    @IsTest
    static void testSendEmailNotification() {
        TestData testData = new TestData();
        Integration_Patient_Referral__c i = new Integration_Patient_Referral__c();
        i.Participant_Enrollment__c = testData.pe.id;
        i.Address_Country__c = 'US';
        i.Address_ZipCode__c = '12345';
        i.Data_Source__c = 'Test';
        i.Language_Preference__c = 'us';
        i.Referred_Date__c = String.valueOf(Date.today());
        i.acceptedTermsAndConditions__c = 'true';
        i.firstName__c = 'test';
        i.lastName__c = 'test';
        i.protocolId__c = 'E7449-E044-101';
        i.referralID__c = '700-112314';
        i.siteSelected__c = '102';
      	//insert i;
      	EmailTemplate e = new EmailTemplate (developerName = 'Covid19_Delegate', FolderId = UserInfo.getUserId() , TemplateType= 'Text', Name = 'Covid19_Delegate',isActive = true);
		insert e;
        EmailTemplate templateId = [SELECT id,name,developerName FROM EmailTemplate WHERE name = 'Covid19_Delegate'];
        OrgWideEmailAddress owa = [
            SELECT id, DisplayName, Address
            FROM OrgWideEmailAddress
            LIMIT 1
        ];
        String developerName= templateId.DeveloperName;
        String emailAddress =owa.Address;
        Id whatId = i.id;
        Id fromId = testData.piDelegateContact.id;
        String templateName =templateId.name;
        Id whatIdName=i.Name;
        Id contactId = testData.piDelegateContact.id;
        Id emailTemplateId =templateId.Id;
        Id studyId=testData.ss.Id;
        String userModePI='PI';
        String userModeHCP='HCP';
        Map<Id, String> whatIdMap = new Map<Id, String>();
        whatIdMap.put(whatId,whatIdName);
        Set<Id> whatIdSet=new Set<Id>();
        whatIdSet.add(whatId);
        Map<Id, Set<Id>> contactIdToWhatIdSet = new Map<Id, Set<Id>>();
        contactIdToWhatIdSet.put(contactId,whatIdSet);
        Test.startTest();
        System.runAs(testData.participantUser) {
        SendEmailTemplate.sendEmailNotification(templateName, whatIdMap);
        SendEmailTemplate.sendEmailNotification(templateName, contactIdToWhatIdSet);
        SendEmailTemplate.createEmail(developerName, contactId, whatId);
        SendEmailTemplate.createEmail(emailTemplateId, contactId, whatId, studyId, true, userModePI);
        SendEmailTemplate.createEmail(emailTemplateId, contactId, whatId, studyId, true, userModeHCP);
        SendEmailTemplate.getOrgWideEmailId(fromId);
        SendEmailTemplate.sendShareEmail(whatId,fromId,emailAddress,templateName);
        Test.stopTest();
    	}
    }
}