force-app/main/integration/objects/Integration_Patient_Referral__c/Integration_Patient_Referral__c.object-meta.xml
<CustomObject>
    <label>Integration Patient Referral</label>
    <nameField>
        <label>Integration Patient Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Patient Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/acceptedTermsAndConditions__c.field-meta.xml
<CustomField>
    <fullName>acceptedTermsAndConditions__c</fullName>
    <label>acceptedTermsAndConditions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Address_Country__c</fullName>
    <label>Address_Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <label>Address_State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Address_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>Address_ZipCode__c</fullName>
    <label>Address_ZipCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <label>Data_Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <label>firstName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language_Preference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <label>lastName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Integration Patient Referrals</relationshipLabel>
    <relationshipName>Integration_Patient_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/phone__c.field-meta.xml
<CustomField>
    <fullName>phone__c</fullName>
    <label>phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/protocolId__c.field-meta.xml
<CustomField>
    <fullName>protocolId__c</fullName>
    <label>protocolId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/referralID__c.field-meta.xml
<CustomField>
    <fullName>referralID__c</fullName>
    <label>referralID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Referred_Date__c.field-meta.xml
<CustomField>
    <fullName>Referred_Date__c</fullName>
    <label>Referred_Date</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/siteSelected__c.field-meta.xml
<CustomField>
    <fullName>siteSelected__c</fullName>
    <label>siteSelected</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Email</label>

    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Phone</label>

    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Referred_Date__c.field-meta.xml
<CustomField>
    <fullName>Referred_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date Potential Participant referred to a Site / PI</inlineHelpText>
    <label>Referred Date</label>
    <type>Date</type>
</CustomField>

force-app/main/tests/classes/Test_DuplicateContactController.cls
/**
 * Created by Slav on 21.08.2019.
 */

@IsTest(SeeAllData=false)
public class Test_DuplicateContactController {
    
    @IsTest
    public static void runTest1() {
        TestData.loadTestData();
        Test.startTest();
        
        TestData testDataInstance = new TestData();
        System.runAs(testDataInstance.participantUser) {
            Integration_Patient_Referral__c referral = new Integration_Patient_Referral__c(
                    firstName__c                    = 'FirstName',
                    lastName__c                     = 'LastName',
                    email__c                        = 'test@mail.com',
                    phone__c                        = '12357890',
                    protocolId__c                   = 'tt123456789',
                    siteSelected__c                 = '_',
                    Address_State__c                = 'New York',
                    referralID__c                   = '453453',
                    Address_ZipCode__c              = '34545',
                    Address_Country__c              = 'US',
                    Language_Preference__c          = 'en_US',
                    Referred_Date__c                = '2019-10-02T10:00:00-05:00',
                    Data_Source__c                  = 'Company',
                    acceptedTermsAndConditions__c   = '2019-10-02T10:00:00-05:00'
            );
//            insert referral;


//            DuplicateContactController.checkDuplicates(referral);
//
//            Participant__c participant;
//            Participant_Enrollment__c participantEnrollment;
//            DuplicateContactController.communityReffering(participant, participantEnrollment);
        
        
        
        
        }
        
        Test.stopTest();
    }

}