force-app/main/default/objects/Televisit__c/Televisit__c.object-meta.xml
<CustomObject>
    <label>Televisit</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Televisit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Televisits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/televisitBatch.cls
global class televisitBatch implements Database.Batchable<sObject> {
     global Database.QueryLocator start( Database.BatchableContext BC ) {
        String query = 'SELECT Id,Status__c,Visit_Date__c,Start_Time__c FROM Televisit__c ';
        return Database.getQueryLocator( query );
 
    }
   
    global void execute( Database.BatchableContext BC, List< Televisit__c > scope ) {
         for (Televisit__c tv : scope) {
             if(tv.Visit_Date__c < system.today()+1){
                 tv.Status__c = 'Completed';  
             }
                           
         }
         update scope;
 
    }   
    
    global void finish( Database.BatchableContext BC ) {
    }
 
}