force-app/main/default/objects/Call_Dispositions__c/Call_Dispositions__c.object-meta.xml
<CustomObject>
    <label>Call Dispositions</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Call Disposition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Dispositions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Dispositions__c/fields/Call_Category__c.field-meta.xml
<CustomField>
    <fullName>Call_Category__c</fullName>
    <label>Call Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Welcome Call Complete</fullName>
            </value>
            <value>
                <fullName>First Referral Call Complete</fullName>
            </value>
            <value>
                <fullName>Aged Referral Call Complete</fullName>
            </value>
            <value>
                <fullName>Left Message</fullName>
            </value>
            <value>
                <fullName>No Answer</fullName>
            </value>
            <value>
                <fullName>Follow up needed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Dispositions__c/fields/Caller__c.field-meta.xml
<CustomField>
    <fullName>Caller__c</fullName>
    <label>Caller</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Dispositions</relationshipLabel>
    <relationshipName>Call_Dispositions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Call_Dispositions__c/fields/Inbound_Outbound__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Outbound__c</fullName>
    <label>Inbound/Outbound</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Dispositions__c/fields/IQVIA_intervention_completed__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_intervention_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA intervention completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Dispositions__c/fields/IQVIA_intervention_required__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_intervention_required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA intervention required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Call_Dispositions__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Call Dispositions</relationshipLabel>
    <relationshipName>Call_Dispositions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/IQVIA_intervention_required__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_intervention_required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA intervention required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/community-pages-cc/classes/FetchCallDispositions.cls
public without sharing class FetchCallDispositions {
    
    @AuraEnabled(Cacheable = true)
    public static todayDate gettodaydate(){
        try {
            Integer Year = Date.Today().Year();
            Integer day = Date.Today().day();
            DateTime dt = Datetime.now();
            Contact userContact = CommunityService.getUserContact();
            String dy='';           
            
            if(day == 01 || day == 21 || day == 31)
            {
                dy=day+'st';  
            }
            else if(day == 02|| day == 22){
                dy=day+'nd'; 
            }
            else if(day == 03|| day == 23){
                dy=day+'rd'; 
            }
            else
            {
                dy=day+'th';
            }            
            
            todayDate td = new todayDate();
            td.day=dy;
            td.year =Year;
            td.month= dt.format('MMMM');
            td.conName =userContact.Name;
            return td;
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static wrapcalls getcalls(integer limits,string siteId){
        try {
            List<Call_Dispositions__c> lstCD =new  List<Call_Dispositions__c>();
            List<Call_Dispositions__c> lstCallDispositions =new  List<Call_Dispositions__c>();
            List<Wrapcd> lstcalldts = new List<Wrapcd>();
            List<String> lstCallDateTime = new List<String>();
            Integer count=0;
            lstCD = [select Id,Call_Category__c,Caller__c,Caller__r.Name,CreatedDate,Inbound_Outbound__c,IQVIA_intervention_completed__c,IQVIA_intervention_required__c,Study_Site__c,Notes__c 
                     from Call_Dispositions__c where Study_Site__c=:siteId order by CreatedDate desc limit:limits];
            count =[select count() from Call_Dispositions__c where Study_Site__c=:siteId];
            
            string calldatetime='';
            string a='';
            for(Call_Dispositions__c c:lstCD)
            {
                calldatetime='';
                a='';
                DateTime dt = c.CreatedDate;
                if(dt.format('dd') == '01' || dt.format('dd') == '21' || dt.format('dd') == '31')
                {
                    a='st';  
                }
                else if(dt.format('dd') == '02'|| dt.format('dd') == '22')
                {
                    a='nd'; 
                }
                else if(dt.format('dd') == '03'|| dt.format('dd') == '23')
                {
                    a='rd'; 
                }
                else
                {
                    a='th';
                }
                calldatetime=calldatetime+dt.format('MMMM')+' '+dt.format('dd')+a+', '+dt.format('yyyy')+', '+dt.format('h:mm a');
                system.debug('cd-->'+c.id+' '+calldatetime);
                lstcalldts.add(new Wrapcd(c, calldatetime));
                lstCallDispositions.add(c);
                lstCallDateTime.add(calldatetime);
            }
            
            
            wrapcalls wc = new wrapcalls();
            wc.lstCDs=lstcalldts;
            //wc.callDateTime=lstCallDateTime;
            wc.count=count;
            return wc;
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    public class todayDate {
        @AuraEnabled
        public String day { get; set; }
        @AuraEnabled
        public string month { get; set; }
        @AuraEnabled
        public Integer year { get; set; }
        @AuraEnabled
        public string conName { get; set; }
    }
    public class wrapcalls {
        @AuraEnabled
        public List<Wrapcd> lstCDs { get; set; }
        @AuraEnabled
        public Integer count { get; set; }
        
        
    }
    public class Wrapcd
    {
        @AuraEnabled
        public Call_Dispositions__c cd { get; set; }
        @AuraEnabled
        public String dtcd{ get; set; }
        public Wrapcd(Call_Dispositions__c cd,String dtcd) {
            this.cd= cd;
            this.dtcd= dtcd;
            
        }
    }
    
}