force-app/main/default/objects/Trial_Survey__c/Trial_Survey__c.object-meta.xml
<CustomObject>
    <label>Trial Survey</label>
    <nameField>
        <displayFormat>TS-{000}</displayFormat>
        <label>Trial Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trial_Survey__c/fields/Is_Recurrence_Survey__c.field-meta.xml
<CustomField>
    <fullName>Is_Recurrence_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Recurrence Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Recurrence_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Frequency__c</fullName>
    <label>Recurrence Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>True</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>InActive</fullName>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey_end_date__c.field-meta.xml
<CustomField>
    <fullName>Survey_end_date__c</fullName>
    <label>Survey end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey_start_date__c.field-meta.xml
<CustomField>
    <fullName>Survey_start_date__c</fullName>
    <label>Survey start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/backend-ctp-setup/classes/TrialSurveyContainerController.cls
/**
 * @description       :
 * @author            : Sravani
 * @group             :
 * @last modified on  : 01-21-2022
 **/
public without sharing class TrialSurveyContainerController {
    @AuraEnabled
    public static String getRecordTypeNameById(String recordTypeId) {
        Schema.SObjectType sObjectType = Trial_Survey__c.getSObjectType();
        return SchemaUtil.getRecordTypeInfoById(recordTypeId, sObjectType).getName();
    }

    @AuraEnabled
    public static Trial_Survey__c getTrialSurveyRecords(String tsRecordId) {
        Trial_Survey__c trialSurvey = [
            SELECT
                Id,
                RecordtypeId,
                RecordType.name,
                Is_Recurrence_Survey__c,
                Survey_start_date__c,
                Survey_end_date__c,
                Last_Occurrence_Date__c,
                Recurrence_Frequency__c,
                Status__c
            FROM Trial_Survey__c
            WHERE Id = :tsRecordId
        ];
        return trialSurvey;
    }
}