force-app/main/default/objects/Participant_Study_Enrollment__c/Participant_Study_Enrollment__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Participant Study Enrollment</label>
    <nameField>
        <displayFormat>PSE{00000000}</displayFormat>
        <label>Participant Study Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Study Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PSE_Status_History__c/PSE_Status_History__c.object-meta.xml
<CustomObject>
    <label>PSE Status History</label>
    <nameField>
        <displayFormat>PSESH-{00000000}</displayFormat>
        <label>PSE Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PSE Status Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PSE_Status_History__c/fields/Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Changed_Date__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Changed Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PSE_Status_History__c/fields/PSE__c.field-meta.xml
<CustomField>
    <fullName>PSE__c</fullName>
    <label>Participant Study Enrollment</label>
    <referenceTo>Participant_Study_Enrollment__c</referenceTo>
    <relationshipLabel>PSE Status Histories</relationshipLabel>
    <relationshipName>PSE_Status_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PSE_Status_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/deprecated/classes/PSEStatusHistoryTriggerHandler.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class PSEStatusHistoryTriggerHandler {
    
    // Handlers: -------------------------------------------------------------------------------------------------------
    
    public class UpdatePSEStatusOnHistoryChangeHandler extends TriggerHandler{
        
        public override void afterInsert(List<SObject> newList) {
//            updatePSEStatuses(newList);
        }
        
        public override void afterUpdate(List<SObject> newList, Map<Id, SObject> oldMap) {
//            updatePSEStatuses(newList);
        }
    }
    
    // Logic: ----------------------------------------------------------------------------------------------------------
    
//    @TestVisible
//    private static void updatePSEStatuses(List<PSE_Status_History__c> newList){
//        Set<Id> pseListIds = new Set<Id>();
//        for(PSE_Status_History__c pseStatusHistory : newList) pseListIds.add(pseStatusHistory.PSE__c);
//
//        List<Participant_Study_Enrollment__c> pseList = [
//                SELECT Id, (SELECT Id, Status__c FROM PSE_Status_Histories__r ORDER BY Changed_Date__c DESC LIMIT 1)
//                FROM Participant_Study_Enrollment__c
//                WHERE Id IN: pseListIds
//        ];
//        List<Participant_Study_Enrollment__c> pseListForUpdate = new List<Participant_Study_Enrollment__c>();
//        for(Participant_Study_Enrollment__c pse : pseList){
//            if(pse.PSE_Status_Histories__r.size() > 0){
//                pse.Status__c = pse.PSE_Status_Histories__r[0].Status__c;
//                pseListForUpdate.add(pse);
//            }
//        }
//        update pseListForUpdate;
//    }
}