force-app/main/default/objects/Ecoa_Task_Configuration__c/Ecoa_Task_Configuration__c.object-meta.xml
<CustomObject>
    <label>Ecoa Task Configuration</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Ecoa Task Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ecoa Task Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ecoa_Task_Configuration__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <formula>Participant_Enrollment__r.Participant_Contact__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ecoa_Task_Configuration__c/fields/Diary_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Diary_End_Date__c</fullName>
    <label>Diary End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ecoa_Task_Configuration__c/fields/Diary_Name__c.field-meta.xml
<CustomField>
    <fullName>Diary_Name__c</fullName>
    <label>Diary Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ecoa_Task_Configuration__c/fields/Diary_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Diary_Start_Date__c</fullName>
    <label>Diary Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ecoa_Task_Configuration__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Ecoa Task Configurations</relationshipLabel>
    <relationshipName>Ecoa_Task_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ecoa_Task_Configuration__c/fields/Reminder_config__c.field-meta.xml
<CustomField>
    <fullName>Reminder_config__c</fullName>
    <label>Reminder config</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/Patient_Delegate__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate</label>
    <nameField>
        <displayFormat>PD-{00000000}</displayFormat>
        <label>Patient Delegate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/fields/Primary_Delegate__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delegate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Delegate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/integration/classes/EcoaTaskService.cls
public class EcoaTaskService {
    
    public static void createTask(List<Ecoa_Task_Configuration__c> taskConfig){
        List<Task> eTasks = new List<Task>();
        List<Id> contactIds = new List<Id>();
        Map<Id, User> userContactIdMap = new Map<Id, User>();
        Map<Id, Id> primarydelegateContactMap = new Map<Id, Id>();
        List<Ecoa_Task_Configuration__c> updatedTaskConfigList = new List<Ecoa_Task_Configuration__c>();

        for(Ecoa_Task_Configuration__c task:taskConfig){
            if(task.ContactId__c != null ){
                contactIds.add(task.ContactId__c);
            }
        }
        System.debug('contactIds:: '+contactIds);
        List<Patient_Delegate__c> patientdelegatesList = [
            SELECT Contact__c, Participant__r.Contact__c
            FROM Patient_Delegate__c
            WHERE Participant__r.Contact__c IN :contactIds AND Primary_Delegate__c = TRUE
        ];
        List<User> participantUsers = [
            SELECT Id, ContactId, LocaleSidKey, TimeZoneSidKey, LanguageLocaleKey
            FROM User
            WHERE ContactId IN :contactIds
        ];
        System.debug('participantUsers:: '+participantUsers);
        for (User userObj : participantUsers) {
            userContactIdMap.put(userObj.ContactId, userObj);
        }
        for(Ecoa_Task_Configuration__c task:taskConfig){

            Datetime remTime;
            if(task.Reminder_config__c != null){
                remTime = task.Diary_End_Date__c.addHours(Integer.valueOf(-task.Reminder_config__c));
            }
            User userObj = userContactIdMap.get(task.ContactId__c);
            User delegateUserObj;
            String timeZoneVal = '';
            if (userObj != null) {
                        timeZoneVal = userObj.TimeZoneSidKey;
            } /*else {
                        Id delegatecontactId = primarydelegateContactMap.get(
                            peObj.Participant_Contact__c
                        );
                        delegateUserObj = userContactIdMap.get(delegatecontactId);
                        if (delegateUserObj != null) {
                            timeZoneVal = delegateUserObj.TimeZoneSidKey;
                        }
                    }*/
            Timezone tz = Timezone.getTimeZone(timeZoneVal);
            Integer offset = tz.getOffset(task.Diary_End_Date__c);
            Datetime userlocaltime = task.Diary_End_Date__c.addSeconds(offset / 1000);
            System.debug('userObj.Id:: '+userObj.Id);

            Task t = new Task();
            t.OwnerId = userObj.Id;
            t.Subject = task.Diary_Name__c;
            t.Priority = 'Normal';
            t.Action_URL__c ='s/e-diaries';
            t.Start_Date__c = date.newinstance(task.Diary_Start_Date__c.year(), task.Diary_Start_Date__c.month(), task.Diary_Start_Date__c.day());//get date
            t.Activity_Datetime__c = task.Diary_End_Date__c;
            t.ReminderDateTime = remTime;
            t.Reminder_Date__c = remTime;
            t.Ecoa_Task_Configuration_del__c = task.Id; // ecoa config id
            t.Remind_Using_Email__c = true;
            t.Visible_For__c = TaskService.TASK_VISIBILITY_ALL;
            t.WhatId = task.Participant_Enrollment__c; // PE id
            t.WhoId = task.ContactId__c;// contact id
            t.Task_Type__c = TaskService.TASK_TYPE_NOT_SELECTED;
            t.CreatedByAdmin__c = true;
            t.InitialTaskNotification__c = true;
            task.IsProcessed__c = true; //config
            updatedTaskConfigList.add(task);
            eTasks.add(t);
        }
        try{
            insert eTasks;
            update updatedTaskConfigList;  
        }Catch (exception e){
            System.debug('error::'+e);
        }
    }
}