force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object contains Video/Articles</description>
    <!--enableLicensing>false</enableLicensing-->
    <label>Resource</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/resources/objects/Resource__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
<!--                <fullName>Helpful Links</fullName>-->
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
<!--                <label>Helpful Links</label>-->
            </value>
            <value>
                <fullName>Patient advocacy groups</fullName>
            </value>
            <value>
                <fullName>Articles for caregivers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RRPicklistLookupRemote.cls
/**
 * Created by Nargiz Mamedova on 3/27/2020.
 */

@IsTest
private class Test_RRPicklistLookupRemote {
    @IsTest
    static void testBehavior() {
        List<LookupSearchResult> lookupSearchResults;
        Test.startTest();
        lookupSearchResults = RRPicklistLookupRemote.getAllValues('Resource__c', 'Type__c', 'custom:custom31');
        Test.stopTest();
        System.assert(lookupSearchResults.size() > 0);
    }

    @IsTest
    static void testException(){
        Boolean isExceptionThrown = false;
        List<LookupSearchResult> lookupSearchResults;
        Test.startTest();
        try {
            lookupSearchResults = RRPicklistLookupRemote.getAllValues(null, null, null);
        } catch (Exception e) {
            isExceptionThrown = true;
            System.assert(e.getTypeName() == 'System.AuraHandledException');
        }
        Test.stopTest();
        System.assert(true, isExceptionThrown);
    }
}