force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object contains Video/Articles</description>
    <!--enableLicensing>false</enableLicensing-->
    <label>Resource</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Content_Class__c.field-meta.xml
<CustomField>
    <fullName>Content_Class__c</fullName>
    <label>Content Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Study-Specific</fullName>
            </value>
            <value>
                <fullName>Platform-TA</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Study Document</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Assignment__c/Therapeutic_Area_Assignment__c.object-meta.xml
<CustomObject>
    <description>Object for relation between Resource and Therapeutic Area</description>
    <label>Therapeutic Area Assignment</label>
    <nameField>
        <displayFormat>TAA - {0000000}</displayFormat>
        <label>Therapeutic Area Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Therapeutic Area Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area_Assignment__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Therapeutic Area Assignments</relationshipLabel>
    <relationshipName>Therapeutic_Area_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Assignment__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Therapeutic Area Assignments</relationshipLabel>
    <relationshipName>Therapeutic_Area_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ResourceTARelatedService.cls
public inherited sharing class ResourceTARelatedService extends ResourceService {

    public static ResourceTARelatedService getInstance(){
        return (ResourceTARelatedService) ClassFactory.newInstance(ResourceTARelatedService.class);
    }
    
    protected String therapeuticAreaId;
    
    public ResourceService init(String resourceType, String resourceId, String contentClass, String therapeuticAreaId) {
        init(resourceType, resourceId, contentClass);
        this.therapeuticAreaId = therapeuticAreaId;
        return this;
    }
    
    protected override List<Id> getResourcesIds() {
        List<String> participantLanguages = ContactService.getPreferredLanguages();

        String filter = DatabaseService.fieldEqual('Therapeutic_Area__c', therapeuticAreaId)
                + (contentClass == null ? '' : ('AND' + DatabaseService.fieldEqual('Resource__r.Content_Class__c', contentClass)))
                + (resourceId == null ? '' : ('AND' + DatabaseService.fieldEqual('Resource__c', resourceId)))
                + 'AND' + DatabaseService.fieldEqual('Resource__r.RecordType.DeveloperName', resourceType)
                + 'AND' + DatabaseService.fieldInValues('Resource__r.Language__c', participantLanguages)
        ;
        List<Therapeutic_Area_Assignment__c> assignments = (List<Therapeutic_Area_Assignment__c>)
                DatabaseService.query(new List<String>{
                'Resource__c',
                'Resource__r.Language__c',
                'Resource__r.Title__c'
        }, Therapeutic_Area_Assignment__c.getSObjectType(), filter);

        Map<String, Map<String, Id>> resIdByLangByTitle = new Map<String, Map<String, Id>>();
        for(Therapeutic_Area_Assignment__c ass : assignments) {
            if(!resIdByLangByTitle.containsKey(ass.Resource__r.Title__c)) {
                resIdByLangByTitle.put(ass.Resource__r.Title__c, new Map<String, Id>());
            }

            resIdByLangByTitle.get(ass.Resource__r.Title__c).put(ass.Resource__r.Language__c, ass.Resource__c);
        }

        List<Id> resourcesIds = new List<Id>();
        for(String title : resIdByLangByTitle.keySet()) {
            Map<String, Id> resIdByLang = resIdByLangByTitle.get(title);
            for(String participantLang : participantLanguages) {
                if(resIdByLang.containsKey(participantLang)) {
                    resourcesIds.add(resIdByLang.get(participantLang));
                    break;
                }
            }
        }

        return resourcesIds;
    }

    protected override ResourceService.ResourceWrapperContainer getErrorNoObjectsToFilter() {
        return ResourceService.getErrorUnhandled();
    }

    protected override Boolean isObjectsToFilterMissing() {
        return this.therapeuticAreaId == null;
    }
}