force-app/main/integration/objects/Integration_Trial_Match__c/Integration_Trial_Match__c.object-meta.xml
<CustomObject>
    <label>Integration Trial Match</label>
    <nameField>
        <displayFormat>ITM-{00000000}</displayFormat>
        <label>Integration Trial Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Trial Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/integration/objects/Integration_Trial_Match__c/fields/Matched_Date__c.field-meta.xml
<CustomField>
    <fullName>Matched_Date__c</fullName>
    <label>Matched Date</label>
    <type>Date</type>
</CustomField>

force-app/main/integration/objects/Integration_Trial_Match__c/fields/Participant_Enrollment_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment_External_ID__c</fullName>
    <label>Participant Enrollment External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/trial-match/objects/Trial_Match__c/Trial_Match__c.object-meta.xml
<CustomObject>
    <label>Trial Match</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Trial Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trial_Match__c/fields/Is_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Is_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/trial-match/objects/Trial_Match__c/fields/Matching_Details__c.field-meta.xml
<CustomField>
    <fullName>Matching_Details__c</fullName>
    <label>Matching Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/trial-match/objects/Trial_Match__c/fields/Matching_Score__c.field-meta.xml
<CustomField>
    <fullName>Matching_Score__c</fullName>
    <label>Matching Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/trial-match/objects/Trial_Match__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/tests/Test_IntegrationTrialMatchTriggerHandler.cls
/**
 * Created by Nargiz Mamedova on 5/6/2020.
 */

@IsTest
private class Test_IntegrationTrialMatchTriggerHandler {
    @TestSetup
    static void setup(){
        TestData.loadTestData();
    }

    @IsTest
    static void testBehavior() {
        TestData testData = new TestData();
        Integration_Trial_Match__c newItm = new Integration_Trial_Match__c(
                Protocol_ID__c = testData.ctp.Protocol_ID__c,
                Participant_Enrollment_External_ID__c = testData.pe.External_Key__c,
                Matching_Score__c = 5, Matching_Details__c = 'Details', Matched_Date__c = Date.today(),
                Therapeutic_Area__c = 'Test TA', IsDeleted__c = false, Is_Eligible__c = true
        );
        Integration_Trial_Match__c changedItm = new Integration_Trial_Match__c(
                Protocol_ID__c = testData.ctp.Protocol_ID__c,
                Participant_Enrollment_External_ID__c = testData.pe.External_Key__c,
                Matching_Score__c = 5, Matching_Details__c = 'Details update', Matched_Date__c = Date.today(),
                Therapeutic_Area__c = 'Test TA', IsDeleted__c = false, Is_Eligible__c = true
        );
        Integration_Trial_Match__c deletedItm = new Integration_Trial_Match__c(
                Protocol_ID__c = testData.ctp.Protocol_ID__c,
                Participant_Enrollment_External_ID__c = testData.pe.External_Key__c,
                Matching_Score__c = 5, Matching_Details__c = 'Details update', Matched_Date__c = Date.today(),
                Therapeutic_Area__c = 'Test TA', IsDeleted__c = true, Is_Eligible__c = false
        );

        Test.startTest();
        insert newItm;
        List<Trial_Match__c> tms = [SELECT Id, Matching_Details__c FROM Trial_Match__c];
        System.assertEquals('Details', tms[0].Matching_Details__c);

        insert changedItm;
        tms = [SELECT Id, Matching_Details__c FROM Trial_Match__c];
        System.assertEquals('Details update', tms[0].Matching_Details__c);

        insert deletedItm;
        Test.stopTest();

        tms = [SELECT Id, Matching_Details__c FROM Trial_Match__c];
        System.assert(tms.size() == 0);
    }

    @IsTest
    static void testExceptionExtKey(){
        Boolean isExceptionThrown = false;
        TestData testData = new TestData();
        Integration_Trial_Match__c newItm = new Integration_Trial_Match__c(
                Protocol_ID__c = testData.ctp.Protocol_ID__c,
                Participant_Enrollment_External_ID__c = 'smth',
                Matching_Score__c = 5, Matching_Details__c = 'Details', Matched_Date__c = Date.today(),
                Therapeutic_Area__c = 'Test TA', IsDeleted__c = false, Is_Eligible__c = true
        );

        Test.startTest();
        try{
            insert newItm;
        } catch (DmlException e){
            isExceptionThrown = true;
        }
        Test.stopTest();
        System.assert(true, isExceptionThrown);
    }

    @IsTest
    static void testExceptionProtId(){
        Boolean isExceptionThrown = false;
        TestData testData = new TestData();
        Integration_Trial_Match__c newItm = new Integration_Trial_Match__c(
                Protocol_ID__c = 'smth',
                Participant_Enrollment_External_ID__c = testData.pe.External_Key__c,
                Matching_Score__c = 5, Matching_Details__c = 'Details', Matched_Date__c = Date.today(),
                Therapeutic_Area__c = 'Test TA', IsDeleted__c = false, Is_Eligible__c = true
        );

        Test.startTest();
        try{
            insert newItm;
        } catch (DmlException e){
            isExceptionThrown = true;
        }
        Test.stopTest();
        System.assert(true, isExceptionThrown);
    }
}