force-app/main/deprecated/objects/Batch_Executor__mdt/Batch_Executor__mdt.object-meta.xml
<CustomObject>
    <label>Batch Executor</label>
    <pluralLabel>Batch Executors</pluralLabel>
</CustomObject>

force-app/main/scheduled-batch/objects/Batch_Executor__mdt/fields/Relaunch_Interval__c.field-meta.xml
<CustomField>
    <fullName>Relaunch_Interval__c</fullName>
    <label>Relaunch Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/scheduled-batch/objects/Batch_Executor__mdt/fields/Scope_Size__c.field-meta.xml
<CustomField>
    <fullName>Scope_Size__c</fullName>
    <label>Scope Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/scheduled-batch/classes/Batch_ScheduledAbstract.cls
/**
 * Created by Igor Malyuta on 31.05.2019.
 */

public abstract class Batch_ScheduledAbstract implements Database.Batchable<SObject>, Database.Stateful{

    public abstract Type getType();

    public virtual void finish(Database.BatchableContext param1) {
        if(Test.isRunningTest()) return;
        List<Batch_Executor__mdt> batchExecutor = [
                SELECT Relaunch_Interval__c, Scope_Size__c
                FROM Batch_Executor__mdt
                WHERE DeveloperName = : getType().getName()
        ];
        if(!batchExecutor.isEmpty()) {
            Integer minutes = batchExecutor.get(0).Relaunch_Interval__c.intValue();
            Integer scopeSize = batchExecutor.get(0).Scope_Size__c.intValue();
            System.scheduleBatch(
                    (Database.Batchable<SObject>) getType().newInstance(), getType().getName(), minutes, scopeSize);
        }
    }

}