force-app/main/deprecated/objects/Batch_Executor__mdt/Batch_Executor__mdt.object-meta.xml
<CustomObject>
    <label>Batch Executor</label>
    <pluralLabel>Batch Executors</pluralLabel>
</CustomObject>

force-app/main/scheduled-batch/objects/Batch_Executor__mdt/fields/Relaunch_Interval__c.field-meta.xml
<CustomField>
    <fullName>Relaunch_Interval__c</fullName>
    <label>Relaunch Interval</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Batch_PatientTaskExpire.cls
/**
 * Created by Igor Malyuta on 28.05.2019.
 */

public with sharing class Batch_PatientTaskExpire implements Database.Batchable<Task>, Database.Stateful{

    private static final String JOB_NAME = 'PatientTaskExpire';

    public Iterable<Task> start(Database.BatchableContext param1) {
        List<Task> tasks = [
                SELECT Id
                FROM Task
                WHERE ActivityDate <=: System.today()
                    AND Status IN: TaskService.TASK_STATUS_GROUP_EXPIRE_AVAILABLE
        ];

        System.debug('Records found: '+ tasks.size());
        return tasks;
    }

    public void execute(Database.BatchableContext param1, List<Task> tasks) {
        for(Task t : tasks) t.Status = TaskService.TASK_STATUS_EXPIRED;
        update tasks;
    }

    public void finish(Database.BatchableContext param1) {
        List<Batch_Executor__mdt> batchExecutor = [
                SELECT Relaunch_Interval__c FROM Batch_Executor__mdt WHERE Job_Name__c = :JOB_NAME];
        if(!batchExecutor.isEmpty()) {
            Integer minutes = batchExecutor.get(0).Relaunch_Interval__c.intValue();
            System.scheduleBatch(
                    new Batch_PatientTaskExpire(), JOB_NAME, minutes);
        }
    }

    public static void run() {
        Database.executeBatch(new Batch_PatientTaskExpire());
    }

    public static void stop() {
        List<CronTrigger> cronTriggers = [
                SELECT Id
                FROM CronTrigger
                WHERE CronJobDetail.Name =: JOB_NAME
        ];
        if(!cronTriggers.isEmpty()) {
            for(CronTrigger cronT : cronTriggers) {
                System.abortJob(cronT.Id);
            }
        }
    }
}