force-app/main/default/objects/Terms_And_Conditions__c/Terms_And_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms And Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms And Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_And_Conditions__c/fields/T_C_Text__c.field-meta.xml
<CustomField>
    <fullName>T_C_Text__c</fullName>
    <label>T&amp;C Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Terms_And_Conditions_Acceptance__c/Terms_And_Conditions_Acceptance__c.object-meta.xml
<CustomObject>
    <label>Terms And Conditions Acceptance</label>
    <nameField>
        <displayFormat>TCA-{000000}</displayFormat>
        <label>Terms And Conditions Acceptance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions Acceptance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_And_Conditions_Acceptance__c/fields/Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Date__c</fullName>
    <label>Accepted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Terms_And_Conditions_Acceptance__c/fields/Terms_And_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_And_Conditions__c</fullName>
    <label>Terms And Conditions</label>
    <referenceTo>Terms_And_Conditions__c</referenceTo>
    <relationshipLabel>Terms And Conditions Acceptance</relationshipLabel>
    <relationshipName>Terms_And_Conditions_Acceptance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_Batch_UpdatePE_PermitEmailFlag.cls
@isTest
public class Test_Batch_UpdatePE_PermitEmailFlag {
@IsTest
    static void testBehavior() {
        
        Account studySiteAccount = new Account(
            Name = 'Study Site Account',
            BillingCountry = 'United States'
        );
        
        insert studySiteAccount;
        
        Contact piContact = new Contact(
            FirstName = 'PITD',
            LastName = 'PITD',
            Email = 'pi@emil.com',
            MailingCountry = 'United States',
            AccountId = studySiteAccount.Id
        );
        insert piContact;
        Terms_And_Conditions__c tc = new Terms_And_Conditions__c(T_C_Text__c = 'T&C');
        insert tc;
        Terms_And_Conditions_Acceptance__c tca = new Terms_And_Conditions_Acceptance__c(Terms_And_Conditions__c = tc.id,
            Accepted_Date__c = system.TODAY());
        insert tca;
        Test.startTest();
        Database.executeBatch(new Batch_UpdatePE_PermitEmailFlag());
        Test.stopTest();
    }
}