force-app/main/default/objects/Contact/fields/Current_Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Current_Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Update_Years_Notification__c.field-meta.xml
<CustomField>
    <fullName>Profile_Update_Years_Notification__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Profile Update Years Notification</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/scheduled-batch/classes/Batch_UserCreatedDateNotification.cls
/**
 * Created by Julia Kazakevich on 19-Sep-19.
 * Refactored by Igor Malyuta on 27-Oct-19
 */

public without sharing class Batch_UserCreatedDateNotification extends Batch_ScheduledAbstract{

    public Database.QueryLocator start(Database.BatchableContext param1) {
        Datetime previousYear = Datetime.now().addYears(-1);
        return Database.getQueryLocator([
                SELECT
                        ContactId,
                        Contact.Current_Participant_Enrollment__c,
                        Contact.Participant_Opt_In_Status_Emails__c,
                        Contact.Profile_Update_Years_Notification__c,
                        CreatedDate
                FROM User
                WHERE CreatedDate =: previousYear
                AND Contact.userCommunityMode__c =: CommunityService.USER_MODE_PARTICIPANT
                AND Contact.Current_Participant_Enrollment__c != NULL
                AND IsActive = TRUE
        ]);
    }

    public void execute(Database.BatchableContext param1, List<User> users) {
        List<Contact> contactsToBeNotified = new List<Contact>();
        for(User user: users) contactsToBeNotified.add(user.Contact);

        if(!contactsToBeNotified.isEmpty()) {
            SendEmailToParticipant.sendParticipantLoginNotification(contactsToBeNotified, true);
            for(Contact contactObj : contactsToBeNotified){
                if(contactObj.Profile_Update_Years_Notification__c == null){
                    contactObj.Profile_Update_Years_Notification__c = 1;
                } else{
                    contactObj.Profile_Update_Years_Notification__c++;
                }
            }
            update contactsToBeNotified;
        }
    }

    public override Type getType() {
        return Batch_UserCreatedDateNotification.class;
    }
}