force-app/main/default/objects/Contact/fields/Current_Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Current_Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityDelegateId__c.field-meta.xml
<CustomField>
    <fullName>userCommunityDelegateId__c</fullName>
    <label>User Community Delegate Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PushNotificationSwitcherUpdate.cls
public without sharing class PushNotificationSwitcherUpdate {
    @AuraEnabled
    public static void updateCurrentContact(String currentPE,String userCommunityDelegateId){
        Contact currentContact = CommunityService.getUserContact();
        //currentContact.Current_Participant_Enrollment__c = currentPE;
        currentContact.userCommunityDelegateId__c = userCommunityDelegateId;
        update currentContact;
        //System.debug('currentContact id : '+currentContact.Id);
    }
}