force-app/main/default/objects/Contact/fields/IQVIA_Artificial_Voice_Consent__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Artificial_Voice_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Artificial Voice Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IQVIA_Assisted_Dialing_Consent__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Assisted_Dialing_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Assisted Dialing Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IQVIA_Contact_info_storage_consent__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Contact_info_storage_consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Contact info storage consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IQVIA_Direct_Mail_Consent__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Direct_Mail_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Direct Mail Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IQVIA_Pre_recorded_Voice_Consent__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Pre_recorded_Voice_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Pre-recorded Voice Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Opt_In_Status_SMS__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Participant Opt In Status SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Phone_Opt_In_Permit_Phone__c.field-meta.xml
<CustomField>
    <fullName>Participant_Phone_Opt_In_Permit_Phone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt In Phone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Mailing Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_UpdateTimeContactsTest.cls
@isTest
public with sharing class Batch_UpdateTimeContactsTest {
    @isTest
    public static void test(){
        Test.startTest();
        TestData.loadTestData();
        TestData testData = new TestData();
        contact con = [select Id from contact limit 1];
        con.IQVIA_Contact_info_storage_consent__c = true;
        con.Participant_Phone_Opt_In_Permit_Phone__c = true;
        con.Participant_Opt_In_Status_SMS__c = true;
        con.Participant_Opt_In_Status_Emails__c = true;
        con.IQVIA_Pre_recorded_Voice_Consent__c = true;
        con.IQVIA_Direct_Mail_Consent__c = true;
        con.IQVIA_Assisted_Dialing_Consent__c = true;
        con.IQVIA_Artificial_Voice_Consent__c = true;
        TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.UpdateParticipantAndUserEmailsOnEmailChangeHandler.class);
                TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.createNotificationsHandler.class);
                TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.CreateUserForDelegateContactHandler.class);
                TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.SetShowTourDefaultHandler.class);
                TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.PopulateOverrideFields.class);
                TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.CreateUserForCCContactHandler.class);
                TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.UpdateParticipantDetailsHandler.class);
                TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.UpdatePhoneNumberContactsHandler.class);
                TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.UpdateConsentTimeStamps.class);
                TriggerHandlerExecutor.bypassHandler(ContactTriggerHandler.ParticipantConsentUpdate.class);
                
        update con;
        Participant__c part = [select Id from Participant__c where contact__c !=null limit 1];
        part.Mailing_Country__c = 'United Kingdom';
        part.Mailing_Country_Code__c = 'GB';
        update part;
        Batch_UpdatetimestampsexistingContacts batch = new Batch_UpdatetimestampsexistingContacts();
        database.executeBatch(batch, 2000);
        Test.stopTest();
    }
}