force-app/main/default/objects/Contact/fields/Is_First_Logon__c.field-meta.xml
<CustomField>
    <fullName>Is_First_Logon__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is First Logon</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Second_Choice_Language__c.field-meta.xml
<CustomField>
    <fullName>Second_Choice_Language__c</fullName>
    <inlineHelpText>This will be used to display study information when your Preferred Language is not available.</inlineHelpText>
    <label>2nd Choice Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Third_Choice_Language__c.field-meta.xml
<CustomField>
    <fullName>Third_Choice_Language__c</fullName>
    <inlineHelpText>This will be used to display study information when your other two choices are not available.</inlineHelpText>
    <label>3rd Choice Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunytyType__c.field-meta.xml
<CustomField>
    <fullName>userCommunytyType__c</fullName>
    <description>User types for community - HCP / PI / Participant</description>
    <inlineHelpText>Select user types for community</inlineHelpText>
    <label>User Community Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/HCP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HCP_Contact__c</fullName>
    <label>HCP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HCP&#39;s Study Sites</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>HCP Status per clinical trial by PI</description>
    <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
    <label>HCP Status</label>

    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>On Hold (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending Orientation</fullName>
            </value>
            <value>
                <fullName>Declined (Approval)</fullName>
            </value>
            <value>
                <fullName>On Hold (Approval)</fullName>
            </value>
            <value>
                <fullName>Declined (Activation)</fullName>
            </value>
            <value>
                <fullName>On Hold (Activation)</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Activated (Admin)</fullName>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
            </value>
            <value>
                <fullName>Declined (Admin)</fullName>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Participant&#39;s First Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s First Name</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Mailing Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Postal_Code__c</fullName>
    <label>Mailing Zip/Postal Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Phone</label>

    <type>Phone</type>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions__c/Terms_And_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms And Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms And Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Terms_And_Conditions__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>

    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions__c/fields/T_C_Text__c.field-meta.xml
<CustomField>
    <fullName>T_C_Text__c</fullName>
    <label>T&amp;C Text</label>
    <length>65536</length>
    <type>Html</type>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions_Acceptance__c/Terms_And_Conditions_Acceptance__c.object-meta.xml
<CustomObject>

    <label>Terms And Conditions Acceptance</label>
    <nameField>
        <displayFormat>TCA-{000000}</displayFormat>
        <label>Terms And Conditions Acceptance Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions Acceptance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions_Acceptance__c/fields/Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Accepted Date</label>

    <type>DateTime</type>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions_Acceptance__c/fields/Terms_And_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_And_Conditions__c</fullName>
    <label>Terms And Conditions</label>
    <referenceTo>Terms_And_Conditions__c</referenceTo>
    <relationshipLabel>Terms And Conditions Acceptance</relationshipLabel>
    <relationshipName>Terms_And_Conditions_Acceptance</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Terms_And_Conditions_Acceptance__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Terms_And_Conditions_Acceptance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Translation__c/Translation__c.object-meta.xml
<CustomObject>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/community-template/first-login/classes/FirstLogonController.cls
/**
 * Created by Nargiz Mamedova on 10/15/2019.
 */

public without sharing class FirstLogonController {
    public static final String ERROR_SUFFIX = ': You must enter a value';
    public static final String ERROR_VALUE_SUFFIX = ': You must enter a valid value';

    public String photolink { get; set; }
    public String newPassword { get; set; }
    public String verifyNewPassword { get; set; }
    public Boolean isPasswordsEquals { get; set; }


    public User currUser { get; set; }
    public Contact contact { get; set; }
    public Account account { get; set; }
    public Boolean isParticipant { get; set; }

    public String helpText_1st_Language { get; private set; }
    public String helpText_2nd_Language { get; private set; }
    public String helpText_3rd_Language { get; private set; }

    public Boolean notEnrollNow { get; set; }
    public Boolean isProfileView { get; set; }
    public String tcText { get; set; }
    public String tcId { get; set; }
    public Participant__c participant { get; set; }

    public Translation__c translation { get; set; }

    private String previousLanguage;

    public List<SelectOption> countries { get; set; }
    public List<SelectOption> states { get; set; }
    public Boolean isStateRequired { get; set; }


    private Map<String, List<LabelValueItem>> statesByCountryMap = CountryStateUtil.getStatesByCountryMap();
    private Map<String, String> countryCodeByName = new Map<String, String>();
    private String oldAccountName;

    public FirstLogonController() {
        getUserAndContactAndAccount();
        initLanguagesAndTranslation();
        photolink = currUser.FullPhotoUrl;
        isProfileView = true;
        isPasswordsEquals = true;

        tcText = '';
        Terms_And_Conditions__c portalTC = TermsAndConditions.getPortalTC(false);
        if (portalTC != null) {
            tcText = portalTC.T_C_Text__c;
            tcId = portalTC.Id;
        }
    }

    private void getUserAndContactAndAccount() {
        currUser = UserContext.getUser();
        contact = UserContext.getUserContact();
        account = UserContext.getUserContact().Account;

        notEnrollNow = !((contact.userCommunytyType__c == null || contact.userCommunytyType__c.contains(CommunityService.USER_MODE_HCP))
                && contact.userCommunityMode__c == CommunityService.USER_MODE_HCP);
        isStateRequired = false;

        account.BillingCountry = TranslateHelper.getPickListLabel(User.CountryCode, account.BillingCountryCode);
        oldAccountName = account.Name;

        isParticipant = contact.userCommunityMode__c == CommunityService.USER_MODE_PARTICIPANT;
        if (isParticipant) {
            participant = [
                    SELECT Id, Name, First_Name__c, Last_Name__c, Phone__c,
                            Mailing_Country__c, Mailing_State__c, Mailing_Zip_Postal_Code__c,
                            Mailing_Country_Code__c, Mailing_State_Code__c

                    FROM Participant__c
                    WHERE Contact__c = :contact.Id
            ];
            updateTranslations();
        }
    }
    
    public String getCommunityLogoURL(){
        return UserContext.getTemplateProperty(CommunityTemplateService.PROPERTY_COMMUNITY_LOGO);
    }

    private void initLanguagesAndTranslation() {
        previousLanguage = contact.Language__c;

        Map<String, SObjectField> fieldMap = Schema.SObjectType.Contact.fields.getMap();
        helpText_1st_Language = fieldMap.get('Language__c').getDescribe().inlineHelpText;
        helpText_2nd_Language = fieldMap.get('Second_Choice_Language__c').getDescribe().inlineHelpText;
        helpText_3rd_Language = fieldMap.get('Third_Choice_Language__c').getDescribe().inlineHelpText;

        translation = new Translation__c();
        if (!contact.Is_First_Logon__c) translation.Language__c = currUser.LanguageLocaleKey;
    }

    public void showProfileAction() {
        isProfileView = true;
    }

    public void checkPasswords() {
        updateNameOfAccount();

        ApexPages.getMessages().clear();
        if (!notEnrollNow) {
            addMessageToPage(contact.FirstName, 'First Name');
            addMessageToPage(contact.LastName, 'Last Name');
            addMessageToPage(contact.MailingStreet, 'Street Address');
            addMessageToPage(contact.MailingCity, 'City');
            addMessageToPage(contact.MailingCountry, 'Country');
            if (states.size() > 1) addMessageToPage(contact.MailingState, 'State');
            addMessageToPage(contact.MailingPostalCode, 'ZIP/Postal Code');
            addMessageToPage(contact.Phone, 'Phone Number');
            addMessageToPage(account.Name, 'Institute Name');
        }

        try {
            Site.validatePassword(currUser, newPassword, verifyNewPassword);
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }

        if (!notEnrollNow) {
            if (ApexPages.getMessages().size() == 0) {
                List<HCP_Enrollment__c> hcpEnrollments = [
                        SELECT Id,
                                HCP_Contact__c,
                                Status__c
                        FROM HCP_Enrollment__c
                        WHERE HCP_Contact__c = :contact.Id AND
                        Status__c = :HCPEnrollmentService.HCP_S_ON_HOLD_ACTIVATION
                ];
                for (HCP_Enrollment__c hcpe : hcpEnrollments) {
                    hcpe.Status__c = HCPEnrollmentService.HCP_S_INVITATION_SENT;
                }
                if (!hcpEnrollments.isEmpty()) {
                    update hcpEnrollments;
                }
                for (HCP_Enrollment__c hcpe : hcpEnrollments) {
                    hcpe.Status__c = HCPEnrollmentService.HCP_S_ACTIVATED;
                }
                if (!hcpEnrollments.isEmpty()) {
                    update hcpEnrollments;
                }
            }
        }

        if (ApexPages.getMessages().size() == 0) isProfileView = false;
    }

    @TestVisible
    private void updateNameOfAccount() {
        if (account.Name != oldAccountName && !String.isEmpty(account.Name)) {
            Account newClinic = new Account(
                    Name = account.Name,
                    BillingCountry = contact.MailingCountry,
                    BillingCity = contact.MailingCity,
                    BillingState = contact.MailingState,
                    BillingStreet = contact.MailingStreet,
                    BillingPostalCode = contact.MailingPostalCode,
                    Phone = contact.Phone,
                    Fax = contact.Fax,
                    OwnerId = contact.OwnerId
            );
            try {
                insert newClinic;
                contact.AccountId = newClinic.Id;
            } catch (Exception exp) {}
        }

        try {
            update contact;
        } catch (Exception exp) {}
    }

    private void addMessageToPage(String field, String message) {
        if (String.isBlank(field)) ApexPages.addMessage(
                new ApexPages.Message(
                        ApexPages.Severity.ERROR,
                        message + ERROR_SUFFIX)
        );
    }

    public PageReference setPassword() {

        if (tcId != null) {
            Terms_And_Conditions_Acceptance__c tca = new Terms_And_Conditions_Acceptance__c();
            tca.Accepted_Date__c = Datetime.now();
            tca.Terms_And_Conditions__c = tcId;
            tca.User__c = UserInfo.getUserId();
            try {
                insert tca;
            } catch (Exception e) {}
        }

        PageReference pageReference;
        try {
            pageReference = Site.changePassword(newPassword, verifyNewPassword, null);
            contact.Is_First_Logon__c = false;
            update contact;
        } catch (Exception e) {
            ApexPages.addMessages(e);
            isProfileView = true;
        }
        return pageReference;
    }

    private void updateTranslations() {
        if (isParticipant) {
            //translate country:
            participant.Mailing_Country__c = CountryStateUtil.getCountryName(participant.Mailing_Country_Code__c);
            //translate state
            participant.Mailing_State__c = CountryStateUtil.getStateName(participant.Mailing_Country_Code__c, participant.Mailing_State_Code__c);
        }
    }

    public void updateLanguageAction() {
        if (String.isBlank(contact.Language__c)) contact.Language__c = previousLanguage;
        currUser.LanguageLocaleKey = contact.Language__c;

        try {
            update currUser;
            updateTranslations();
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }
    }

    public void updateStatesAction() {
        states = new List<SelectOption>();
        List<LabelValueItem> statesByCountry = statesByCountryMap.get(countryCodeByName.get(contact.MailingCountry));
        if (statesByCountry != null) {
            for (LabelValueItem state : statesByCountry) {
                states.add(new SelectOption(state.label, state.label));
            }
        }
        isStateRequired = statesByCountry != null && !statesByCountry.isEmpty();
    }
}