force-app/main/default/objects/Contact/fields/Is_First_Logon__c.field-meta.xml
<CustomField>
    <fullName>Is_First_Logon__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is First Logon</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Second_Choice_Language__c.field-meta.xml
<CustomField>
    <fullName>Second_Choice_Language__c</fullName>
    <inlineHelpText>This will be used to display study information when your Preferred Language is not available.</inlineHelpText>
    <label>2nd Choice Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Third_Choice_Language__c.field-meta.xml
<CustomField>
    <fullName>Third_Choice_Language__c</fullName>
    <inlineHelpText>This will be used to display study information when your other two choices are not available.</inlineHelpText>
    <label>3rd Choice Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UserCommunityIsDelegate__c.field-meta.xml
<CustomField>
    <fullName>UserCommunityIsDelegate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Community Is Delegate</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunytyType__c.field-meta.xml
<CustomField>
    <fullName>userCommunytyType__c</fullName>
    <description>User types for community - HCP / PI / Participant</description>
    <inlineHelpText>Select user types for community</inlineHelpText>
    <label>User Community Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/community-template/first-login/ChangePasswordPageController.cls
/**
 * Created by Nargiz Mamedova on 10/15/2019.
 */

public without sharing class ChangePasswordPageController {
    public User user {get; set;}
    public Contact contact {get; set;}

    public String browserLanguage {get; set;}

    public Boolean isParticipant {get; set;}

    public ChangePasswordPageController() {
        user = [
                SELECT Id,
                        Contact.Is_First_Logon__c,
                        Contact.Language__c,
                        Contact.Second_Choice_Language__c,
                        Contact.Third_Choice_Language__c,
                        Contact.userCommunityMode__c,
                        Contact.userCommunytyType__c,
                        Contact.UserCommunityIsDelegate__c,
                        LanguageLocaleKey
                FROM User
                WHERE Id =: UserInfo.getUserId()
        ];

        contact = user.Contact;

        isParticipant = contact.userCommunityMode__c == CommunityService.USER_MODE_PARTICIPANT && !contact.UserCommunityIsDelegate__c;

    }

    public void updateBrowserLanguageAction(){
        List<String> browserLanguages = (List<String>)JSON.deserialize(browserLanguage, List<String>.class);
        List<String> convertedLanguages = new List<String>();
        for (String bLanguage : browserLanguages ) {
            String convertedLanguage = TranslateHelper.convertBrowserLanguage(new List<String> { bLanguage });
            if(convertedLanguage != null) convertedLanguages.add(convertedLanguage);
        }
        if(convertedLanguages.size() > 0) convertedLanguages.add('en_US');
        user.Contact.Language__c = convertedLanguages.remove(0);

        if(convertedLanguages.size() > 0) user.Contact.Second_Choice_Language__c = convertedLanguages.remove(0);
        if(convertedLanguages.size() > 0) user.Contact.Third_Choice_Language__c = convertedLanguages.remove(0);

        update user.Contact;
        user.LanguageLocaleKey = user.Contact.Language__c;
        update user;
    }
}