force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Resource_Notifications__c</fullName>
    <label>Resource Notifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Second_Choice_Language__c.field-meta.xml
<CustomField>
    <fullName>Second_Choice_Language__c</fullName>
    <inlineHelpText>This will be used to display study information when your Preferred Language is not available.</inlineHelpText>
    <label>2nd Choice Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Third_Choice_Language__c.field-meta.xml
<CustomField>
    <fullName>Third_Choice_Language__c</fullName>
    <inlineHelpText>This will be used to display study information when your other two choices are not available.</inlineHelpText>
    <label>3rd Choice Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityDelegateId__c.field-meta.xml
<CustomField>
    <fullName>userCommunityDelegateId__c</fullName>
    <label>User Community Delegate Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserCommunityIsDelegate__c.field-meta.xml
<CustomField>
    <fullName>UserCommunityIsDelegate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Community Is Delegate</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/messaging/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Notification__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Target_Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>Target_Record_Ids__c</fullName>
    <label>Target Record Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/Therapeutic_Area_Patient__c.object-meta.xml
<CustomObject>
    <label>Therapeutic Area Patient</label>
    <nameField>
        <displayFormat>TAP - {00000000}</displayFormat>
        <label>Therapeutic Area Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Therapeutic Area Patients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Therapeutic Areas</relationshipLabel>
    <relationshipName>Therapeutic_Area_Patients</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Therapeutic Area Patients</relationshipLabel>
    <relationshipName>Therapeutic_Area_Patients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/scheduled-batch-implementation/classes/Batch_InsertPlatformResNotification.cls
/**
 * Created by Sandeep on 17.03.2023.
 */
public without sharing class Batch_InsertPlatformResNotification implements Database.Batchable<SObject>, Database.AllowsCallouts {
    public Map<Id, Batch_CreatePlatformResourceNotification.ThereaputicAreaLang> resWithTherapeuticAreasMap = new Map<Id, Batch_CreatePlatformResourceNotification.ThereaputicAreaLang>();

    public Batch_InsertPlatformResNotification(
        Map<Id, Batch_CreatePlatformResourceNotification.ThereaputicAreaLang> resWithTherapeuticAreasMap
    ) {
        this.resWithTherapeuticAreasMap = resWithTherapeuticAreasMap;
    }

    public Database.QueryLocator start(Database.BatchableContext param1) {
        List<Id> theraputicAreaIds = new List<Id>();
        for (Id resId : this.resWithTherapeuticAreasMap.keySet()) {
            theraputicAreaIds.addAll(this.resWithTherapeuticAreasMap.get(resId).therapeuticAreaIds);
        }
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    Participant__r.Contact__c,
                    Participant__r.Contact__r.userCommunityDelegateId__c,
                    Participant__r.Contact__r.UserCommunityIsDelegate__c,
                    Participant__c,
                    Therapeutic_Area__c,
                    Participant__r.Contact__r.Resource_Notifications__c,
                    Participant__r.Contact__r.Third_Choice_Language__c,
                    Participant__r.Contact__r.Second_Choice_Language__c,
                    Participant__r.Contact__r.Language__c
                FROM Therapeutic_Area_Patient__c
                WHERE
                    Participant__r.Contact__r.userCommunityMode__c = 'Participant'
                    AND Therapeutic_Area__c = :theraputicAreaIds
            ]
        );
    }
    public void execute(
        Database.BatchableContext param1,
        List<Therapeutic_Area_Patient__c> therapeuticAreaPatientsList
    ) {
        Map<Id, Contact> contactstoNotify = new Map<Id, Contact>();
        List<Notification__c> notificationsList = new List<Notification__c>();

        List<Id> participantContactIds = new List<Id>();
        Map<Id, Integer> contactPeMap = new Map<Id, Integer>();
        for (Therapeutic_Area_Patient__c tap : therapeuticAreaPatientsList) {
            if (!tap.Participant__r.Contact__r.UserCommunityIsDelegate__c) {
                participantContactIds.add(tap.Participant__r.Contact__c);
            }
        }
        for (AggregateResult aggre : [
            SELECT Participant__r.Contact__c contactId, Count(Id) counterr
            FROM Participant_Enrollment__c
            WHERE
                Participant_Status__c IN :PEStatusState.PE_STATUS_GROUP_ALUMNI
                AND Participant__r.Contact__c = :participantContactIds
            GROUP BY Participant__r.Contact__c
        ]) {
            contactPeMap.put((Id) aggre.get('contactId'), (Integer) aggre.get('counterr'));
        }
        for (Therapeutic_Area_Patient__c tap : therapeuticAreaPatientsList) {
            Contact currentContact;
            if (contactstoNotify.get(tap.Participant__r.Contact__c) != null) {
                currentContact = contactstoNotify.get(tap.Participant__r.Contact__c);
            } else {
                currentContact = new Contact(
                    Id = tap.Participant__r.Contact__c,
                    Resource_Notifications__c = tap.Participant__r.Contact__r.Resource_Notifications__c
                );
            }
            Boolean notifyUser = false;
            for (Id resourceId : resWithTherapeuticAreasMap.keySet()) {
                Boolean isResourceVisible = false;
                Batch_CreatePlatformResourceNotification.ThereaputicAreaLang therapeuticAreaLang = resWithTherapeuticAreasMap.get(
                    resourceId
                );
                if (
                    tap.Participant__r.Contact__r.UserCommunityIsDelegate__c ||
                    (contactPeMap.get(tap.Participant__r.Contact__c) != null &&
                    contactPeMap.get(tap.Participant__r.Contact__c) > 0 &&
                    therapeuticAreaLang.contentClass == '3rd Party') ||
                    (therapeuticAreaLang.contentClass == 'Platform-TA' &&
                    contactPeMap.get(tap.Participant__r.Contact__c) == null)
                ) {
                    if (
                        currentContact.Resource_Notifications__c == null ||
                        !currentContact.Resource_Notifications__c.contains(resourceId)
                    ) {
                        notifyUser = true;
                    }

                    if (
                        notifyUser &&
                        ((therapeuticAreaLang.langCodeList.contains(
                            tap.Participant__r.Contact__r.Language__c
                        )) ||
                        (therapeuticAreaLang.langCodeList.contains(
                            tap.Participant__r.Contact__r.Second_Choice_Language__c
                        )) ||
                        (therapeuticAreaLang.langCodeList.contains(
                            tap.Participant__r.Contact__r.Third_Choice_Language__c
                        )))
                    ) {
                        notifyUser = true;

                        currentContact.Resource_Notifications__c = currentContact.Resource_Notifications__c !=
                            null
                            ? currentContact.Resource_Notifications__c + ';' + resourceId
                            : resourceId;
                    } else {
                        notifyUser = false;
                    }
                    if (
                        notifyUser &&
                        therapeuticAreaLang.therapeuticAreaIds.contains(tap.Therapeutic_Area__c)
                    ) {
                        String notificationType;
                        if (therapeuticAreaLang.resourceType == 'Article') {
                            notificationType = NotificationCatalog.UPDATE_TO_PT_NEW_PLATFROM_ARTICLE_TYPE;
                        }
                        if (therapeuticAreaLang.resourceType == 'Video') {
                            notificationType = NotificationCatalog.UPDATE_TO_PT_NEW_PLATFORM_VIDEO_TYPE;
                        }
                        if (therapeuticAreaLang.resourceType == 'Multimedia') {
                            notificationType = NotificationCatalog.UPDATE_TO_PT_NEW_PLATFROMMULTIMEDIA_TYPE;
                        }
                        if (therapeuticAreaLang.resourceType == 'Relevant_Link') {
                            notificationType = NotificationCatalog.UPDATE_TO_PT_NEW_PLATFORM_LINK_TYPE;
                        }
                        notificationsList.add(
                            new Notification__c(
                                Recipient__c = tap.Participant__r.Contact__c,
                                WhatId__c = tap.Participant__c,
                                Notification_Type__c = notificationType,
                                Target_Record_Ids__c = '' + resourceId
                            )
                        );
                        notifyUser = true;
                    } else {
                        notifyUser = false;
                    }
                }
            }
            if (notifyUser) {
                contactstoNotify.put(currentContact.Id, currentContact);
            }
        }

        if (contactstoNotify.size() > 0)
            update contactstoNotify.values();
        if (notificationsList.size() > 0)
            insert notificationsList;
    }
    public void finish(Database.BatchableContext param1) {
        system.debug('The job is finished');
    }
}