force-app/main/default/objects/Contact/fields/Phone_Type__c.field-meta.xml
<CustomField>
    <fullName>Phone_Type__c</fullName>
    <label>Phone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/Integration_Patient_Referral__c.object-meta.xml
<CustomObject>
    <label>Integration Patient Referral</label>
    <nameField>
        <label>Integration Patient Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Patient Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Address_Country__c.field-meta.xml
<CustomField>
    <fullName>Address_Country__c</fullName>
    <label>Address_Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <label>Address_State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Address_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>Address_ZipCode__c</fullName>
    <label>Address_ZipCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <label>BirthDate</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/birthYear__c.field-meta.xml
<CustomField>
    <fullName>birthYear__c</fullName>
    <label>birthYear</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <label>Data_Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <label>firstName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language_Preference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/lastName__c.field-meta.xml
<CustomField>
    <fullName>lastName__c</fullName>
    <label>lastName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Integration Patient Referrals</relationshipLabel>
    <relationshipName>Integration_Patient_Referrals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/phone__c.field-meta.xml
<CustomField>
    <fullName>phone__c</fullName>
    <label>phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Patient_Referral__c/fields/Phone_Type__c.field-meta.xml
<CustomField>
    <fullName>Phone_Type__c</fullName>
    <label>Phone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/integration/objects/Integration_Patient_Referral__c/fields/sex__c.field-meta.xml
<CustomField>
    <fullName>sex__c</fullName>
    <label>sex</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Email</label>

    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Participant&#39;s First Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s First Name</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Postal_Code__c</fullName>
    <label>Mailing Zip/Postal Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Phone</label>

    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone_Type__c.field-meta.xml
<CustomField>
    <fullName>Phone_Type__c</fullName>
    <label>Phone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <label>Mailing Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source__c</fullName>
    <description>HCP/Physician Participant Referral Source</description>
    <inlineHelpText>HCP/Physician Participant Referral Source</inlineHelpText>
    <label>Referral Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>HCP Prescreen Log</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>ePR</fullName>
            </value>
            <value>
                <fullName>ACOE</fullName>
            </value>
            <value>
                <fullName>3rd_Party</fullName>
                <label>3rd Party</label>
            </value>
            <value>
                <fullName>Autocruitment</fullName>
            </value>
            <value>
                <fullName>23andMe</fullName>
            </value>
            <value>
                <fullName>IQVIA registry</fullName>
            </value>
            <value>
			 <fullName>Ciitizen</fullName>
                </value>
            <value>
                <fullName>MassiveBio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/Patient_Delegate__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate</label>
    <nameField>
        <displayFormat>PD-{00000000}</displayFormat>
        <label>Patient Delegate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/deprecated/classes/DuplicateContactController.cls
/**
 * Created by Denis Shpilevsky
 */

//TODO !!! DEPRECATED MUST BE REMOVED!!!

public without sharing class  DuplicateContactController {

    /*
    public static Boolean isPERCreated = false;
    public static void checkDuplicates(Integration_Patient_Referral__c record){
        primaryPhoneEmailCheck(record);
    }

    public static Participant__c communityReffering(Participant__c participant, Participant_Enrollment__c participantEnrollment){
        Integration_Patient_Referral__c tempRecord = new Integration_Patient_Referral__c(
                firstName__c = participant.First_Name__c,
                lastName__c = participant.Last_Name__c,
                email__c = participant.Email__c,
                phone__c = participant.Phone__c,
                Phone_Type__c = participant.Phone_Type__c,
                birthYear__c = participant.Date_of_Birth__c != null && participant.Date_of_Birth__c != '' ?  getYearOfBirth(participant.Date_of_Birth__c) : '',
                Address_Country__c = participant.Mailing_Country_Code__c,
                Address_State__c = CountryStateUtil.getStateName(participant.Mailing_Country_Code__c, participant.Mailing_State_Code__c),
                Data_Source__c = participantEnrollment.Referral_Source__c,
                sex__c = participant.Gender__c,
                Address_ZipCode__c = participant.Mailing_Zip_Postal_Code__c
        );
        if(String.isEmpty(tempRecord.Language_Preference__c)) tempRecord.Language_Preference__c = UserInfo.getLanguage();
        if(participant.Date_of_Birth__c != null) {
            if (participant.Date_of_Birth__c.indexOf('-') == 4 || participant.Date_of_Birth__c.indexOf('/') == 4) {
                tempRecord.BirthDate__c = participant.Date_of_Birth__c.replaceAll('/', '-');
            } else {
                tempRecord.BirthDate__c = participant.Date_of_Birth__c.substring(3, 5) + '/' + participant.Date_of_Birth__c.substring(0, 2) + '/' + participant.Date_of_Birth__c.substring(6);
            }
        }
        Participant__c participantRecord = primaryPhoneEmailCheck(tempRecord);
        isPERCreated = false;
        return participantRecord;
    }

    private static Participant__c primaryPhoneEmailCheck(Integration_Patient_Referral__c record){
        Participant__c participant = new Participant__c();
        List<Contact> contactRecords = new List<Contact>();
        List<Participant__c> participantRecords = new List<Participant__c>();
        List<Id> contactsIds = new List<Id>();
        String email = record.email__c == null ? '+' : record.email__c;
        String phone = record.phone__c == null ? '+' : record.phone__c;

        participantRecords = [
                SELECT  id,
                        Contact__c
                FROM    Participant__c
                WHERE   (Email__c = :email OR
                Phone__c = :phone)
        ];
        for(Participant__c item : participantRecords){
            contactsIds.add(item.Contact__c);
        }

        contactRecords = [
                SELECT 	id,
                        BirthDate,
                        FirstName,
                        LastName,
                        userCommunityMode__c,
                        userCommunytyType__c,
                (
                        SELECT	id,
                                First_Name__c,
                                Last_Name__c,
                                Phone__c,
                                Email__c,
                                Date_of_Birth__c,
                                Birth_Year__c
                        FROM	Participants__r
                )
                FROM    Contact
                WHERE   (Email = :email OR
                Phone = :phone OR Id IN:contactsIds)
        ];

        Integer recordsContactCount = contactRecords.size();
        if(recordsContactCount != 0){
            if((record.BirthYear__c != null && record.BirthYear__c != '') || (record.BirthDate__c != null && record.BirthDate__c != '')){
                for(Integer i = 0; i < recordsContactCount; i++){
                    if(checkBirthDate(record, contactRecords[i])){
                        System.debug('Passed checkBirthDate');
                        if(checkFirstName(record, contactRecords[i])){
                            System.debug('Passed checkFirstName');
                            participant = processedDuplicate(contactRecords[i].id, record);
                            break;
                        }else if(recordsContactCount == (i + 1)){
                            participant = createNewRecords(record);
                            break;
                        }
                    }else if(contactRecords[i].BirthDate == null && dateIsPresentInSystem(contactRecords[i]) && checkBirthDateWeak(record)){
                        System.debug('BirthDate null');
                        if(checkFirstName(record, contactRecords[i])){
                            System.debug('Passed checkBirthDate');
                            contactRecords[i].BirthDate = record.BirthDate__c != null ? convertBirthDate(record.BirthDate__c) : Date.newInstance(Integer.valueOf(record.BirthYear__c), 1, 1);
                            participant = processedDuplicate(contactRecords[i].id, record);
                            break;
                        }else if(recordsContactCount == (i + 1)){
                            participant = createNewRecords(record);
                            break;
                        }
                    }else if(recordsContactCount == (i + 1)){
                        participant = createNewRecords(record);
                        break;
                    }
                }
            }else{
                for(Integer i = 0; i < recordsContactCount; i++){
                    if(checkFirstName(record, contactRecords[i])){
                        System.debug('Passed checkFirstName');
                        if(checkLastName(record,contactRecords[i])){
                            System.debug('Passed checkLastName');
                            if(contactRecords[i].userCommunytyType__c == null  || !contactRecords[i].userCommunytyType__c.contains(CommunityService.USER_MODE_PARTICIPANT)){
                                participant = ParticipantDeduplicationController.checkPER(contactRecords[i].id, record);
                                break;
                            }else{
                                participant = processedDuplicate(contactRecords[i].id, record);
                                break;
                            }

                        }else if(recordsContactCount == (i + 1)){
                            participant = createNewRecords(record);
                            break;
                        }
                    }else if(recordsContactCount == (i + 1)){
                        participant = createNewRecords(record);
                        break;
                    }
                }
            }
        }else{
            participant = createNewRecords(record);
        }
        if(!isPERCreated){
            update contactRecords;
        }
        return participant;
    }

    private static Participant__c createNewRecords(Integration_Patient_Referral__c record){
        System.debug('createNewRecords');
        return ParticipantDeduplicationController.checkPER(record);
    }

    private static Participant__c processedDuplicate(String contactId, Integration_Patient_Referral__c record){
        System.debug('processedDuplicate');
        List<Participant__c> listOfParticipants = new List<Participant__c>();
        listOfParticipants = [SELECT id, Secondary_Source__c FROM Participant__c WHERE Contact__c = :contactId];
        if(listOfParticipants.size() != 0){
            if(!isPERCreated){
                return ParticipantDeduplicationController.checkPER(contactId, listOfParticipants[0], record);
            }else{
                return listOfParticipants[0];
            }
        }else{
            return ParticipantDeduplicationController.checkPER(contactId, record);
        }
    }

    private static boolean checkFirstName(Integration_Patient_Referral__c record, Contact contactRecord){
        System.debug('checkFirstName');
        return  record.firstName__c  == contactRecord.FirstName ||
                (
                        !contactRecord.Participants__r.isEmpty() &&
                            contactRecord.Participants__r[0].First_Name__c == record.firstName__c
                );
    }

    private static boolean checkLastName(Integration_Patient_Referral__c record, Contact contactRecord){
        System.debug('checkLastName');
        return  record.lastName__c == contactRecord.LastName ||
                (
                        !contactRecord.Participants__r.isEmpty() &&
                                contactRecord.Participants__r[0].Last_Name__c == record.lastName__c
                );
    }

    private static boolean checkBirthDate(Integration_Patient_Referral__c record, Contact contactRecord){
        System.debug('checkBirthDate');
        if(!String.isEmpty(record.BirthDate__c)){
            return  (
                    contactRecord.BirthDate != null &&
                            contactRecord.BirthDate == convertBirthDate(record.BirthDate__c)
            ) ||
                    (
                            !contactRecord.Participants__r.isEmpty() &&
                                    !String.isEmpty(contactRecord.Participants__r[0].Date_of_Birth__c) &&
                                    convertBirthDate(contactRecord.Participants__r[0].Date_of_Birth__c) == convertBirthDate(record.BirthDate__c)
                    ) ||
                    (
                            !contactRecord.Participants__r.isEmpty() &&
                                    !String.isEmpty(contactRecord.Participants__r[0].Birth_Year__c) &&

                                    contactRecord.Participants__r[0].Birth_Year__c == getYearOfBirth(record.BirthDate__c)
                    );
        }else{
            return  (
                    contactRecord.BirthDate != null && record.BirthYear__c == String.valueOf(contactRecord.BirthDate.year())
            ) ||
                    (
                            !contactRecord.Participants__r.isEmpty() &&
                                    !String.isEmpty(contactRecord.Participants__r[0].Date_of_Birth__c) &&
                                    record.BirthYear__c == getYearOfBirth(contactRecord.Participants__r[0].Date_of_Birth__c)
                    ) ||
                    (
                            !contactRecord.Participants__r.isEmpty() &&
                                    !String.isEmpty(contactRecord.Participants__r[0].Birth_Year__c) &&
                                    record.BirthYear__c == contactRecord.Participants__r[0].Birth_Year__c
                    );
        }
    }


    private static boolean checkBirthDateWeak(Integration_Patient_Referral__c record){
        System.debug('checkBirthDate');
        if(record.BirthDate__c != null && record.BirthDate__c != ''){
            return !checkBirthDate(getYearOfBirth(record.BirthDate__c));
        }else{
            return !checkBirthDate(record.BirthYear__c);
        }
    }

    private static boolean dateIsPresentInSystem(Contact contactRecord){
        return  contactRecord.Participants__r.isEmpty() ||
                (
                        contactRecord.Participants__r[0].Date_of_Birth__c == null &&
                                contactRecord.Participants__r[0].Birth_Year__c == null
                );
    }

    private static boolean checkBirthDate(String birthYear){
        System.debug('birthYear:' + birthYear);
        if(String.isEmpty(birthYear)){
            System.debug('empty birthdate');
            return true;
        }
        Integer referralDateYear = Integer.valueOf(birthYear);
        Integer currentYear = Date.today().year();
        if((currentYear - referralDateYear) > 18){
            System.debug('+18');
            return false;
        }else{
            System.debug('-18');
            return true;
        }

    }

    private static Date convertBirthDate(String birthDate){
        if(birthDate.length() == 10){
            System.debug(birthDate);
            String updatedDateString = birthDate;
            if(birthDate.indexOf('-') == 2 || birthDate.indexOf('/') == 2) {
                updatedDateString = birthDate.substring(6) + '-' + birthDate.substring(0, 2) + '-' + birthDate.substring(3, 5);
            }
            Date newDate = Date.valueOf(updatedDateString);
            return newDate;
        }
        return null;
    }

    private static String getYearOfBirth(String birthDate){
        if(birthDate.indexOf('-') == 2 || birthDate.indexOf('/') == 2){
            return birthDate.substring(6);
        }
        return birthDate.substring(0,4);
    }
    */

}