force-app/main/default/objects/Contact/fields/UserCommunityIsDelegate__c.field-meta.xml
<CustomField>
    <fullName>UserCommunityIsDelegate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Community Is Delegate</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/messaging/email-template/classes/EmailTemplateInitialFactory.cls
/**
 * Created by Igor Malyuta on 23.03.2020.
 */

public without sharing class EmailTemplateInitialFactory {

    public static EmailTemplateInitial getTemplateInitial(Id userId, String outputMode, String communityTemplateName) {
        User user = [
                SELECT ContactId,
                        Contact.UserCommunityIsDelegate__c,
                        Contact.userCommunityMode__c
                FROM User
                WHERE Id = :userId
        ];
        String userMode = user.Contact.userCommunityMode__c;
        Boolean isDelegate = user.Contact.UserCommunityIsDelegate__c;

        EmailTemplateInitial emailTemplateInitial;
        switch on userMode {
            when 'PI' {
                if (isDelegate) {
                    emailTemplateInitial = new EmailTemplateInitialPIDel(user.ContactId, outputMode);
                } else {
                    emailTemplateInitial = new EmailTemplateInitialPI(user.ContactId, outputMode);
                }
            }
            when 'HCP' {
                if (isDelegate) {
                    emailTemplateInitial = new EmailTemplateInitialHCPDel(user.ContactId, outputMode);
                } else {
                    emailTemplateInitial = new EmailTemplateInitialHCP(user.ContactId, outputMode);
                }
            }
            //added by Akanksha
            when 'CC' {
                
                    emailTemplateInitial = new EmailTemplateInitialCC(user.ContactId, outputMode);
                
            }
            
            when else {
                if (isDelegate) {
                    emailTemplateInitial = new EmailTemplateInitialPTDel(user.ContactId, outputMode, communityTemplateName);
                } else {
                    emailTemplateInitial = new EmailTemplateInitialPT(user.ContactId, outputMode, communityTemplateName);
                }
            }
        }

        return emailTemplateInitial;
    }

 

}