force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunytyType__c.field-meta.xml
<CustomField>
    <fullName>userCommunytyType__c</fullName>
    <description>User types for community - HCP / PI / Participant</description>
    <inlineHelpText>Select user types for community</inlineHelpText>
    <label>User Community Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/Degrees_of_Separation__c.field-meta.xml
<CustomField>
    <fullName>Degrees_of_Separation__c</fullName>
    <description># of HCP&#39;s separating PI and HCP to establish a connection based on DX Referrals &amp; RX Shared Patient.</description>
    <inlineHelpText>0 = No Connection
1 = Friends (HCP sent at least 1 dx-referral-patient)
2 = Friends of friends
3 = Friends of friends of friends
etc.</inlineHelpText>
    <label>Degrees of Separation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/HCP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HCP_Contact__c</fullName>
    <label>HCP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HCP&#39;s Study Sites</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/HCP_Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>HCP_Referral_Source__c</fullName>
    <description>The source of referral for HCP</description>
    <inlineHelpText>The source of referral for HCP</inlineHelpText>
    <label>HCP Referral Source</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACoE Data Source</fullName>
            </value>
            <value>
                <fullName>PI Recommended</fullName>
            </value>
            <value>
                <fullName>HCP Self Referral</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Patient_Count__c.field-meta.xml
<CustomField>
    <fullName>Patient_Count__c</fullName>
    <description>HCP Patient Density</description>
    <inlineHelpText>HCP Patient Density</inlineHelpText>
    <label>Patient Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Pre_Screened_and_Did_Not_Qualify_Count__c.field-meta.xml
<CustomField>
    <fullName>Pre_Screened_and_Did_Not_Qualify_Count__c</fullName>
    <label>Pre-Screened and Did Not Qualify Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Pre_Screened_Count__c.field-meta.xml
<CustomField>
    <fullName>Pre_Screened_Count__c</fullName>
    <label>Pre-Screened Count</label>
    <precision>18</precision>
    <scale>0</scale>

    <type>Number</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>HCP Status per clinical trial by PI</description>
    <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
    <label>HCP Status</label>

    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>On Hold (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending Orientation</fullName>
            </value>
            <value>
                <fullName>Declined (Approval)</fullName>
            </value>
            <value>
                <fullName>On Hold (Approval)</fullName>
            </value>
            <value>
                <fullName>Declined (Activation)</fullName>
            </value>
            <value>
                <fullName>On Hold (Activation)</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Activated (Admin)</fullName>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
            </value>
            <value>
                <fullName>Declined (Admin)</fullName>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hospital of rainbow</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Referring HCPs</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Converted_to_HCP__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_HCP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Converted to HCP</label>
    <referenceTo>HCP_Enrollment__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Degrees_of_Separation__c.field-meta.xml
<CustomField>
    <fullName>Degrees_of_Separation__c</fullName>
    <description># of HCP&#39;s separating PI and HCP to establish a connection based on DX Referrals &amp; RX Shared Patient.</description>
    <inlineHelpText>0 = No Connection
1 = Friends (HCP sent at least 1 dx-referral-patient)
2 = Friends of friends
3 = Friends of friends of friends
etc.</inlineHelpText>
    <label>Degrees of Separation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/HCP_Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>HCP_Referral_Source__c</fullName>
    <label>HCP Referral Source</label>

    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HCP_Referral_Source_c</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Patient_Count__c.field-meta.xml
<CustomField>
    <fullName>Patient_Count__c</fullName>
    <label>Patient Count</label>
    <precision>18</precision>
    <scale>0</scale>

    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/POC_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>POC_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Point of Contact Last Name</label>
    <length>30</length>

    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Pre_Screened_and_Did_Not_Qualify_Count__c.field-meta.xml
<CustomField>
    <fullName>Pre_Screened_and_Did_Not_Qualify_Count__c</fullName>
    <label>Pre-Screened and Did Not Qualify Count</label>
    <precision>18</precision>
    <scale>0</scale>

    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Pre_Screened_Count__c.field-meta.xml
<CustomField>
    <fullName>Pre_Screened_Count__c</fullName>
    <label>Pre-Screened Count</label>
    <precision>18</precision>
    <scale>0</scale>

    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>

    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Material_Sent__c/Material_Sent__c.object-meta.xml
<CustomObject>

    <label>Material Sent</label>
    <nameField>
        <label>Material Sent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials Sent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Material_Sent__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Materials Sent</relationshipLabel>
    <relationshipName>Materials_Sent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material_Sent__c/fields/HCP_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>HCP_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HCP Enrollment</label>
    <referenceTo>HCP_Enrollment__c</referenceTo>
    <relationshipLabel>Materials Sent</relationshipLabel>
    <relationshipName>Materials_Sent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material_Sent__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Materials Sent</relationshipLabel>
    <relationshipName>Materials_Sent</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Material_Sent__c/fields/Material_Sent__c.field-meta.xml
<CustomField>
    <fullName>Material_Sent__c</fullName>
    <label>Material Sent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Material_Sent</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/National_ID__c/National_ID__c.object-meta.xml
<CustomObject>

    <label>National ID</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>National ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National ID&#39;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/National_ID__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>National ID&#39;s</relationshipLabel>
    <relationshipName>National_ID_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/National_ID__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>National ID&#39;s</relationshipLabel>
    <relationshipName>National_ID_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Point_of_Contact__c/Point_of_Contact__c.object-meta.xml
<CustomObject>

    <label>Point of Contact</label>
    <nameField>
        <displayFormat>POC-{00000}</displayFormat>
        <label>Point of Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points of Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Point_of_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Point of Contact for</relationshipLabel>
    <relationshipName>Points_of_Contact1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Point_of_Contact__c/fields/Point_of_Contact_for__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact_for__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact for</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Points of Contact</relationshipLabel>
    <relationshipName>Points_of_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Point_of_Contact__c/fields/Point_of_Contact_for_Account__c.field-meta.xml
<CustomField>
    <fullName>Point_of_Contact_for_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point of Contact for Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points of Contact</relationshipLabel>
    <relationshipName>Points_of_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/HCP_Referral_Source_c.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACOE Data</fullName>
    </customValue>
    <customValue>
        <fullName>NANOS</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Physician Society</fullName>
    </customValue>
    <customValue>
        <fullName>PI Recommended</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Referred</fullName>
    </customValue>
    <masterLabel>HCP Referral Source</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/unpackaged/main/default/globalValueSets/Material_Sent.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Card</fullName>
    </customValue>
    <customValue>
        <fullName>Criteria Card</fullName>
    </customValue>
    <customValue>
        <fullName>Dr to Dr Letter - Email</fullName>
    </customValue>
    <customValue>
        <fullName>Dr to Dr Letter - Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Dr to Dr Letter - Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-up Letter</fullName>
    </customValue>
    <customValue>
        <fullName>Opt-in Letter</fullName>
    </customValue>
    <customValue>
        <fullName>Patient Informational Brochure</fullName>
    </customValue>
    <customValue>
        <fullName>Physician Referral Brochure</fullName>
    </customValue>
    <customValue>
        <fullName>Poster</fullName>
    </customValue>
    <customValue>
        <fullName>PowerPoint Presentation</fullName>
    </customValue>
    <customValue>
        <fullName>Thank You Note</fullName>
    </customValue>
    <masterLabel>Material Sent</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/LeadConversionHelper.cls
/**
 * Created by RAMukhamadeev on 2019-03-04.
 */

public without sharing class LeadConversionHelper {
    public static String LEAD_STATUS_QUALIFIED_AND_SEND_INVITATION = 'Qualified and Send Invitation';

    public static void afterLeadsUpdate(
        List<Lead> newLeads,
        Map<Id, Lead> oldLeadsMap,
        Map<Id, Lead> newLeadsMap
    ) {
        System.debug('newLeads: ' + newLeads);
        // extract only converted leads
        List<Lead> convertedLeads = getConvertedLeads(newLeads, oldLeadsMap);

        // create HCP_Enrollment__c records on lead conversion
        Map<Id, HCP_Enrollment__c> leadConvertedToEnrollmentMap = insertEnrollments(convertedLeads);

        // create contacts
        Map<Id, Map<String, Contact>> accountPOCMap = getAccountPOCMap(convertedLeads);
        Map<Id, Contact> leadPOCMap = createContacts(convertedLeads, accountPOCMap);

        // insert new Point_of_Contact__c records
        insertPointOfContacts(convertedLeads, leadPOCMap);

        // update Lead with Converted_to_HCP__c lookup
        updateLeadsWithHCPEnrollments(leadConvertedToEnrollmentMap);

        // update National_ID__c records with Contact__c lookup
        updateNationalIds(convertedLeads, newLeadsMap);

        // update Material_Sent__c records with HCP_Enrollment__c lookup
        updateMaterialsSent(convertedLeads, newLeadsMap, leadConvertedToEnrollmentMap);

        // update contacts Without Study Site (setting user community type = HCP)
        updateContactsWithoutStudySite(convertedLeads);

        // create portal users
        createPortalUsersWithoutStudy(convertedLeads);
    }

    public static void createPortalUsersWithoutStudy(List<Lead> convertedLeads) {
        Set<Id> contactsWithoutStudySite = new Set<Id>();
        for (Lead lead : convertedLeads) {
            if (
                lead.Study_Site__c == null &&
                lead.Status == LEAD_STATUS_QUALIFIED_AND_SEND_INVITATION
            ) {
                contactsWithoutStudySite.add(lead.ConvertedContactId);
            }
        }
        if (!contactsWithoutStudySite.isEmpty()) {
            Map<Id, User> communityUsersMap = new Map<Id, User>();
            for (
                User usr : CommunityService.getCommunityUsersByContactIds(contactsWithoutStudySite)
            ) {
                communityUsersMap.put(usr.ContactId, usr);
            }

            Set<Id> contactIdsForCreateUser = new Set<Id>();
            for (Lead lead : convertedLeads) {
                if (!communityUsersMap.containsKey(lead.ConvertedContactId)) {
                    contactIdsForCreateUser.add(lead.ConvertedContactId);
                }
            }
            if (!contactIdsForCreateUser.isEmpty()) {
                ((CommunityService) ClassFactory.newInstance(CommunityService.class))
                    .createPortalUsers(contactIdsForCreateUser);
            }
        }
    }

    public static void updateContactsWithoutStudySite(List<Lead> convertedLeads) {
        Set<Id> contactsWithoutStudySite = new Set<Id>();
        for (Lead lead : convertedLeads) {
            if (lead.Study_Site__c == null) {
                contactsWithoutStudySite.add(lead.ConvertedContactId);
            }
        }
        if (!contactsWithoutStudySite.isEmpty()) {
            List<Contact> toUpdateContacts = new List<Contact>();
            for (Id contactId : contactsWithoutStudySite) {
                toUpdateContacts.add(
                    new Contact(
                        Id = contactId,
                        userCommunityMode__c = CommunityService.USER_MODE_HCP,
                        userCommunytyType__c = CommunityService.USER_MODE_HCP
                    )
                );
            }
            update toUpdateContacts;
        }
    }

    private static List<Lead> getConvertedLeads(List<Lead> newLeads, Map<Id, Lead> oldLeadsMap) {
        List<Lead> convertedLeads = new List<Lead>();
        for (Lead lead : newLeads) {
            if (lead.IsConverted && !(oldLeadsMap.get(lead.Id).IsConverted)) {
                convertedLeads.add(lead);
            }
        }
        return convertedLeads;
    }

    public static Map<Id, HCP_Enrollment__c> insertEnrollments(List<Lead> convertedLeads) {
        Map<Id, HCP_Enrollment__c> leadConvertedToEnrollmentMap = new Map<Id, HCP_Enrollment__c>();
        List<HCP_Enrollment__c> hcpEnrollmentsToCreate = new List<HCP_Enrollment__c>();
        for (Lead lead : convertedLeads) {
            if (lead.Study_Site__c != null) {
                String hcpeStatus;
                if (lead.Status == LEAD_STATUS_QUALIFIED_AND_SEND_INVITATION) {
                    hcpeStatus = HCPEnrollmentService.HCP_S_INVITATION_SENT;
                }

                HCP_Enrollment__c hcpe = new HCP_Enrollment__c(
                    Study_Site__c = lead.Study_Site__c,
                    HCP_Contact__c = lead.ConvertedContactId,
                    HCP_Referral_Source__c = lead.HCP_Referral_Source__c,
                    Patient_Count__c = lead.Patient_Count__c,
                    Pre_Screened_Count__c = lead.Pre_Screened_Count__c,
                    Pre_Screened_and_Did_Not_Qualify_Count__c = lead.Pre_Screened_and_Did_Not_Qualify_Count__c,
                    Status__c = hcpeStatus,
                    Degrees_of_Separation__c = lead.Degrees_Of_Separation__c
                );
                leadConvertedToEnrollmentMap.put(lead.Id, hcpe);
                hcpEnrollmentsToCreate.add(hcpe);
            }
        }
        if (!hcpEnrollmentsToCreate.isEmpty()) {
            insert hcpEnrollmentsToCreate;
        }
        return leadConvertedToEnrollmentMap;
    }

    private static void updateMaterialsSent(
        List<Lead> convertedLeads,
        Map<Id, Lead> newLeadsMap,
        Map<Id, HCP_Enrollment__c> leadConvertedToEnrollmentMap
    ) {
        List<Material_Sent__c> materialsToUpdate = new List<Material_Sent__c>();
        for (Material_Sent__c material : [
            SELECT Id, Lead__c, Contact__c
            FROM Material_Sent__c
            WHERE Lead__c IN :convertedLeads
        ]) {
            material.Contact__c = newLeadsMap.get(material.Lead__c).ConvertedContactId;
            HCP_Enrollment__c currEnrollment = leadConvertedToEnrollmentMap.get(material.Lead__c);
            if (currEnrollment != null) {
                material.HCP_Enrollment__c = currEnrollment.Id;
            }
            materialsToUpdate.add(material);
        }
        if (!materialsToUpdate.isEmpty()) {
            update materialsToUpdate;
        }
    }

    private static void updateNationalIds(List<Lead> convertedLeads, Map<Id, Lead> newLeadsMap) {
        List<National_ID__c> nidsToUpdate = new List<National_ID__c>();
        for (National_ID__c lnid : [
            SELECT Id, Lead__c, Contact__c
            FROM National_ID__c
            WHERE Lead__c IN :convertedLeads
        ]) {
            lnid.Contact__c = newLeadsMap.get(lnid.Lead__c).ConvertedContactId;
            nidsToUpdate.add(lnid);
        }
        if (!nidsToUpdate.isEmpty()) {
            update nidsToUpdate;
        }
    }

    public static void updateLeadsWithHCPEnrollments(
        Map<Id, HCP_Enrollment__c> leadConvertedToEnrollmentMap
    ) {
        List<Lead> leadsToUpdate = new List<Lead>();
        for (Lead lead : [
            SELECT Id, Converted_to_HCP__c
            FROM Lead
            WHERE Id IN :leadConvertedToEnrollmentMap.keySet()
        ]) {
            HCP_Enrollment__c currEnrollment = leadConvertedToEnrollmentMap.get(lead.Id);
            if (currEnrollment != null) {
                lead.Converted_to_HCP__c = currEnrollment.Id;
            }
            leadsToUpdate.add(lead);
        }
        if (!leadsToUpdate.isEmpty()) {
            update leadsToUpdate;
        }
    }

    public static void insertPointOfContacts(
        List<Lead> convertedLeads,
        Map<Id, Contact> leadPOCMap
    ) {
        List<Point_of_Contact__c> pocsToCreate = new List<Point_of_Contact__c>();
        for (Lead lead : convertedLeads) {
            if (!String.isBlank(lead.POC_Last_Name__c)) {
                Point_of_Contact__c poc = new Point_of_Contact__c(
                    Point_of_Contact_for_Account__c = lead.ConvertedAccountId,
                    Point_of_Contact_for__c = lead.ConvertedContactId,
                    Point_of_Contact_Type__c = lead.POC_Type__c,
                    Point_of_Contact_Type_Description__c = lead.POC_Type_Description__c,
                    Contact__c = leadPOCMap.get(lead.Id).Id
                );
                pocsToCreate.add(poc);
            }
        }
        if (!pocsToCreate.isEmpty()) {
            insert pocsToCreate;
        }
    }

    public static Map<Id, Contact> createContacts(
        List<Lead> convertedLeads,
        Map<Id, Map<String, Contact>> accountPOCMap
    ) {
        List<Contact> contactsToCreate = new List<Contact>();
        Map<Id, Contact> leadPOCMap = new Map<Id, Contact>();
        for (Lead lead : convertedLeads) {
            if (!String.isBlank(lead.POC_Last_Name__c)) {
                Contact poc;
                Map<String, Contact> contactsByNameMap = accountPOCMap.get(lead.ConvertedAccountId);
                if (contactsByNameMap != null)
                    poc = contactsByNameMap.get(
                        lead.POC_First_Name__c +
                        ' ' +
                        lead.POC_Last_Name__c
                    );
                if (poc == null) {
                    poc = new Contact(
                        Email = lead.POC_Email__c,
                        FirstName = lead.POC_First_Name__c,
                        LastName = lead.POC_Last_Name__c,
                        Phone = lead.POC_Phone__c,
                        AccountId = lead.ConvertedAccountId,
                        Contact_Method_Preference__c = lead.Contact_Method_Preference__c,
                        Language__c = lead.Language__c
                    );
                    contactsToCreate.add(poc);
                }
                leadPOCMap.put(lead.Id, poc);
            }
        }
        if (!contactsToCreate.isEmpty()) {
            insert contactsToCreate;
        }
        return leadPOCMap;
    }

    public static Map<Id, Map<String, Contact>> getAccountPOCMap(List<Lead> convertedLeads) {
        Set<Id> accountsForLeads = new Set<Id>();
        Set<String> pocFirstNames = new Set<String>();
        Set<String> pocLastNames = new Set<String>();
        for (Lead lead : convertedLeads) {
            if (!String.isBlank(lead.POC_Last_Name__c)) {
                accountsForLeads.add(lead.ConvertedAccountId);
                pocFirstNames.add(lead.POC_First_Name__c);
                pocLastNames.add(lead.POC_Last_Name__c);
            }
        }

        Map<Id, Map<String, Contact>> accountPOCMap = new Map<Id, Map<String, Contact>>();
        List<Contact> contacts = [
            SELECT Id, AccountId, Name
            FROM Contact
            WHERE
                AccountId IN :accountsForLeads
                AND FirstName IN :pocFirstNames
                AND LastName IN :pocLastNames
        ];
        for (Contact c : contacts) {
            Map<String, Contact> contactsByNameMap = accountPOCMap.get(c.AccountId);
            if (contactsByNameMap == null)
                contactsByNameMap = new Map<String, Contact>();
            contactsByNameMap.put(c.Name, c);
            accountPOCMap.put(c.AccountId, contactsByNameMap);
        }
        return accountPOCMap;
    }
}