force-app/main/default/objects/Contact/fields/userCommunytyType__c.field-meta.xml
<CustomField>
    <fullName>userCommunytyType__c</fullName>
    <description>User types for community - HCP / PI / Participant</description>
    <inlineHelpText>Select user types for community</inlineHelpText>
    <label>User Community Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referring_HCP_Staff__c/Referring_HCP_Staff__c.object-meta.xml
<CustomObject>

    <label>Referring HCP Staff</label>
    <nameField>
        <displayFormat>HCPS-{000000}</displayFormat>
        <label>Referring HCP Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referring HCP Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Referring_HCP_Staff__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referring HCP Staffs</relationshipLabel>
    <relationshipName>Referring_HCP_Staffs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Referring_HCP_Staff__c/fields/Delegate_Level__c.field-meta.xml
<CustomField>
    <fullName>Delegate_Level__c</fullName>
    <label>Delegate Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateDelegatesBatch.cls
global class UpdateDelegatesBatch implements Database.Batchable<sObject>, Database.Stateful{

   	global final String Query;
    global List<Referring_HCP_Staff__c> listOfReferringStaff;
	global List<Id> rpContacts;
   
    global UpdateDelegatesBatch(){
    	Query = 'SELECT id, userCommunytyType__c, (SELECT id, Delegate_Level__c FROM Referring_HCP_Staffs__r), LastName FROM Contact'; 
   	}
    
   	global Database.QueryLocator start(Database.BatchableContext BC){
       	listOfReferringStaff = new List<Referring_HCP_Staff__c>();
        rpContacts = new List<Id>();
  		return Database.getQueryLocator(query);
   	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope){
       	listOfReferringStaff = new List<Referring_HCP_Staff__c>();
     	for(sObject s : scope){
            Contact contactRecords = (Contact)s;
            Boolean isDelegate = iterateStaff(contactRecords.Referring_HCP_Staffs__r);
            if(isDelegate && contactRecords.userCommunytyType__c != null && contactRecords.userCommunytyType__c.contains('HCP')){
                rpContacts.add(contactRecords.id);
            }
            
     	}
        update listOfReferringStaff;
     	
    }
    
    global boolean iterateStaff(List<Referring_HCP_Staff__c> staffs){
        String highLevel = '';
        if(staffs != null && staffs.size() != 0){
        	for(Referring_HCP_Staff__c item : staffs){
                highLevel = (highLevel == '' || highLevel == 'Level 2') ? item.Delegate_Level__c : highLevel;
                if(highLevel == 'Level 1'){
                    break;
                }
            }
            for(Referring_HCP_Staff__c item : staffs){
                item.Delegate_Level__c = highLevel;
            }
            listOfReferringStaff.addAll(staffs);
          	return true;
        }
        return false; 
        
    }
    
    global void  sendingEmail() {
		Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
		String[] sendingTo = new String[]{'R&DSReferralHubSupport@quintiles.com'};
		semail.setToAddresses(sendingTo);
		String[] sendingTocAdd = new String[]{'Olena.Usoltseva@highpointsolutions.com', 'mikhail.pochkin@highpointsolutions.com', 'diana.antonyan@highpointsolutions.com'};
		semail.setCcAddresses(sendingTocAdd);
		semail.setSubject('RP Delegates');
		semail.setPlainTextBody('List of Ids RP Delegates' + JSON.serialize(rpContacts));
		Messaging.sendEmail(new Messaging.SingleEmailMessage[] {semail});
	}

   	global void finish(Database.BatchableContext BC){
        sendingEmail();
    }
}