force-app/main/default/objects/Contact/fields/UserCommunityIsDelegate__c.field-meta.xml
<CustomField>
    <fullName>UserCommunityIsDelegate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Community Is Delegate</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/Site_Staff__c.object-meta.xml
<CustomObject>
    <description>Used to connect Contacts with Study Sites to represent a Principal Investigator&#39;s team</description>

    <label>Site Staff</label>
    <nameField>
        <displayFormat>Staff #{0000}</displayFormat>
        <label>Site Staff</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Staff__c/fields/is_Invited__c.field-meta.xml
<CustomField>
    <fullName>is_Invited__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check whether site staff is invited or not</description>
    <label>is Invited</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact__c</fullName>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staff&#39;s Study Sites</relationshipLabel>
    <relationshipName>PI_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <formula>if(is_Site_and_Staff_Same_Country__c == false,  HYPERLINK(&quot;/&quot;&amp; Id , Name ) , &apos;-&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Staff</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Site Staff</relationshipLabel>
    <relationshipName>Site_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to study site delegate</description>
    <label>Site Staff</label>
    <referenceTo>Site_Staff__c</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_UpdateUserCommunityIsDelegate.cls
global without sharing class Batch_UpdateUserCommunityIsDelegate implements Database.Batchable<SObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            [
                Select id,Study_Site__c,Site_Contact__r.UserCommunityIsDelegate__c,Site_Contact__c,is_Invited__c 
                from Site_Staff__c where is_Invited__c=true AND Site_Contact__r.UserCommunityIsDelegate__c = False
            ]
        );
    }
    global void execute(Database.BatchableContext bc, List<Site_Staff__c> scope) {
        List<Site_Staff__c>sitestaffLST  = new List<Site_Staff__c>();
        List<Id>contactIDSLST  = new List<Id>();
        Map<Id,Contact>updtContactLST  = new Map<Id,Contact>();
        Contact updtStaffContact;
        system.debug('scopeline16>>'+scope);
        for (Site_Staff__c staff : scope) {
           contactIDSLST.add(staff.Site_Contact__c);
       }
        system.debug('contactIDSLST19>>'+contactIDSLST);
        for(Id cntstaff : contactIDSLST){
            updtStaffContact = new Contact();
            updtStaffContact.Id = cntstaff;
            updtStaffContact.UserCommunityIsDelegate__c = true;
            updtContactLST.put(updtStaffContact.Id,updtStaffContact);
        }
        system.debug('updtContactLST>>'+updtContactLST.Values());
        //TriggerHandlerExecutor.bypassHandler(PETriggerHandler.class);
        TriggerHandlerExecutor.bypassHandler(
            ContactTriggerHandler.UpdateParticipantAndUserEmailsOnEmailChangeHandler.class
        );
        TriggerHandlerExecutor.bypassHandler(
            ContactTriggerHandler.updateParticipantAndUserEmailsOnEmailChange.class
        );
        TriggerHandlerExecutor.bypassHandler(
            ContactTriggerHandler.CreateUserForDelegateContactHandler.class
        );
        TriggerHandlerExecutor.bypassHandler(
            ContactTriggerHandler.SetShowTourDefaultHandler.class
        );
        TriggerHandlerExecutor.bypassHandler(
            ContactTriggerHandler.PopulateOverrideFields.class
        );
        TriggerHandlerExecutor.bypassHandler(
            ContactTriggerHandler.CreateUserForCCContactHandler.class
        );
        TriggerHandlerExecutor.bypassHandler(
            ContactTriggerHandler.UpdateParticipantDetailsHandler.class
        );
       
        Database.update(updtContactLST.Values(), false);
    }
    global void finish(Database.BatchableContext bc) {
    }
}