force-app/main/default/objects/Contact/fields/Welcome_Message_Sent__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Message_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Welcome Message Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Notification__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Welcome_Message_Sent__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Message_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Welcome Message Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Send_Result__c/Send_Result__c.object-meta.xml
<CustomObject>
    <label>Send Result</label>
    <nameField>
        <label>Send Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Send Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Send_Result__c/fields/Msg_Id__c.field-meta.xml
<CustomField>
    <fullName>Msg_Id__c</fullName>
    <label>Message Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Send_Result__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Send Results</relationshipLabel>
    <relationshipName>Send_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/messaging/objects/Send_Result__c/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <description>Notification Type as set in parent Notification. Required for sending Push Notifications.</description>
    <label>Notification Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendResultTriggerHandler.cls
/**
* Created by Anitha Chavva on 27.04.2022
*/

public without sharing class SendResultTriggerHandler {
    
    // Handlers: -------------------------------------------------------------------------------------------------------
    
    public class updatewelcomeMsgflagsHandler extends TriggerHandler {
        public override void afterInsert(List<SObject> newList) {
            updatewelcomeMsgflags(newList, null); 
        }
        public override void afterUpdate(List<SObject> newList, Map<Id, SObject> oldMap) {
			updatewelcomeMsgflags(newList, (Map<Id, Send_Result__c>) oldMap); 
        }
    }
    
    // Logic: ----------------------------------------------------------------------------------------------------------
    
    @TestVisible
    private static void updatewelcomeMsgflags(
        List<Send_Result__c> newList,
        Map<Id, Send_Result__c> oldMap
    ) {
        Map<Id,Send_Result__c> sendresultmap = new Map<Id,Send_Result__c>();
        Set<Id> perids = new Set<Id>();
        Set<Id> conids = new Set<Id>();
        List<Participant_Enrollment__c> perrecrdslst = new List<Participant_Enrollment__c>();
        List<Contact> conrecrdslst = new List<Contact>(); 
        Map<Id,Notification__c> objidslst = new Map<Id,Notification__c>();
        for (Send_Result__c ss : newList){
            if((oldMap == null && !String.isBlank(ss.Msg_Id__c)) || (oldMap != null && ss.Msg_Id__c != oldMap.get(ss.Id).Msg_Id__c)){
                sendresultmap.put(ss.Notification__c, ss);
            }
        }
        if(sendresultmap.size()>0){
            Map<Id,Notification__c> notificationmap = new Map<Id,Notification__c>([Select Id,WhatId__c,Notification_Type__c, Recipient__c From Notification__c where ID IN: sendresultmap.keyset()]);
            if(notificationmap.size()>0){
                for (Id ss : notificationmap.keyset()){
                    if(NotificationService.welcomemsgNoticationtypes.Contains(notificationmap.get(ss).Notification_Type__c)){
                        Id whatId = Id.valueOf(notificationmap.get(ss).WhatId__c);
                        Id recipientId = Id.valueOf(notificationmap.get(ss).Recipient__c);
                        if(String.valueOf(whatId.getSobjectType()) == 'Participant_Enrollment__c'){
                            perids.add(whatId);    
                        }
                        else if(String.valueOf(whatId.getSobjectType()) == 'Participant__c'){
                            conids.add(recipientId);    
                            
                        }  
                    }
                }
            }
            if(perids.size()>0){
                List<Participant_Enrollment__c> perlist = [Select Id,Welcome_Message_Sent__c From Participant_Enrollment__c where ID IN : perids];
                for(Participant_Enrollment__c ps : perlist){
                    if(!ps.Welcome_Message_Sent__c){
                        ps.Welcome_Message_Sent__c = true;
                        perrecrdslst.add(ps);
                    }
                }
            }
            if(conids.size()>0){
                List<Contact> conlist = [Select Id,Welcome_Message_Sent__c From Contact where ID IN : conids];
                for(Contact con : conlist){
                    if(!con.Welcome_Message_Sent__c){
                        con.Welcome_Message_Sent__c = true;
                        conrecrdslst.add(con);
                    }
                }
            }
            if(perrecrdslst.size()>0) update perrecrdslst;
            if(conrecrdslst.size()>0) update conrecrdslst;
        }
    }
}