force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Icon_Details__c/Icon_Details__c.object-meta.xml
<CustomObject>
    <description>icon description</description>
    <label>Icon Details</label>
    <nameField>
        <label>Icon Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Icons Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Icon_Details__c/fields/Custom_Icon__c.field-meta.xml
<CustomField>
    <fullName>Custom_Icon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Icon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Icon_Details__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Icon_Details__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Icons Details</relationshipLabel>
    <relationshipName>Icons_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Icons__c.field-meta.xml
<CustomField>
    <fullName>Icons__c</fullName>
    <label>Icons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Questions</fullName>
                <default>true</default>
                <label>Questions about your health and medications</label>
            </value>
            <value>
                <fullName>Electrocardiogram</fullName>
                <label>Electrocardiogram (ECG)</label>
            </value>
            <value>
                <fullName>Vital_signs_weight_and_height</fullName>
                <label>Vital signs, weight and height</label>
            </value>
            <value>
                <fullName>Blood_tests</fullName>
                <label>Blood tests</label>
            </value>
            <value>
                <fullName>Urine_test</fullName>
                <label>Urine test</label>
            </value>
            <value>
                <fullName>Pregnancy_test</fullName>
                <label>Pregnancy test</label>
            </value>
            <value>
                <fullName>Receive_study_medication</fullName>
                <label>Receive study medication</label>
            </value>
            <value>
                <fullName>Return_study_medication</fullName>
                <label>Return study medication</label>
            </value>
            <value>
                <fullName>No_food_or_drink</fullName>
                <label>No food or drink except water for 10 hours prior to visit</label>
            </value>
            <value>
                <fullName>Physical_examination</fullName>
                <label>Physical examination</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Patient_Portal_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Portal_Name__c</fullName>
    <label>Patient Portal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Number__c.field-meta.xml
<CustomField>
    <fullName>Visit_Number__c</fullName>
    <label>SDH Visit Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Visit_Schedule__c</fullName>
    <label>Patient Portal Schedule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Plan__c/Visit_Plan__c.object-meta.xml
<CustomObject>
    <label>Visit Plan</label>
    <nameField>
        <label>Visit Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Visit Plans</relationshipLabel>
    <relationshipName>Visit_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CTPSelector.cls
/**
 * Created by dmytro.fedchyshyn on 24.07.2019.
 */

public without sharing class CTPSelector {
    public List<Clinical_Trial_Profile__c> getCtpById(Id ctpId) {
        return [
                SELECT Id,
                        Visit_Plan__c
                FROM Clinical_Trial_Profile__c
                WHERE Id = :ctpId
        ];
    }

    public List<Visit__c> getVisitsByCtpId(Id visitPlanId) {
        return [
                SELECT Id,Name
                        ,Visit_Plan__c
                        ,Patient_Portal_Name__c
                        ,Visit_Schedule__c
                        ,Visit_Number__c
                        ,Icons__c
                FROM Visit__c
                WHERE Visit_Plan__c = :visitPlanId
                ORDER BY Visit_Number__c
        ];
    }

    public List<Icon_Details__c> getIconDetailsByVisitPlanInCTP(Id planId) {
        return [
                SELECT Id
                        ,Name
                        ,Label__c
                        ,Description__c
                        ,Custom_Icon__c
                FROM Icon_Details__c
                WHERE Visit_Plan__c =: planId
        ];
    }

}