force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Plan__c/Visit_Plan__c.object-meta.xml
<CustomObject>
    <label>Visit Plan</label>
    <nameField>
        <label>Visit Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Visit Plans</relationshipLabel>
    <relationshipName>Visit_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_VisitConfigurationRemote.cls
@IsTest
public with sharing class Test_VisitConfigurationRemote {

    @IsTest
    static void getRelatedPlannedVisitsWithVisit_test() {
        List<Clinical_Trial_Profile__c> ctp = new List<Clinical_Trial_Profile__c>{
                (Clinical_Trial_Profile__c) TestDataFactory.getSObject(Clinical_Trial_Profile__c.getSObjectType(),
                        new Map<String, Object>{
                                'Visit_Plan__c' => TestDataFactory.getFakeId(Visit_Plan__c.getSObjectType())})};

        List<Visit__c> visits2 = new List<Visit__c>{
                new Visit__c(Name = 'Test1'),
                new Visit__c(Name = 'Test2')
        };

        ClassFactory.clearStubTypesByClassNamesMap();
        ClassFactory.putStubTypeByClassName(CTPSelector.class, StubFactory.newInstance(CTPSelector.class)
                .when('getCtpById')
                .then(ctp)
                .when('getVisitsByCtpId')
                .then(visits2)
                .getInstance()
        );

        Test.startTest();
        List<Visit__c> visits = VisitConfigurationRemote.getRelatedPlannedVisits(ctp[0].Id);
        Test.stopTest();

        System.assertEquals(2, visits.size());
    }

    @IsTest
    static void getRelatedPlannedVisitsWithoutVisit_test() {
        List<Clinical_Trial_Profile__c> ctp = new List<Clinical_Trial_Profile__c>{
                (Clinical_Trial_Profile__c) TestDataFactory.getSObject(Clinical_Trial_Profile__c.getSObjectType())
        };

        ClassFactory.clearStubTypesByClassNamesMap();
        ClassFactory.putStubTypeByClassName(CTPSelector.class, StubFactory.newInstance(CTPSelector.class)
                .when('getCtpById')
                .then(ctp)
                .getInstance()
        );

        Test.startTest();
        List<Visit__c> visits = VisitConfigurationRemote.getRelatedPlannedVisits(ctp[0].Id);
        Test.stopTest();

        System.assertEquals(0, visits.size());
    }

    @IsTest
    static void getRelatedPlannedVisitsWithException_test() {
        Boolean isExceptionThrown = false;
        Test.startTest();
        try {
            VisitConfigurationRemote.getRelatedPlannedVisits(null);
        } catch (Exception e) {
            isExceptionThrown = true;
            System.assert(e.getTypeName() == 'System.AuraHandledException');
        }
        Test.stopTest();
        System.assert(true, isExceptionThrown);
    }

    @IsTest
    static void updateCtp_test() {
        TriggerHandlerExecutor.bypassHandler(ClinicalTrialProfileTriggerHandler.class);

        List<Clinical_Trial_Profile__c> ctp = new List<Clinical_Trial_Profile__c>{
                (Clinical_Trial_Profile__c) TestDataFactory.getSObject(Clinical_Trial_Profile__c.getSObjectType())
        };

        ClassFactory.clearStubTypesByClassNamesMap();
        ClassFactory.putStubTypeByClassName(DatabaseProxy.class, StubFactory.newInstance(DatabaseProxy.class)
                .when('updateRecord')
                .then(null)
                .getInstance()
        );

        Test.startTest();
        VisitConfigurationRemote.updateCtp(ctp[0].Visit_Plan__c, ctp[0].Id);
        Test.stopTest();
    }

    @IsTest
    static void updateCtpWithException_test() {
        TriggerHandlerExecutor.bypassHandler(ClinicalTrialProfileTriggerHandler.class);

        Boolean isExceptionThrown = false;
        Test.startTest();
        try {
            VisitConfigurationRemote.updateCtp(null, null);
        } catch (Exception e) {
            isExceptionThrown = true;
            System.assert(e.getTypeName() == 'System.AuraHandledException');
        }
        Test.stopTest();
        System.assert(true, isExceptionThrown);
    }

    @IsTest
    static void deleteVisit_test() {
        Visit_Plan__c visitPlan = new Visit_Plan__c(Name = 'Test');
        insert visitPlan;

        List<Visit__c> visits = new List<Visit__c>{
                new Visit__c(Name = 'Test1', Visit_Plan__c = visitPlan.Id),
                new Visit__c(Name = 'Test2', Visit_Plan__c = visitPlan.Id)
        };
        insert visits;

        Test.startTest();
        VisitConfigurationRemote.deleteVisit(visits[0].Id);
        visits = [SELECT Id FROM Visit__c];
        Test.stopTest();

        System.assertEquals(1, visits.size());
    }

    @IsTest
    static void deleteVisitWithException_test() {
        Boolean isExceptionThrown = false;
        Test.startTest();
        try {
            VisitConfigurationRemote.deleteVisit(null);
        } catch (Exception e) {
            isExceptionThrown = true;
            System.assert(e.getTypeName() == 'System.AuraHandledException');
        }
        Test.stopTest();
        System.assert(true, isExceptionThrown);
    }
}