force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/CommunityTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommunityTemplate__c</fullName>
    <label>Community Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>IQVIA Patient Portal</label>
            </value>
            <value>
                <fullName>GSK</fullName>
                <label>GSK Pan Oncology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_First_Logon__c.field-meta.xml
<CustomField>
    <fullName>Is_First_Logon__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is First Logon</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_FollowUp_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_FollowUp_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is FollowUp Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Visited_Communities__c.field-meta.xml
<CustomField>
    <fullName>Visited_Communities__c</fullName>
    <label>Visited Communities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IQVIA Patient Portal</fullName>
            </value>
            <value>
                <fullName>GSK Pan Oncology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FollowUp_Reminder__mdt/FollowUp_Reminder__mdt.object-meta.xml
<CustomObject>
    <label>FollowUp Reminder</label>
    <pluralLabel>FollowUp Reminders</pluralLabel>
</CustomObject>

force-app/main/default/objects/FollowUp_Reminder__mdt/fields/Days_after_Permission_gets__c.field-meta.xml
<CustomField>
    <fullName>Days_after_Permission_gets__c</fullName>
    <label>Days after Permission gets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Notification__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/scheduled-batch-implementation/classes/Batch_FollowUpReminder.cls
 /**
 * Created by Igor Malyuta on 10.06.2020.
 */
public with sharing class Batch_FollowUpReminder extends Batch_ScheduledAbstract {
    public Database.QueryLocator start(Database.BatchableContext param1) {
        List<FollowUp_Reminder__mdt> followUpReminder = [
            SELECT Days_after_Permission_gets__c
            FROM FollowUp_Reminder__mdt
            WHERE DeveloperName = 'Org_Default' AND Days_after_Permission_gets__c != NULL
        ];
        if (followUpReminder.isEmpty())
            return null;
        Integer followUpDays;
        if(Test.isRunningTest()){
            followUpDays = 0;
        }
        else{
                  followUpDays = (Integer) followUpReminder.get(0).Days_after_Permission_gets__c;
 
        }
        return Database.getQueryLocator(
            [
                SELECT AssigneeId FROM PermissionSetAssignment WHERE Assignee.Contact.Is_First_Logon__c = TRUE AND Assignee.Contact.Is_FollowUp_Sent__c = FALSE AND Assignee.Contact.Visited_Communities__c = NULL AND Assignee.Contact.userCommunityMode__c = 'Participant' AND PermissionSet.Name IN :CommunityTemplateService.getAllPermissionSets() AND SystemModstamp <= :Datetime.now().addDays(-followUpDays)
            ]
        );
    }

    public void execute(
        Database.BatchableContext param1,
        List<PermissionSetAssignment> oldAssignments
    ) {
        Map<Id, Map<Datetime, String>> permSetNameWithDTByContact = getPermSetByContactMap(
            oldAssignments
        );
        Map<Id, List<Participant_Enrollment__c>> enrollmentsByContact = getEnrollmentsByContact(
            permSetNameWithDTByContact
        );

        Map<Id, Id> peByContact = new Map<Id, Id>();
        for (Id contactId : enrollmentsByContact.keySet()) {
            Map<Datetime, String> permByDT = permSetNameWithDTByContact.get(contactId);
            List<Datetime> datesSet = new List<Datetime>(permByDT.keySet());
            datesSet.sort();

            Id whatId;
            Integer datesIndex = datesSet.size() - 1;
            do {
                String permissionName = permByDT.get(datesSet.get(datesIndex));
                for (Participant_Enrollment__c pe : enrollmentsByContact.get(contactId)) {
                    String template = pe.Clinical_Trial_Profile__r.CommunityTemplate__c;
                    if (
                        CommunityTemplateService.getTemplate(template).templateName ==
                        CommunityTemplateService.getTemplateByPermissionSetName(permissionName)
                            .templateName
                    ) {
                        whatId = pe.Id;
                        break;
                    }
                }
                datesIndex--;
            } while (whatId == null && datesIndex >= 0);

            if (whatId != null)
                peByContact.put(contactId, whatId);
        }
        createNotificationsAndUpdateContacts(peByContact);
    }

    private Map<Id, Map<Datetime, String>> getPermSetByContactMap(
        List<PermissionSetAssignment> oldAssignments
    ) {
        Set<Id> userIds = new Set<Id>();
        for (PermissionSetAssignment assignment : oldAssignments)
            userIds.add(assignment.AssigneeId);

        List<PermissionSetAssignment> assignments = [
            SELECT Assignee.ContactId, PermissionSet.Name, SystemModstamp
            FROM PermissionSetAssignment
            WHERE
                AssigneeId IN :userIds
                AND PermissionSet.Name IN :CommunityTemplateService.getAllPermissionSets()
        ];
        Map<Id, Map<Datetime, String>> permSetNameWithDTByContact = new Map<Id, Map<Datetime, String>>();
        for (PermissionSetAssignment assignment : assignments) {
            Id contactId = assignment.Assignee.ContactId;
            if (!permSetNameWithDTByContact.containsKey(contactId)) {
                permSetNameWithDTByContact.put(contactId, new Map<Datetime, String>());
            }
            Map<Datetime, String> dateTimeByPermSet = permSetNameWithDTByContact.get(contactId);
            dateTimeByPermSet.put(assignment.SystemModstamp, assignment.PermissionSet.Name);
            permSetNameWithDTByContact.put(contactId, dateTimeByPermSet);
        }
        return permSetNameWithDTByContact;
    }

    private Map<Id, List<Participant_Enrollment__c>> getEnrollmentsByContact(
        Map<Id, Map<Datetime, String>> permSetNameWithDTByContact
    ) {
        List<Participant_Enrollment__c> enrollments = [
            SELECT Id, Clinical_Trial_Profile__r.CommunityTemplate__c, Participant_Contact__c
            FROM Participant_Enrollment__c
            WHERE Participant_Contact__c IN :permSetNameWithDTByContact.keySet()
        ];
        Map<Id, List<Participant_Enrollment__c>> enrollmentsByContact = new Map<Id, List<Participant_Enrollment__c>>();
        for (Participant_Enrollment__c enrollment : enrollments) {
            if (!enrollmentsByContact.containsKey(enrollment.Participant_Contact__c)) {
                enrollmentsByContact.put(
                    enrollment.Participant_Contact__c,
                    new List<Participant_Enrollment__c>()
                );
            }
            enrollmentsByContact.get(enrollment.Participant_Contact__c).add(enrollment);
        }
        return enrollmentsByContact;
    }

    private void createNotificationsAndUpdateContacts(Map<Id, Id> peByContact) {
        List<Contact> contacts = new List<Contact>();
        List<Notification__c> notifications = new List<Notification__c>();
        for (Id contactId : peByContact.keySet()) {
            contacts.add(new Contact(Id = contactId, Is_FollowUp_Sent__c = true));
            notifications.add(
                new Notification__c(
                    Notification_Type__c = NotificationCatalog.MESSAGE_TO_PT_FOLLOWUP,
                    Recipient__c = contactId,
                    WhatId__c = peByContact.get(contactId)
                )
            );
        }
        update contacts;
        insert notifications;
    }

    public override Type getType() {
        return Batch_FollowUpReminder.class;
    }

    public override String getBatchDescription() {
        return 'Creates Follow-up notifications when participant does not enroll in X number of days';
    }

    public override String getRecommendedIntervalMode() {
        return INTERVAL_DAYS;
    }

    public override Integer getRecommendedRelaunchInterval() {
        return 1;
    }
}