force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Config_API__mdt/Config_API__mdt.object-meta.xml
<CustomObject>
    <description>Add the list of APIs that need some configuration value.</description>
    <label>Config API</label>
    <pluralLabel>Config APIs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Config_API_Param__mdt/Config_API_Param__mdt.object-meta.xml
<CustomObject>
    <description>Define the params and their value for each API</description>
    <label>Config API Param</label>
    <pluralLabel>Config API Params</pluralLabel>
</CustomObject>

force-app/main/default/objects/Config_API_Param__mdt/fields/ConfigAPI__c.field-meta.xml
<CustomField>
    <fullName>ConfigAPI__c</fullName>
    <label>Config API</label>
    <referenceTo>Config_API__mdt</referenceTo>
    <relationshipLabel>Config API Params</relationshipLabel>
    <relationshipName>Config_API_Params</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Config_API_Param__mdt/fields/Param_Value_Long__c.field-meta.xml
<CustomField>
    <fullName>Param_Value_Long__c</fullName>
    <label>Param Value Long</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Config_API_Param__mdt/fields/ParamValue__c.field-meta.xml
<CustomField>
    <fullName>ParamValue__c</fullName>
    <label>Param Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Subject_GUID__c.field-meta.xml
<CustomField>
    <fullName>Subject_GUID__c</fullName>
    <description>eCOA Subject GUID</description>
    <inlineHelpText>required for creating subject in eCOA</inlineHelpText>
    <label>Subject GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/Patient_Visit__c.object-meta.xml
<CustomObject>
    <label>Patient Visit</label>
    <nameField>
        <displayFormat>PV-{000000}</displayFormat>
        <label>Patient Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Visit__c/fields/Ecoa_Key__c.field-meta.xml
<CustomField>
    <fullName>Ecoa_Key__c</fullName>
    <formula>IF( Is_Adhoc__c ,&apos;&apos;,  &apos;visit_&apos;+ TEXT( Visit_Number__c )  )</formula>
    <label>Ecoa Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/visits/classes/PatientVisitTriggerHandler.cls
/**
 * Created by Denis Z on 01-Jul-19.
 * Modified by Ranjit Ravindranath 28/03/2022
 * Desc: handler for patient visit trigger.
 */

public without sharing class PatientVisitTriggerHandler {
    public static Map<String, Config_API_Param__mdt> apiParamsMap;
    public static final String ECOA_CONFIG_NAME = 'ECOAIntegration';
    public static final String ORG_GUID = 'OrgGuid';

    static {
        apiParamsMap = new Map<String, Config_API_Param__mdt>();
        for (Config_API_Param__mdt mdt : [
            SELECT DeveloperName, ParamValue__c, Param_Value_Long__c
            FROM Config_API_Param__mdt
            WHERE ConfigAPI__r.DeveloperName = :ECOA_CONFIG_NAME
        ]) {
            apiParamsMap.put(mdt.DeveloperName, mdt);
        }
        System.debug('apiParamsMap::' + apiParamsMap);
    }

    public class updateEcoaEvents extends TriggerHandler {
        public override void afterUpdate(List<SObject> newList, Map<Id, SObject> oldMap) {
            updateEcoaEvents(newList, (Map<Id, Patient_Visit__c>) oldMap);
        }
    }
    public class completePatientVisitTask extends TriggerHandler {
        public override void afterUpdate(List<SObject> newList, Map<Id, SObject> oldMap) {
            completePVTask(newList, (Map<Id, Patient_Visit__c>) oldMap);
        }
    }
    /*public override void afterInsert(List<SObject> newList) {
        updateEcoaEvents(newList);
    }*/
    @TestVisible
    private static void updateEcoaEvents(
        List<Patient_Visit__c> patientVisits,
        Map<Id, Patient_Visit__c> oldMap
    ) {
        List<Patient_Visit__c> completedVisitPatients = new List<Patient_Visit__c>();
        Set<Id> pvIds = new Set<Id>();
        for (Patient_Visit__c pv : patientVisits) {
            if (pv.Status__c == 'Completed' && pv.Status__c != oldMap.get(pv.Id).Status__c) {
                completedVisitPatients.add(pv);
                pvIds.add(pv.Id);
            }
        }
        if (!pvIds.isEmpty() && !system.isBatch()) {
            triggerEcoaEventAsync(pvIds);
        }
    }

    private static void completePVTask(
        List<Patient_Visit__c> patientVisits,
        Map<Id, Patient_Visit__c> oldMap
    ) {
        Set<Id> pvIds = new Set<Id>();
        List<Task> tasks = new List<Task>();
        for (Patient_Visit__c pv : patientVisits) {
            if (pv.Status__c == 'Completed' && pv.Status__c != oldMap.get(pv.Id).Status__c) {
                pvIds.add(pv.Id);
            }
        }
        if(!pvIds.isEmpty() && !system.isBatch()){
            for(Task task:[Select Id from Task where Patient_Visit__c IN:pvIds]){
                Task newTask = new Task();
                newTask.Id = task.Id;
                newTask.Status = 'Completed';
                newTask.Completed_Date__c = Datetime.now();
                tasks.add(newTask);
            }
        }
        if(!tasks.isEmpty())
        update tasks;
    }

    @Future(Callout=true)
    public static void triggerEcoaEventAsync(Set<Id> pvIds) {
        List<Map<String, String>> requestMapList = new List<Map<String, String>>();
        for (Patient_Visit__c pv : [
            SELECT
                Id,
                Completed_Date__c,
                Ecoa_Key__c,
                Participant_Enrollment__r.Subject_GUID__c,
                Participant_Enrollment__r.Clinical_Trial_Profile__r.Study_GUID__c
            FROM Patient_Visit__c
            WHERE Id IN :pvIds AND Completed_Date__c != NULL
        ]) {
            Date dateToday = pv.Completed_Date__c;
            String sMonth = String.valueof(dateToday.month());
            String sDay = String.valueof(dateToday.day());
            if (sMonth.length() == 1) {
                sMonth = '0' + sMonth;
            }
            if (sDay.length() == 1) {
                sDay = '0' + sDay;
            }
            String dateVal = String.valueof(dateToday.year()) + '-' + sMonth + '-' + sDay;

            Map<String, String> ecoaEventMap = new Map<String, String>{
                'studyGuid' => pv.Participant_Enrollment__r.Clinical_Trial_Profile__r.Study_GUID__c,
                'orgGuid' => apiParamsMap.get(ORG_GUID).ParamValue__c,
                'subjectGuid' => pv.Participant_Enrollment__r.Subject_GUID__c,
                'date' => dateVal,
                'dateKey' => pv.Ecoa_Key__c
            };
            requestMapList.add(ecoaEventMap);
        }
        if (requestMapList != null && !requestMapList.isEmpty()) {
            try {
                ECOAService.createEcoaEvent(requestMapList);
            } catch (Exception e) {
                System.debug('Err');
            }
        }
    }
}