force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Terms_And_Conditions_ID__c.field-meta.xml
<CustomField>
    <fullName>Terms_And_Conditions_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terms And Conditions</label>
    <referenceTo>Terms_And_Conditions__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserCommunityIsDelegate__c.field-meta.xml
<CustomField>
    <fullName>UserCommunityIsDelegate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Community Is Delegate</label>

    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>HCP Enrollments</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hospital of rainbow</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Referring HCPs</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Terms_And_Conditions__c/Terms_And_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms And Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms And Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_And_Conditions__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Portal T&amp;C</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_MyReferringClinicsController.cls
@IsTest
public class Test_MyReferringClinicsController {
    @TestSetup
    static void init() {
        Test.startTest();
        TestData.loadTestData();
        TestData.createTCAcceptance();
        Test.stopTest();
    }
    @isTest
    public static void testHCPEnrollmentWrapper() {
        TestData testData = new TestData();
        List<Terms_And_Conditions__c> tcList = new List<Terms_And_Conditions__c>();
        Terms_And_Conditions__c portalTC = new Terms_And_Conditions__c(Active__c = true);
        //tcList.add(portalTC);

        Test.startTest();
        System.runAs(testdata.piUser) {
            List<String> fields = new List<String>();
            fields.addAll(ReferringClinicsFilter.REFERRING_CLINICS_COMMON_FIELDS);
            fields.add('Clinical_Trial_Profile__r.Terms_And_Conditions_ID__c');
            fields.add('Clinical_Trial_Profile__c');
            List<HCP_Enrollment__c> hcpEnrollments = DataBaseService.query(
                fields,
                HCP_Enrollment__c.getSObjectType(),
                ' Id =\'' + testData.hcpEnrollment.Id + '\''
            );
            HCP_Enrollment__c hcpEnrollment = hcpEnrollments[0];

            Participant__c participant = new Participant__c();
            MyReferringClinicsController.ClinicWrapper clinicWrapper = new MyReferringClinicsController.ClinicWrapper(
                new List<HCP_Enrollment__c>{ hcpEnrollment },
                new Map<Id, Participant__c>{
                    hcpEnrollment.Study_Site__r.Principal_Investigator__c => testdata.participant
                },
                testdata.participant
            );
            MyReferringClinicsController.HCPEnrollmentWrapper wrapper = clinicWrapper.enrollments[0];
            MyReferringClinicsController.ClinicWrapper clinicWrapper2 = new MyReferringClinicsController.ClinicWrapper(
                new List<HCP_Enrollment__c>{ hcpEnrollment }
            );

            Test.stopTest();
        }
    }
    @IsTest
    static void baseHCPTest5() {
        TestData testData = new TestData();
        Test.startTest();
        User hcpu = [SELECT ContactId FROM User WHERE Id = :testData.hcpUser.Id];
        Contact hcpc = new Contact();
        hcpc.Id = hcpu.ContactId;
        hcpc.UserCommunityIsDelegate__c = true;
        update hcpc;
        System.runAs(testData.hcpUser) {
            String initDataString = MyReferringClinicsController.getInitData(
                testData.ctp.Id,
                testData.ss.Id,
                CommunityTemplateService.TEMPLATE_DEFAULT
            );
            MyReferringClinicsController.InitData initData = (MyReferringClinicsController.InitData) JSON.deserializeStrict(
                initDataString,
                MyReferringClinicsController.InitData.class
            );
            MyReferringClinicsController.searchReferringClinics(
                JSON.serialize(initData.referringClinicsFilter.filterValues),
                JSON.serialize(initData.referringClinicsFilter.sortData),
                JSON.serialize(initData.paginationData),
                false
            );
            MyReferringClinicsController.searchReferringClinics(
                JSON.serialize(initData.referringClinicsFilter.filterValues),
                JSON.serialize(initData.referringClinicsFilter.sortData),
                JSON.serialize(initData.paginationData),
                true
            );
        }
        Test.stopTest();
    }
}