force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/Media_Outreach__c.object-meta.xml
<CustomObject>
    <description>To provides the ability to support PI team members requesting assistance with site recruitment activities, such as placing an advertising orders and viewing the status of their previous and current requests.</description>
    <label>Media Outreach</label>
    <nameField>
        <displayFormat>RQ-{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Outreachs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Media_Outreach__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <label>Study Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Media_Type__c.field-meta.xml
<CustomField>
    <fullName>Media_Type__c</fullName>
    <label>Media Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Preferred_contact_method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_contact_method__c</fullName>
    <label>Preferred Contact Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Requested_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_End_Date__c</fullName>
    <label>Requested End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Study_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the study Name.</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Media Outreachs</relationshipLabel>
    <relationshipName>Media_Outreachs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MediaOutreachServices.cls
/* Created By
 * Akanksha */

public class MediaOutreachServices {
    
    public static final String STUDIES_FILTER_DATA_FIELD = 'studies';
    
    public static final Map<String, Map<String, String>> FILTER_FIELD_MAP = new Map<String, Map<String, String>>{
        STUDIES_FILTER_DATA_FIELD => new Map<String, String>{
            'Study_Name__c' => 'Study_Name__r.Clinical_Trial_Profile__r.Study_Code_Name__c'
                }
    };
        
        public class moFilter{
            public List<Id> trialIds;
            public Id study;
            public String searchText;
            public String mode;
            public moFilter(moFilterData filterData) {
                mode = filterData.mode;
                trialIds = filterData.trialIds;
            }
        }
    
    public class moFilterData {
        public String mode;
        public List<Id> trialIds;
        public List<LabelValueItem> studies;
    }
    
    public static moFilterData getMOFilterData(Id trialId, String mode, Boolean restrictTrial, String delegateId) {
        Id userContactId = CommunityService.getUserContact().Id;
        Clinical_Trial_Profile__c trial;
        moFilterData moFilterData = new moFilterData();
        moFilterData.mode = mode;
        Map<Id, Clinical_Trial_Profile__c> trialsMap = new Map<Id, Clinical_Trial_Profile__c>(TrialService.getAvailableTrials(mode, delegateId));
        moFilterData.studies = new List<LabelValueItem>();
        moFilterData.studies.add(new LabelValueItem(Label.PG_MRRL_L_All_studies, null));
        moFilterData.trialIds = new List<Id>();
        
        for (String id : trialsMap.keySet()) {
            moFilterData.trialIds.add(id);
            trial = trialsMap.get(id);
            moFilterData.studies.add(new LabelValueItem(trial.Study_Code_Name__c, trial.Id));
        }
        return moFilterData;
    }
    
    public static List<Media_Outreach__c> getMediaOutreach(moFilter filter, PaginationData paginationData) {
        return getMediaOutreach(filter, paginationData, null);
    }
    
    public static List<Media_Outreach__c> getMediaOutreach(moFilter filter, PaginationData paginationData, String delegateId) {
        List<Media_Outreach__c> mList = getMediaOutreach(filter, delegateId);
        return getMediaOutreachPagination(mList, paginationData);
    }
    
    public static List<Media_Outreach__c> getMediaOutreachPagination(List<Media_Outreach__c> mList, PaginationData paginationData) {
        //Pagination:
        if (paginationData != null) {
            paginationData.setRecordsCount(mList.size());
            List<Media_Outreach__c> pageList = new List<Media_Outreach__c>();
            for (Integer i = paginationData.offset; i < paginationData.endOffset; i++) {
                pageList.add(mList[i]);
            }
            return pageList;
        }
        return mList;
    }
    
    //Media Outreach fields
    public static final List<String> MO_COMMON_FIELDS = new List<String>{
        'Id',
            'Name',
            'Preferred_contact_method__c',
            'Status__c',
            'Media_Type__c',
            'Study_Name__r.Site__r.Name',
            'Study_Name__r.Name',
            'Study_Name__r.Clinical_Trial_Profile__r.Study_Code_Name__c',
            'Study_Name__r.Clinical_Trial_Profile__c',
            'Study_Name__r.Principal_Investigator__c',
            'Requested_End_Date__c',
            'Requested_Start_Date__c'
            
            };
                
                //filter criteria - existing filter on study
                public static List<Media_Outreach__c> getMediaOutreach(moFilter filter, String delegateId){
                    //get all the media outreach assigned to a PI
                    String filterStr = ' AND Study_Name__r.Clinical_Trial_Profile__c IN (\'' + String.join(filter.trialIds, '\',\'') + '\') ';
                    if (filter.searchText != null) filter.searchText = filter.searchText.trim();
                    
                    //If a filter is selected
                    if (String.isEmpty(filter.searchText)) {
                        if (!String.isEmpty(filter.study)) filterStr += ' AND Study_Name__c = \'' + filter.study + '\' ';
                    }
                    
                    //sort
                    filterStr += ' ORDER BY Name DESC';
                    
                    //get media outreach List:
                    List<Media_Outreach__c> mList = getMOutreachCommon(filterStr, delegateId);
                    return mList;
                }
    
    public static List<Media_Outreach__c> getMOutreachCommon(String filter, String delegateId) {
        List<Media_Outreach__c> mList = getMOutreachCommonCustomFields(MO_COMMON_FIELDS, filter, delegateId);
        return mList;
    }
    
    public static List<Media_Outreach__c> getMOutreachCommonCustomFields(List<String> customFields, String filter, String delegateId) {
        return getMOutreachCommonCustomFieldsImpl(customFields, filter, delegateId);
    }
    
    public static List<Media_Outreach__c> getMOutreachCommonCustomFieldsImpl(List<String> customFields, String filter) {
        return getMOutreachCommonCustomFieldsImpl(customFields, filter, null);
    }
    
    
    //dynamic query formation. Adding the filters and fields to be fetched from Media Outreach object
    public static List<Media_Outreach__c> getMOutreachCommonCustomFieldsImpl(List<String> customFields, String filter, String delegateId) {
        String defaultFilter = ' Study_Name__c != NULL AND Status__c !=NULL';// AND ' + getUserModeFilter(userMode, delegateId);
        defaultFilter += ' AND ' + getUserModeFilter(delegateId);
        if (filter != null) defaultFilter += ' ' + filter;
        
        List<Media_Outreach__c> mList = DatabaseService.query(
            customFields,
            Media_Outreach__c.getSObjectType(),
            defaultFilter
        );
        return mList;
    }
    
    //default filter on the Principal Investigator
    private static String getUserModeFilter(String delegateId) {
        String delegatesFilter = '';
        List<Id> delegatedSSIds = DelegateService.getDelegatedStudySiteIds();
        if (delegatedSSIds.size() > 0) delegatesFilter = ' OR Study_Name__c IN (\'' + String.join(delegatedSSIds, '\',\'') + '\')' ;
        return '( ' +
            '   Study_Name__r.Principal_Investigator__c = \'' + CommunityService.getUserContact().Id + '\' ' +
            delegatesFilter +
            ') ';
    }
    
}