force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/ECOA_Is_Avaialble__c.field-meta.xml
<CustomField>
    <fullName>ECOA_Is_Avaialble__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECOA Is Avaialble</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_GUID__c.field-meta.xml
<CustomField>
    <fullName>Study_GUID__c</fullName>
    <label>Study GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Version_GUID__c.field-meta.xml
<CustomField>
    <fullName>Study_Version_GUID__c</fullName>
    <label>Study Version GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECOA_Study_Schedule__c/ECOA_Study_Schedule__c.object-meta.xml
<CustomObject>
    <label>ECOA Study Schedule</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>ECOA Study Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECOA Study Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ECOA_Study_Schedule__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>ECOA Study Schedules</relationshipLabel>
    <relationshipName>ECOA_Study_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ECOA_Study_Schedule__c/fields/ClinroRuleSetGuid__c.field-meta.xml
<CustomField>
    <fullName>ClinroRuleSetGuid__c</fullName>
    <label>ClinroRuleSetGuid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECOA_Study_Schedule__c/fields/EproRuleSetGuid__c.field-meta.xml
<CustomField>
    <fullName>EproRuleSetGuid__c</fullName>
    <label>EproRuleSetGuid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Subject_GUID__c.field-meta.xml
<CustomField>
    <fullName>Subject_GUID__c</fullName>
    <description>eCOA Subject GUID</description>
    <inlineHelpText>required for creating subject in eCOA</inlineHelpText>
    <label>Subject GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/ECOA_Site_Guid__c.field-meta.xml
<CustomField>
    <fullName>ECOA_Site_Guid__c</fullName>
    <label>ECOA Site Guid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/tests/classes/Test_Batch_CreateECOASubject.cls
@IsTest
private class Test_Batch_CreateECOASubject {
    @testSetup
    static void setUp() {
        Test.startTest();
        TestData.loadTestData();
        Test.stopTest();
        
        Clinical_Trial_Profile__c ctp = [
            SELECT id, Study_GUID__c
            FROM Clinical_Trial_Profile__c
            LIMIT 1
        ];
        ctp.Study_GUID__c = 'testguid1234';
        ctp.ECOA_Is_Avaialble__c = true;
        ctp.Study_Version_GUID__c = 'abc123';
        update ctp;

        ECOA_Study_Schedule__c obj1 = new ECOA_Study_Schedule__c();
        obj1.Clinical_Trial_Profile__c = ctp.id;
        obj1.ClinroRuleSetGuid__c = 'test123';
        obj1.EproRuleSetGuid__c = 'eprorule12';
        insert obj1;
    }
    @IsTest
    static void testBehavior() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_ECOAServiceMockCallout());
        TriggerHandlerExecutor.bypassHandler(ParticipantEnrollmentTriggerHandler.class);

        Clinical_Trial_Profile__c ctp = [
            SELECT id, Study_GUID__c
            FROM Clinical_Trial_Profile__c
            LIMIT 1
        ];
        Participant_Enrollment__c pe = [
            SELECT id, Subject_GUID__c, Participant_Status__c
            FROM Participant_Enrollment__c
            WHERE Clinical_Trial_Profile__c = :ctp.id
            LIMIT 1
        ];
        pe.Subject_GUID__c = null;
        pe.Participant_Status__c = 'Enrollment Success';
        update pe;

        Study_Site__c ss = [SELECT id FROM Study_Site__c LIMIT 1];
        ss.ECOA_Site_Guid__c = 'ecosite123';
        update ss;

        Batch_CreateECOASubject obj = new Batch_CreateECOASubject();
        DataBase.executeBatch(obj);

        obj.getBatchDescription();
        obj.getType();
        obj.getRecommendedRelaunchInterval();
        obj.getRecommendedScopeSize();
        Test.stopTest();
    }
}