force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Res_study__c/Res_study__c.object-meta.xml
<CustomObject>
    <label>Study Resource</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Res-study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Res-study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Res_study__c/fields/Active_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Active_After_Days__c</fullName>
    <label>Active After Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Active_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_On_Status__c</fullName>
    <label>Active On Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Resource</relationshipLabel>
    <relationshipName>Resource</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Expires_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Expires_After_Days__c</fullName>
    <label>Expires After Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Expires_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Expires_On_Status__c</fullName>
    <label>Expires On Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Participant_Statuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Study</relationshipLabel>
    <relationshipName>Study</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_In_Alumni__c.field-meta.xml
<CustomField>
    <fullName>Visible_In_Alumni__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible In Alumni</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_To_Delegates__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Delegates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Delegates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_Participant__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object contains Video/Articles</description>
    <!--enableLicensing>false</enableLicensing-->
    <label>Resource</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Resource__c/fields/Countries__c.field-meta.xml
<CustomField>
    <fullName>Countries__c</fullName>
    <label>Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Resource__c/recordTypes/Relevant_Link.recordType-meta.xml
<RecordType>
    <fullName>Relevant_Link</fullName>
    <active>true</active>
    <label>Relevant Link</label>
</RecordType>

force-app/main/default/globalValueSets/Participant_Statuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Failed Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Failed Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded from Referring</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Success</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-Up Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Participation Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Trial Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Drop Out</fullName>
    </customValue>
    <customValue>
        <fullName>Deceased</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Successfully Contacted</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Reach</fullName>
    </customValue>
    <customValue>
        <fullName>Contacted - Not Suitable</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Success</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress - Wash Out Period</fullName>
        <label>In Wash Out Period</label>
    </customValue>
    <customValue>
        <fullName>Ready to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Declined Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent After Screening</fullName>
    </customValue>
    <masterLabel>Participant Statuses</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RelevantLinksRemote.cls
/**
 * Created by Nargiz Mamedova on 12/13/2019.
 */

public without sharing class RelevantLinksRemote {
    @AuraEnabled
    public static List<Resource__c> getInitData() {
        try {
            ParticipantService.ParticipantState ps = ParticipantService.getInstance().getState();
            List<Res_study__c> resStudies = [
                    SELECT Id, Resource__r.URL__c, Resource__r.Title__c,
                            Visible_To_Participant__c, Active_On_Status__c, Expires_On_Status__c, Visible_To_Delegates__c,
                            Active_After_Days__c, Expires_After_Days__c, Visible_In_Alumni__c
                    FROM Res_study__c
                    WHERE Clinical_Trial_Profile__c = :ps.ctp.Id
                    AND Resource__r.Content_Type__c = 'Relevant_Link'
                    AND Resource__r.Countries__c INCLUDES( :ps.pe.Study_Site__r.Site__r.BillingCountryCode)
            ];

            List<Resource__c> resources = new List<Resource__c>();
            for (Res_study__c rs : resStudies) {
                if (StudyResourceVisibilityService.isResourceVisibleForPE(rs, ps.pe, ContactService.getPreferredLanguages(),
                        CommunityService.getUserContact().userCommunityMode__c, ps.isDelegate)) {
                    resources.add(rs.Resource__r);
                }
            }
            return resources;
        } catch (Exception e) {
            return (List<Resource__c>) AuraHelper.throwException(e);
        }
    }
}