force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/CommunityTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommunityTemplate__c</fullName>
    <label>Community Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>IQVIA Patient Portal</label>
            </value>
            <value>
                <fullName>GSK</fullName>
                <label>GSK Pan Oncology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Content__c.field-meta.xml
<CustomField>
    <fullName>Study_Content__c</fullName>
    <description>This field maps to the content accessible via Learn More links in PP.</description>
    <inlineHelpText>This field maps to the content accessible via Learn More links in PP.</inlineHelpText>
    <label>Trial Match Study Content</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Title__c.field-meta.xml
<CustomField>
    <fullName>Study_Title__c</fullName>
    <description>Title of the Study</description>
    <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
    <label>Study Title</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TrialMatchLearnMorePageController.cls
/**
 * Created by Sandeep Kiran on 17.12.2020.
 */
public without sharing class TrialMatchLearnMorePageController {
    
   public String htmlformattedString {get;set;}
   public String studyTitle {get;set;}
   public String CTPId {get;set;}
   public String imgUrl {get;set;}
   public TrialMatchLearnMorePageController()
   {
       
      CTPId= System.currentPagereference().getParameters().get('CTPId');
   //  Clinical_Trial_Profile__c cobj=  [Select Id,Study_Content__c,Study_Title__c  from Clinical_Trial_Profile__c where Id=: VId];a0A1D000005RPuhUAG
       if(CTPId != ''){
        Clinical_Trial_Profile__c cobj=  [Select Id,Study_Content__c,Study_Title__c,CommunityTemplate__c  from Clinical_Trial_Profile__c where Id=: CTPId limit 1];
        htmlformattedString=cobj.Study_Content__c;
        imgUrl=cobj.CommunityTemplate__c + '.png';
        studyTitle=cobj.Study_Title__c;
      }
           
   }
   
    public Boolean getisRTL() {
        return (System.Label.RTL_Languages).contains(UserInfo.getLanguage()) ;
    }
    

}