force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Initial_Visit_Required__c.field-meta.xml
<CustomField>
    <fullName>Initial_Visit_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initial Visit Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Phone_Type__c.field-meta.xml
<CustomField>
    <fullName>Phone_Type__c</fullName>
    <label>Phone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/deprecated/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log Old</label>
    <nameField>
        <displayFormat>IL-{00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Response_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Status_Code__c</fullName>
    <label>Response Status Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Email</label>

    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Participant&#39;s First Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s First Name</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Phone</label>

    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Non_Enrollment_Reason__c.field-meta.xml
<CustomField>
    <fullName>Non_Enrollment_Reason__c</fullName>
    <label>Non-Enrollment Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Participant_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Site No Longer Accepting Referrals</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Meet Pre-Screening Eligibility</fullName>
            </value>
            <value>
                <fullName>Declined Practitioner</fullName>
            </value>
            <value>
                <fullName>PI Decision</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Show For Initial Visit</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Sign Consent</fullName>
            </value>
            <value>
                <fullName>Failed Inclusion/Exclusion Criteria</fullName>
            </value>
            <value>
                <fullName>Patient Declined</fullName>
            </value>
            <value>
                <fullName>Visit Out Of Window</fullName>
            </value>
            <value>
                <fullName>Patient Decision</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Ready to Schedule</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Transportation Issues</fullName>
            </value>
            <value>
                <fullName>Childcare Issues</fullName>
            </value>
            <value>
                <fullName>Participant Not Interested</fullName>
            </value>
            <value>
                <fullName>Did Not Meet Inclusion/Exclusion Criteria</fullName>
            </value>
            <value>
                <fullName>Did Not Attend Appointment</fullName>
            </value>
            <value>
                <fullName>Left a Message</fullName>
            </value>
            <value>
                <fullName>Protocol Concerns</fullName>
            </value>
            <value>
                <fullName>Inadequate Documentation</fullName>
            </value>
            <value>
                <fullName>Does Not Meet Eligibility Criteria</fullName>
            </value>
            <value>
                <fullName>Could not schedule visit</fullName>
                <isActive>false</isActive>
                <label>Could not schedule visit</label>
            </value>
            <value>
                <fullName>Declined or Withdrew Consent</fullName>
                <isActive>false</isActive>
                <label>Declined or Withdrew Consent</label>
            </value>
            <value>
                <fullName>Did not respond to contact attempts</fullName>
                <isActive>false</isActive>
                <label>Did not respond to contact attempts</label>
            </value>
            <value>
                <fullName>Failed screening / does not qualify</fullName>
                <isActive>false</isActive>
                <label>Failed screening / does not qualify</label>
            </value>
            <value>
                <fullName>No longer interested</fullName>
                <isActive>false</isActive>
                <label>No longer interested</label>
            </value>
            <value>
                <fullName>No show for scheduled visit</fullName>
                <isActive>false</isActive>
                <label>No show for scheduled visit</label>
            </value>
            <value>
                <fullName>Not eligible</fullName>
                <isActive>false</isActive>
                <label>Not eligible</label>
            </value>
            <value>
                <fullName>Not willing to sign informed consent</fullName>
                <isActive>false</isActive>
                <label>Not willing to sign informed consent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Hub_Log__c.field-meta.xml
<CustomField>
    <fullName>Study_Hub_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Hub Log</label>
    <referenceTo>Integration_Log__c</referenceTo>
    <relationshipLabel>Study_Hub Integration Enrollments</relationshipLabel>
    <relationshipName>Study_Hub_Integration_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/Participant_Enrollment_Status_History__c.object-meta.xml
<CustomObject>

    <label>Participant Enrollment Status History</label>
    <nameField>
        <displayFormat>PESH-{0000000}</displayFormat>
        <label>Participant Enrollment Status History Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollment Status History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/Non_Enrollment_Reason__c.field-meta.xml
<CustomField>
    <fullName>Non_Enrollment_Reason__c</fullName>
    <label>Non-Enrollment Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Site No Longer Accepting Referrals</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Meet Pre-Screening Eligibility</fullName>
            </value>
            <value>
                <fullName>Declined Practitioner</fullName>
            </value>
            <value>
                <fullName>PI Decision</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Show For Initial Visit</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Sign Consent</fullName>
            </value>
            <value>
                <fullName>Failed Inclusion/Exclusion Criteria</fullName>
            </value>
            <value>
                <fullName>Patient Declined</fullName>
            </value>
            <value>
                <fullName>Visit Out Of Window</fullName>
            </value>
            <value>
                <fullName>Patient Decision</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Ready to Schedule</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Transportation Issues</fullName>
            </value>
            <value>
                <fullName>Childcare Issues</fullName>
            </value>
            <value>
                <fullName>Participant Not Interested</fullName>
            </value>
            <value>
                <fullName>Did Not Meet Inclusion/Exclusion Criteria</fullName>
            </value>
            <value>
                <fullName>Did Not Attend Appointment</fullName>
            </value>
            <value>
                <fullName>Left a Message</fullName>
            </value>
            <value>
                <fullName>Protocol Concerns</fullName>
            </value>
            <value>
                <fullName>Inadequate Documentation</fullName>
            </value>
            <value>
                <fullName>Does Not Meet Eligibility Criteria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Participant_Enrollment_Status_History__c/fields/ParticipantEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ParticipantEnrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Participant Enrollment Status History</relationshipLabel>
    <relationshipName>Participant_Enrollment_Status_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Participant Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Participant_Statuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Participant_Statuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Failed Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Failed Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded from Referring</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Success</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-Up Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Participation Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Trial Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Drop Out</fullName>
    </customValue>
    <customValue>
        <fullName>Deceased</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Successfully Contacted</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Reach</fullName>
    </customValue>
    <customValue>
        <fullName>Contacted - Not Suitable</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Success</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress - Wash Out Period</fullName>
        <label>In Wash Out Period</label>
    </customValue>
    <customValue>
        <fullName>Ready to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Declined Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent After Screening</fullName>
    </customValue>
    <masterLabel>Participant Statuses</masterLabel>
</GlobalValueSet>

force-app/main/deprecated/classes/Test_AddPatientByPIRemote.cls
/**
 * Created by Leonid Bartenev
 */

@IsTest
private without sharing class Test_AddPatientByPIRemote {
    //deprecated
     @TestSetup
    static void init() {
        Test.startTest();
        TestData.loadTestData();
        TestData.createTCAcceptance();
        Test.stopTest();
    }
    
    @IsTest
    static void updateState() {
        TestData testData = new TestData();
        Test.startTest();
        System.runAs(testData.piUser) {
            List<String> PE_COMMON_FIELDS = new List<String>();
            PE_COMMON_FIELDS.addAll(ParticipantEnrollmentService.PE_COMMON_FIELDS);
            PE_COMMON_FIELDS.add(
                '(SELECT Id,Date__c,Non_Enrollment_Reason__c FROM Participant_Enrollment_Status_History__r WHERE Status__c =\'Eligibility Passed\' ORDER BY CreatedDate DESC LIMIT 1)'
            );
            PE_COMMON_FIELDS.add('Clinical_Trial_Profile__r.Initial_Visit_Required__c');
            PE_COMMON_FIELDS.add('Study_Hub_Log__c');
            //PE_COMMON_FIELDS.add('Date_of_Birth__c');
            PE_COMMON_FIELDS.add('Study_Hub_Log__r.Response_Status_Code__c');
            Participant_Enrollment__c pe = ParticipantEnrollmentService.getParticipantEnrollment(
                testData.pe.Id,
                CommunityService.USER_MODE_PI,
                null,
                PE_COMMON_FIELDS
            );
            ParticipantWorkflowService.ParticipantWorkflowWrapper path = ParticipantWorkflowService.prepareParticipantWorkflow(
                testData.ctp,
                pe
            );
            path.steps[path.currentStepInd].outcome = PEStatusState.PE_STATUS_CONTACT_ATTEMPTED;
            
            Participant__c participantDel = new Participant__c();
            participantDel.Email__c = 'Test01@mail.ru';
            participantDel.First_Name__c = 'testName';
            participantDel.Last_Name__c = 'testLastName';
            participantDel.Phone__c = '141241';
            participantDel.Phone_Type__c = 'Home';
            
            Participant__c participantDel1 = new Participant__c();
            participantDel1.Email__c = 'Test0198@mail.ru';
            participantDel1.First_Name__c = 'testName1';
            participantDel1.Last_Name__c = 'testLastName1';
            participantDel1.Phone__c = '14124189';
    
            participantDel1.Birth_Year__c = '1990';
            
            Contact objCon = new Contact();
            objCon.Participant_Phone_Opt_In_Permit_Phone__c = true;
            objCon.Participant_Opt_In_Status_Emails__c = true;
            objCon.Participant_Opt_In_Status_SMS__c = true;
            
            AddPatientByPIRemote.updateParticipant(JSON.serialize(testData.participant));
            AddPatientByPIRemote.updatePatientInfo(JSON.serialize(testData.participant), JSON.serialize(testData.pe));
            AddPatientByPIRemote.getUserLanguage();
            //AddPatientByPIRemote.trimParticipantFields(testData.participant);
            AddPatientByPIRemote.checkNeedsGuardian(JSON.serialize(testData.participant));
            AddPatientByPIRemote.checkDuplicateDelegate('del@del.com','del','del');
            AddPatientByPIRemote.checkDelegateAge(JSON.serialize(testData.participant),JSON.serialize(participantDel));
            AddPatientByPIRemote.assignParticipantPermissions(testData.ss.Id,testData.piContact.Id);
            AddPatientByPIRemote.savePER(null,
            JSON.serialize(testData.pe),
            testData.ss.Id,
            JSON.serialize(participantDel),
            JSON.serialize(testData.participant),
            null,
            JSON.serialize(objCon),
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            null);
            
            AddPatientByPIRemote.createParticipantDelegate(
                    JSON.serialize(participantDel),
                    null,
                    testData.participant.Id,
                    JSON.serialize(testData.participant),
                    false,
                    null,
                    JSON.serialize(objCon),
                    true,
                    false,
                    null
                );
                AddPatientByPIRemote.createParticipantDelegate(
                    JSON.serialize(participantDel1),
                    null,
                    testData.participant.Id,
                    JSON.serialize(testData.participant),
                    false,
                    null,
                    JSON.serialize(objCon),
                    true,
                    false,
                    null
                );
                
        }
        Test.stopTest();
    }
    
    @IsTest
    static void updateState1() {
        TestData testData = new TestData();
        
        System.runAs(testData.piUser) {
            List<String> PE_COMMON_FIELDS = new List<String>();
            PE_COMMON_FIELDS.addAll(ParticipantEnrollmentService.PE_COMMON_FIELDS);
            PE_COMMON_FIELDS.add(
                '(SELECT Id,Date__c,Non_Enrollment_Reason__c FROM Participant_Enrollment_Status_History__r WHERE Status__c =\'Eligibility Passed\' ORDER BY CreatedDate DESC LIMIT 1)'
            );
            PE_COMMON_FIELDS.add('Clinical_Trial_Profile__r.Initial_Visit_Required__c');
            PE_COMMON_FIELDS.add('Study_Hub_Log__c');
            //PE_COMMON_FIELDS.add('Date_of_Birth__c');
            PE_COMMON_FIELDS.add('Study_Hub_Log__r.Response_Status_Code__c');
            Participant_Enrollment__c pe = ParticipantEnrollmentService.getParticipantEnrollment(
                testData.pe.Id,
                CommunityService.USER_MODE_PI,
                null,
                PE_COMMON_FIELDS
            );
            ParticipantWorkflowService.ParticipantWorkflowWrapper path = ParticipantWorkflowService.prepareParticipantWorkflow(
                testData.ctp,
                pe
            );
            path.steps[path.currentStepInd].outcome = PEStatusState.PE_STATUS_CONTACT_ATTEMPTED;
            
            Participant__c participantDel = new Participant__c();
            participantDel.Email__c = 'Test01@mail.ru';
            participantDel.First_Name__c = 'testName';
            participantDel.Last_Name__c = 'testLastName';
            participantDel.Phone__c = '141241';
            participantDel.Phone_Type__c = 'Home';
            
            Participant__c participantDel1 = new Participant__c();
            participantDel1.Email__c = 'Test0198@mail.ru';
            participantDel1.First_Name__c = 'testName1';
            participantDel1.Last_Name__c = 'testLastName1';
            participantDel1.Phone__c = '14124189';
    
            participantDel1.Birth_Year__c = '1990';
            
            Contact objCon = new Contact();
            objCon.Participant_Phone_Opt_In_Permit_Phone__c = true;
            objCon.Participant_Opt_In_Status_Emails__c = true;
            objCon.Participant_Opt_In_Status_SMS__c = true;
            
            Test.startTest();
                
                 Account studySiteAccount = new Account(
                Name = 'Study Site Account',
                BillingLatitude = 41.766594,
                BillingLongitude = -74.991509,
                BillingCountry = 'United States'
            );
            insert studySiteAccount;
                
                Participant__c participant4 = new Participant__c(
                    First_Name__c = 'PI',
                    Last_Name__c = 'PI',
                    Phone__c = '8343212',
                    Email__c = '04ipremail@gmtesstail.com',
                    Mailing_Country_Code__c = 'US',
                    Mailing_State_Code__c = 'AL',
                    Adult__c = true,
                    Site__c = studySiteAccount.Id,
                    Date_of_Birth__c = '1987-03-01',
                    Contact__c = testdata.piContact.Id,
                    Mailing_Zip_Postal_Code__c = '12345'
                );
                insert participant4;
                
                
                AddPatientByPIRemote.saveParticipants(
                JSON.serialize(participant4),
                JSON.serialize(testData.pe),
                null,
                testData.ss.Id,
                false,
                JSON.serialize(participantDel1),
                null,
                false,
                false,
                false,
                false,
                false,
                JSON.serialize(objCon),
                true);
                
                
                AddPatientByPIRemote.saveParticipant(
                JSON.serialize(participant4),
                JSON.serialize(testData.pe),
                null,
                testData.ss.Id,
                false,
                JSON.serialize(participantDel1),
                null,
                false,
                false,
                false,
                false,
                false,
                JSON.serialize(objCon),
                true
                );
                
                AddPatientByPIRemote.getInitData(testData.ss.Id);
                
                Test.stopTest();
        }
        
    }
}