force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Include_in_RP_trial_search__c.field-meta.xml
<CustomField>
    <fullName>Include_in_RP_trial_search__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in RP Trial Search</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Link_to_Pre_screening__c.field-meta.xml
<CustomField>
    <fullName>Link_to_Pre_screening__c</fullName>
    <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires pre-screening.</inlineHelpText>
    <label>Link to Pre-screening</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
    <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
    <label>NCT Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Override_Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_Recruitment_Status__c</fullName>
    <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
    <label>Override Recruitment Status</label>

    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actively Enrolling</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>No_Longer_Enrolling</fullName>
                <label>No Longer Enrolling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Patient_Portal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Patient_Portal_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Patient Portal Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <description>QI assigned unique ID for a study</description>
    <externalId>true</externalId>
    <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
    <label>Protocol ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Shareback_Availability_Timing__c.field-meta.xml
<CustomField>
    <fullName>Shareback_Availability_Timing__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Show visit result after # completed visits</description>
    <label>Shareback Availability Timing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Shareback_Settings_On_Participant_Level__c.field-meta.xml
<CustomField>
    <fullName>Shareback_Settings_On_Participant_Level__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shareback Settings On Participant Level</description>
    <label>Shareback Settings On Participant Level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Title__c.field-meta.xml
<CustomField>
    <fullName>Study_Title__c</fullName>
    <description>Title of the Study</description>
    <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
    <label>Study Title</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Suppress_Participant_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Participant_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, no emails will be sent to participants for this study.</inlineHelpText>
    <label>Suppress Participant Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Synch_with_TMDH__c.field-meta.xml
<CustomField>
    <fullName>Synch_with_TMDH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TMDH Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Terms_And_Conditions_ID__c.field-meta.xml
<CustomField>
    <fullName>Terms_And_Conditions_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terms And Conditions</label>
    <referenceTo>Terms_And_Conditions__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Data_Shareback__c.field-meta.xml
<CustomField>
    <fullName>Visit_Data_Shareback__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Data Shareback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunytyType__c.field-meta.xml
<CustomField>
    <fullName>userCommunytyType__c</fullName>
    <description>User types for community - HCP / PI / Participant</description>
    <inlineHelpText>Select user types for community</inlineHelpText>
    <label>User Community Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <formula>Clinical_Trial_Profile__r.Protocol_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Clinical Trial Profile&#39;s Protocol Id</inlineHelpText>
    <label>Protocol ID</label>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Suppress_Participant_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Participant_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, no emails will be sent to participants for this study site.</inlineHelpText>
    <label>Suppress Participant Emails</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Terms_And_Conditions__c/Terms_And_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms And Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms And Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_And_Conditions__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Portal T&amp;C</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions__c/fields/Community_Name__c.field-meta.xml
<CustomField>
    <fullName>Community_Name__c</fullName>
    <label>Community Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IQVIA Referral Hub</fullName>
                <default>true</default>
                <label>IQVIA Referral Hub</label>
            </value>
            <value>
                <fullName>GSK Community</fullName>
            </value>
            <value>
                <fullName>IQVIA Patient Portal</fullName>
            </value>
            <value>
                <fullName>Janssen Community</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Terms_And_Conditions__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>

    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions__c/fields/Last_Updated_on__c.field-meta.xml
<CustomField>
    <fullName>Last_Updated_on__c</fullName>
    <label>Last Updated on</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions__c/fields/Policy_Headers__c.field-meta.xml
<CustomField>
    <fullName>Policy_Headers__c</fullName>
    <label>Policy Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Terms_And_Conditions__c/fields/T_C_Text__c.field-meta.xml
<CustomField>
    <fullName>T_C_Text__c</fullName>
    <label>T&amp;C Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions__c/fields/T_C_Type__c.field-meta.xml
<CustomField>
    <fullName>T_C_Type__c</fullName>
    <label>T&amp;C Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privacy Policy</fullName>
            </value>
            <value>
                <fullName>Terms and Conditions</fullName>
                <default>true</default>
                <label>Terms and Conditions</label>
            </value>
            <value>
                <fullName>Cookie Policy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Terms_And_Conditions_Acceptance__c/Terms_And_Conditions_Acceptance__c.object-meta.xml
<CustomObject>
    <label>Terms And Conditions Acceptance</label>
    <nameField>
        <displayFormat>TCA-{000000}</displayFormat>
        <label>Terms And Conditions Acceptance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions Acceptance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_And_Conditions_Acceptance__c/fields/Terms_And_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_And_Conditions__c</fullName>
    <label>Terms And Conditions</label>
    <referenceTo>Terms_And_Conditions__c</referenceTo>
    <relationshipLabel>Terms And Conditions Acceptance</relationshipLabel>
    <relationshipName>Terms_And_Conditions_Acceptance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_TermsAndConditionAcceptanceHandler.cls
@isTest
private class Test_TermsAndConditionAcceptanceHandler {
     @isTest
    static void test() {
         TriggerHandlerExecutor.bypassHandler(
            ParticipantTriggerHandler.StudySiteTriggerHandler.class
        );

         UserRole userRole_1 = [SELECT Id FROM UserRole WHERE Name = 'View All' LIMIT 1];
         Terms_And_Conditions__c ppTc = new Terms_And_Conditions__c(
            Active__c = true,
            Community_Name__c = 'IQVIA Referral Hub',
            Language__c = 'en_US',
            Last_Updated_on__c = 'July 10, 2020',
            Policy_Headers__c = 'Test Header 1',
            T_C_Text__c = '<p><b style="font-size: 12pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0);">PRIVACY POLICY</b></p>',
            T_C_Type__c = 'Privacy Policy'
        );
        insert ppTc;

        Profile profile_1 = [
            SELECT Id
            FROM Profile
            WHERE Name = 'IQVIA Customer Community Plus Login User'
            LIMIT 1
        ];
        User admin = [
            SELECT Id, Username, UserRoleId
            FROM User
            WHERE
                Profile.Name = 'System Administrator'
                AND UserRoleId = :userRole_1.Id
                AND IsActive = TRUE
            LIMIT 1
        ];

        User user_1;
        Contact piContact;
        System.runAs(admin) {
            Account studySiteAccount = new Account(
            Name = 'Study Site Account',
            BillingLatitude = 41.766594,
            BillingLongitude = -74.991509,
            BillingCountry = 'United States'
        );
        insert studySiteAccount;
             piContact = new Contact(
                AccountId = studySiteAccount.Id,
                LastName = 'ParticipantTD12',
                FirstName = 'ParticipantTD11',
                Email = 'someexample@gmail.com',
                userCommunytyType__c = 'PI'
            );
            insert piContact;
            user_1 = new User(
                Email = 'someexample@gmail.com',
                ProfileId = profile_1.Id,
                UserName = 'yourusername@gmail.com',
                Alias = 'Test',
                TimeZoneSidKey = 'America/New_York',
                EmailEncodingKey = 'ISO-8859-1',
                LocaleSidKey = 'en_US',
                LanguageLocaleKey = 'en_US',
                ContactId = piContact.Id,
                PortalRole = 'Manager',
                FirstName = 'ParticipantTD11',
                LastName = 'ParticipantTD12'
            );
            insert user_1;
             Therapeutic_Area__c area = new Therapeutic_Area__c(Name = 'Test TA TD');
        insert area;

        Clinical_Trial_Profile__c study = new Clinical_Trial_Profile__c(
            Protocol_ID__c = 'CTP1',
            Override_Recruitment_Status__c = 'Actively Enrolling',
            NCT_Number__c = 'NCT99999999',
            Link_to_Pre_screening__c = 'some link',
            Terms_And_Conditions_ID__c = ppTc.Id,
            Study_Title__c = 'Some Title',
            Study_Code_Name__c = 'Some Code Name',
            Suppress_Participant_Emails__c = false,
            Therapeutic_Area__c = area.Id,
            Synch_with_TMDH__c = true,
            Include_in_RP_trial_search__c = true,
            Patient_Portal_Enabled__c = true,
            Shareback_Settings_On_Participant_Level__c = true,
            Shareback_Availability_Timing__c = 1,
            Visit_Data_Shareback__c = true,
            Visit_Schedule_Is_Available__c = true,
            Tasks_Are_Available__c = true,
            Study_Documents_Are_Available__c = true,
            Video_And_Articles_Are_Available__c = true,
            Travel_Vendor_Is_Available__c = true,
            Relevant_Links_Are_Available__c = true,
            Sponsor_Pays_for_Referral_Activity__c = 'Yes',
            CommunityTemplate__c = CommunityTemplateService.TEMPLATE_DEFAULT,
            Logged_Out_Days_Notification__c = 1,
            Enable_for_Call_Center_Support__c = true
        );
        insert study;
        
        Study_Site__c studySite1 = new Study_Site__c(
            Principal_Investigator__c = piContact.Id,
            Clinical_Trial_Profile__c = study.Id,
            Override_PI_Referral_Status__c = StudySiteService.PI_S_INVITATION_SENT,
            Site__c = studySiteAccount.Id,
            Study_Site_Type__c = 'Traditional',
            Suppress_Participant_Emails__c = false,
            Study_Site_Number__c = 'SS1',
            Billable_Code_CRM_Number__c = 'Test_Billable_Code',
            Enable_for_Call_Center_Support__c = true
          
        );
        insert studySite1;
             Terms_And_Conditions_Acceptance__c tcAcceptance = new Terms_And_Conditions_Acceptance__c(
            Terms_And_Conditions__c = ppTc.id,
            User__c = user_1.id,
            Accepted_Date__c = Date.today()
        );
        insert tcAcceptance;
        
        Test.startTest();
        TermsAndConditionAcceptanceHandler.handleAcceptance(new list<Terms_And_Conditions_Acceptance__c>{tcAcceptance});
        Test.stopTest();
 
        }
    }
}