force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Orientation_Required__c.field-meta.xml
<CustomField>
    <fullName>Orientation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Orientation Required</label>
<!--    <trackHistory>true</trackHistory>-->
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>HCP Enrollments</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/HCP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HCP_Contact__c</fullName>
    <label>HCP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HCP&#39;s Study Sites</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>HCP Status per clinical trial by PI</description>
    <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
    <label>HCP Status</label>

    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>On Hold (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending Orientation</fullName>
            </value>
            <value>
                <fullName>Declined (Approval)</fullName>
            </value>
            <value>
                <fullName>On Hold (Approval)</fullName>
            </value>
            <value>
                <fullName>Declined (Activation)</fullName>
            </value>
            <value>
                <fullName>On Hold (Activation)</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Activated (Admin)</fullName>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
            </value>
            <value>
                <fullName>Declined (Admin)</fullName>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hospital of rainbow</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Referring HCPs</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Action_RequestToReferByHCPRemote.cls
/**
 * Created by Kryvolap on 26.03.2019.
 */

public without sharing class Action_RequestToReferByHCPRemote {

    @AuraEnabled
    public static void requestToReferForHCP(String studySiteId, String hcpeId, String delegateId) {
        System.debug('delegateId1:'+delegateId);
        Savepoint sp = Database.setSavepoint();
        try {
            HCP_Enrollment__c hcpEnrollment;
            Study_Site__c studySite = StudySiteService.getStudySiteForHCPById(studySiteId);
            if(hcpeId==null || hcpeId == ''){
                Id userContactId = CommunityService.getUserContact().Id;
                if( delegateId!=null && delegateId != ''){
                    userContactId = (Id)delegateId;
                }
                System.debug('delegateId:'+delegateId);
                System.debug('userContactId:'+userContactId);
                hcpEnrollment = new HCP_Enrollment__c();
                new StudyActionsHCP(studySite.Clinical_Trial_Profile__r, studySite, null, delegateId).checkAction(StudyActions.ACT_REQUEST_TO_REFER);
                hcpEnrollment.HCP_Contact__c = userContactId;
                hcpEnrollment.Study_Site__c = studySiteId;
            }
            else{
                hcpEnrollment = [SELECT Id, Status__c FROM HCP_Enrollment__c WHERE Id = :hcpeId LIMIT 1];
            }

            hcpEnrollment.Status__c = HCPEnrollmentService.HCP_S_ACTIVATION_PENDING;
            if (studySite.Clinical_Trial_Profile__r.Orientation_Required__c) hcpEnrollment.Status__c = HCPEnrollmentService.HCP_S_APPROVAL_PENDING;
            upsert hcpEnrollment;
        } catch (Exception e) {
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

}