force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/incentive-program/objects/Completed_Incentive_Task__c/Completed_Incentive_Task__c.object-meta.xml
<CustomObject>
    <label>Completed Incentive Task</label>
    <nameField>
        <displayFormat>CITASK-{0000000}</displayFormat>
        <label>Completed Incentive Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completed Incentive Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/incentive-program/objects/Completed_Incentive_Task__c/fields/Completed_By__c.field-meta.xml
<CustomField>
    <fullName>Completed_By__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Completed By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Completed Incentive Tasks</relationshipLabel>
    <relationshipName>Completed_Incentive_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/incentive-program/objects/Completed_Incentive_Task__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <label>Completed Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/incentive-program/objects/Completed_Incentive_Task__c/fields/Incentive_Plan_Task__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Plan_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incentive Plan Task</label>
    <referenceTo>Incentive_Plan_Task__c</referenceTo>
    <relationshipLabel>Completed Incentive Tasks</relationshipLabel>
    <relationshipName>Completed_Incentive_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/incentive-program/objects/Completed_Incentive_Task__c/fields/Incentive_Task_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Task_Catalog__c</fullName>
    <label>Incentive Task Catalog</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Plan__c/Incentive_Plan__c.object-meta.xml
<CustomObject>
    <label>Incentive Plan</label>
    <nameField>
        <displayFormat>INCPLAN-{0000}</displayFormat>
        <label>Incentive Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/incentive-program/objects/Incentive_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Incentive Plans</relationshipLabel>
    <relationshipName>Incentive_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Plan_Task__c/Incentive_Plan_Task__c.object-meta.xml
<CustomObject>
    <label>Incentive Plan Task</label>
    <nameField>
        <displayFormat>IPT-{000000}</displayFormat>
        <label>Incentive Plan Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Plan Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/incentive-program/objects/Incentive_Plan_Task__c/fields/Incentive_Plan__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Plan__c</fullName>
    <label>Incentive Plan</label>
    <referenceTo>Incentive_Plan__c</referenceTo>
    <relationshipLabel>Incentive Plan Tasks</relationshipLabel>
    <relationshipName>Incentive_Plan_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Plan_Task__c/fields/Incentive_Task_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Task_Catalog__c</fullName>
    <label>Incentive Task Catalog</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Plan_Task__c/fields/IQVIA_Supported__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Supported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Supported</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/Study_Incentive_Plan__c.object-meta.xml
<CustomObject>
    <label>Study Incentive Plan</label>
    <nameField>
        <displayFormat>SIP-{000000}</displayFormat>
        <label>Study Incentive Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Incentive Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Study Incentive Plans</relationshipLabel>
    <relationshipName>Study_Incentive_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/fields/Incentive_Plan__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incentive Plan</label>
    <referenceTo>Incentive_Plan__c</referenceTo>
    <relationshipLabel>Study Incentive Plans</relationshipLabel>
    <relationshipName>Study_Incentive_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Study Incentive Plans</relationshipLabel>
    <relationshipName>Study_Incentive_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/incentive-program/classes/IncentiveProgramService.cls
/**
 * Created by Andrii Kryvolap.
 */

public without sharing class IncentiveProgramService {

    public static PointsResultWrapper getCurrentContactPoints(Datetime timeStamp){
        return getContactPoints(UserContext.getUserContactId(), timeStamp);
    }

    public static PointsResultWrapper getContactPoints(Id contactId, Datetime timeStamp){
        PointsResultWrapper result = new PointsResultWrapper();
        for (Completed_Incentive_Task__c task : [SELECT Id, Points__c, Completed_Date__c FROM Completed_Incentive_Task__c WHERE Completed_By__c =:contactId]){
            result.totalPoints += Math.round(task.Points__c);
            if(task.Completed_Date__c >= timeStamp){
                result.lastPoints += Math.round(task.Points__c);
            }
        }
        return result;
    }

    public static void completeIncentiveTaskCurrentContact(String taskName, Id ctpId, Id peId){
        completeIncentiveTask(UserContext.getUserContactId(), taskName, ctpId, peId);
    }

    public static void completeIncentiveTaskCurrentContact(String taskName, Id ctpId){
        completeIncentiveTask(UserContext.getUserContactId(), taskName, ctpId, null);
    }

    public static void completeIncentiveTask(Id contactId, String taskName, Id ssId){
        completeIncentiveTask(contactId, taskName, ssId, null);
    }

    public static void completeIncentiveTask(Id contactId, String taskName, Id ssId, Id peId){
        Incentive_Plan_Task__c incentivePlanTask = getIncentivePlanTask(taskName, ssId);
        if (incentivePlanTask != null && incentivePlanTask.Enabled__c) {
            Completed_Incentive_Task__c completedIncentiveTask = new Completed_Incentive_Task__c();
            completedIncentiveTask.Completed_By__c = contactId;
            completedIncentiveTask.Completed_Date__c = Datetime.now();
            completedIncentiveTask.Incentive_Task_Catalog__c = taskName;
            completedIncentiveTask.Points__c = incentivePlanTask.Points__c;
            insert completedIncentiveTask;
        }
    }

    public static Incentive_Plan_Task__c getIncentivePlanTask(String taskName, Id ssId){
        Set<Id> planIds = new Set<Id>();
        for (Study_Incentive_Plan__c studyIncentivePlan : [
                SELECT Id, Incentive_Plan__c, Clinical_Trial_Profile__c, Study_Site__c
                FROM Study_Incentive_Plan__c
                WHERE Study_Site__c = :ssId
        ]){
            planIds.add(studyIncentivePlan.Incentive_Plan__c);
        }
        if (!planIds.isEmpty()) {
            List<Incentive_Plan_Task__c> incentiveTasks = [
                    SELECT Id,Points__c, Enabled__c, IQVIA_Supported__c
                    FROM Incentive_Plan_Task__c
                    WHERE Incentive_Plan__c IN :planIds AND Incentive_Task_Catalog__c = :taskName
            ];
            if (incentiveTasks.isEmpty()) {
                return null;
            }
            else{
                return incentiveTasks[0];
            }
        }
        else{
            return null;
        }

    }

    public class PointsResultWrapper{
        @AuraEnabled public Integer totalPoints = 0;
        @AuraEnabled public Integer lastPoints = 0;
    }
}