force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/resources/objects/Res_study__c/Res_study__c.object-meta.xml
<CustomObject>
    <label>Study Resource</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Resource Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Res_study__c/fields/Active_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Active_After_Days__c</fullName>
    <label>Active After Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Active_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_On_Status__c</fullName>
    <label>Active On Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <inlineHelpText>master detail</inlineHelpText>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Resource</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Expires_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Expires_After_Days__c</fullName>
    <label>Number of Days Before Document Expires</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Expires_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Expires_On_Status__c</fullName>
    <label>Expires On Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Active_On_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Participant_Statuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Notify_On_Availability__c.field-meta.xml
<CustomField>
    <fullName>Notify_On_Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify On Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>Only Study Specific Resource can be added.</errorMessage>
        <filterItems>
            <field>Resource__c.Content_Class__c</field>
            <operation>equals</operation>
            <value>Study-Specific</value>
        </filterItems>
        <filterItems>
            <field>Resource__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Study Document</value>
        </filterItems>
        <filterItems>
            <field>Resource__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Relevant Link</value>
        </filterItems>
        <infoMessage>Only Study Specific Resource can be added.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Study Resources</relationshipLabel>
    <relationshipName>Study</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_In_Alumni__c.field-meta.xml
<CustomField>
    <fullName>Visible_In_Alumni__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible In Alumni</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_To_Delegates__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Delegates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Delegates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_Participant__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_PI__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_PI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To PI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_RP__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_RP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To RP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object contains Video/Articles</description>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/resources/objects/Resource__c/fields/Content_Class__c.field-meta.xml
<CustomField>
    <fullName>Content_Class__c</fullName>
    <label>Content Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Study-Specific</fullName>
            </value>
            <value>
                <fullName>Platform-TA</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Resource__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Study_Document</fullName>
                <label>Study Document</label>
            </value>
            <value>
                <fullName>Relevant_Link</fullName>
                <label>Relevant Link</label>
            </value>
            <value>
                <fullName>Submitted_Articles</fullName>
                <label>Submitted Articles</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Resource__c/recordTypes/Study_Document.recordType-meta.xml
<RecordType>
    <fullName>Study_Document</fullName>
    <active>true</active>
    <label>Study Document</label>
</RecordType>

force-app/main/default/globalValueSets/Participant_Statuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Failed Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Failed Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded from Referring</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Success</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-Up Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Participation Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Trial Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Drop Out</fullName>
    </customValue>
    <customValue>
        <fullName>Deceased</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Successfully Contacted</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Reach</fullName>
    </customValue>
    <customValue>
        <fullName>Contacted - Not Suitable</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Success</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress - Wash Out Period</fullName>
        <label>In Wash Out Period</label>
    </customValue>
    <customValue>
        <fullName>Ready to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Declined Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent After Screening</fullName>
    </customValue>
    <masterLabel>Participant Statuses</masterLabel>
</GlobalValueSet>

force-app/main/resources/classes/ResourceStudyRelatedService.cls
public virtual inherited sharing class ResourceStudyRelatedService extends ResourceService {
    private static final List<String> RES_STUDY_FIELDS = new List<String>{
        'Id',
        'Active_On_Status__c',
        'Expires_On_Status__c',
        'Active_After_Days__c',
        'Expires_After_Days__c',
        'Notify_On_Availability__c',
        'Visible_In_Alumni__c',
        'Visible_To_Delegates__c',
        'Visible_To_Participant__c',
        'Visible_To_PI__c',
        'Visible_To_RP__c',
        'Resource__c',
        'Resource__r.Language__c',
        'Resource__r.Content_Type__c',
        'Resource__r.Title__c'
    };

    private Id ctpId;

    public static ResourceStudyRelatedService getInstance() {
        return (ResourceStudyRelatedService) ClassFactory.newInstance(
            ResourceStudyRelatedService.class
        );
    }

    public ResourceService init(
        String resourceType,
        String resourceId,
        String contentClass,
        Id ctpId
    ) {
        this.init(resourceType, resourceId, contentClass,participantData);
        this.ctpId = ctpId;
        return this;
    }

    protected virtual override List<Id> getResourcesIds() {
        if (resourceId != null)
            return new List<Id>{ resourceId };
            List<String> listResourceType= new List<String>();
            listResourceType=resourceType.split(';');
        //Create filter for query:
        String filter = DatabaseService.fieldInValues(
            'Resource__r.RecordType.DeveloperName',
            listResourceType
        );
        if (contentClass != null)
            filter +=
                ' AND ' + DatabaseService.fieldEqual('Resource__r.Content_Class__c', contentClass);
        if (resourceId != null) {
            filter += ' AND ' + DatabaseService.fieldEqual('Resource__c', resourceId);
        } else {
            filter += ' AND ' + DatabaseService.fieldEqual('Clinical_Trial_Profile__c', getCTPId());
        }
        List<Res_study__c> resStudies = (List<Res_study__c>) DatabaseService.query(
            RES_STUDY_FIELDS,
            Res_study__c.getSObjectType(),
            filter
        );

        //split resources
        List<Res_study__c> studyDocumentsResources = new List<Res_study__c>();
        List<Res_study__c> otherResources = new List<Res_study__c>();
        for (Res_study__c rs : resStudies) {
            if (rs.Resource__r.Content_Type__c == 'Study_Document') {
                studyDocumentsResources.add(rs);
            } else {
                otherResources.add(rs);
            }
        }

        List<String> contactPreferredLanguages = ContactService.getPreferredLanguages();
        String userMode= CommunityService.getUserContact().userCommunityMode__c;

        //retrieve languages for study docs
        Map<Id, List<String>> contentLangByResId = new Map<Id, List<String>>();
        Set<Id> studyDocResourceIds = new Set<Id>();
        for (Res_study__c rs : studyDocumentsResources)
            studyDocResourceIds.add(rs.Resource__c);
        if (studyDocumentsResources.size() > 0) {
            List<ContentDocumentLink> contentDocumentLinks = [
                SELECT
                    Id,
                    ContentDocument.Title,
                    LinkedEntityId,
                    ContentDocument.LatestPublishedVersion.LanguageCode__c
                FROM ContentDocumentLink
                WHERE
                    LinkedEntityId IN :studyDocResourceIds
                    AND (ContentDocument.Title IN :contactPreferredLanguages
                    OR ContentDocument.LatestPublishedVersion.LanguageCode__c IN :contactPreferredLanguages)
            ];

            for (ContentDocumentLink content : contentDocumentLinks) {
                if (!contentLangByResId.containsKey(content.LinkedEntityId)) {
                    contentLangByResId.put(content.LinkedEntityId, new List<String>());
                }
                if (contactPreferredLanguages.contains(content.ContentDocument.Title)) {
                    contentLangByResId.get(content.LinkedEntityId)
                        .add(content.ContentDocument.Title);
                } else {
                    contentLangByResId.get(content.LinkedEntityId)
                        .add(content.ContentDocument.LatestPublishedVersion.LanguageCode__c);
                }
            }
        }

        //group other resources by title:
        Map<String, Map<String, Res_study__c>> otherResourceMap = new Map<String, Map<String, Res_study__c>>();
        for (Res_study__c resStudy : otherResources) {
            if (!otherResourceMap.containsKey(resStudy.Resource__r.Title__c))
                otherResourceMap.put(
                    resStudy.Resource__r.Title__c,
                    new Map<String, Res_study__c>()
                );
            otherResourceMap.get(resStudy.Resource__r.Title__c)
                .put(resStudy.Resource__r.Language__c, resStudy);
        }

        //Get Res Study records and filters result resource Ids
        //Study document resources:
        List<Id> resourcesIds = new List<Id>();
        for (Res_study__c resStudy : studyDocumentsResources) {
            if (
                StudyResourceVisibilityService.isResourceVisibleForPE(
                    resStudy,
                    pState.pe,
                    contentLangByResId.get(resStudy.Resource__c),
                    userMode,
                    pState.isDelegate
                )
            )
                resourcesIds.add(resStudy.Resource__c);
        }
        //Other resources:
        for (String resTitle : otherResourceMap.keySet()) {
            Map<String, Res_study__c> resourceTranslationsMap = otherResourceMap.get(resTitle);
            for (String lang : contactPreferredLanguages) {
                Res_study__c resStudy = resourceTranslationsMap.get(lang);
                if (
                    resStudy != null &&
                    StudyResourceVisibilityService.isResourceVisibleForPE(
                        resStudy,
                        pState.pe,
                        new List<String>{ lang },
                        userMode,
                        pState.isDelegate
                    )
                ) {
                    resourcesIds.add(resStudy.Resource__c);
                    break;
                }
            }
        }
        return resourcesIds;
    }

    protected override ResourceService.ResourceWrapperContainer getErrorNoObjectsToFilter() {
        return ResourceService.getErrorMissingStudy();
    }

    protected override Boolean isObjectsToFilterMissing() {
        return (resourceId == null && pState.value == ParticipantService.ParticipantStates.ALUMNI);
    }

    protected Id getCTPId() {
        if (ctpId == null && pState.ctp != null)
            ctpId = pState.ctp.Id;
        return ctpId;
    }
}