force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Study_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Study_Site_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Study Site Number</label>
    <length>255</length>
<!--    <trackHistory>true</trackHistory>-->
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravelVendor__c/TravelVendor__c.object-meta.xml
<CustomObject>
    <label>TravelVendor</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TravelVendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelVendorSettings__c/TravelVendorSettings__c.object-meta.xml
<CustomObject>
    <label>TravelVendorSettings</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>TravelVendorSettings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TravelVendorSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelVendorSettings__c/fields/isEnable__c.field-meta.xml
<CustomField>
    <fullName>isEnable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isEnable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TravelVendorSettings__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>TravelVendorSettings</relationshipLabel>
    <relationshipName>TravelVendorSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TravelVendorSettings__c/fields/TravelVendor__c.field-meta.xml
<CustomField>
    <fullName>TravelVendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TravelVendor</label>
    <referenceTo>TravelVendor__c</referenceTo>
    <relationshipLabel>TravelVendorSettings</relationshipLabel>
    <relationshipName>TravelVendorSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TravelSupportHelper.cls
/**
 * Created by Yehor Dobrovolskyi
 */
public without sharing class TravelSupportHelper {

    public List<TravelVendorPanelRemote.VendorItem> getVendorItems(List<String> countryCodes, Id ctpId,
            List<String> studySiteIds, List<TravelVendor__c> vendors) {
        DatabaseProxy databaseProxy = (DatabaseProxy) ClassFactory.newInstance(DatabaseProxy.class);
        String clauseChild = '';
        if (vendors != null && !vendors.isEmpty()) {
            Set<Id> venIds = new Map<Id, TravelVendor__c>(vendors).keySet();
            clauseChild = ' WHERE TravelVendor__c IN ' + '(\'' + String.join(new List<Id>(venIds), '\',\'') + '\')';
        }
        String query = 'SELECT Id, ' +
                'Name, ' +
                'Clinical_Trial_Profile__c, ' +
                'Site__r.BillingCountry, ' +
                'Site__r.BillingCountryCode, ' +
                'Study_Site_Number__c, ' +
                '(SELECT Id, isEnable__c, TravelVendor__r.Name, TravelVendor__r.Default_Country__c, TravelVendor__r.Link_Vendor__c FROM TravelVendorSettings__r' + (String.isBlank(clauseChild) ? '' : clauseChild) + ') ' +
                'FROM Study_Site__c ';
        String clause = ' WHERE Clinical_Trial_Profile__c = \'' + ctpId + '\' ';
        if (countryCodes != null && !countryCodes.isEmpty()) {
            clause += ' AND Site__r.BillingCountryCode IN ' + '(\'' + String.join(countryCodes, '\',\'') + '\')';
        }
        if (studySiteIds != null && !studySiteIds.isEmpty()) {
            clause += ' AND Id IN ' + '(\'' + String.join(studySiteIds, '\',\'') + '\')';
        }
        String order = ' ORDER BY Name';
        query += clause;
        query += order;
        System.debug(query);
        List<Study_Site__c> studySites = databaseProxy.query(query);
        List<TravelVendorPanelRemote.VendorItem> vendorItems = new List<TravelVendorPanelRemote.VendorItem>();
        for (Study_Site__c studySite : studySites) {
            TravelVendorPanelRemote.VendorItem vendorItem = new TravelVendorPanelRemote.VendorItem(studySite);
            if (studySite.TravelVendorSettings__r != null && !studySite.TravelVendorSettings__r.isEmpty()) {
                vendorItem.vendorSettings = studySite.TravelVendorSettings__r;
            }

            vendorItems.add(vendorItem);
        }
        return vendorItems;
    }

    public List<TravelVendor__c> getTravelVendorsByIds(List<Id> travelVendorIds) {
        DatabaseProxy databaseProxy = (DatabaseProxy) ClassFactory.newInstance(DatabaseProxy.class);
        String query = 'SELECT Id, ' +
                'Name, ' +
                'Link_Vendor__c ' +
                'FROM TravelVendor__c ';
        String clause = 'WHERE Id IN ' + '(\'' + String.join(travelVendorIds, '\',\'') + '\')';
        String order = ' ORDER BY Name';
        query += clause;
        query += order;
        List<TravelVendor__c> travelVendors = databaseProxy.query(query);
        return travelVendors;
    }

}