force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/Patient_Delegate_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate Enrollment</label>
    <nameField>
        <displayFormat>PDE-{00000}</displayFormat>
        <label>Patient Delegate Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegate Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Delegate Enrollments</relationshipLabel>
    <relationshipName>Patient_Delegate_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Primary_Delegate__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delegate__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This checkbox is to say if this delegate is a primary delegate on the study</inlineHelpText>
    <label>Primary Delegate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PpPastStudiesFilesController.cls
public with sharing class PpPastStudiesFilesController {
    public PpPastStudiesFilesController() {

    }
        @AuraEnabled                            
        public static pastStudyFileWrapper getData(Id contID, Boolean isDelegate){
                Set<id> perIDs= new Set<id>();
                Set<id> studyIDs= new Set<id>();
                String getUserContact=UserContext.getUserContactId();
                List<Patient_Delegate_Enrollment__c> pder = new List<Patient_Delegate_Enrollment__c> ();
                pastStudyFileWrapper wrap = new pastStudyFileWrapper();

                List<Participant_Enrollment__c> alumiPerList= [ SELECT id, Participant_Status__c ,
                                    Clinical_Trial_Profile__c, 
                                    Clinical_Trial_Profile__r.Study_Code_Name__c
                                    FROM Participant_Enrollment__c 
                                   WHERE Participant_Status__c IN: PEStatusState.PE_STATUS_GROUP_ALUMNI
                                   AND Participant_Contact__c =: contID LIMIT 10000];
                //logged in contact ka per alumi more thn 1 meaning ki multiple studies alumi hai.
                
                for( Participant_Enrollment__c per : alumiPerList){
                    perIDs.add(per.id);
                    studyIDs.add(per.Clinical_Trial_Profile__c);
                }
                if(isDelegate){
                     pder= [SELECT id, Participant_Enrollment__c FROM Patient_Delegate_Enrollment__c
                                        WHERE Participant_Enrollment__c IN : perIDs
                                        AND Participant_Enrollment__r.Participant_Contact__c =: contID 
                                        AND Primary_Delegate__c =TRUE 
                                         LIMIT 10000 ];
                }

                List<ContentDocumentLink> getFiles= 
                                    [SELECT id, ContentDocument.CreatedBy.name, 
                                    ContentDocument.FileType, ContentDocument.Title, 
                                    ContentDocument.CreatedDate from 
                                    ContentDocumentLink WHERE LinkedEntityId in: perIDs];

                wrap.fileList=getFiles;
                wrap.perList=alumiPerList;
                if(!pder.isEmpty()){
                    wrap.isPrimary=true;
                }
                //wrap.isPrimary=getFiles;
                return wrap;

        }
    
    public class pastStudyFileWrapper{
        @AuraEnabled
        public Boolean isPrimary =false;
        @AuraEnabled
        public List<ContentDocumentLink> fileList =new List<ContentDocumentLink>();
        @AuraEnabled
        public List<Clinical_Trial_Profile__c> alumiStudy =new List<Clinical_Trial_Profile__c>();
        @AuraEnabled
        public List<Participant_Enrollment__c> perList =new List<Participant_Enrollment__c>();

       
        
        
    }
}