force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/CommunityTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommunityTemplate__c</fullName>
    <label>Community Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>IQVIA Patient Portal</label>
            </value>
            <value>
                <fullName>GSK</fullName>
                <label>GSK Pan Oncology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/IQVIA_Outreach__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Outreach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Outreach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/MDM_Parent_Sponsor_Name__c.field-meta.xml
<CustomField>
    <fullName>MDM_Parent_Sponsor_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>MDM Parent Sponsor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/MDM_Sponsor_Name__c.field-meta.xml
<CustomField>
    <fullName>MDM_Sponsor_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>MDM Sponsor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
    <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
    <label>NCT Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/PPTemplate__c.field-meta.xml
<CustomField>
    <fullName>PPTemplate__c</fullName>
    <label>PP Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PP 1.0</fullName>
            </value>
            <value>
                <fullName>PP 2.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/UCPM_Sponsor_Org_Id__c.field-meta.xml
<CustomField>
    <fullName>UCPM_Sponsor_Org_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UCPM Sponsor Org Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/UCPM_Study_Purpose_Id__c.field-meta.xml
<CustomField>
    <fullName>UCPM_Study_Purpose_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UCPM Study Purpose Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IQVIA_Direct_Mail_Consent__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Direct_Mail_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Direct Mail Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Opt_In_Status_SMS__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Participant Opt In Status SMS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Phone_Opt_In_Permit_Phone__c.field-meta.xml
<CustomField>
    <fullName>Participant_Phone_Opt_In_Permit_Phone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt In Phone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PPM_ID__c.field-meta.xml
<CustomField>
    <fullName>PPM_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>IQVIA consents specific PPM ID captured at Contact level for Participants/Caregivers</inlineHelpText>
    <label>PPM ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Email</label>

    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/DataControllerOrg__c.field-meta.xml
<CustomField>
    <fullName>DataControllerOrg__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DataControllerOrg</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/IQVIA_Direct_Mail_Consent__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Direct_Mail_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Direct Mail Consent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <label>Mailing Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value on this field is place holder for IQVIA outreach consent for email which will later be copied on to contact fields</description>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Opt_In_Status_SMS__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value on this field is place holder for IQVIA outreach consent for email which will later be copied on to contact fields</description>
    <label>Opt In SMS/text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Phone_Opt_In_Permit_Phone__c.field-meta.xml
<CustomField>
    <fullName>Participant_Phone_Opt_In_Permit_Phone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value on this field is place holder for IQVIA outreach consent for email which will later be copied on to contact fields</description>
    <label>Opt In Phone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Permit_Mail_Email_contact_for_this_study__c.field-meta.xml
<CustomField>
    <fullName>Permit_Mail_Email_contact_for_this_study__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permit Mail-Email contact for this study</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source__c</fullName>
    <description>HCP/Physician Participant Referral Source</description>
    <inlineHelpText>HCP/Physician Participant Referral Source</inlineHelpText>
    <label>Referral Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>HCP Prescreen Log</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>ePR</fullName>
            </value>
            <value>
                <fullName>ACOE</fullName>
            </value>
            <value>
                <fullName>3rd_Party</fullName>
                <label>3rd Party</label>
            </value>
            <value>
                <fullName>Autocruitment</fullName>
            </value>
            <value>
                <fullName>23andMe</fullName>
            </value>
            <value>
                <fullName>IQVIA registry</fullName>
            </value>
            <value>
			 <fullName>Ciitizen</fullName>
                </value>
            <value>
                <fullName>MassiveBio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/Patient_Delegate__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate</label>
    <nameField>
        <displayFormat>PD-{00000000}</displayFormat>
        <label>Patient Delegate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/Patient_Delegate_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate Enrollment</label>
    <nameField>
        <displayFormat>PDE-{00000}</displayFormat>
        <label>Patient Delegate Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegate Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Delegate Enrollments</relationshipLabel>
    <relationshipName>Patient_Delegate_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/PPM_ID__c.field-meta.xml
<CustomField>
    <fullName>PPM_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Study+Participant consents specific PPM ID captured at PDE level only for Caregivers</inlineHelpText>
    <label>PPM ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/UCPM/classes/UCPM_ConsentPostBulkImport_Queueable.cls
public without sharing class UCPM_ConsentPostBulkImport_Queueable implements Queueable, Database.AllowsCallouts {
    String accessToken;
    List<Id> perRecIds;
    List<Id> pDelEnrolRecIds;
    String createtypeIdentity;
    String updatetypeIdentity;
    String createrequestJSON;
    String updaterequestJSON;
    String placeOfFunctionality;
    public UCPM_ConsentPostBulkImport_Queueable(List<Id> perIdList, List<Id> pderEnrolIds,String functionalityPlace) {
        perRecIds = perIdList != null ? perIdList : null;
        pDelEnrolRecIds = pderEnrolIds != null ? pderEnrolIds : null;
        placeOfFunctionality=functionalityPlace;
    }

    public void execute(QueueableContext context) {
        fetchPerAndPderDetails(perRecIds, pDelEnrolRecIds);
    }
    public void fetchPerAndPderDetails(List<Id> perIds, List<Id> pderIds) {
        List<Participant_Enrollment__c> perList;
        Map<Participant_Enrollment__c, List<Patient_Delegate_Enrollment__c>> perandPderMap = new Map<Participant_Enrollment__c, List<Patient_Delegate_Enrollment__c>>();
        if (pderIds != null && pderIds.size() > 0 && perIds != null && perIds.size() > 0) {
            perList = [
                SELECT
                    Id,
                    Participant__r.Email__c,
                    Participant__c,
                    Referral_Source__c,
                    DataControllerOrg__c,
                    Clinical_Trial_Profile__r.Study_Code_Name__c,
                    Clinical_Trial_Profile__r.NCT_Number__c,
                    Clinical_Trial_Profile__r.UCPM_Sponsor_Org_Id__c,
                    Clinical_Trial_Profile__r.UCPM_Study_Purpose_Id__c,
                    Clinical_Trial_Profile__r.MDM_Sponsor_Name__c,
                    Clinical_Trial_Profile__r.IQVIA_Outreach__c,
                    Clinical_Trial_Profile__r.MDM_Parent_Sponsor_Name__c,
                    Clinical_Trial_Profile__r.CommunityTemplate__c,
                    Clinical_Trial_Profile__r.PPTemplate__c,
                    Participant_Contact__r.IQVIA_Direct_Mail_Consent__c,
                    Participant_Contact__r.Participant_Opt_In_Status_Emails__c,
                    Participant_Contact__r.Participant_Opt_In_Status_SMS__c,
                    Participant_Contact__r.Participant_Phone_Opt_In_Permit_Phone__c,
                    Participant_Contact__r.PPM_ID__c,
                    Participant__r.Mailing_Country_Code__c,
                    Permit_Mail_Email_contact_for_this_study__c,
                    Permit_SMS_Text_for_this_study__c,
                    Permit_Voice_Text_contact_for_this_study__c,
                    Study_Direct_Mail_Consent__c,
                    PPMID__c,
                    (
                        SELECT
                            Id,
                            Patient_Delegate__c,
                            Patient_Delegate__r.Participant_Delegate__r.Mailing_Country_Code__c,
                            Patient_Delegate__r.Participant_Delegate__r.Id,
                            Patient_Delegate__r.Participant_Delegate__r.Email__c,
                            Patient_Delegate__r.Contact__r.Participant_Opt_In_Status_Emails__c,
                            Patient_Delegate__r.Contact__r.Participant_Opt_In_Status_SMS__c,
                            Patient_Delegate__r.Contact__r.Participant_Phone_Opt_In_Permit_Phone__c,
                            Patient_Delegate__r.Contact__r.IQVIA_Direct_Mail_Consent__c,
                            Study_Phone_Consent__c,
                            Study_Email_Consent__c,
                            Study_SMS_Consent__c,
                            Study_Direct_Mail_Consent__c,
                            Status__c,
                            PPM_ID__c,
                            Primary_Delegate__c,
                            Patient_Delegate__r.Contact__r.PPM_ID__c
                        FROM Patient_Delegate_Enrollments__r
                        WHERE ID IN :pderIds
                    )
                FROM Participant_Enrollment__c
                WHERE id IN :perIds
            ];
        } else if (
            perIds != null &&
            perIds.size() > 0 &&
            (pderIds == null ||
            pderIds.size() == 0)
        ) {
            perList = [
                SELECT
                    Id,
                    Participant__r.Email__c,
                    Participant__c,
                    Referral_Source__c,
                    DataControllerOrg__c,
                    Clinical_Trial_Profile__r.Study_Code_Name__c,
                    Clinical_Trial_Profile__r.NCT_Number__c,
                    Clinical_Trial_Profile__r.UCPM_Sponsor_Org_Id__c,
                    Clinical_Trial_Profile__r.UCPM_Study_Purpose_Id__c,
                    Clinical_Trial_Profile__r.MDM_Sponsor_Name__c,
                    Clinical_Trial_Profile__r.MDM_Parent_Sponsor_Name__c,
                    Clinical_Trial_Profile__r.IQVIA_Outreach__c,
                    Clinical_Trial_Profile__r.CommunityTemplate__c,
                    Clinical_Trial_Profile__r.PPTemplate__c,
                    Participant_Contact__r.IQVIA_Direct_Mail_Consent__c,
                    Participant_Contact__r.Participant_Opt_In_Status_Emails__c,
                    Participant_Contact__r.Participant_Opt_In_Status_SMS__c,
                    Participant_Contact__r.Participant_Phone_Opt_In_Permit_Phone__c,
                    Participant_Contact__r.PPM_ID__c,
                    Participant__r.Mailing_Country_Code__c,
                    Permit_Mail_Email_contact_for_this_study__c,
                    Permit_SMS_Text_for_this_study__c,
                    Permit_Voice_Text_contact_for_this_study__c,
                    Study_Direct_Mail_Consent__c,
                    PPMID__c
                FROM Participant_Enrollment__c
                WHERE id IN :perIds
            ];
        }

        Map<Participant_Enrollment__c, Id> mapPerAndCtpIds = new Map<Participant_Enrollment__c, Id>();
        if (!perList.isEmpty()) {
            for (Participant_Enrollment__c per : perList) {
                perandPderMap.put(per, per.Patient_Delegate_Enrollments__r);
                mapPerAndCtpIds.put(per, per.Clinical_Trial_Profile__c);
            }
        }
        Map<Id, List<Restricted_Source_Config__c>> mapCtpAndRestSources = new Map<Id, List<Restricted_Source_Config__c>>();

        for (Clinical_Trial_Profile__c ctp : [
            SELECT
                Id,
                IQVIA_Outreach__c,
                (
                    SELECT Id, Sponsor__c, Study__c, Referral_Resource__c
                    FROM Restricted_Source_Config__r
                )
            FROM Clinical_Trial_Profile__c
            WHERE Id IN :mapPerAndCtpIds.values()
        ]) {
            mapCtpAndRestSources.put(ctp.Id, ctp.Restricted_Source_Config__r);
        }
        Map<Id, Boolean> mapPerIdAndOutReach = new Map<Id, Boolean>();
        
    //Checking restricted resource and Iqvia Outreach validation
        for (Participant_Enrollment__c per : perList) {
            String referralSource;
            Boolean iqviaOutreach = false;
            String[] restrictedlst;
            if (per.Clinical_Trial_Profile__r.IQVIA_Outreach__c) {
                if (
                    per.Clinical_Trial_Profile__r.CommunityTemplate__c != 'PatientPortal' &&
                    (per.Clinical_Trial_Profile__r.CommunityTemplate__c != 'Janssen' ||
                    per.Clinical_Trial_Profile__r.PPTemplate__c != 'PP 2.0')
                ) {
                    iqviaOutreach = true;
                } else {
                    List<Restricted_Source_Config__c> restrictedRecrd = (mapCtpAndRestSources !=
                        null &&
                        mapCtpAndRestSources.get(per.Clinical_Trial_Profile__c) != null)
                        ? mapCtpAndRestSources.get(per.Clinical_Trial_Profile__c)
                        : null;
                    if (restrictedRecrd != null && !restrictedRecrd.isEmpty()) {
                        for (Restricted_Source_Config__c rsc : restrictedRecrd) {
                            restrictedlst = rsc.Referral_Resource__c != null
                                ? rsc.Referral_Resource__c.split(';')
                                : null;
                            if (restrictedlst != null && !restrictedlst.isEmpty()) {
                                referralSource = (per.Referral_Source__c == 'ePR' ||
                                    per.Referral_Source__c == 'ePRCampaign')
                                    ? per.Referral_Source__c + '-' + per.DataControllerOrg__c
                                    : per.Referral_Source__c;
                                if (restrictedlst.contains(referralSource)) {
                                    iqviaOutreach = false;
                                    break;
                                } else {
                                    iqviaOutreach = true;
                                }
                            }
                        }
                    } else {
                        iqviaOutreach = true;
                    }
                }
            } else {
                iqviaOutreach = false;
            }

            mapPerIdAndOutReach.put(per.Id, iqviaOutreach);
        }

        if (perList != null && perList.size() > 0) {
            for (Participant_Enrollment__c per : perList) {
                //New PER and new participant contact without delegate
                if (
                    per.PPMID__c == null &&
                    per.Participant_Contact__r.PPM_ID__c == null &&
                    perandPderMap.get(per).size() == 0
                ) {
                    createtypeIdentity = 'PARTICIPANT';
                    accessToken = UCPM_ConsentPostController.getAccessToken();
                    createrequestJSON = UCPM_ConsentPostController.requestJsonGeneration_Create(
                        per,
                        null,
                        mapPerIdAndOutReach.get(per.Id),
                        'Participant:ParticipantContact',
                        placeOfFunctionality
                    );
                    if (
                        String.isNotBlank(createrequestJSON) && String.isNotEmpty(createrequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoPostConsents(
                            createrequestJSON,
                            accessToken,
                            createtypeIdentity
                        );
                    }
                }
                //New PER,existing participant contact without delegate
                else if (
                    per.PPMID__c == null &&
                    per.Participant_Contact__r.PPM_ID__c != null &&
                    perandPderMap.get(per).size() == 0
                ) {
                    accessToken = UCPM_ConsentPostController.getAccessToken();
                    createtypeIdentity = 'PARTICIPANT';
                    updatetypeIdentity = 'PARTICIPANT';
                    createrequestJSON = UCPM_ConsentPostController.requestJsonGeneration_Create(
                        per,
                        null,
                        mapPerIdAndOutReach.get(per.Id),
                        'Participant',
                        placeOfFunctionality
                    );
                    updaterequestJSON = UCPM_ConsentPostController.requestJsonGeneration_update(
                        per,
                        null,
                        mapPerIdAndOutReach.get(per.Id),
                        'ParticipantContact',
                        placeOfFunctionality
                    );
                    if (
                        String.isNotBlank(createrequestJSON) && String.isNotEmpty(createrequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoPostConsents(
                            createrequestJSON,
                            accessToken,
                            createtypeIdentity
                        );
                    }
                    if (
                        String.isNotBlank(updaterequestJSON) && String.isNotEmpty(updaterequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoupdateConsents(
                            updaterequestJSON,
                            accessToken,
                            updatetypeIdentity
                        );
                    }
                }
                //New PER ,new participant contact,new delegate and new delegate contact
                else if (
                    per.PPMID__c == null &&
                    per.Participant_Contact__r.PPM_ID__c == null &&
                    perandPderMap.get(per) != null &&
                    perandPderMap.get(per).size() > 0 &&
                    perandPderMap.get(per)[0].PPM_ID__c == null &&
                    perandPderMap.get(per)[0].Patient_Delegate__r.Contact__r.PPM_ID__c == null
                ) {
                    accessToken = UCPM_ConsentPostController.getAccessToken();
                    createtypeIdentity = 'PARTICIPANT-DELEGATE';
                    createrequestJSON = UCPM_ConsentPostController.requestJsonGeneration_Create(
                        per,
                        perandPderMap.get(per),
                        mapPerIdAndOutReach.get(per.Id),
                        'Participant:ParticipantContact:Delegate:DelegateContact',
                        placeOfFunctionality
                    );
                    if (
                        String.isNotBlank(createrequestJSON) && String.isNotEmpty(createrequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoPostConsents(
                            createrequestJSON,
                            accessToken,
                            createtypeIdentity
                        );
                    }
                }
                //New PER,new participant contact,new delegate,existing delegate contact
                else if (
                    per.PPMID__c == null &&
                    per.Participant_Contact__r.PPM_ID__c == null &&
                    perandPderMap.get(per) != null &&
                    perandPderMap.get(per).size() > 0 &&
                    perandPderMap.get(per)[0].PPM_ID__c == null &&
                    perandPderMap.get(per)[0].Patient_Delegate__r.Contact__r.PPM_ID__c != null
                ) {
                    accessToken = UCPM_ConsentPostController.getAccessToken();
                    createtypeIdentity = 'PARTICIPANT-DELEGATE';
                    updatetypeIdentity = 'DELEGATE';
                    createrequestJSON = UCPM_ConsentPostController.requestJsonGeneration_Create(
                        per,
                        perandPderMap.get(per),
                        mapPerIdAndOutReach.get(per.Id),
                        'Participant:ParticipantContact:Delegate',
                        placeOfFunctionality
                    );

                    updaterequestJSON = UCPM_ConsentPostController.requestJsonGeneration_update(
                        per,
                        perandPderMap.get(per),
                        mapPerIdAndOutReach.get(per.Id),
                        'DelegateContact',
                        placeOfFunctionality
                    );
                    if (
                        String.isNotBlank(createrequestJSON) && String.isNotEmpty(createrequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoPostConsents(
                            createrequestJSON,
                            accessToken,
                            createtypeIdentity
                        );
                    }
                    if (
                        String.isNotBlank(updaterequestJSON) && String.isNotEmpty(updaterequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoupdateConsents(
                            updaterequestJSON,
                            accessToken,
                            updatetypeIdentity
                        );
                    }
                }
                //New PER,old participant contact,new delegate,new delegate contact
                else if (
                    per.PPMID__c == null &&
                    per.Participant_Contact__r.PPM_ID__c != null &&
                    perandPderMap.get(per) != null &&
                    perandPderMap.get(per).size() > 0 &&
                    perandPderMap.get(per)[0].PPM_ID__c == null &&
                    perandPderMap.get(per)[0].Patient_Delegate__r.Contact__r.PPM_ID__c == null
                ) {
                    accessToken = UCPM_ConsentPostController.getAccessToken();
                    createtypeIdentity = 'PARTICIPANT-DELEGATE';
                    updatetypeIdentity = 'PARTICIPANT';
                    createrequestJSON = UCPM_ConsentPostController.requestJsonGeneration_Create(
                        per,
                        perandPderMap.get(per),
                        mapPerIdAndOutReach.get(per.Id),
                        'Participant:Delegate:DelegateContact',
                        placeOfFunctionality
                        
                    );
                    updaterequestJSON = UCPM_ConsentPostController.requestJsonGeneration_update(
                        per,
                        null,
                        mapPerIdAndOutReach.get(per.Id),
                        'ParticipantContact',
                        placeOfFunctionality
                    );

                    if (
                        String.isNotBlank(createrequestJSON) && String.isNotEmpty(createrequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoPostConsents(
                            createrequestJSON,
                            accessToken,
                            createtypeIdentity
                        );
                    }
                    if (
                        String.isNotBlank(updaterequestJSON) && String.isNotEmpty(updaterequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoupdateConsents(
                            updaterequestJSON,
                            accessToken,
                            updatetypeIdentity
                        );
                    }
                }
                //New PER,old participant contact,new delegate,old delegate contact
                else if (
                    per.PPMID__c == null &&
                    per.Participant_Contact__r.PPM_ID__c != null &&
                    perandPderMap.get(per) != null &&
                    perandPderMap.get(per).size() > 0 &&
                    perandPderMap.get(per)[0].PPM_ID__c == null &&
                    perandPderMap.get(per)[0].Patient_Delegate__r.Contact__r.PPM_ID__c != null
                ) {
                    accessToken = UCPM_ConsentPostController.getAccessToken();
                    createtypeIdentity = 'PARTICIPANT-DELEGATE';
                    updatetypeIdentity = 'PARTICIPANT-DELEGATE';
                    createrequestJSON = UCPM_ConsentPostController.requestJsonGeneration_Create(
                        per,
                        perandPderMap.get(per),
                        mapPerIdAndOutReach.get(per.Id),
                        'Participant:Delegate',
                        placeOfFunctionality
                    );
                    updaterequestJSON = UCPM_ConsentPostController.requestJsonGeneration_update(
                        per,
                        perandPderMap.get(per),
                        mapPerIdAndOutReach.get(per.Id),
                        'ParticipantContact:DelegateContact',
                        placeOfFunctionality
                    );

                    if (
                        String.isNotBlank(createrequestJSON) && String.isNotEmpty(createrequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoPostConsents(
                            createrequestJSON,
                            accessToken,
                            createtypeIdentity
                        );
                    }
                    if (
                        String.isNotBlank(updaterequestJSON) && String.isNotEmpty(updaterequestJSON)
                    ) {
                        UCPM_ConsentPostController.callUCPMtoupdateConsents(
                            updaterequestJSON,
                            accessToken,
                            updatetypeIdentity
                        );
                    }
                }
            }
        }
    }
}