force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
    <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
    <label>NCT Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Patient_Portal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Patient_Portal_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Patient Portal Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <description>QI assigned unique ID for a study</description>
    <externalId>true</externalId>
    <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
    <label>Protocol ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Terms_And_Conditions_ID__c.field-meta.xml
<CustomField>
    <fullName>Terms_And_Conditions_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Terms And Conditions</label>
    <referenceTo>Terms_And_Conditions__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Adult__c.field-meta.xml
<CustomField>
    <fullName>Adult__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adult</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <label>Date of Birth</label>
    <length>10</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <label>Mailing Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State_Code__c</fullName>
    <label>Mailing State Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <formula>Clinical_Trial_Profile__r.Protocol_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Clinical Trial Profile&#39;s Protocol Id</inlineHelpText>
    <label>Protocol ID</label>

    <type>Text</type>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions__c/Terms_And_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms And Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms And Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Portal T&amp;C</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/visits/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>SDH Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/visits/objects/Visit__c/fields/Icons__c.field-meta.xml
<CustomField>
    <fullName>Icons__c</fullName>
    <label>Icons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>icon-blood-test</fullName>
                <label>Blood tests</label>
            </value>
            <value>
                <fullName>icon-brief-ph-ex</fullName>
                <label>Physical examination</label>
            </value>
            <value>
                <fullName>icon-ecg</fullName>
                <label>Electrocardiogram (ECG)</label>
            </value>
            <value>
                <fullName>icon-joint</fullName>
                <label>Joint assessment</label>
            </value>
            <value>
                <fullName>icon-lung-test</fullName>
                <label>Lung function test</label>
            </value>
            <value>
                <fullName>icon-lung-check</fullName>
                <label>Lung health check</label>
            </value>
            <value>
                <fullName>icon-pregnancy</fullName>
                <label>Pregnancy test</label>
            </value>
            <value>
                <fullName>icon-questionnaires</fullName>
                <label>Questionnaires</label>
            </value>
            <value>
                <fullName>icon-questions</fullName>
                <label>Questions about your health and medications</label>
            </value>
            <value>
                <fullName>icon-vital-signs</fullName>
                <label>Vital signs</label>
            </value>
            <value>
                <fullName>icon-urine-tests</fullName>
                <label>Urine tests</label>
            </value>
            <value>
                <fullName>icon-receive-study-medication-injection</fullName>
                <label>Receive study medication injection</label>
            </value>
            <value>
                <fullName>icon-receive-study-medication-capsules</fullName>
                <label>Receive study medication capsules</label>
            </value>
            <value>
                <fullName>icon-fasting</fullName>
                <label>Fasting</label>
            </value>
            <value>
                <fullName>icon-hands-and-feet-x-rays</fullName>
                <label>Hands and feet X-rays</label>
            </value>
            <value>
                <fullName>icon-chest-x-rays</fullName>
                <label>Chest X-rays</label>
            </value>
            <value>
                <fullName>icon-no-study-visit</fullName>
                <label>No study visit if you take part in contRAst-X</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Visit_Schedule__c</fullName>
    <label>Patient Portal Schedule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Plan__c/Visit_Plan__c.object-meta.xml
<CustomObject>
    <label>Visit Plan</label>
    <nameField>
        <label>Visit Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Visit Plans</relationshipLabel>
    <relationshipName>Visit_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/tests/classes/Test_ParticipantService.cls
/**
 * Created by Leonid Bartenev
 */

@IsTest
public class Test_ParticipantService {

    public class ParticipantEnrollmentServiceMock implements StubProvider {

        String participant_Status;

        public ParticipantEnrollmentServiceMock() {
        }

        public ParticipantEnrollmentServiceMock(String participant_Status) {
            this.participant_Status = participant_Status;
        }

        public Object handleMethodCall(Object stubbedObject, String stubbedMethodName, Type returnType,
                List<Type> listOfParamTypes, List<String> listOfParamNames, List<Object> listOfArgs) {
            if (stubbedMethodName == 'getPEnrolmentsCommonCustomFieldsImpl') {
                return new List<Participant_Enrollment__c>{
                        getPE(participant_Status)
                };
            }
            return null;
        }
    }

    public class PatientDelegateServiceMock implements StubProvider {
        public Object handleMethodCall(Object stubbedObject, String stubbedMethodName, Type returnType,
                List<Type> listOfParamTypes, List<String> listOfParamNames, List<Object> listOfArgs) {
            if (stubbedMethodName == 'isDelegate') {
                return false;
            }
            return null;
        }
    }

    public class CommunityServiceMock implements StubProvider {
        public Object handleMethodCall(Object stubbedObject, String stubbedMethodName, Type returnType,
                List<Type> listOfParamTypes, List<String> listOfParamNames, List<Object> listOfArgs) {
            if (stubbedMethodName == 'getCurrentContactId') {
                return TestDataFactory.getFakeId(Contact.getSObjectType());
            }
            if (stubbedMethodName == 'getUserContactImpl') {
                String c = '{"attributes":{"type":"Contact"},"FirstName":"TestF","LastName":"TestL","Name":"TestF TestL"}';
                return (Contact) JSON.deserialize(c, Contact.class);
            }
            return null;
        }
    }

    public class DatabaseServiceMock implements StubProvider {
        public Object handleMethodCall(Object stubbedObject, String stubbedMethodName, Type returnType,
                List<Type> listOfParamTypes, List<String> listOfParamNames, List<Object> listOfArgs) {
            if (stubbedMethodName == 'insertSObjImpl') {
                return (Database.SaveResult)
                        JSON.deserialize('{"id":"0030v00000Dcyq3AAB","success":true,"errors":[]}', Database.SaveResult.class);
            }
            if (stubbedMethodName == 'upsertToDB') {
            }
            if (stubbedMethodName == 'queryImpl' && listOfArgs.size() > 1) {
                SObjectType sObjectType = (SObjectType) listOfArgs[1];
                if (sObjectType == Visit__c.getSObjectType()) {
                    return new Visit__c(Name = 'TestVisit', Visit_Schedule__c = 'Week 1', Icons__c = '');
                } else if (SObjectType == Account.getSObjectType()) {
                    return new List<Account>{
                            new Account(Id = TestDataFactory.getFakeId(Account.getSObjectType()))
                    };
                }
            }
            return null;
        }
    }
    public class ParticipantServiceMock implements System.StubProvider {

        public Object handleMethodCall(Object stubbedObject, String stubbedMethodName, Type returnType,
                List<Type> listOfParamTypes, List<String> listOfParamNames, List<Object> listOfArgs) {
            if (stubbedMethodName == 'getState') {
                return new ParticipantService.ParticipantState();
            }
            return null;
        }
    }

    @IsTest
    static void participantServiceTest() {
        // Set mocks:
        ParticipantEnrollmentService.setMock(new ParticipantEnrollmentServiceMock());
        CommunityService.setMock(new CommunityServiceMock());
        ParticipantService.setMock(new ParticipantServiceMock());
        // Test logic
        Test.startTest();
        ParticipantService.getParticipantState();
        ParticipantService.getInstance().getState();
        try {
            ParticipantService.getParticipantFullName(getPE(null).Participant__r.Contact__c);
        } catch (ParticipantService.ParticipantServiceException e) {}
        Test.stopTest();
    }

    @IsTest
    static void participantServiceGROUP_FAILEDTest() {
        // Set mocks:
        ParticipantEnrollmentService.setMock(new ParticipantEnrollmentServiceMock(PEStatusState.PE_STATUS_ENROLLMENT_FAILED));
        CommunityService.setMock(new CommunityServiceMock());
        ParticipantService.setMock(new ParticipantServiceMock());
        // Test logic
        Test.startTest();
        ParticipantService.getInstance().getState();
        Test.stopTest();
    }

    @IsTest
    static void participantServiceENROLLMENT_SUCCESSTest() {
        // Set mocks:
        ParticipantEnrollmentService.setMock(new ParticipantEnrollmentServiceMock(PEStatusState.PE_STATUS_ENROLLMENT_SUCCESS));
        CommunityService.setMock(new CommunityServiceMock());
        ParticipantService.setMock(new ParticipantServiceMock());
        // Test logic
        Test.startTest();
        ParticipantService.getInstance().getState();
        Test.stopTest();
    }

    @IsTest
    static void showTermsTest() {
        // Set mocks:
        ParticipantEnrollmentService.setMock(new ParticipantEnrollmentServiceMock());
        CommunityService.setMock(new CommunityServiceMock());
        ParticipantService.setMock(new ParticipantServiceMock());
        Test.startTest();
        ParticipantService.ParticipantState participantState = ParticipantService.getInstance().getState();
        Boolean showTerms = participantState.showTerms;
        Test.stopTest();

        System.assertEquals(false, showTerms);
    }

    @IsTest
    static void showVisitsTest() {
        // Set mocks:
        ParticipantEnrollmentService.setMock(new ParticipantEnrollmentServiceMock());
        CommunityService.setMock(new CommunityServiceMock());
        ParticipantService.setMock(new ParticipantServiceMock());
        Test.startTest();
        ParticipantService.ParticipantState participantState = ParticipantService.getInstance().getState();
        participantState.ctp = getPE(null).Clinical_Trial_Profile__r;
        Boolean isShow = participantState.showVisits;
        Test.stopTest();

        System.assertEquals(false, isShow);
    }

    @IsTest
    static void createParticipantAndUpdatePEImplTest() {
        // Set mocks:
        ParticipantEnrollmentService.setMock(new ParticipantEnrollmentServiceMock());
        CommunityService.setMock(new CommunityServiceMock());
        DatabaseService.setMock(new DatabaseServiceMock());
        ParticipantService.setMock(new ParticipantServiceMock());
        String language = 'ru';
        Test.startTest();
        ParticipantService.createParticipantAndUpdatePE(getParticipant(), getParticipantDelegate(), getPE(null), language);
        Test.stopTest();
    }

    @IsTest
    static void getGenderLVListTest() {
        List<LabelValueItem> genderLVList = ParticipantService.getGenderLVList();
        System.assertEquals(2, genderLVList.size());
        System.assertEquals(Label.Gender_Male, genderLVList.get(0).label);
        System.assertEquals('Female', genderLVList.get(1).value);
    }

    @IsTest
    static void isParticipantsAgeOfMajorityTest() {
        System.debug(JSON.serializePretty(ParticipantService.checkParticipantsAgeOfMajority(new List<Participant__c>{new Participant__c(
                Last_Name__c = 'Participant',
                Date_of_Birth__c = '2002-03-10',
                Mailing_Country_Code__c = 'US',
                Mailing_State_Code__c = 'MS',
                Adult__c = true
        ),
                new Participant__c(
                Last_Name__c = 'Participant',
                Date_of_Birth__c = '2000-03-10',
                Mailing_Country_Code__c = 'US',
                Mailing_State_Code__c = 'AL',
                Adult__c = false
                )
        })));
    }

    //Mock data: -------------------------------------------------------------------------------------------------------
    static Participant_Enrollment__c getPE(String partStatus) {
        if (partStatus == null) partStatus = PEStatusState.PE_STATUS_REFERRAL_DECLINED;

        Terms_And_Conditions__c tc = new Terms_And_Conditions__c(Active__c = false);

        Clinical_Trial_Profile__c trial = new Clinical_Trial_Profile__c(
                Id = TestDataFactory.getFakeId(Clinical_Trial_Profile__c.getSObjectType()),
                Protocol_ID__c = 'Prot-333',
                NCT_Number__c = 'NCT02804789',
                Therapeutic_Area__r = new Therapeutic_Area__c(Name = 'Test Area'),
                Patient_Portal_Enabled__c = true,
                Terms_And_Conditions_ID__r = tc,
                Visit_Plan__c = TestDataFactory.getFakeId(Visit_Plan__c.getSObjectType())
        );

        Contact patientContact = new Contact(
                FirstName = 'Richard',
                LastName = 'Wilson',
                Email = 'r.wilson@gmail.com',
                userCommunityMode__c = 'Participant'
        );

        Participant__c participant = new Participant__c(
                Id = TestDataFactory.getFakeId(Participant__c.getSObjectType()),
                First_Name__c = patientContact.FirstName,
                Contact__r = patientContact
        );

        Contact pi = new Contact(
                FirstName = 'Joseph',
                LastName = 'Davis PI And HCP',
                Email = 'jdavis@somemail.com'
        );

        Study_Site__c studySite = new Study_Site__c(
                Name = 'Test SS1',
                Clinical_Trial_Profile__c = trial.Id,
                Clinical_Trial_Profile__r = trial,
                Site__r = new Account(Name = 'Clinic'),
                Principal_Investigator__r = pi,
                Override_PI_Referral_Status__c = StudySiteService.PI_S_INVITATION_SENT,
                Study_Site_Key__c = '12132123132313',
                Study_Site_Phone__c = '+1(232) 222-3434'
        );

        return new Participant_Enrollment__c(
                Participant_Status__c = partStatus,
                Participant__c = participant.Id,
                Participant__r = participant,
                Clinical_Trial_Profile__c = trial.Id,
                Clinical_Trial_Profile__r = trial,
                Study_Site__r = studySite,
                Study_Site__c = TestDataFactory.getFakeId(Study_Site__c.getSObjectType())
        );
    }

    static Participant__c getParticipant() {
        Contact patientContact = new Contact(
                FirstName = 'Ashly',
                LastName = 'Doyle',
                Email = 'a.doyle@gmail.com',
                userCommunityMode__c = 'Participant'
        );

        return new Participant__c(
                First_Name__c = patientContact.FirstName
        );
    }

    static Participant__c getParticipantDelegate() {
        Contact patientContact = new Contact(
                FirstName = 'Ashly',
                LastName = 'DoyleDelegate',
                Email = 'a.doyledelegate@gmail.com',
                userCommunityMode__c = 'Participant'
        );

        return new Participant__c(
                First_Name__c = patientContact.FirstName
        );
    }

}