force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UserCommunityIsDelegate__c.field-meta.xml
<CustomField>
    <fullName>UserCommunityIsDelegate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Community Is Delegate</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunytyType__c.field-meta.xml
<CustomField>
    <fullName>userCommunytyType__c</fullName>
    <description>User types for community - HCP / PI / Participant</description>
    <inlineHelpText>Select user types for community</inlineHelpText>
    <label>User Community Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/user-communications/objects/Conversation__c/Conversation__c.object-meta.xml
<CustomObject>
    <label>Conversation</label>
    <nameField>
        <displayFormat>CNV-{0000000}</displayFormat>
        <label>Conversation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conversations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/user-communications/objects/Conversation__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Conversations</relationshipLabel>
    <relationshipName>Conversations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/BMI__c.field-meta.xml
<CustomField>
    <fullName>BMI__c</fullName>
    <label>BMI</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Participant&#39;s First Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s First Name</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/HighRisk_Indicator__c.field-meta.xml
<CustomField>
    <fullName>HighRisk_Indicator__c</fullName>
    <label>HighRisk Indicator</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Participant&#39;s Last Name can be removed from layout for PI compliance purposes</description>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>Participant&#39;s Last Name</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Comorbidities__c.field-meta.xml
<CustomField>
    <fullName>Comorbidities__c</fullName>
    <label>Comorbidities</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/High_Priority__c.field-meta.xml
<CustomField>
    <fullName>High_Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <label>High Priority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/HighRisk_Indicator__c.field-meta.xml
<CustomField>
    <fullName>HighRisk_Indicator__c</fullName>
    <label>HighRisk Indicator</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source__c</fullName>
    <description>HCP/Physician Participant Referral Source</description>
    <inlineHelpText>HCP/Physician Participant Referral Source</inlineHelpText>
    <label>Referral Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>HCP Prescreen Log</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>ePR</fullName>
            </value>
            <value>
                <fullName>ACOE</fullName>
            </value>
            <value>
                <fullName>3rd_Party</fullName>
                <label>3rd Party</label>
            </value>
            <value>
                <fullName>Autocruitment</fullName>
            </value>
            <value>
                <fullName>23andMe</fullName>
            </value>
            <value>
                <fullName>IQVIA registry</fullName>
            </value>
            <value>
			 <fullName>Ciitizen</fullName>
                </value>
            <value>
                <fullName>MassiveBio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/Patient_Delegate__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate</label>
    <nameField>
        <displayFormat>PD-{00000000}</displayFormat>
        <label>Patient Delegate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/fields/Primary_Delegate__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delegate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Delegate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/Patient_Delegate_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate Enrollment</label>
    <nameField>
        <displayFormat>PDE-{00000}</displayFormat>
        <label>Patient Delegate Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegate Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Delegate Enrollments</relationshipLabel>
    <relationshipName>Patient_Delegate_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Patient_Delegate__c.field-meta.xml
<CustomField>
    <fullName>Patient_Delegate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Associated Patient Delegate Record of the delegate</inlineHelpText>
    <label>Patient Delegate</label>
    <referenceTo>Patient_Delegate__c</referenceTo>
    <relationshipLabel>Patient Delegate Enrollments</relationshipLabel>
    <relationshipName>Patient_Delegate_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Primary_Delegate__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delegate__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This checkbox is to say if this delegate is a primary delegate on the study</inlineHelpText>
    <label>Primary Delegate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ppFileUploadControllerTest.cls
@isTest
public class ppFileUploadControllerTest {
    @TestSetup
    static void init(){
        TestData.loadTestData(); 
    }
    @isTest
    static void saveTheChunkFileTest() {
        TestData testData = new TestData();
        user u = [select id,contactid from user where LastName = 'HCPTD' ];
       
        test.startTest();
        string fId = ppFileUploadController.saveTheChunkFile(u.ContactId, 'Test.pdf', EncodingUtil.base64Encode(blob.valueOf('File test data')) , '.pdf', '','',true,false,'99',true); 
        
        ppFileUploadController.saveTheChunkFile(u.ContactId, 'Testttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuggggggggggggggggggggggggggggggggggggg.pdf', EncodingUtil.base64Encode(blob.valueOf('File test data')) , 'pdf', '','',false,false,'99',false);
        ppFileUploadController.saveTheChunkFile(u.ContactId, 'Test.pdf', EncodingUtil.base64Encode(blob.valueOf('File test data')) , 'pdf', '','',true,false,'99',false);
        ppFileUploadController.fetchUploadedFiles(testData.pe.Id, 1, true , 'CreatedDate', 'ASC',false,true);
        
        ppFileUploadController.fetchFiles(u.ContactId);
        string fIdn = nonReferedBulkUpload.saveTheChunkFile(u.ContactId, 'Test.xlsx', EncodingUtil.base64Encode(blob.valueOf('File test data')) , '.xlsx', ''); 
         ContentVersion contentVersionInsert = new ContentVersion(
             Title = 'Test File',
            PathOnClient = 'testFile.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
              
        );
        Insert contentVersionInsert;
		Id newId = Id.valueOf(fIdn);
        ContentDistribution cdist = new ContentDistribution(
                                        Name = contentVersionInsert.Title,
                                        ContentVersionId = newId
                                        );
        insert cdist;
        ppFileUploadController.saveTheChunkFile(u.ContactId, 'Test.pdf', EncodingUtil.base64Encode(blob.valueOf('File test data')) , 'pdf', fIdn,'',false,false,'99',false);
        ppFileUploadController.saveTheChunkFile(u.ContactId, 'Test.pdf', EncodingUtil.base64Encode(blob.valueOf('File test data')) , 'pdf', fIdn,'',false,true,'99',false);
        Test.stopTest();
    }
    @isTest
    static void checkifPrimaryTest() {
        TestData testData = new TestData();
        test.startTest();
         Contact delegate = new Contact(
            FirstName = 'Patient',
            LastName = 'Delegate',
            Email = 'jsmith@somemail.com',
          
            userCommunityMode__c = CommunityService.USER_MODE_PARTICIPANT,
            userCommunytyType__c = CommunityService.USER_MODE_PARTICIPANT,
            UserCommunityIsDelegate__c = true
        );
        insert delegate;
        
        Participant__c p = new Participant__c(
            First_Name__c = 'Patient',
            Last_Name__c = 'Delegate',
            Contact__c = delegate.Id
        );
        insert p;

        Patient_Delegate__c patientDelegate = new Patient_Delegate__c(
            Contact__c = delegate.Id,
            Contact__r = delegate,
            Participant__c = p.Id,
            Participant__r = p
        );
        insert patientDelegate;
 
        
        Patient_Delegate_Enrollment__c pde = new Patient_Delegate_Enrollment__c();
        pde.Participant_Enrollment__c = testData.pe.Id;
        pde.Patient_Delegate__c = patientDelegate.Id;
        pde.Primary_Delegate__c = true;
        pde.Status__c = 'Active';
        Insert pde;
        
        ppFileUploadController.checkifPrimary(testData.pe.Id,delegate.Id);
        Test.stopTest();
    }
     @isTest
    static void fetchUploadedFilesTest() {
        TestData testData = new TestData();
        user u = [select id,contactid from user where LastName = 'HCPTD' ];
        
        Profile profile_1 = [
            SELECT Id
            FROM Profile
            WHERE Name = 'IQVIA Customer Community Plus Login User'
            LIMIT 1
        ];
        
        List<Participant_Enrollment__c> objpart = [SELECT Id,Participant__r.BMI__c,Comorbidities__c,HighRisk_Indicator__c,High_Priority__c,Referral_Source__c,Participant__c
        ,Clinical_Trial_Profile__r.Medical_Vendor_is_Available__c,Study_Site__c,Unique_HumanId__c,MRR_Survey_Results_URL__c FROM Participant_Enrollment__c ];
        
         List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
          List<ContentDocumentLink> contentDocList = new List<ContentDocumentLink>();
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = objpart[0].Participant__c;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        cdl.Visibility = 'AllUsers';
        contentDocList.add(cdl);

        insert contentDocList;
        
        List<string> cv= new List<string>();
        Set<id> cd= new Set<id>();
        cd.add(documents[0].id);
        ContentVersion contentVersionInsert = new ContentVersion(
             Title = 'Test File',
            PathOnClient = 'testFile.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
              
        );
        Insert contentVersionInsert;
      
        cv.add(contentVersionInsert.id);
       Conversation__c conversation = new Conversation__c(
            Participant_Enrollment__c = testData.pe.Id
        );
        insert conversation;
        insert ConversationService.createConversationSharesForUser(
            new List<Id>{ conversation.Id },
            testData.participantUser.Id
        );
        insert new Message__c(
            Conversation__c = conversation.Id,
            Message_Content__c = 'Why???',
            Sender_Name__c = 'Morgan Stark'
        ); 
    
        test.startTest();
       
                              
        try{
             ppFileUploadController.fetchUploadedFiles(testData.pe.Id, 1, true , 'CreatedDate', 'ASC',true,true);
        System.runAs(testData.participantUser) {
        ppFileUploadController.fetchMessageFiles(testData.pe.Id, 1, 'CreatedDate', 'ASC',true,true);
        }
        ppFileUploadController.isUplaodAvailable(testData.pe.Id);
        ppFileUploadController.deleteFilewithlist(cv,testData.pe.Id);
        ppFileUploadController.DeleteAlldraftFiles(testData.pe.Id);
        ppFileUploadController.deleteFile(contentVersionInsert.id);
       
        }
        catch(Exception ex) {System.assertEquals(ex.getMessage(),'Script-thrown exception' );}
        string fId = ppFileUploadController.saveTheChunkFile(u.ContactId, 'Testttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuggggggggggggggggggggggggggggggggggggg.pdf', EncodingUtil.base64Encode(blob.valueOf('File test data')) , '.pdf', '','',true,false,'99',true); 
        

        Test.stopTest();
    }
    @isTest
    static void fetchUploadedFilesTest12() {
        TestData testData = new TestData();
        user u = [select id,contactid from user where LastName = 'HCPTD' ];
        
        Profile profile_1 = [
            SELECT Id
            FROM Profile
            WHERE Name = 'IQVIA Customer Community Plus Login User'
            LIMIT 1
        ];
        
        List<Participant_Enrollment__c> objpart = [SELECT Id,Participant__r.BMI__c,Comorbidities__c,HighRisk_Indicator__c,High_Priority__c,Referral_Source__c,Participant__c
        ,Clinical_Trial_Profile__r.Medical_Vendor_is_Available__c,Study_Site__c,Unique_HumanId__c,MRR_Survey_Results_URL__c FROM Participant_Enrollment__c ];
        
         List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
          List<ContentDocumentLink> contentDocList = new List<ContentDocumentLink>();
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = objpart[0].Participant__c;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        cdl.Visibility = 'AllUsers';
        contentDocList.add(cdl);

        insert contentDocList;
        
        List<string> cv= new List<string>();
        Set<id> cd= new Set<id>();
        cd.add(documents[0].id);
        ContentVersion contentVersionInsert = new ContentVersion(
             Title = 'Test File',
            PathOnClient = 'testFile.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
              
        );
        Insert contentVersionInsert;
      
        cv.add(contentVersionInsert.id);
       Conversation__c conversation = new Conversation__c(
            Participant_Enrollment__c = testData.pe.Id
        );
        insert conversation;
        insert ConversationService.createConversationSharesForUser(
            new List<Id>{ conversation.Id },
            testData.participantUser.Id
        );
        insert new Message__c(
            Conversation__c = conversation.Id,
            Message_Content__c = 'Why???',
            Sender_Name__c = 'Morgan Stark'
        );
        test.startTest(); 
        try{
             ppFileUploadController.fetchUploadedFiles(testData.pe.Id, 1, true , 'CreatedDate', 'ASC',false,true);
        System.runAs(testData.participantUser) {
        ppFileUploadController.fetchMessageFiles(testData.pe.Id, 1, 'ContentDocument.CreatedDate', 'ASC',false,true);
        }
        ppFileUploadController.isUplaodAvailable(testData.pe.Id);
        ppFileUploadController.deleteFilewithlist(cv,testData.pe.Id);
        ppFileUploadController.DeleteAlldraftFiles(testData.pe.Id);
        ppFileUploadController.deleteFile(contentVersionInsert.id);
         
        }
        catch(Exception ex) {System.assertEquals(ex.getMessage(),'Script-thrown exception' );}
        string fId = ppFileUploadController.saveTheChunkFile(u.ContactId, 'Testttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuggggggggggggggggggggggggggggggggggggg.pdf', EncodingUtil.base64Encode(blob.valueOf('File test data')) , '.pdf', '','',true,false,'99',true); 
        

        Test.stopTest();
    }
    @isTest
    static void isUplaodAvailableTest() {
        TestData testData = new TestData();
        user u = [select id,contactid from user where LastName = 'HCPTD' ];
        
         List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
          List<ContentDocumentLink> contentDocList = new List<ContentDocumentLink>();
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = testData.pe.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        cdl.Visibility = 'AllUsers';
        contentDocList.add(cdl);
        
        insert contentDocList;
        
        List<string> cv= new List<string>();
        Set<id> cd= new Set<id>();
        cd.add(documents[0].id);
        ContentVersion contentVersionInsert = new ContentVersion(
            Title = 'Test.pdf',
            PathOnClient = 'Test.pdf',
            VersionData = Blob.valueOf('Test Content Data'),
            IsMajorVersion = true,
            ContentDocumentId=documents[0].id,
            FileStatus__c='Draft'
              
        );
        Insert contentVersionInsert;
      
        cv.add(contentVersionInsert.id);
        
        test.startTest();
        ppFileUploadController.isUplaodAvailable(testData.pe.Id);

        Test.stopTest();
    }
    @isTest
    static void testUploadFiles() {
        TestData testData = new TestData();
        user u = [select id,contactid from user where LastName = 'HCPTD' ];
        Profile profile_1 = [
            SELECT Id
            FROM Profile
            WHERE Name = 'IQVIA Customer Community Plus Login User'
            LIMIT 1
        ];
        List<Participant_Enrollment__c> objpart = [SELECT Id,Participant__r.BMI__c,Comorbidities__c,HighRisk_Indicator__c,High_Priority__c,Referral_Source__c,Participant__c
        ,Clinical_Trial_Profile__r.Medical_Vendor_is_Available__c,Study_Site__c,Unique_HumanId__c,MRR_Survey_Results_URL__c FROM Participant_Enrollment__c ];
        
         List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
          List<ContentDocumentLink> contentDocList = new List<ContentDocumentLink>();
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = objpart[0].Participant__c;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        cdl.Visibility = 'AllUsers';
        contentDocList.add(cdl);

        insert contentDocList;
        
        List<string> cv= new List<string>();
        Set<id> cd= new Set<id>();
        cd.add(documents[0].id);
        ContentVersion contentVersionInsert = new ContentVersion(
             Title = 'Test File',
            PathOnClient = 'testFile.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
              
        );
        Insert contentVersionInsert;
      
        cv.add(contentVersionInsert.id);
        
       
        List<ppFileUploadcontroller.uploadFileWrapper> testWrapperList = new List<ppFileUploadcontroller.uploadFileWrapper>();
        ppFileUploadcontroller.uploadFileWrapper objWrapper = new ppFileUploadcontroller.uploadFileWrapper();
        
        objWrapper.fileContentVerId = contentVersionInsert.Id;
        objWrapper.isDeleted = false;
        objWrapper.error = false;
        objWrapper.fileName = 'Test File';
        objWrapper.index = 0;
        testWrapperList.add(objWrapper);
       
        
       
        String strFileData = JSON.serialize(testWrapperList);
        
       
        Test.startTest();
        ppFileUploadcontroller.uploadFiles(strFileData,testData.pe.Id);
        ppFileUploadController.fetchMessageFiles(testData.pe.Id, 1, 'CreatedDate', 'ASC',true,true);
        Test.stopTest();
        
        
    }
    }