force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Override_Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_Recruitment_Status__c</fullName>
    <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
    <label>Override Recruitment Status</label>

    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actively Enrolling</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>No_Longer_Enrolling</fullName>
                <label>No Longer Enrolling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrialSearchWhereClauseFactory.cls
/**
 * Created by Vitalii Aheienko on 9/13/2019.
 * Updated by Sravani Dasari on 5/14/2020 
 */

public with sharing class TrialSearchWhereClauseFactory {

    //ORS status
    public static final String ACTIVELY_ENROLLING = 'Actively Enrolling';
    public static final String ON_HOLD = 'On Hold';

    //CTMS status
    public static final String ENROLLING = 'Enrolling';
    public static final String OPEN_TO_ENROLLMENT = 'Open to Enrollment';
    public static final String PLANNING = 'Planning';
    public static final String IN_DEVELOPMENT = 'In Development';

    public static final List<String> ORS_STATUS_ENROLLING = new List<String>{
            ACTIVELY_ENROLLING,
            ON_HOLD
    };

    public static final List<String> CTMS_RECRUITMENT = new List<String>{
            ENROLLING,
            OPEN_TO_ENROLLMENT,
            PLANNING,
            IN_DEVELOPMENT
    };

    public static final List<String> CTMS_RECRUITMENT_ENROLLING = new List<String>{
            ENROLLING,
            OPEN_TO_ENROLLMENT
    };

    public static final List<String> CTMS_ON_HOLD = new List<String>{
            PLANNING,
            IN_DEVELOPMENT
    };


    public WhereClause getInstance(List<Id> taIds, Boolean isEnrolling, Boolean isNotYetEnrolling, Set<Id> userQCareSSIds) {
        WhereClause idFilteredClause = new IdFilteredWhereClause(taIds);
        WhereClause enrolledIdFilteredClause = this.getEnrollingExtendedWhereClause(idFilteredClause, isEnrolling, isNotYetEnrolling);
        if (userQCareSSIds != null && !userQCareSSIds.isEmpty()) {
            WhereClause qCareEnrolledidFilteredClause = new QCareWhereClauseDecorator(enrolledIdFilteredClause, userQCareSSIds);
            return qCareEnrolledidFilteredClause;
        }

        return enrolledIdFilteredClause;
    }
    // Added by Sravani Dasari for Trial Match PEH-2031
    public WhereClause getInstance(List<Id> taIds, String objfield, Boolean isEnrolling, Boolean isNotYetEnrolling, Set<Id> userQCareSSIds) {
        WhereClause idFilteredClause = new IdFilteredWhereClause(taIds,objfield);
        WhereClause enrolledIdFilteredClause = this.getEnrollingExtendedWhereClause(idFilteredClause, isEnrolling, isNotYetEnrolling);
        if (userQCareSSIds != null && !userQCareSSIds.isEmpty()) {
            WhereClause qCareEnrolledidFilteredClause = new QCareWhereClauseDecorator(enrolledIdFilteredClause, userQCareSSIds);
            return qCareEnrolledidFilteredClause;
        }

        return enrolledIdFilteredClause;
    }
	//Ended by Sravani Dasari
    private WhereClause getEnrollingExtendedWhereClause(WhereClause clause, Boolean isEnrolling, Boolean isNotYetEnrolling) {
        if (isEnrolling && isNotYetEnrolling) {
            return new EnrollingNotEnrollingWhereClauseDecorator(clause);
        } else if (isEnrolling) {
            return new EnrollingWhereClauseDecorator(clause);
        } else if (isNotYetEnrolling) {
            return new NotEnrollingWhereClauseDecorator(clause);
        }
        return new WhereClauseDecorator(clause);
    }


    public interface WhereClause {
        String getWhereClause();
    }

    public virtual class WhereClauseDecorator implements WhereClause {
        private WhereClause clause;

        public WhereClauseDecorator(WhereClause clause) {
            this.clause = clause;
        }

        public virtual String getWhereClause() {
            return clause != null ? clause.getWhereClause() : '';
        }
    }

    public class IdFilteredWhereClause implements WhereClause {

        List<Id> taIds;
		String whereField; // Added by Sravani Dasari for Trial Match PEH-2031
        
        public IdFilteredWhereClause(List<Id> taIds) {
            this.taIds = taIds;
            whereField = 'Therapeutic_Area__c';
        }
		// Added by Sravani Dasari for Trial Match PEH-2031
        public IdFilteredWhereClause(List<Id> taIds, String objType) {
            this.taIds = taIds;
			if(objType!=null)
			 whereField= objType;
		}
        //Ended by Sravani
        public String getWhereClause() {
            Boolean emptyTaIds = taIds == null || taIds.isEmpty();
            return emptyTaIds ? '' : 'WHERE '+ whereField +' IN (' + CollectionUtil.joinByComa(CollectionUtil.wrapInApostrophes(taIds)) + ') ';
        }

    }

    public class QCareWhereClauseDecorator extends WhereClauseDecorator {

        private List<Id> qCareSSIds;

        public QCareWhereClauseDecorator(WhereClause clause, Set<Id> qCareSSIds) {
            super(clause);
            this.qCareSSIds = new List<Id>(qCareSSIds);
        }

        public override String getWhereClause() {
            return (String.isBlank(clause.getWhereClause()) ? 'WHERE' : clause.getWhereClause() + 'AND') +
                    ' Id IN (SELECT Clinical_Trial_Profile__c FROM Study_Site__c WHERE Id IN (' + CollectionUtil.joinByComa(CollectionUtil.wrapInApostrophes(qCareSSIds)) + ')) ';
        }
    }

    public class EnrollingWhereClauseDecorator extends WhereClauseDecorator {

        public EnrollingWhereClauseDecorator(WhereClause clause) {
            super(clause);
        }

        public override String getWhereClause() {
            return (String.isBlank(clause.getWhereClause()) ? 'WHERE' : clause.getWhereClause() + 'AND') +
                    ' (Override_Recruitment_Status__c = ' + '\'' + ACTIVELY_ENROLLING + '\' ' +
                    'OR Override_Recruitment_Status__c IN (' + CollectionUtil.joinByComa(CollectionUtil.wrapInApostrophes(CTMS_RECRUITMENT_ENROLLING)) + ')) ';
        }
    }

    public class NotEnrollingWhereClauseDecorator extends WhereClauseDecorator {

        public NotEnrollingWhereClauseDecorator(WhereClause clause) {
            super(clause);
        }

        public override String getWhereClause() {
            return (String.isBlank(clause.getWhereClause()) ? 'WHERE' : clause.getWhereClause() + 'AND') +
                    ' (Override_Recruitment_Status__c = ' + '\'' + ON_HOLD + '\' ' +
                    'OR Override_Recruitment_Status__c IN (' + CollectionUtil.joinByComa(CollectionUtil.wrapInApostrophes(CTMS_ON_HOLD)) + ')) ';
        }
    }

    public class EnrollingNotEnrollingWhereClauseDecorator extends WhereClauseDecorator {

        public EnrollingNotEnrollingWhereClauseDecorator(WhereClause clause) {
            super(clause);
        }

        public override String getWhereClause() {
            return (String.isBlank(clause.getWhereClause()) ? 'WHERE' : clause.getWhereClause() + 'AND') +
                    ' (Override_Recruitment_Status__c IN (' + CollectionUtil.joinByComa(CollectionUtil.wrapInApostrophes(ORS_STATUS_ENROLLING)) + ') ' +
                    'OR Override_Recruitment_Status__c IN (' + CollectionUtil.joinByComa(CollectionUtil.wrapInApostrophes(CTMS_RECRUITMENT)) + ')) ';
        }
    }

}