force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/UCPM_Sponsor_Org_Id__c.field-meta.xml
<CustomField>
    <fullName>UCPM_Sponsor_Org_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UCPM Sponsor Org Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/UCPM_Study_Purpose_Id__c.field-meta.xml
<CustomField>
    <fullName>UCPM_Study_Purpose_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UCPM Study Purpose Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PPM_ID__c.field-meta.xml
<CustomField>
    <fullName>PPM_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>IQVIA consents specific PPM ID captured at Contact level for Participants/Caregivers</inlineHelpText>
    <label>PPM ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UCPM_Status__c.field-meta.xml
<CustomField>
    <fullName>UCPM_Status__c</fullName>
    <label>UCPM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/PPMID__c.field-meta.xml
<CustomField>
    <fullName>PPMID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PPM ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/UCPM_Status__c.field-meta.xml
<CustomField>
    <fullName>UCPM_Status__c</fullName>
    <label>UCPM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/Patient_Delegate__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate</label>
    <nameField>
        <displayFormat>PD-{00000000}</displayFormat>
        <label>Patient Delegate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/Patient_Delegate_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate Enrollment</label>
    <nameField>
        <displayFormat>PDE-{00000}</displayFormat>
        <label>Patient Delegate Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegate Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Attested_By__c.field-meta.xml
<CustomField>
    <fullName>Attested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>PI / Site Staff / Participant added and attested in the frontend</inlineHelpText>
    <label>Attested By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Patient Delegate Enrollments</relationshipLabel>
    <relationshipName>Patient_Delegate_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Delegate Enrollments</relationshipLabel>
    <relationshipName>Patient_Delegate_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/Patient_Delegate__c.field-meta.xml
<CustomField>
    <fullName>Patient_Delegate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Associated Patient Delegate Record of the delegate</inlineHelpText>
    <label>Patient Delegate</label>
    <referenceTo>Patient_Delegate__c</referenceTo>
    <relationshipLabel>Patient Delegate Enrollments</relationshipLabel>
    <relationshipName>Patient_Delegate_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/PPM_ID__c.field-meta.xml
<CustomField>
    <fullName>PPM_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Study+Participant consents specific PPM ID captured at PDE level only for Caregivers</inlineHelpText>
    <label>PPM ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate_Enrollment__c/fields/UCPM_Status__c.field-meta.xml
<CustomField>
    <fullName>UCPM_Status__c</fullName>
    <label>UCPM Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UCPM_UpdatePPMID_oneTimeBatch.cls
global without sharing class UCPM_UpdatePPMID_oneTimeBatch implements Database.Batchable<SObject>, Database.Stateful {
  public Set<ID> conUniqueIDppm = new Set<ID>();
  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(
      [
        SELECT
          Id,
          PPMID__c,
          UCPM_Status__c,
          Participant_Contact__c,
          Participant_Contact__r.PPM_ID__c,
          Participant_Contact__r.UCPM_Status__c,
          Clinical_Trial_Profile__r.UCPM_Sponsor_Org_Id__c,
          Clinical_Trial_Profile__r.UCPM_Study_Purpose_Id__c,
          (
            SELECT
              id,
              PPM_ID__c,
              UCPM_Status__c,
              Patient_Delegate__r.Contact__c,
              Patient_Delegate__r.Contact__r.PPM_ID__c,
              Patient_Delegate__r.Contact__r.UCPM_Status__c
            FROM Patient_Delegate_Enrollments__r
            WHERE
              PPM_ID__c = NULL
              OR Patient_Delegate__r.Contact__r.PPM_ID__c = NULL
          )
        FROM Participant_Enrollment__c
        WHERE
          Clinical_Trial_Profile__r.UCPM_Sponsor_Org_Id__c != NULL
          AND Clinical_Trial_Profile__r.UCPM_Study_Purpose_Id__c != NULL
          AND (PPMID__c = NULL
          OR Participant_Contact__r.PPM_ID__c = NULL)
      ]
    );
  }
  global void execute(
    Database.BatchableContext bc,
    List<Participant_Enrollment__c> scope
  ) {
    List<Participant_Enrollment__c> perListToUpdate = new List<Participant_Enrollment__c>();
    List<Patient_Delegate_Enrollment__c> pderListToUpdate = new List<Patient_Delegate_Enrollment__c>();
    List<Contact> conListToUpdate = new List<Contact>();

    for (Participant_Enrollment__c per : scope) {
      if (per.PPMID__c == null) {
        per.PPMID__c = generateUUID();
        perListToUpdate.add(per);
      }
      if (
        per.Participant_Contact__c != null &&
        per.Participant_Contact__r.PPM_ID__c == null &&
        !conUniqueIDppm.contains(per.Participant_Contact__c)
      ) {
        Contact con = new Contact();
        con.Id = per.Participant_Contact__c;
        con.PPM_ID__c = generateUUID();
        conListToUpdate.add(con);
        conUniqueIDppm.add(per.Participant_Contact__c);
      }
      for (
        Patient_Delegate_Enrollment__c pder : per.Patient_Delegate_Enrollments__r
      ) {
        if (pder.PPM_ID__c == null) {
          Patient_Delegate_Enrollment__c pd = new Patient_Delegate_Enrollment__c();
          pd.Id = pder.ID;
          pd.PPM_ID__c = generateUUID();
          pderListToUpdate.add(pd);
        }
        if (
          pder.Patient_Delegate__r != null &&
          pder.Patient_Delegate__r.Contact__c != null &&
          pder.Patient_Delegate__r.Contact__r.PPM_ID__c == null &&
          !conUniqueIDppm.contains(pder.Patient_Delegate__r.Contact__c)
        ) {
          pder.Patient_Delegate__r.Contact__r.PPM_ID__c = generateUUID();
          Contact con1 = new Contact();
          con1.Id = pder.Patient_Delegate__r.Contact__c;
          con1.PPM_ID__c = generateUUID();
          conListToUpdate.add(con1);
          conUniqueIDppm.add(pder.Patient_Delegate__r.Contact__c);
        }
      }
    }

    if (!perListToUpdate.isEmpty()) {
      update perListToUpdate;
    }
    if (!pderListToUpdate.isEmpty()) {
      update pderListToUpdate;
    }
    if (!conListToUpdate.isEmpty()) {
      update conListToUpdate;
    }
  }
  global void finish(Database.BatchableContext bc) {
    //call another batch to create records for staging table
    Database.executeBatch(new UCPM_CreateCSVfileRecords_oneTimeBatch());
  }

  //UUID generator
  public static String generateUUID() {
    String finalUUID;
    String version = '01';
    String mappingRH = '004';
    UUID randomUuid = UUID.randomUUID();
    finalUUID = version + mappingRH + '_' + randomUuid;
    System.debug('finalUUID: ' + finalUUID);
    return finalUUID;
  }
}
//TODO: To execute this batch
// Database.executeBatch(new UCPM_UpdatePPMID_oneTimeBatch(), 30);