force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/CommunityTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommunityTemplate__c</fullName>
    <label>Community Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>IQVIA Patient Portal</label>
            </value>
            <value>
                <fullName>GSK</fullName>
                <label>GSK Pan Oncology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
<!--    <trackHistory>true</trackHistory>-->
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Patient_User_Created__c.field-meta.xml
<CustomField>
    <fullName>Is_Patient_User_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Patient User Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunityMode__c.field-meta.xml
<CustomField>
    <fullName>userCommunityMode__c</fullName>
    <description>Current view point for Community</description>
    <label>User Community Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/userCommunytyType__c.field-meta.xml
<CustomField>
    <fullName>userCommunytyType__c</fullName>
    <description>User types for community - HCP / PI / Participant</description>
    <inlineHelpText>Select user types for community</inlineHelpText>
    <label>User Community Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>Participant</fullName>
            </value>
            <value>
                <fullName>Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reminder_Schedule__c/Reminder_Schedule__c.object-meta.xml
<CustomObject>
    <label>Reminder Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Reminder Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reminder Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reminder_Schedule__c/fields/First_Reminder_day__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder_day__c</fullName>
    <inlineHelpText>Define how many days should pass before 1st reminder email is sent to a Participant in case Survey Task is still pending</inlineHelpText>
    <label>First Reminder day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/Site_Staff__c.object-meta.xml
<CustomObject>
    <description>Used to connect Contacts with Study Sites to represent a Principal Investigator&#39;s team</description>

    <label>Site Staff</label>
    <nameField>
        <displayFormat>Staff #{0000}</displayFormat>
        <label>Site Staff</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Staff__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; Study_Site__r.Clinical_Trial_Profile__c,  Study_Site__r.Clinical_Trial_Profile__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clinical Trial Profile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/is_Invited__c.field-meta.xml
<CustomField>
    <fullName>is_Invited__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check whether site staff is invited or not</description>
    <label>is Invited</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact__c</fullName>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staff&#39;s Study Sites</relationshipLabel>
    <relationshipName>PI_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <formula>if(is_Site_and_Staff_Same_Country__c == false,  HYPERLINK(&quot;/&quot;&amp; Id , Name ) , &apos;-&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Staff</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Site Staff</relationshipLabel>
    <relationshipName>Site_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to study site delegate</description>
    <label>Site Staff</label>
    <referenceTo>Site_Staff__c</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/ExpireDateTime__c.field-meta.xml
<CustomField>
    <fullName>ExpireDateTime__c</fullName>
    <label>ExpireDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Reminder_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reminder Schedule</label>
    <referenceTo>Reminder_Schedule__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit__c/Televisit__c.object-meta.xml
<CustomObject>
    <label>Televisit</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Televisit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Televisits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/Televisit_Attendee__c.object-meta.xml
<CustomObject>
    <label>Televisit Attendee</label>
    <nameField>
        <label>Televisit Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Televisit Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Televisit__c.field-meta.xml
<CustomField>
    <fullName>Televisit__c</fullName>
    <label>Televisit</label>
    <referenceTo>Televisit__c</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/triggers-implementation/classes/UserTriggerHandler.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class UserTriggerHandler {
    // Handlers: -------------------------------------------------------------------------------------------------------

    public class UpdateLanguageOnRelatedContactsHandler extends TriggerHandler {
        public override void afterInsert(List<SObject> newList) {
            updateLanguageOnRelatedContactsAfterInsert(newList, null);
        }

        public override void afterUpdate(List<SObject> newList, Map<Id, SObject> oldMap) {
            updateLanguageOnRelatedContacts(newList, (Map<Id, User>) oldMap);
        }
    }

    public class UpdateEmailOnRelatedContactsHandler extends TriggerHandler {
        public override void afterUpdate(List<SObject> newList, Map<Id, SObject> oldMap) {
            updateEmailOnRelatedContacts(newList, (Map<Id, User>) oldMap);
        }
    }

    public class CreateCompleteYourProfileTaskHandler extends TriggerHandler {
        public override void afterInsert(List<SObject> newList) {
            createCompleteYourProfileTask(newList);
        }
    }

    public class AssignCommunityPermissionSetToUserHandler extends TriggerHandler {
        public override void afterInsert(List<SObject> newList) {
            assignCommunityPermissionSetToUser(newList);
        }
    }

    public class AssignPendingTasksHandler extends TriggerHandler {
        public override void afterInsert(List<SObject> newList) {
            assignTasks(newList);
        }
    }
    public class AssignPendingTelevisitsHandler extends TriggerHandler {
        public override void afterInsert(List<SObject> newList) {
            assignPendingTelevisits(newList);
        }
    }
    // Logic: ----------------------------------------------------------------------------------------------------------

    @TestVisible
    private static void updateLanguageOnRelatedContacts(List<User> newList, Map<Id, User> oldMap) {
        List<Contact> contactsForUpdate = new List<Contact>();
        for (User user : newList) {
            if (user.ContactId == null)
                continue;
            if (
                oldMap == null ||
                (oldMap != null &&
                oldMap.get(user.Id).LanguageLocaleKey != user.LanguageLocaleKey)
            ) {
                contactsForUpdate.add(
                    new Contact(Id = user.ContactId, Language__c = user.LanguageLocaleKey)
                );
            }
        }
        if (contactsForUpdate.size() > 0)
            update contactsForUpdate;
    }

    @TestVisible
    private static void updateLanguageOnRelatedContactsAfterInsert(List<User> newList, Map<Id, User> oldMap) {
        List<Contact> contactsForUpdate = new List<Contact>();
        List<Id> conId = new List<Id>();
        List<Contact> lstContacts = new List<Contact>();
        Map<Id, String> usrLangKey = new Map<Id, String>();
        for (User user : newList) {
            if (user.ContactId != null)
            {
              conId.add(user.ContactId);
              usrLangKey.put(user.ContactId,user.LanguageLocaleKey);
            }
          } 
       if (conId.size() > 0) {
            lstContacts = [select Id,Is_Patient_User_Created__c,Language__c,userCommunytyType__c from Contact where Id IN:conId];
            for(Contact con:lstContacts)
            {
               if(!con.Is_Patient_User_Created__c)
                {
                    contactsForUpdate.add(new Contact(Id = con.Id,Is_Patient_User_Created__c=true,Language__c = usrLangKey.get(con.Id)));
                }else{
                     contactsForUpdate.add(new Contact(Id = con.Id, Language__c = usrLangKey.get(con.Id)));
                }
            }
            if (contactsForUpdate.size() > 0)
            update contactsForUpdate;
         }
    }

    @TestVisible
    private static void updateEmailOnRelatedContacts(List<User> newList, Map<Id, User> oldMap) {
        List<Contact> changeEmailContacts = new List<Contact>();
        for (User user : newList) {
            if (user.ContactId == null)
                continue;
            if (oldMap.get(user.Id).Email != user.Email) {
                if (user.ContactId != null) {
                    changeEmailContacts.add(new Contact(Id = user.ContactId, Email = user.Email));
                }
            }
        }
        if (changeEmailContacts.size() > 0)
            update changeEmailContacts;
    }
	

    @TestVisible
    private static void createCompleteYourProfileTask(List<User> newList) {
        Set<Id> userContactIds = new Set<Id>();
        for (User user : newList) {
            if (user.ContactId != null)
                userContactIds.add(user.ContactId);
        }

        List<Participant__c> participants = [
            SELECT Id, Contact__c
            FROM Participant__c
            WHERE Contact__c IN :userContactIds FOR UPDATE
        ];
        Map<Id, Id> participantByContact = new Map<Id, Id>();
        for (Participant__c participant : participants)
            participantByContact.put(participant.Contact__c, participant.Id);

        List<Task> tasksForInsert = new List<Task>();
        for (User user : newList) {
            if (
                user.ContactId != null &&
                user.ProfileId == CommunityService.COMMUNITY_USER_PROFILE_ID
            ) {
                Id participantId = participantByContact.get(user.ContactId);
                if (participantId != null) {
                    tasksForInsert.add(
                        TaskService.getInstance()
                            .createCompleteYourProfileTask(user.Id, participantId, user.ContactId)
                    );
                }
            }
        }
        insert tasksForInsert;
    }

    @TestVisible
    private static void assignCommunityPermissionSetToUser(List<User> insertedUsers) {
        List<User> rhUsers = [
            SELECT Id, ContactId, Contact.userCommunityMode__c, Contact.userCommunytyType__c
            FROM User
            WHERE
                Id IN :insertedUsers
                AND ContactId != NULL
                AND Contact.userCommunityMode__c != 'Participant'
                AND CreatedBy.Name != 'Covid-19 Site Guest User'
        ];

        Action_AssignContactPermissions actionAssignContactPermissions = new Action_AssignContactPermissions();
        if (rhUsers != null) {
            Set<Id> piIds = new Set<Id>();
            for (User user : rhUsers) {
                if (
                    !String.isBlank(user.Contact.userCommunytyType__c) &&
                    user.Contact.userCommunytyType__c.contains('PI')
                ) {
                    piIds.add(user.ContactId);
                } else {
                    actionAssignContactPermissions.addPermission(
                        user.ContactId,
                        CommunityTemplateService.PERMISSION_COMMUNITY_DEFAULT_NAME
                    );
                }

                if (!actionAssignContactPermissions.isEmpty()) {
                    ActionExecutor.executeAsync(actionAssignContactPermissions, Datetime.now());
                }
            }
            if (!piIds.isEmpty()) {
                Map<String, Set<Id>> commUserPermission = new Map<String, Set<Id>>{
                    CommunityTemplateService.TEMPLATE_DEFAULT => new Set<Id>(),
                    CommunityTemplateService.TEMPLATE_JANSSEN => new Set<Id>()
                };
                List<Study_Site__c> ssList = [
                    SELECT
                        Id,
                        Clinical_Trial_Profile__r.CommunityTemplate__c,
                        Principal_Investigator__c
                    FROM Study_Site__c
                    WHERE Principal_Investigator__c IN :piIds
                ];
                if (!ssList.isEmpty()) {
                    for (Integer i = 0, j = ssList.size(); i < j; i++) {
                        if (
                            ssList[i].Clinical_Trial_Profile__r.CommunityTemplate__c ==
                            CommunityTemplateService.TEMPLATE_JANSSEN
                        ) {
                            commUserPermission.get(CommunityTemplateService.TEMPLATE_JANSSEN)
                                .add(ssList[i].Principal_Investigator__c);
                        } else {
                            commUserPermission.get(CommunityTemplateService.TEMPLATE_DEFAULT)
                                .add(ssList[i].Principal_Investigator__c);
                        }
                    }
                } else {
                    List<Site_Staff__c> delegatesSS = [
                        SELECT
                            Id,
                            Site_Contact__c,
                            Study_Site__r.Clinical_Trial_Profile__r.CommunityTemplate__c
                        FROM Site_Staff__c
                        WHERE Site_Contact__c IN :piIds AND is_Invited__c = true
                    ];
                    if (!delegatesSS.isEmpty()) {
                        for (Integer i = 0, j = delegatesSS.size(); i < j; i++) {
                            if (
                                delegatesSS[i]
                                    .Study_Site__r.Clinical_Trial_Profile__r.CommunityTemplate__c ==
                                CommunityTemplateService.TEMPLATE_JANSSEN
                            ) {
                                commUserPermission.get(CommunityTemplateService.TEMPLATE_JANSSEN)
                                    .add(delegatesSS[i].Site_Contact__c);
                            } else {
                                commUserPermission.get(CommunityTemplateService.TEMPLATE_DEFAULT)
                                    .add(delegatesSS[i].Site_Contact__c);
                            }
                        }
                    }
                }
                for (String community : commUserPermission.keySet()) {
                    for (Id contId : commUserPermission.get(community)) {
                        if (community == CommunityTemplateService.TEMPLATE_JANSSEN) {
                            actionAssignContactPermissions.addPermission(
                                contId,
                                CommunityTemplateService.PERMISSION_COMMUNITY_JANSSEN_NAME
                            );
                        } else {
                            actionAssignContactPermissions.addPermission(
                                contId,
                                CommunityTemplateService.PERMISSION_COMMUNITY_DEFAULT_NAME
                            );
                        }
                    }
                }
                if (!actionAssignContactPermissions.isEmpty()) {
                    ActionExecutor.executeAsync(actionAssignContactPermissions, Datetime.now());
                }
            }
        } else {
            List<User> registryUsers = [
                SELECT Id, ContactId
                FROM User
                WHERE
                    Id IN :insertedUsers
                    AND ContactId != NULL
                    AND Contact.userCommunityMode__c != 'Participant'
            ];

            Action_AssignContactPermissions registryActionAssignContactPermissions = new Action_AssignContactPermissions();

            for (User user : registryUsers) {
                registryActionAssignContactPermissions.addPermission(
                    user.ContactId,
                    CommunityTemplateService.PERMISSION_COMMUNITY_COVID19_NAME
                );
            }

            if (!registryActionAssignContactPermissions.isEmpty()) {
                ActionExecutor.executeAsync(registryActionAssignContactPermissions, Datetime.now());
            }
        }
    }

    @TestVisible
    private static void assignTasks(List<User> users) {
        //assign tasks from tmp user to new user
        Set<Id> conIds = new Set<Id>();
        Map<Id, User> usersByContactMap = new Map<Id, User>();
        for (User user : users) {
            if (user.ContactId != null) {
                conIds.add(user.ContactId);
                usersByContactMap.put(user.ContactId, user);
            }
        }
        Map<Id, TimeZone> userTimezoneMap = DateTimeConverterUtil.getUsersTimezoneMap(conIds);

        List<Task> tasks = [
            SELECT
                Id,
                Activity_Datetime__c,
                OwnerId,
                Owner_Contact__c,
                Task_Type__c,
                Start_Date__c,
                ReminderDateTime,
                Reminder_Date__c,
                Survey_Invitation__r.ExpireDateTime__c,
                Survey_Invitation__r.Reminder_Schedule__r.First_Reminder_day__c
            FROM Task
            WHERE Owner_Contact__c IN :conIds
        ];
        for (Task task : tasks) {
            User taskUser = usersByContactMap.get(task.Owner_Contact__c);
            task.OwnerId = taskUser.Id;
            task.Owner_Contact__c = null;

            if (task.Task_Type__c == TaskService.TASK_TYPE_SURVEY) {
                TimeZone userTZ = userTimezoneMap.get(taskUser.Id);
                Datetime userDatetime = DateTimeConverterUtil.getUserDT(
                    Datetime.now().date(),
                    Datetime.now().time(),
                    userTZ
                );

                task.Start_Date__c = userDatetime.date();
                SurveyInvitation invitation = task.Survey_Invitation__r;
                if (invitation.ExpireDateTime__c != null) {
                    Date expiryDate = invitation.ExpireDateTime__c.date();
                    Integer daysBetween = Date.today().daysBetween(expiryDate);
                    task.Activity_Datetime__c = userDatetime.addDays(daysBetween);
                }

                if (invitation.Reminder_Schedule__r.First_Reminder_day__c != null) {
                    Integer firstReminderDay = (Integer) invitation.Reminder_Schedule__r.First_Reminder_day__c;
                    task.Reminder_Date__c = userDatetime.addDays(firstReminderDay);
                    task.ReminderDateTime = Datetime.now().addDays(firstReminderDay);
                }
            }
        }
        update tasks;
    }
    @TestVisible
    private static void assignPendingTelevisits(List<User> users) {
        Map<Id, User> usersByContactMap = new Map<Id, User>();
        List<Televisit_Attendee__c> attendeeList = new List<Televisit_Attendee__c>();

        for (User user : users) {
            if (user.ContactId != null) {
                usersByContactMap.put(user.ContactId, user);
            }
        }

        for (Televisit_Attendee__c tvAttendee : [SELECT Id, User__c, Contact__c FROM Televisit_Attendee__c
                                                 WHERE Contact__c IN :usersByContactMap.keyset() AND User__c = NULL AND
                                                 Televisit__r.Status__c = 'Scheduled']) {
            Televisit_Attendee__c tva = new Televisit_Attendee__c();
            tva.id = tvAttendee.Id;                                       
            tva.User__c = usersByContactMap.get(tvAttendee.Contact__c).Id;
            attendeeList.add(tva);                                         
        }
        if(!attendeeList.isEmpty()){
            update attendeeList; 
        }
        
    }
}
}