force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <description>QI assigned unique ID for a study</description>
    <externalId>true</externalId>
    <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
    <label>Protocol ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Sponsor__c.field-meta.xml
<CustomField>
    <fullName>Study_Sponsor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field should map to the &quot;Study Sponsor&quot; field in clinicaltrials.gov</inlineHelpText>
    <label>Study Sponsor</label>
    <length>400</length>

    <type>LongTextArea</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Plan__c/Incentive_Plan__c.object-meta.xml
<CustomObject>
    <label>Incentive Plan</label>
    <nameField>
        <displayFormat>INCPLAN-{0000}</displayFormat>
        <label>Incentive Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/incentive-program/objects/Incentive_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Incentive Plans</relationshipLabel>
    <relationshipName>Incentive_Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Plan_Task__c/Incentive_Plan_Task__c.object-meta.xml
<CustomObject>
    <label>Incentive Plan Task</label>
    <nameField>
        <displayFormat>IPT-{000000}</displayFormat>
        <label>Incentive Plan Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incentive Plan Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/incentive-program/objects/Incentive_Plan_Task__c/fields/Incentive_Plan__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Plan__c</fullName>
    <label>Incentive Plan</label>
    <referenceTo>Incentive_Plan__c</referenceTo>
    <relationshipLabel>Incentive Plan Tasks</relationshipLabel>
    <relationshipName>Incentive_Plan_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Plan_Task__c/fields/Incentive_Task_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Task_Catalog__c</fullName>
    <label>Incentive Task Catalog</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Plan_Task__c/fields/IQVIA_Supported__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Supported__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Supported</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Task_Catalog__mdt/Incentive_Task_Catalog__mdt.object-meta.xml
<CustomObject>
    <label>Incentive Task Catalog</label>
    <pluralLabel>Incentive Task Catalog</pluralLabel>
</CustomObject>

force-app/main/incentive-program/objects/Incentive_Task_Catalog__mdt/fields/Default_Number_of_Points__c.field-meta.xml
<CustomField>
    <fullName>Default_Number_of_Points__c</fullName>
    <label>Default Number of Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/incentive-program/objects/Incentive_Task_Catalog__mdt/fields/Title_Label__c.field-meta.xml
<CustomField>
    <fullName>Title_Label__c</fullName>
    <label>Title Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/Study_Incentive_Plan__c.object-meta.xml
<CustomObject>
    <label>Study Incentive Plan</label>
    <nameField>
        <displayFormat>SIP-{000000}</displayFormat>
        <label>Study Incentive Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Incentive Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Study Incentive Plans</relationshipLabel>
    <relationshipName>Study_Incentive_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/fields/Incentive_Plan__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incentive Plan</label>
    <referenceTo>Incentive_Plan__c</referenceTo>
    <relationshipLabel>Study Incentive Plans</relationshipLabel>
    <relationshipName>Study_Incentive_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Study Incentive Plans</relationshipLabel>
    <relationshipName>Study_Incentive_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <formula>Clinical_Trial_Profile__r.Protocol_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Clinical Trial Profile&#39;s Protocol Id</inlineHelpText>
    <label>Protocol ID</label>

    <type>Text</type>
</CustomField>

force-app/main/backend-ctp-setup/classes/IncentivePlanConfigurationRemote.cls
/**
 * Created by Alexey Moseev on 5/7/20.
 */

public without sharing class IncentivePlanConfigurationRemote {

    public static final String FEATURE_SS_INCENTIVE_CONFIG = 'Incentive_Program';
    public static final String STUDY_SITES_INCENTIVE_PLANS_SETUP_FILTER = 'StudySitesIncentivePlansSetupFilter';

    public class InitData {
        @AuraEnabled public String viewMode = GetPermissions.getViewMode(FEATURE_SS_INCENTIVE_CONFIG);
        @AuraEnabled public StudySiteFilter filter;
        @AuraEnabled public SSIncentiveConfigSearchResponse searchResponse;
    }

    @AuraEnabled
    public static InitData getInitData(Id ctpId) {
        try {
            InitData initData = new InitData();
            StudySiteFilter filter = (StudySiteFilter) SettingStoreService.getOrgDefault(STUDY_SITES_INCENTIVE_PLANS_SETUP_FILTER + ctpId);
            if (filter == null) {
                filter = new StudySiteFilter(ctpId);
            }
            initData.filter = filter;
            initData.searchResponse = new SSIncentiveConfigSearchResponse(initData.filter, new PaginationData(15));
            return initData;
        } catch (Exception e) {
            return (InitData) AuraHelper.throwException(e);
        }
    }

    @AuraEnabled
    public static SSIncentiveConfigSearchResponse getItems(String ssItemsJSON, String filterJSON, String paginationJSON) {
        try {
            StudySiteFilter filter = (StudySiteFilter) JSON.deserialize(filterJSON, StudySiteFilter.class);
            PaginationData pagination = (PaginationData) JSON.deserialize(paginationJSON, PaginationData.class);
            save(ssItemsJSON);
            saveFilter(filter);
            return new SSIncentiveConfigSearchResponse(filter, pagination);
        } catch (Exception e) {
            return (SSIncentiveConfigSearchResponse) AuraHelper.throwException(e);
        }
    }

    @AuraEnabled
    public static SSIncentiveConfigSearchResponse setIncentivePlanForAll(String visitPlanId, Boolean state, String filterJSON, String paginationJSON, String ssItemsJSON) {
        try {
            save(ssItemsJSON);
            StudySiteFilter filter = (StudySiteFilter) JSON.deserialize(filterJSON, StudySiteFilter.class);
            saveFilter(filter);
            PaginationData pagination = (PaginationData) JSON.deserialize(paginationJSON, PaginationData.class);
            List<StudySiteItem> allSSItems = SSIncentiveConfigSearchResponse.convertToSSItems(SearchService.search(filter), visitPlanId);
            for (StudySiteItem ssItem : allSSItems) {
                for (ValueStateItem assigment : ssItem.assignments) assigment.state = state;
            }
            save(allSSItems);
            return new SSIncentiveConfigSearchResponse(filter, pagination);
        } catch (Exception e) {
            return (SSIncentiveConfigSearchResponse) AuraHelper.throwException(e);
        }
    }

    @AuraEnabled
    public static SSIncentiveConfigSearchResponse deleteIncentivePlan(String planId, String filterJSON, String paginationJSON) {
        try {
            delete new Incentive_Plan__c(Id = planId);
            StudySiteFilter filter = (StudySiteFilter) JSON.deserialize(filterJSON, StudySiteFilter.class);
            PaginationData pagination = (PaginationData) JSON.deserialize(paginationJSON, PaginationData.class);
            saveFilter(filter);
            return new SSIncentiveConfigSearchResponse(filter, pagination);
        } catch (Exception e) {
            return (SSIncentiveConfigSearchResponse) AuraHelper.throwException(e);
        }
    }
    @AuraEnabled
    public static List<Incentive_Task_Catalog__mdt> getIncentiveTasks() {
        return [SELECT Id, Title_Label__c, Description_Label__c, Default_Number_of_Points__c FROM Incentive_Task_Catalog__mdt];
    }

    @AuraEnabled
    public static Clinical_Trial_Profile__c getStudyInfo(String id) {
        return [SELECT Id, Name, Study_Code_Name__c, Protocol_ID__c, Study_Sponsor__c, OwnerId, Owner.Name, CreatedById, CreatedBy.Name, LastModifiedById, LastModifiedBy.Name FROM Clinical_Trial_Profile__c WHERE Id =: id];
    }

    @AuraEnabled
    public static String createIncentivePlan(Incentive_Task_Catalog__mdt task, Boolean checkON, Boolean checkIQVIA, String planName) {
        Incentive_Plan__c plan = new Incentive_Plan__c(Plan_Name__c = planName);
        insert plan;
        Incentive_Plan_Task__c newTask = new Incentive_Plan_Task__c(Incentive_Plan__c = plan.Id,
                                                                 Incentive_Task_Catalog__c = task.Title_Label__c,
                                                                 Points__c = task.Default_Number_of_Points__c,
                                                                 Enabled__c = checkON, IQVIA_Supported__c = checkIQVIA);
        insert newTask;
        return plan.Id;

    }

    private static void save(String ssItemsJSON) {
        if (String.isEmpty(ssItemsJSON)) return;
        List<StudySiteItem> studySiteItems = (List<StudySiteItem>) JSON.deserialize(ssItemsJSON, List<StudySiteItem>.class);
        save(studySiteItems);
    }

    private static void save(List<StudySiteItem> studySiteItems) {
        List<Study_Incentive_Plan__c> toDelete = new List<Study_Incentive_Plan__c>();
        List<Study_Incentive_Plan__c> toInsert = new List<Study_Incentive_Plan__c>();
        for (StudySiteItem ssItem : studySiteItems) {
            for (ValueStateItem assigment : ssItem.assignments) {
                if (assigment.sourceId != null && !assigment.state) {
                    toDelete.add(new Study_Incentive_Plan__c(Id = assigment.sourceId));
                } else if (assigment.sourceId == null && assigment.state){
                    toInsert.add(new Study_Incentive_Plan__c(
                            Study_Site__c = ssItem.ss.Id,
                            Incentive_Plan__c = assigment.value
                    ));
                }
            }
        }
        delete toDelete;
        insert toInsert;
    }

    private static void saveFilter(StudySiteFilter filter){
        SettingStoreService.saveOrgDefault(STUDY_SITES_INCENTIVE_PLANS_SETUP_FILTER + filter.ctpId, filter, StudySiteFilter.class);
    }

}