force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Icon_Details__c/Icon_Details__c.object-meta.xml
<CustomObject>
    <description>icon description</description>
    <label>Icon Details</label>
    <nameField>
        <label>Icon Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Icons Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Icon_Details__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Icons Details</relationshipLabel>
    <relationshipName>Icons_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Plan__c/Visit_Plan__c.object-meta.xml
<CustomObject>
    <label>Visit Plan</label>
    <nameField>
        <label>Visit Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Visit Plans</relationshipLabel>
    <relationshipName>Visit_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IconPlanetVisitInfoEditRemote.cls
/**
 * Created by dobro on 21.06.2019.021.
 */

public inherited sharing class IconPlanetVisitInfoEditRemote {

    @AuraEnabled
    public static void saveIconInfo(List<Icon_Details__c> iconsDetails, String ctpId) {
        CTPSelector selector = (CTPSelector) ClassFactory.newInstance(CTPSelector.class);

        List<Clinical_Trial_Profile__c> ctp = selector.getCtpById(ctpId);
        try {

            if (ctp != null) {
                for (Icon_Details__c singleIconDetails : iconsDetails) {
                    singleIconDetails.Visit_Plan__c = ctp[0].Visit_Plan__c;
                }
                ((DatabaseProxy) ClassFactory.newInstance(DatabaseProxy.class))
                        .upsertRecords(iconsDetails, true);
            }
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
    }

    @AuraEnabled
    public static List<Icon_Details__c> getIconDetails(String ctpId) {
        CTPSelector selector = (CTPSelector) ClassFactory.newInstance(CTPSelector.class);

        try {
            if (ctpId != null) {
                List<Icon_Details__c> iconDetails = selector.getIconDetailsByVisitPlanInCTP(ctpId);
                if (iconDetails == null) {
                    return new List<Icon_Details__c>();
                }
                return iconDetails;
            } else {
                throw new AuraHandledException('CTP id is empty');
            }
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
        return null;
    }
}