force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Patient_Portal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Patient_Portal_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Patient Portal Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Data_Shareback__c.field-meta.xml
<CustomField>
    <fullName>Visit_Data_Shareback__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Data Shareback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Visit_Results_OptIn__c.field-meta.xml
<CustomField>
    <fullName>Visit_Results_OptIn__c</fullName>
    <label>Visit Results Opt In</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vitals</fullName>
            </value>
            <value>
                <fullName>Labs</fullName>
            </value>
            <value>
                <fullName>Biomarkers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <label>Mailing Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/Patient_Visit__c.object-meta.xml
<CustomObject>
    <label>Patient Visit</label>
    <nameField>
        <displayFormat>PV-{000000}</displayFormat>
        <label>Patient Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Visit__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/visits/objects/Patient_Visit__c/fields/Visit_Number__c.field-meta.xml
<CustomField>
    <fullName>Visit_Number__c</fullName>
    <label>Visit Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Visit_Results_Sharing__c.field-meta.xml
<CustomField>
    <fullName>Visit_Results_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Results Sharing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/Visit_Result__c.object-meta.xml
<CustomObject>
    <label>Visit_Result</label>
    <nameField>
        <displayFormat>VR-{0000000}</displayFormat>
        <label>Visit_Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit_Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Result__c/fields/Actual_Value__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value__c</fullName>
    <label>Actual Result</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Max_Value__c</fullName>
    <label>Max Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/visits/objects/Visit_Result__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Min_Value__c.field-meta.xml
<CustomField>
    <fullName>Min_Value__c</fullName>
    <label>Min Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Patient_Visit__c.field-meta.xml
<CustomField>
    <fullName>Patient_Visit__c</fullName>
    <label>Patient Visit</label>
    <referenceTo>Patient_Visit__c</referenceTo>
    <relationshipLabel>Visit_Results</relationshipLabel>
    <relationshipName>Visit_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Result_Type__c.field-meta.xml
<CustomField>
    <fullName>Result_Type__c</fullName>
    <description>.</description>
    <label>Result Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/visits/classes/VisitResultsRemote.cls
/**
 * Created by Dmytro Pokutnii
 */
public without sharing class VisitResultsRemote {

    @AuraEnabled
    public static InitDataWrapper getInitData(String visitResultsMode, Map<String, Map<String, List<String>>> visitResultSharings) {
        try {
            List<Visit_Result__c> visitResultsForMode = VisitResultsService.getVisitResults(
                    ParticipantContext.getCurrentPE().Clinical_Trial_Profile__c,
                    ParticipantContext.getCurrentPE().Participant__r.Mailing_Country_Code__c
            );
            InitDataWrapper wrapper = (InitDataWrapper) ClassFactory.newInstance(InitDataWrapper.class);
            wrapper.isVisitResultsAvailable = isVisitResultAvailable();
            wrapper.contact = ParticipantContext.getCurrentContact();
            wrapper.isResultsExist = existForModeAndAvailableByCTP(visitResultSharings.get(visitResultsMode), visitResultsForMode);
            wrapper.visitResultsGroupNames = notEmptyVisitResultsGroupName(visitResultsMode, visitResultSharings, visitResultsForMode);
            wrapper.visitResultsShares = visitResultSharings.get(visitResultsMode);
            wrapper.isDelegate = ParticipantContext.isCurrentDelegate();
            wrapper.toggleState = toggleState(visitResultsMode);
            return wrapper;
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
        return null;
    }

    @AuraEnabled
    public static List<String> getVisitResultsGroupNames(String visitResultsMode) {

        try {
            return ((VisitResultsService) ClassFactory.newInstance(VisitResultsService.class)).getVisitResultsGroupNames(visitResultsMode);
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
        return null;
    }

    @AuraEnabled
    public static VisitResultsService.VisitResultsContainer getVisitResultsContainer(String visitResultGroupName, String visitResultsShares) {
        try {
            return ((VisitResultsService) ClassFactory.newInstance(VisitResultsService.class)).getVisitResultsContainer(
                    visitResultGroupName, convertJSONtoMap(visitResultsShares), ParticipantContext.getCurrentPE().Clinical_Trial_Profile__c,
                    ParticipantContext.getCurrentPE().Participant__r.Mailing_Country_Code__c
            );
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
        return null;
    }

    @AuraEnabled
    public static List<VisitResultsService.VisitResultWrapper> getVisitResultWrappersForDashboard() {

        try {
            return ((VisitResultsService) ClassFactory.newInstance(VisitResultsService.class)).getVisitResultWrappersForDashboard();
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
        return null;
    }

    @AuraEnabled
    public static Boolean toggleState(String visitResultsMode) {
        Contact currentContact = ParticipantContext.getCurrentContact();
        String currentVisitResults = currentContact.Visit_Results_OptIn__c == null ? '' : currentContact.Visit_Results_OptIn__c;
        return currentVisitResults.contains(visitResultsMode);
    }

    @AuraEnabled
    public static void switchToggleRemote(String visitResultsMode, Boolean isToggleOn) {
        Contact currentContact = ParticipantContext.getCurrentContact();
        String currentVisitResults = currentContact.Visit_Results_OptIn__c == null ? '' : currentContact.Visit_Results_OptIn__c;
        String updatedVisitResults = '';
        if (isToggleOn) {
            if (!currentVisitResults.contains(visitResultsMode)) {
                updatedVisitResults = currentVisitResults + ';' + visitResultsMode;
            }
        } else {
            List<String> visitResults = currentVisitResults.split(';');
            for (String str : visitResults) {
                if (!str.equals(visitResultsMode)) updatedVisitResults += str + ';';
            }
        }
        currentContact.Visit_Results_OptIn__c = updatedVisitResults;
        update currentContact;
    }

    public static List<String> notEmptyVisitResultsGroupName(String visitResultsMode,
            Map<String, Map<String, List<String>>> visitResultSharingByGroupAndMode,
            List<Visit_Result__c> visitResultsForMode) {

        VisitResultMService visitResultMService = new VisitResultMService();
        List<String> existingVisitResultGroups = new List<String>();

        if (visitResultsForMode != null) {
            for (Visit_Result__c visitResult : visitResultsForMode) {
                existingVisitResultGroups.add(
                        visitResultMService.getVisitResultGroupByTypeName(visitResult.Result_Type__c));
            }
        }

        Map<String, List<String>> visitResultGroupNamesWithTypes =
                visitResultSharingByGroupAndMode.get(visitResultsMode);
        List<String> notEmptyVisitResultsGroupName = new List<String>();

        if (visitResultGroupNamesWithTypes != null) {
            for (String groupName : visitResultGroupNamesWithTypes.keySet()) {
                if (existingVisitResultGroups.contains(groupName)) {
                    notEmptyVisitResultsGroupName.add(groupName);
                }
            }
        }
        return notEmptyVisitResultsGroupName;
    }

    public static Boolean existForModeAndAvailableByCTP(Map<String, List<String>> availableVisitResults,
            List<Visit_Result__c> visitResultsForMode) {
        if (availableVisitResults != null) {
            List<String> availableAndExistResults = new List<String>();
            for (Visit_Result__c visitResult : visitResultsForMode) {
                availableAndExistResults.add(visitResult.Result_Type__c);
            }
            for (String str : availableVisitResults.keySet()) {
                List<String> availableResultsForGroup = availableVisitResults.get(str);
                for (String result : availableResultsForGroup) {
                    if (availableAndExistResults.contains(result)) return true;
                }
            }
        }
        return false;
    }

    private static Map<String, List<String>> convertJSONtoMap(String visitResultsShares) {
        Map<String, Object> visitResultsSharesFirstStageDeserialize = (Map<String, Object>) JSON.deserializeUntyped(visitResultsShares);
        Map<String, List<String>> visitResultSharings = new Map<String, List<String>>();
        Set <String> groups = visitResultsSharesFirstStageDeserialize.keySet();
        for (String groupName : groups) {
            List<Object> visitResultsSharesSecondStageDeserialize = (List<Object>) visitResultsSharesFirstStageDeserialize.get(groupName);
            List<String> visitResultsSharesForGroup = new List<String>();
            for (Integer i = 0; i < visitResultsSharesSecondStageDeserialize.size(); i++) {
                visitResultsSharesForGroup.add(visitResultsSharesSecondStageDeserialize.get(i).toString());
            }
            visitResultSharings.put(groupName, visitResultsSharesForGroup);
        }
        return visitResultSharings;
    }

    public class InitDataWrapper {

        @AuraEnabled
        public Contact contact;
        @AuraEnabled
        public Boolean isDelegate;
        @AuraEnabled
        public Boolean isVisitResultsAvailable;
        @AuraEnabled
        public Boolean isResultsExist;
        @AuraEnabled
        public List<String> visitResultsGroupNames;
        @AuraEnabled
        public Map<String, List<String>> visitResultsShares;
        @AuraEnabled
        public Boolean toggleState;
    }

    public static List<Patient_Visit__c> getPatientVisits() {
        if (!isOnStudy()) return new List<Patient_Visit__c>();

        return [
                SELECT
                        Id,
                        Completed_Date__c,
                        Visit_Number__c, (
                        SELECT
                                Id,
                                Actual_Value__c,
                                Max_Value__c,
                                Measurement__c,
                                Min_Value__c,
                                Patient_Visit__r.Completed_Date__c,
                                Result_Type__c,
                                RecordType.DeveloperName
                        FROM Visit_Results__r
                )
                FROM Patient_Visit__c
                WHERE Participant_Enrollment__c = :ParticipantContext.getCurrentPEId()
                AND Status__c = 'Completed'
                ORDER BY Visit_Number__c, Completed_Date__c
        ];
    }

    public static Boolean isVisitResultAvailable() {
        if (!isOnStudy()) return false;

        ParticipantService.ParticipantState participantState = ParticipantService.getParticipantState();
        return participantState.pe.Clinical_Trial_Profile__r.Visit_Data_Shareback__c &&
                participantState.ctp.Patient_Portal_Enabled__c &&
                participantState.pe.Study_Site__r.Visit_Results_Sharing__c;
    }

    public static Boolean isOnStudy() {
        ParticipantService.ParticipantState participantState = ParticipantService.getParticipantState();
        if (PEStatusState.PE_STATUS_GROUP_PARTICIPATION_IN_PROGRESS.contains(participantState.pe.Participant_Status__c) ||
                PEStatusState.PE_STATUS_GROUP_COMPLETE.contains(participantState.pe.Participant_Status__c)) {
            return true;
        }
        return false;
    }
}