force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reminder_Schedule__c/Reminder_Schedule__c.object-meta.xml
<CustomObject>
    <label>Reminder Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Reminder Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reminder Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reminder_Schedule__c/fields/First_Reminder_day__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder_day__c</fullName>
    <inlineHelpText>Define how many days should pass before 1st reminder email is sent to a Participant in case Survey Task is still pending</inlineHelpText>
    <label>First Reminder day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reminder_Schedule__c/fields/Second_Reminder_day__c.field-meta.xml
<CustomField>
    <fullName>Second_Reminder_day__c</fullName>
    <inlineHelpText>Define how many days should pass before the Final reminder email is sent to a Participant in case Survey Task is still pending</inlineHelpText>
    <label>Second Reminder day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Reminder_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reminder Schedule</label>
    <referenceTo>Reminder_Schedule__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SurveyL</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Trial_Survey__c.field-meta.xml
<CustomField>
    <fullName>Trial_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trial Survey</label>
    <referenceTo>Trial_Survey__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/Trial_Survey__c.object-meta.xml
<CustomObject>
    <label>Trial Survey</label>
    <nameField>
        <displayFormat>TS-{000}</displayFormat>
        <label>Trial Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trial_Survey__c/fields/Active_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_On_Status__c</fullName>
    <label>Active on status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Referral Sent to PI</fullName>
            </value>
            <value>
                <fullName>Referral Accepted</fullName>
            </value>
            <value>
                <fullName>Contact Attempt In Progress</fullName>
            </value>
            <value>
                <fullName>Contact Successful</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Complete</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Trial Surveys</relationshipLabel>
    <relationshipName>Trial_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Expires_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Expires_After_Days__c</fullName>
    <description>Task expires</description>
    <label>Expires after (days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Is_Recurrence_Survey__c.field-meta.xml
<CustomField>
    <fullName>Is_Recurrence_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Recurrence Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Recurrence_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Frequency__c</fullName>
    <label>Recurrence Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Reminder_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reminder Schedule</label>
    <referenceTo>Reminder_Schedule__c</referenceTo>
    <relationshipLabel>Trial Surveys</relationshipLabel>
    <relationshipName>Trial_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Trial Surveys</relationshipLabel>
    <relationshipName>Trial_Surveys</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey_end_date__c.field-meta.xml
<CustomField>
    <fullName>Survey_end_date__c</fullName>
    <label>Survey end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey_start_date__c.field-meta.xml
<CustomField>
    <fullName>Survey_start_date__c</fullName>
    <label>Survey start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Whose_response_needed__c.field-meta.xml
<CustomField>
    <fullName>Whose_response_needed__c</fullName>
    <inlineHelpText>Please select whose responses is needed for this Survey</inlineHelpText>
    <label>Whose response needed</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Patient only</fullName>
            </value>
            <value>
                <fullName>Each Delegate</fullName>
            </value>
            <value>
                <fullName>Patient or any Delegate</fullName>
            </value>
            <value>
                <fullName>Any Delegate</fullName>
            </value>
            <value>
                <fullName>Patient and each Delegate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/tests/classes/Test_SurveyService.cls
/**
 * Created by Igor Malyuta on 13.06.2019.
 */
@IsTest(SeeAllData=true)
private class Test_SurveyService {
    static Trial_Survey__c ts;
    static Id communityId = CommunityService.getCommunityId(null);

    @IsTest
    static void generateInvitationTest() {
        List<Survey> survey = [SELECT Id, Name FROM Survey WHERE ActiveVersionId != NULL LIMIT 1];
        if (survey.isEmpty())
            return;

        TestData.loadTestData();
        Test.startTest();

        Reminder_Schedule__c schedule = new Reminder_Schedule__c(
            First_Reminder_day__c = 1,
            Second_Reminder_day__c = 2
        );
        insert schedule;

        TestData testData = new TestData();
        TriggerHandlerExecutor.bypassHandler(
            StudySiteTriggerHandler.CreatePIOrSendNotificationHandler.class
        );
        ts = new Trial_Survey__c(
            Active_On_Status__c = PEStatusState.PE_STATUS_SCREENING_IN_PROGRESS,
            Clinical_Trial_Profile__c = testData.ctp.Id,
            Reminder_Schedule__c = schedule.Id,
            Survey__c = survey.get(0).Id,
            Survey_end_date__c = date.today(),
            Survey_start_date__c = date.today() - 1,
            Is_Recurrence_Survey__c = true,
            Recurrence_Frequency__c = 'weekly',
            Whose_response_needed__c = 'Patient only'
        );
        insert ts;

        SurveyInvitation invitation = SurveyService.getInstance()
            .generateInvitation(
                ts,
                testData.pe.Id,
                communityId,
                System.today(),
                UserInfo.getTimeZone()
            );
        insert invitation;

        SurveyService.getInstance().getSurveyWrapper(invitation.Id);
        SurveyService.getInstance().expireInvitation(new List<Id>{ invitation.Id });
        Test.stopTest();
    }

    @IsTest
    static void generateInvitationWithoutTSTest() {
        List<Survey> survey = [SELECT Id, Name FROM Survey WHERE ActiveVersionId != NULL LIMIT 1];
        if (survey.isEmpty())
            return;

        TestData.loadTestData();
        Test.startTest();

        Reminder_Schedule__c schedule = new Reminder_Schedule__c(
            First_Reminder_day__c = 1,
            Second_Reminder_day__c = 2
        );
        insert schedule;

        TestData testData = new TestData();

        SurveyInvitation invitation = SurveyService.getInstance()
            .generateInvitation(survey.get(0), schedule, 5, true, testData.pe.Id, communityId);
        insert invitation;
        Test.stopTest();
    }

    @IsTest
    static void getSurveyInvitationIdTest() {
        List<Survey> survey = [SELECT Id, Name FROM Survey WHERE ActiveVersionId != NULL LIMIT 1];
        if (survey.isEmpty())
            return;

        TestData.loadTestData();
        Test.startTest();
        Reminder_Schedule__c schedule = new Reminder_Schedule__c(
            First_Reminder_day__c = 1,
            Second_Reminder_day__c = 2
        );
        insert schedule;

        TestData testData = new TestData();

        ts = new Trial_Survey__c(
            Active_On_Status__c = PEStatusState.PE_STATUS_SCREENING_IN_PROGRESS,
            Clinical_Trial_Profile__c = testData.ctp.Id,
            Expires_After_Days__c = 5,
            Survey__c = survey.get(0).Id,
            Whose_response_needed__c = 'Patient only'
        );
        insert ts;
        insert SurveyService.getInstance()
            .generateInvitation(
                ts,
                testData.pe.Id,
                communityId,
                System.today(),
                UserInfo.getTimeZone()
            );

        SurveyService.getInstance()
            .isInvitationExpired(
                SurveyService.getInstance()
                    .getSurveyInvitationId(survey.get(0).Id, testData.pe.Participant_Contact__c)
            );
        Test.stopTest();
    }
}