force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/CommunityTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommunityTemplate__c</fullName>
    <label>Community Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>IQVIA Patient Portal</label>
            </value>
            <value>
                <fullName>GSK</fullName>
                <label>GSK Pan Oncology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Res_study__c/Res_study__c.object-meta.xml
<CustomObject>
    <label>Study Resource</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Res-study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Res-study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Res_study__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Resource</relationshipLabel>
    <relationshipName>Resource</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Study</relationshipLabel>
    <relationshipName>Study</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_PI__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_PI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To PI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object contains Video/Articles</description>
    <!--enableLicensing>false</enableLicensing-->
    <label>Resource</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Resource__c/fields/Resource_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Resource_Visibility__c</fullName>
    <label>Resource Visibility</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_LibraryPIRemote.cls
/**
 * Created by Nikita Abrazhevitch on 18-May-20.
 */

@IsTest
public class Test_LibraryPIRemote {
    @IsTest
    static void testBehavior() {
        TestData.loadTestData();
        Test.startTest();
        TestData testDataInstance = new TestData();
        List<Resource__c> resources = new List<Resource__c>{
            new Resource__c(Resource_Visibility__c = 'PI', Language__c = 'en_US',
                           RecordTypeId = Schema.SObjectType.Resource__c.getRecordTypeInfosByName()
                    .get('Document')
                    .getRecordTypeId()),
            new Resource__c(
                Language__c = 'en_US',
                Resource_Visibility__c = 'PI',
                RecordTypeId = Schema.SObjectType.Resource__c.getRecordTypeInfosByName()
                    .get('Document')
                    .getRecordTypeId()
            )
        };
        insert resources;
        update new Clinical_Trial_Profile__c(
            Id = testDataInstance.ctp.Id,
            CommunityTemplate__c = 'Default'
        );
        Res_study__c studyRes = new Res_study__c(
            Resource__c = resources[1].Id,
            Visible_To_PI__c = true,
            Clinical_Trial_Profile__c = testDataInstance.ctp.Id
        );
        insert studyRes;

        string searchstr = 'study';
        System.runAs(testDataInstance.piUser) {
            LibraryPIRemote.getInitData(false, null, null, 'Default');
            LibraryPIRemote.getInitData(true, null, null, 'Default');
            LibraryPIRemote.getInitData(true, 'en_US', searchstr, 'Default');
        }
        Test.stopTest();
    }
    @IsTest
    static void Test_Downloaddocument() {
        TestData.loadTestData();
        Test.startTest();
        TestData testDataInstance = new TestData();
        List<Resource__c> resources = new List<Resource__c>{
            new Resource__c(Resource_Visibility__c = 'PI', Language__c = 'en_US'),
            new Resource__c(
                Language__c = 'en_US',
                Resource_Visibility__c = 'PI',
                RecordTypeId = Schema.SObjectType.Resource__c.getRecordTypeInfosByName()
                    .get('Document')
                    .getRecordTypeId()
            )
        };
        insert resources;
        Res_study__c studyRes = new Res_study__c(
            Resource__c = resources[1].Id,
            Visible_To_PI__c = true,
            Clinical_Trial_Profile__c = testDataInstance.ctp.Id
        );
        insert studyRes;

        // Test.startTest();
        ContentVersion contentVersionInsert = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.jpg',
            VersionData = Blob.valueOf('Test Content Data'),
            IsMajorVersion = true
        );
        insert contentVersionInsert;

        // Test INSERT
        List<ContentDocument> documents = [
            SELECT Id, Title, LatestPublishedVersionId
            FROM ContentDocument
        ];

        ContentDocumentLink DDL = new ContentDocumentLink(
            ContentDocumentId = Documents[0].id,
            LinkedEntityId = resources[1].Id
        );
        insert DDL;
        LibraryPIRemote.getBase64Resource(resources[1].id,'en_US' );
        Test.stopTest();
    }
}