force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Condition_s_Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Condition_s_Therapeutic_Area__c</fullName>
    <description>Therapeutic Area</description>
    <inlineHelpText>This field should map to the &quot;Condition&quot; field in clinicaltrials.gov</inlineHelpText>
    <label>Condition(s) Therapeutic Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Enable_RP_Outreach_Email__c.field-meta.xml
<CustomField>
    <fullName>Enable_RP_Outreach_Email__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable RP Outreach Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Link_to_ePR_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Link_to_ePR_Campaign__c</fullName>
    <label>Link to ePR Campaign</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Patient_Outreach_Info__c.field-meta.xml
<CustomField>
    <fullName>Patient_Outreach_Info__c</fullName>
    <label>Patient Outreach Info</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Legal_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Status__c</fullName>
    <label>Legal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <label>Mailing Country Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Outreach_Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Email_Status__c</fullName>
    <label>Outreach Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Outreach_Mail_Sent__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Mail_Sent__c</fullName>
    <label>Outreach Mail Sent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Name__c.field-meta.xml
<CustomField>
    <fullName>Participant_Name__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Participant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Surname__c.field-meta.xml
<CustomField>
    <fullName>Participant_Surname__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Participant Surname</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Patient_Auth__c.field-meta.xml
<CustomField>
    <fullName>Patient_Auth__c</fullName>
    <label>Patient Auth</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Patient_ID__c.field-meta.xml
<CustomField>
    <fullName>Patient_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Patient ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/PI_Contact__c.field-meta.xml
<CustomField>
    <fullName>PI_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PI Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (PI)</relationshipLabel>
    <relationshipName>Participant_Profile2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Primary_Delegate_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delegate_Email__c</fullName>
    <label>Primary Delegate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Primary_Delegate_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delegate_First_Name__c</fullName>
    <label>Primary Delegate First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Primary_Delegate_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delegate_Last_Name__c</fullName>
    <label>Primary Delegate Last Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Name__c</fullName>
    <formula>Study_Site__r.Clinical_Trial_Profile__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Study Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/YOB__c.field-meta.xml
<CustomField>
    <fullName>YOB__c</fullName>
    <label>YOB</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/rpPatientOutreachController.cls
public without sharing class rpPatientOutreachController {
    @AuraEnabled(cacheable=false)                          
    public static list<Clinical_Trial_Profile__c> fetchOutreachInfo(list<string> peIds) {
        set<Clinical_Trial_Profile__c> studies = new set<Clinical_Trial_Profile__c>();
        for(Participant_Enrollment__c pe : [select  Clinical_Trial_Profile__c,Clinical_Trial_Profile__r.Study_Code_Name__c, Clinical_Trial_Profile__r.Patient_Outreach_Info__c FROM Participant_Enrollment__c where id in : peids]){
            studies.add(new Clinical_Trial_Profile__c(id=pe.Clinical_Trial_Profile__c,Study_Code_Name__c=pe.Clinical_Trial_Profile__r.Study_Code_Name__c, Patient_Outreach_Info__c=pe.Clinical_Trial_Profile__r.Patient_Outreach_Info__c ));
        }
        return  new list<Clinical_Trial_Profile__c>(studies);
    }
    @AuraEnabled(cacheable=false)                          
    public static List<Participant_Enrollment__c> getPatientInfo(String peId) {
        List<Participant_Enrollment__c> res = [SELECT id, Outreach_Email_Status__c,Patient_ID__c,Participant_Name__c, Participant_Surname__c, Email__c, Study_Name__c, Legal_Status__c, YOB__c, Patient_Auth__c, Clinical_Trial_Profile__r.Enable_RP_Outreach_Email__c
               FROM Participant_Enrollment__c where Id=:peId and Clinical_Trial_Profile__r.Enable_RP_Outreach_Email__c = true];
        res[0].Outreach_Email_Status__c = 'Submitted';
        update res;
       return res;
    }
    //GN: created for bulk validation of PE records.
    @AuraEnabled
    public static Map<String,String> peBulkValidate(List<Id> listOfPeIds){
        List<rpPatientOutreachAPIController.PatientOutreachWrapper> patientOutreachWrapperList 
        = new List<rpPatientOutreachAPIController.PatientOutreachWrapper>();

        Map<String, String> peValidationResultMap = new Map<String, String>();
        List<Participant_Enrollment__c> peDetails = [SELECT id,Name,Patient_ID__c, Participant_Name__c, Participant_Surname__c, Email__c,Study_Name__c, 
                                                     Legal_Status__c, YOB__c, Patient_Auth__c,Outreach_Email_Status__c,Primary_Delegate_Email__c,Primary_Delegate_First_Name__c,
                                                     Primary_Delegate_Last_Name__c,CreatedDate,Mailing_Country_Code__c,
                                                     PI_Contact__r.Name,PI_Contact__r.Phone,PI_Contact__r.Language__c,PI_Contact__r.Email,PI_Contact__r.MailingCity,PI_Contact__r.MailingState,
                                                     PI_Contact__r.MailingCountry, PI_Contact__r.MailingPostalCode, PI_Contact__r.MailingAddress,PI_Contact__r.MailingStreet,
                                                     Clinical_Trial_Profile__r.Study_Code_Name__c,Clinical_Trial_Profile__r.Link_to_ePR_Campaign__c,
                                                     Clinical_Trial_Profile__r.Condition_s_Therapeutic_Area__c,Clinical_Trial_Profile__r.Enable_RP_Outreach_Email__c

                                                     FROM Participant_Enrollment__c 
                                                     WHERE Id IN : listOfPeIds]; 

        List<Participant_Enrollment__c> submittedPEs = new  List<Participant_Enrollment__c>();
        for(Participant_Enrollment__c peRec : peDetails){
            String peRecValidationMsgs = '';
            Boolean isError = false;
            if(!peRec.Clinical_Trial_Profile__r.Enable_RP_Outreach_Email__c){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'Outreach not Supported';
                isError = true;
            }
            if(String.isBlank(peRec.Patient_ID__c)){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'Patient Id';
                isError = true;
            }
            if(String.isBlank(peRec.Participant_Name__c)){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'First Name';
                isError = true;
            }
            if(String.isBlank(peRec.Participant_Surname__c)){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'Last Name';
                isError = true;
            }
            if(String.isBlank(peRec.Email__c)){
                if(String.isBlank(peRec.Primary_Delegate_Email__c)){
                    peRecValidationMsgs = peRecValidationMsgs + ', ' + 'Email';
                    isError = true;
                }
            }
            if(String.isBlank(peRec.Study_Name__c)){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'Study Name';
                isError = true;
            }
            if(peRec.Legal_Status__c != 'Yes'){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'Legal Status';
                isError = true;
            }
            if(String.isBlank(peRec.YOB__c)){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'YOB';
                isError = true;
            }
            if(peRec.Patient_Auth__c != 'Yes'){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'Patient Auth';
                isError = true;
            }
            if(peRec.Outreach_Email_Status__c == 'Submitted'){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'Outreach already initiated';
                isError = true;
            }
            if(peRec.Outreach_Email_Status__c == 'Delivered'){
                peRecValidationMsgs = peRecValidationMsgs + ', ' + 'Outreach was sent';
                isError = true;
            }
            if(isError){          
                peValidationResultMap.put(peRec.Patient_ID__c,peRecValidationMsgs.substring(1));
            }     
            else if(!isError){
                peRec.Outreach_Email_Status__c = 'Submitted';
                peRec.Outreach_Mail_Sent__c = 'Yes';
                rpPatientOutreachAPIController.PatientOutreachWrapper outreachWrapper = rpPatientOutreachAPIController.generateObjectToJSON(peRec);
                patientOutreachWrapperList.add(outreachWrapper);
                submittedPEs.add(peRec);
            }
        }     
        try{
            if(!submittedPEs.isEmpty()){
                String json = JSON.serialize(patientOutreachWrapperList);
                rpPatientOutreachAPIController.sendDataToMuleSoft(json);
                update submittedPEs;
            }
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        return peValidationResultMap;
    }


}