force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/ECOA_Is_Avaialble__c.field-meta.xml
<CustomField>
    <fullName>ECOA_Is_Avaialble__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECOA Is Avaialble</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_GUID__c.field-meta.xml
<CustomField>
    <fullName>Study_GUID__c</fullName>
    <label>Study GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECOA_Study_Schedule__c/ECOA_Study_Schedule__c.object-meta.xml
<CustomObject>
    <label>ECOA Study Schedule</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>ECOA Study Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECOA Study Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ECOA_Study_Schedule__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>ECOA Study Schedules</relationshipLabel>
    <relationshipName>ECOA_Study_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ECOA_Study_Schedule__c/fields/ClinroRuleSetGuid__c.field-meta.xml
<CustomField>
    <fullName>ClinroRuleSetGuid__c</fullName>
    <label>ClinroRuleSetGuid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECOA_Study_Schedule__c/fields/EproRuleSetGuid__c.field-meta.xml
<CustomField>
    <fullName>EproRuleSetGuid__c</fullName>
    <label>EproRuleSetGuid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/tests/classes/Test_Batch_CreateECOASite.cls
@IsTest
private class Test_Batch_CreateECOASite {
    @testSetup
    static void setUp() {
        Test.startTest();
        TestData.loadTestData();
        Test.stopTest();
        Clinical_Trial_Profile__c ctp = [
            SELECT id, Study_GUID__c
            FROM Clinical_Trial_Profile__c
            LIMIT 1
        ];
        ctp.Study_GUID__c = 'testguid123';
        ctp.ECOA_Is_Avaialble__c = true;
        update ctp;
        ECOA_Study_Schedule__c obj1 = new ECOA_Study_Schedule__c();
        obj1.Clinical_Trial_Profile__c = ctp.id;
        obj1.ClinroRuleSetGuid__c = 'test123';
        obj1.EproRuleSetGuid__c = 'eprorule12';
        insert obj1;
    }

    @isTest
    static void ecoaTest() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Test_ECOAServiceMockCallout());

        Batch_CreateECOASite obj1 = new Batch_CreateECOASite();
        DataBase.executeBatch(obj1);
        obj1.getRecommendedRelaunchInterval();
        obj1.getRecommendedScopeSize();
        obj1.getBatchDescription();

        Test.StopTest();
    }
}