force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
    <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
    <label>NCT Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Suppress_Participant_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Participant_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, no emails will be sent to participants for this study.</inlineHelpText>
    <label>Suppress Participant Emails</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>HCP Enrollments</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/HCP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HCP_Contact__c</fullName>
    <label>HCP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HCP&#39;s Study Sites</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Study_Site__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>HCP Status per clinical trial by PI</description>
    <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
    <label>HCP Status</label>

    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>On Hold (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending Orientation</fullName>
            </value>
            <value>
                <fullName>Declined (Approval)</fullName>
            </value>
            <value>
                <fullName>On Hold (Approval)</fullName>
            </value>
            <value>
                <fullName>Declined (Activation)</fullName>
            </value>
            <value>
                <fullName>On Hold (Activation)</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Activated (Admin)</fullName>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
            </value>
            <value>
                <fullName>Declined (Admin)</fullName>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hospital of rainbow</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Referring HCPs</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Healthcare_Provider__c/Healthcare_Provider__c.object-meta.xml
<CustomObject>
    <label>Healthcare Provider</label>
    <nameField>
        <displayFormat>PROVIDERID{00000}</displayFormat>
        <label>Healthcare Provider Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Healthcare Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Healthcare_Provider__c/fields/HCP_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>HCP_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HCP Enrollment</label>
    <referenceTo>HCP_Enrollment__c</referenceTo>
    <relationshipLabel>Healthcare Providers</relationshipLabel>
    <relationshipName>Healthcare_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Healthcare_Provider__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Healthcare Providers</relationshipLabel>
    <relationshipName>Healthcare_Providers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Healthcare_Provider__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>No Sharing</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/HCP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HCP_Contact__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; HCP__r.HCP_Contact__c ,HCP__r.HCP_Contact__r.FirstName&amp;&quot; &quot;&amp;  HCP__r.HCP_Contact__r.LastName )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HCP Contact</label>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Override_PI_Referral_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_PI_Referral_Status__c</fullName>
    <label>PI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Accepted (Admin)</fullName>
                <isActive>false</isActive>
                <label>Accepted (Admin)</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Active (Admin)</fullName>
                <isActive>false</isActive>
                <label>Active (Admin)</label>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
                <isActive>false</isActive>
                <label>Deactivated (Admin)</label>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
                <isActive>false</isActive>
                <label>Declined (Acceptance)</label>
            </value>
            <value>
                <fullName>No Response</fullName>
                <isActive>false</isActive>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
                <isActive>false</isActive>
                <label>Non-Responsive (Admin)</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
                <isActive>false</isActive>
                <label>On Hold (Admin)</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Study_Site_Key__c.field-meta.xml
<CustomField>
    <fullName>Study_Site_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Study Site Key</label>
    <length>255</length>

    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Study_Site_Type__c.field-meta.xml
<CustomField>
    <fullName>Study_Site_Type__c</fullName>
    <label>Study Site Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Traditional</fullName>
                <default>true</default>
                <label>Traditional</label>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Suppress_Participant_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Participant_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, no emails will be sent to participants for this study site.</inlineHelpText>
    <label>Suppress Participant Emails</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/tests/classes/Test_EmailTemplateController.cls
/**
 * Created by Slav on 21.08.2019.
 */

@IsTest(SeeAllData=true)
public with sharing class Test_EmailTemplateController {

    @IsTest
    public static void runTest() {
        TestData.loadTestData();
        Test.startTest();

        TestData testDataInstance = new TestData();
        System.runAs(testDataInstance.participantUser) {

            EmailTemplateController controller = new EmailTemplateController();
            ParametersDataProvider provider = getDataProvider(controller);
            provider.isDelegate = true;
            provider.userMode = CommunityService.USER_MODE_PARTICIPANT;
            String s = controller.bodyLabel;

            controller = new EmailTemplateController();
            provider = getDataProvider(controller);
            provider.isDelegate = true;
            provider.userMode = CommunityService.USER_MODE_PI;
            s = controller.bodyLabel;

            controller = new EmailTemplateController();
            provider = getDataProvider(controller);
            provider.isDelegate = false;
            provider.userMode = CommunityService.USER_MODE_PARTICIPANT;
            provider.parameters.put('ReferralSource', 'OTHER');
            s = controller.bodyLabel;

            controller = new EmailTemplateController();
            provider = getDataProvider(controller);
            provider.isDelegate = false;
            provider.userMode = CommunityService.USER_MODE_PARTICIPANT;
            provider.parameters.put('ReferralSource', 'PI');
            s = controller.bodyLabel;

            controller = new EmailTemplateController();
            provider = getDataProvider(controller);
            provider.isDelegate = false;
            provider.userMode = CommunityService.USER_MODE_PARTICIPANT;
            provider.parameters.put('ReferralSource', 'HCP');
            s = controller.bodyLabel;

            controller = new EmailTemplateController();
            provider = getDataProvider(controller);
            provider.isDelegate = false;
            provider.userMode = CommunityService.USER_MODE_PI;
            s = controller.bodyLabel;

            controller = new EmailTemplateController();
            provider = getDataProvider(controller);
            provider.isDelegate = false;
            provider.userMode = CommunityService.USER_MODE_HCP;
            s = controller.bodyLabel;
        }
    }

    @IsTest
    public static void runTestHCP() {
        TestData.loadTestData();
        Test.startTest();
        TestData testDataInstance = new TestData();
        System.runAs(testDataInstance.hcpUser) {
            EmailTemplateController controller = new EmailTemplateController();
            controller.sourceRecordId = testDataInstance.hcpUser.Id;
            controller.multiplePIMessageValue = false;
//            controller.getDataProvider();
//            String emailTemplateBackground = controller.emailTemplateBackground;
//            Boolean hasPIRPDelegationRecords = controller.hasPIRPDelegationRecords;
//            String emailTemplateTextBackground = controller.emailTemplateTextBackground;
//            String emailTemplateHeaderBackground = controller.emailTemplateHeaderBackground;
//            String emailTemplateHeader = controller.emailTemplateHeader;
//            String emailTemplateTitle = controller.emailTemplateTitle;
//            String emailTemplateBrandLogo = controller.emailTemplateBrandLogo;
//            String emailTemplateBottomLogo = controller.emailTemplateBottomLogo;
//            String emailTemplateBrandLogoCSS = controller.emailTemplateBrandLogoCSS;
//            String dataParametersValue = controller.dataParametersValue;
        }

        testDataInstance.hcpEnrollment = [
                SELECT Id,
                        HCP_Contact__c
                FROM HCP_Enrollment__c
                WHERE Id = :testDataInstance.hcpEnrollment.Id
        ];
        Healthcare_Provider__c provider = new Healthcare_Provider__c(Participant_Enrollment__c = testDataInstance.pe.Id, HCP_Enrollment__c = testDataInstance.hcpEnrollment.Id);
        insert provider;
        System.runAs(testDataInstance.hcpUser) {
            EmailTemplateController controller = new EmailTemplateController();
            controller.sourceRecordId = testDataInstance.hcpUser.Id;
            controller.multiplePIMessageValue = true;
//            controller.getDataProvider();
        }
        Account acc = [
                SELECT Id
                FROM Account
                WHERE Name = 'PI Account'
        ];
        Contact piContact = new Contact(
                FirstName = 'PITD2',
                LastName = 'PITD2',
                Email = 'pi2@emil.com',
                AccountId = acc.Id
        );
        insert piContact;
        Clinical_Trial_Profile__c ctp = [
                SELECT Id
                FROM Clinical_Trial_Profile__c
                WHERE NCT_Number__c = 'NCT99999999'
        ];
        Account ssAccount = [
                SELECT Id
                FROM Account
                WHERE Name = 'Study Site Account'
        ];
        Study_Site__c studySite = new Study_Site__c(
                Principal_Investigator__c = piContact.Id,
                Clinical_Trial_Profile__c = ctp.Id,
                Override_PI_Referral_Status__c = StudySiteService.PI_S_INVITATION_SENT,
                Site__c = ssAccount.Id,
                Study_Site_Key__c = '001',
                Study_Site_Type__c = 'Traditional',
                Suppress_Participant_Emails__c = false,
                Study_Site_Number__c = 'SS1'
        );
        insert studySite;
        HCP_Enrollment__c hcpEnrollment = new HCP_Enrollment__c(
                Study_Site__c = studySite.Id,
                HCP_Contact__c = testDataInstance.hcpEnrollment.HCP_Contact__c,
                Status__c = HCPEnrollmentService.HCP_S_ACTIVATED
        );
        insert hcpEnrollment;

        System.runAs(testDataInstance.hcpUser) {
            EmailTemplateController controller = new EmailTemplateController();
            controller.sourceRecordId = testDataInstance.hcpUser.Id;
            controller.multiplePIMessageValue = true;
//            controller.getDataProvider();
        }
    }

    @IsTest
    public static void runTestHCP2() {
        TestData.loadTestData();
        Test.startTest();
        TestData testDataInstance = new TestData();
        delete [
                SELECT Id
                FROM HCP_Enrollment__c
        ];
        System.runAs(testDataInstance.hcpUser) {
            EmailTemplateController controller = new EmailTemplateController();
            controller.sourceRecordId = testDataInstance.hcpUser.Id;
            controller.multiplePIMessageValue = true;
//            controller.getDataProvider();
        }
    }

    @IsTest
    public static void runTest2() {
        TestData.loadTestData();
        Test.startTest();
        TestData testDataInstance = new TestData();
        EmailTemplateController controller = new EmailTemplateController();
        System.runAs(testDataInstance.participantUser) {
            String s = controller.bodyLabel;
            controller = new EmailTemplateController();
            controller.bodyLabel = 'body ## value';
            try {
                s = controller.bodyLabel;
            } catch (Exception e) {
                //
            }

            s = controller.titleLabel;

            controller.headerLabel = 'header ## value';
            try {
                s = controller.headerLabel;
            } catch (Exception e) {
                //
            }

            controller.headerLabel = 'header value';
            s = controller.headerLabel;

            s = controller.preSignatureLabel;
            controller.preSignatureLabel = 'string\n new line';
            try {
                s = controller.preSignatureLabel;
            } catch (Exception e) {
                //
            }
            s = controller.signatureLabel;

            controller.greetingLabel = 'greeting ## value';
            try {
                s = controller.greetingLabel;
            } catch (Exception e) {
                //
            }

            controller.buttonLabel = 'button ## value';
            s = controller.buttonLabel;

            controller.buttonUrl = 'button URL ## value';
            s = controller.buttonUrl;

            controller.getResultUserMode();
            controller.getIsDelegate();
        }
    }

    private static ParametersDataProvider getDataProvider(EmailTemplateController controller) {
        controller.sourceRecordId = UserInfo.getUserId();
        controller.replaceLineBreaksOnHTMLBreaks = true;
        controller.communityTemplateValue = CommunityTemplateService.TEMPLATE_DEFAULT;

        ParametersDataProvider provider;
//        = controller.getDataProvider();
//        provider.userMode = 'userType';
//        provider.recipientName = 'recipientName';
//        provider.recipientId = UserInfo.getUserId();
//        provider.recipientLanguage = 'recipientLanguage';
//        provider.parametersProviderName = 'parametersProviderName';
        return provider;
    }

}