force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>HCP Enrollments</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hospital of rainbow</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Referring HCPs</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StudyDetailItem.cls
/**
 * Created by RAMukhamadeev on 2019-04-16.
 */

public class StudyDetailItem implements Comparable {
    public static String sortType;

    public Clinical_Trial_Profile__c trial;
    public List<StudyActions.Action> studyActions;
    public Map<String, StudyActions.Action> actionsMap;
    public String studyStatus;
    public Study_Site__c ss;
    public List<StudySiteService.StudySiteDistanceWrapper> sites = new List<StudySiteService.StudySiteDistanceWrapper>();
    public StudySiteService.StudySiteDistanceWrapper site;
    public List<StudyTrialService.EnrollmentWrapper> hcpEnrollments = new List<StudyTrialService.EnrollmentWrapper>();
    public HCP_Enrollment__c hcpe;
    public List<StudyTotalPassed> statistics = new List<StudyTotalPassed>();
    public String trialRecruitmentStatusLabel;
    public Boolean hasHCPEnrollments;
    public Boolean hasActiveHCPEnrollments;
    public String distance;
    public String therapeuticArea;
    public Datetime maxHCPCreatedDate;
    public Boolean hasPatients;
    public List<Study_Site__c> ssList;
    public String primaryContactName;

    public Integer compareTo(Object compareTo) {
        StudyDetailItem compareItem = (StudyDetailItem) compareTo;
        if (sortType == 'Distance ASC') {
            if (this.sites.isEmpty()) {
                if (compareItem.sites.isEmpty()) {
                    return 0;
                } else {
                    return 1;
                }
            } else if (compareItem.sites.isEmpty()) {
                return -1;
            } else if (this.sites[0].siteType == StudySiteService.SS_TYPE_VIRTUAL) {
                return -1;
            } else if (compareItem.sites[0].siteType == StudySiteService.SS_TYPE_VIRTUAL) {
                return 1;
            } else if (this.sites[0].distance == null) {
                return 1;
            } else if (compareItem.sites[0].distance == null) {
                return -1;
            } else if (this.sites[0].distance > compareItem.sites[0].distance) {
                return 1;
            } else if (this.sites[0].distance < compareItem.sites[0].distance) {
                return -1;
            } else {
                return 0;
            }
        }
        if (sortType == 'CreatedDate DESC') {
            if (compareItem.maxHCPCreatedDate > this.maxHCPCreatedDate || this.maxHCPCreatedDate == null) {
                return 1;
            } else if (this.maxHCPCreatedDate > compareItem.maxHCPCreatedDate || compareItem.maxHCPCreatedDate == null) {
                return -1;
            } else {
                return 0;
            }
        }

        return 0;
    }
}