force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_GUID__c.field-meta.xml
<CustomField>
    <fullName>Study_GUID__c</fullName>
    <label>Study GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/tests/classes/Test_ECOADiariesController.cls
@isTest
private class Test_ECOADiariesController {
    static user thisUser;
    @testSetup
    static void setUp() {
        TestData.loadTestData();
        Clinical_Trial_Profile__c ctp = [
            SELECT id, Study_GUID__c
            FROM Clinical_Trial_Profile__c
            LIMIT 1
        ];
        ctp.Study_GUID__c = 'testguid123';
        update ctp;
    }

    @isTest
    static void ecoaTest() {
        Test.startTest();

        try {
            ECOADiariesController.getToken();
        } catch (Exception ex) {
            system.debug('line number:' + ex.getLineNumber());
        }
        try {
            ECOADiariesController.getSubjectGuid();
        } catch (Exception ex) {
            system.debug('line number:' + ex.getLineNumber());
        }
        Test.StopTest();
    }
}