force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Detailed_Description__c.field-meta.xml
<CustomField>
    <fullName>Detailed_Description__c</fullName>
    <description>Study Detail Description</description>
    <inlineHelpText>This field should map to the &quot;Detailed Description&quot; field in clinicaltrials.gov</inlineHelpText>
    <label>Detailed Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Override_Description__c.field-meta.xml
<CustomField>
    <fullName>Override_Description__c</fullName>
    <inlineHelpText>If populated, this will be the description seen within the community by PIs, HCPs, Participants, etc. describing the clinical study.  This will &quot;override&quot; display of the &quot;Detailed Description&quot; if &quot;Override Description&quot; is populated.</inlineHelpText>
    <label>Override Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Override_Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_Recruitment_Status__c</fullName>
    <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
    <label>Override Recruitment Status</label>

    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actively Enrolling</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>No_Longer_Enrolling</fullName>
                <label>No Longer Enrolling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Override_Status_Updated_By__c.field-meta.xml
<CustomField>
    <fullName>Override_Status_Updated_By__c</fullName>
    <description>Populated via workflow rule when the Override Status field is changed.  Shows the profile of the user who changed the field. Validation created around who can change this field by profile.</description>
    <inlineHelpText>Populated via workflow rule when the Override Status field is changed.</inlineHelpText>
    <label>Override Status Updated By</label>
    <length>85</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Status__c</fullName>
    <inlineHelpText>field populated from Data Factory</inlineHelpText>
    <label>CTMS Recruitment Status</label>
<!--    <trackHistory>true</trackHistory>-->
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed Follow-up / In Analysis</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Enrolling</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Open to Enrollment</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Closed to Enrollment</fullName>
            </value>
            <value>
                <fullName>Closed Follow Up / In Analysis</fullName>
                <isActive>false</isActive>
                <label>Closed Follow Up / In Analysis</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Travel_Vendor_Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Travel_Vendor_Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Travel Vendor Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/Patient_Delegate__c.object-meta.xml
<CustomObject>
    <label>Patient Delegate</label>
    <nameField>
        <displayFormat>PD-{00000000}</displayFormat>
        <label>Patient Delegate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Delegates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Delegate__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Delegate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Override_Status_Updated_By__c.field-meta.xml
<CustomField>
    <fullName>Override_Status_Updated_By__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Override Status Updated By</label>
    <length>85</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Status__c</fullName>
    <label>CTMS Recruitment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved for SSV</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Conditional Selected</fullName>
            </value>
            <value>
                <fullName>Contacted (Feasibility)</fullName>
            </value>
            <value>
                <fullName>Contacted (Site ID)</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>Enrollment On Hold</fullName>
            </value>
            <value>
                <fullName>Enrollment Open</fullName>
            </value>
            <value>
                <fullName>Essential Documents in place</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Interested (Feasibility)</fullName>
            </value>
            <value>
                <fullName>Interested (Site ID)</fullName>
            </value>
            <value>
                <fullName>Non-responder (Feasibility)</fullName>
            </value>
            <value>
                <fullName>Non-responder (Site ID)</fullName>
            </value>
            <value>
                <fullName>Not Interested (Feasibility)</fullName>
            </value>
            <value>
                <fullName>Not Interested (Site ID)</fullName>
            </value>
            <value>
                <fullName>Not Selected</fullName>
            </value>
            <value>
                <fullName>Null</fullName>
            </value>
            <value>
                <fullName>Permanently Closed</fullName>
            </value>
            <value>
                <fullName>Prematurely Closed</fullName>
            </value>
            <value>
                <fullName>Preselected</fullName>
            </value>
            <value>
                <fullName>Ready for Initiation</fullName>
            </value>
            <value>
                <fullName>Regulatory Green Light</fullName>
            </value>
            <value>
                <fullName>Regulatory Initiation</fullName>
            </value>
            <value>
                <fullName>Rejected for SSV</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Targeted</fullName>
            </value>
            <value>
                <fullName>Unsure (Feasibility)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TravelVendorSettings__c/TravelVendorSettings__c.object-meta.xml
<CustomObject>
    <label>TravelVendorSettings</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>TravelVendorSettings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TravelVendorSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelVendorSettings__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>TravelVendorSettings</relationshipLabel>
    <relationshipName>TravelVendorSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/triggers-implementation/classes/ClinicalTrialProfileTriggerHandler.cls
/**
 * Created by AlexKetch on 4/16/2019.
 */

public with sharing class ClinicalTrialProfileTriggerHandler{

    public class UpdateClinicalTrialProfile extends TriggerHandler{

        public override void beforeInsert(List<SObject> newList){
            overrideStatusChangedBy(newList, null);
            populateOverrideFields(newList);
            updateShortCommunityName(newList, null);
        }

        public override void beforeUpdate(List<SObject> newList, Map<Id, SObject> oldMap){
            overrideStatusChangedBy(newList, (Map<Id, Clinical_Trial_Profile__c>)oldMap);
            populateOverrideFields(newList);
            populateDateOnTrialComplete(newList, (Map<Id, Clinical_Trial_Profile__c>)oldMap);
            updateShortCommunityName(newList, (Map<Id, Clinical_Trial_Profile__c>)oldMap);
        }

        public override void afterInsert(List<SObject> newList) {
            updateNextNotifyDateByCTP((List<Clinical_Trial_Profile__c>)newList);
        }

        public override void afterUpdate(List<SObject> newList, Map<Id, SObject> oldMap){
            updateClinicalTrialProfile(newList, (Map<Id, Clinical_Trial_Profile__c>)oldMap);
            deleteTravelVendors(newList, (Map<Id, Clinical_Trial_Profile__c>)oldMap);
            updateNextNotifyDateByCTP((List<Clinical_Trial_Profile__c>)newList);
        }

        public override void beforeDelete(List<SObject> oldList) {
        }
    }

    private static void updateClinicalTrialProfile(List<SObject> newList, Map<Id, Clinical_Trial_Profile__c> oldMap) {
        ClinicalTrialProfileService service = (ClinicalTrialProfileService) ClassFactory.newInstance(ClinicalTrialProfileService.class);
        service.deleteRelatedToStudyDocuments((List<Clinical_Trial_Profile__c>) newList,(Map<Id, Clinical_Trial_Profile__c>)oldMap);
        service.addDeleteTherapeuticAreasOnParticipants((List<Clinical_Trial_Profile__c>) newList, (Map<Id, Clinical_Trial_Profile__c>)oldMap);
    }

    private static void overrideStatusChangedBy(List<SObject> newList, Map<Id, Clinical_Trial_Profile__c> oldMap) {
        Profile profile = [SELECT Name FROM Profile WHERE Id =: UserInfo.getProfileId()];
        String profileName = profile.Name;
        for(Clinical_Trial_Profile__c ctp : (List<Clinical_Trial_Profile__c>)newList){
            if((oldMap == null && ctp.Override_Recruitment_Status__c  != null) ||
                    (oldMap != null && oldMap.get(ctp.Id).Override_Recruitment_Status__c != ctp.Override_Recruitment_Status__c)) {
                ctp.Override_Status_Updated_By__c = profileName;
            }
        }
    }

    private static void populateOverrideFields(List<Clinical_Trial_Profile__c> newList) {
        for(Clinical_Trial_Profile__c ctp : newList){
            if((ctp.Recruitment_Status__c == 'Enrolling' || ctp.Recruitment_Status__c == 'Open to Enrollment') && ctp.Override_Status_Updated_By__c != 'IQVIA SPNL'){
                ctp.Override_Recruitment_Status__c = 'Actively Enrolling';
            } else if((ctp.Recruitment_Status__c == 'Closed Follow-up / In Analysis' ||
                    ctp.Recruitment_Status__c == 'Completed' ||
                    ctp.Recruitment_Status__c == 'Enrollment Closed') &&
                    ctp.Override_Status_Updated_By__c != 'IQVIA SPNL'){
                ctp.Override_Recruitment_Status__c = 'Enrollment Closed';
            } else if(ctp.Recruitment_Status__c == 'Discontinued'){
                ctp.Override_Recruitment_Status__c = TrialService.STATUS_NO_LONGER_ENROLLING;
            } else if(ctp.Recruitment_Status__c == 'In Development' ||
                    ctp.Recruitment_Status__c == 'On Hold' ||
                    ctp.Recruitment_Status__c == 'Planning'){
                ctp.Override_Recruitment_Status__c = 'On Hold';
            }
            if(ctp.Detailed_Description__c != null && ctp.Override_Description__c == null){
                ctp.Override_Description__c = ctp.Detailed_Description__c;
            }
        }
    }

    private static void deleteTravelVendors(List<Clinical_Trial_Profile__c> newList, Map<Id, Clinical_Trial_Profile__c> oldMap){
        List<Id> ctpIdsForUpdate = new List<Id>();
        for (Clinical_Trial_Profile__c ctp : newList){
            Clinical_Trial_Profile__c ctpOld = oldMap.get(ctp.Id);
            if(!ctp.Travel_Vendor_Is_Available__c && ctpOld.Travel_Vendor_Is_Available__c) {
                ctpIdsForUpdate.add(ctp.Id);
            }
        }

        List<TravelVendorSettings__c> travelVendorSettingsToDelete = [
                SELECT Id
                FROM TravelVendorSettings__c
                WHERE Study_Site__r.Clinical_Trial_Profile__c IN: ctpIdsForUpdate
        ];
        delete travelVendorSettingsToDelete;
        SettingStoreService.deleteSettings('TravelVendorSetupFilter' , ctpIdsForUpdate);
    }

    private static void updateNextNotifyDateByCTP(List<Clinical_Trial_Profile__c> trialProfiles){
        List<Participant_Enrollment__c> enrollments = [
                SELECT Participant__r.Contact__c
                FROM Participant_Enrollment__c
                WHERE Clinical_Trial_Profile__c IN:trialProfiles
                AND Participant_Status__c IN: PEStatusState.PE_STATUS_GROUP_IN_PROGRESS_ALL
                AND Clinical_Trial_Profile__r.Logged_Out_Days_Notification__c != NULL
        ];

        List<Id> allContactsIds = new List<Id>();
        List<Id> participantContIds = new List<Id>();
        for(Participant_Enrollment__c pe : enrollments) {
            Id contactId = pe.Participant__r.Contact__c;
            allContactsIds.add(contactId);
            participantContIds.add(contactId);
        }

        List<Patient_Delegate__c> patientDelegates = [
                SELECT
                        Id,
                        Contact__c,
                        Contact__r.Next_Notify_Date__c,
                        Participant__r.Contact__c
                FROM Patient_Delegate__c
                WHERE Participant__r.Contact__c IN:participantContIds
        ];

        Map<Id, Id> partCntByDelegateCnt = new Map<Id, Id>();
        for(Patient_Delegate__c pd : patientDelegates) {
            partCntByDelegateCnt.put(pd.Contact__c, pd.Participant__r.Contact__c);
            allContactsIds.add(pd.Contact__c);
        }

        List<User> users = [
                SELECT
                        Id,
                        ContactId,
                        Contact.UserCommunityIsDelegate__c,
                        LastLoginDate
                FROM User
                WHERE IsActive = TRUE
                AND LastLoginDate != NULL
                AND ContactId != NULL
                AND ContactId IN:allContactsIds
        ];

        Map<Id, Integer> nearestNotificationByContactIds = ParticipantService.getNearestLogOutNotification(participantContIds);
        List<Contact> forUpdateContacts = new List<Contact>();
        for(User user : users) {
            Integer daysToNotify;
            if(user.Contact.UserCommunityIsDelegate__c && partCntByDelegateCnt.containsKey(user.ContactId)) {
                if(nearestNotificationByContactIds.containsKey(partCntByDelegateCnt.get(user.ContactId))) {
                    daysToNotify = nearestNotificationByContactIds.get(partCntByDelegateCnt.get(user.ContactId));
                }
            } else if(nearestNotificationByContactIds.containsKey(user.ContactId)){
                daysToNotify = nearestNotificationByContactIds.get(user.ContactId);
            }

            if(daysToNotify == null) continue;
            Date nextNotifyDate = user.LastLoginDate.addDays(daysToNotify).dateGmt();
            forUpdateContacts.add(new Contact(
                    Id = user.ContactId,
                    Next_Notify_Date__c = nextNotifyDate
            ));
        }

        if(!forUpdateContacts.isEmpty()) update forUpdateContacts;
    }

    private static void populateDateOnTrialComplete(List<SObject> newList, Map<Id, Clinical_Trial_Profile__c> oldMap) {
        for(Object obj : newList){
            Clinical_Trial_Profile__c ctp = (Clinical_Trial_Profile__c) obj;
            if(oldMap != null && ctp.Status__c == ClinicalTrialProfileService.STATUS_COMPLETED
                && oldMap.get(ctp.Id).Status__c != ctp.Status__c) {
                ctp.Trial_Complete__c = Date.today();
            }
        }
    }

    private static void updateShortCommunityName(List<SObject> newList, Map<Id, Clinical_Trial_Profile__c> oldMap) {
        for(Clinical_Trial_Profile__c ctp : (List<Clinical_Trial_Profile__c>)newList){
            if((oldMap == null && String.isEmpty(ctp.ShortCommunityName__c) && String.isNotEmpty(ctp.CommunityTemplate__c)) ||
                    (oldMap != null && oldMap.get(ctp.Id).CommunityTemplate__c != ctp.CommunityTemplate__c)) {
                CommunityTemplate template = CommunityTemplateService.getTemplate(ctp.CommunityTemplate__c);
                ctp.ShortCommunityName__c = template.shortCommunityName;
            }
        }
    }
}