force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/CommunityTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommunityTemplate__c</fullName>
    <label>Community Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>IQVIA Patient Portal</label>
            </value>
            <value>
                <fullName>GSK</fullName>
                <label>GSK Pan Oncology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/LanguageCode__c.field-meta.xml
<CustomField>
    <fullName>LanguageCode__c</fullName>
    <label>LanguageCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Res_study__c/Res_study__c.object-meta.xml
<CustomObject>
    <label>Study Resource</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Res-study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Res-study</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Res_study__c/fields/Active_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Active_After_Days__c</fullName>
    <label>Active After Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Active_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_On_Status__c</fullName>
    <label>Active On Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Resource</relationshipLabel>
    <relationshipName>Resource</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Expires_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Expires_After_Days__c</fullName>
    <label>Expires After Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Expires_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Expires_On_Status__c</fullName>
    <label>Expires On Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Participant_Statuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Notify_On_Availability__c.field-meta.xml
<CustomField>
    <fullName>Notify_On_Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify On Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Study</relationshipLabel>
    <relationshipName>Study</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_In_Alumni__c.field-meta.xml
<CustomField>
    <fullName>Visible_In_Alumni__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible In Alumni</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_To_Delegates__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Delegates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Delegates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_Participant__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_PI__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_PI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To PI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object contains Video/Articles</description>
    <!--enableLicensing>false</enableLicensing-->
    <label>Resource</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Resources Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/document_type__c.field-meta.xml
<CustomField>
    <fullName>document_type__c</fullName>
    <label>Document type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/recordTypes/Study_Document.recordType-meta.xml
<RecordType>
    <fullName>Study_Document</fullName>
    <active>true</active>
    <label>Study Document</label>
</RecordType>

force-app/main/default/globalValueSets/Participant_Statuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Failed Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Failed Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded from Referring</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Success</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-Up Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Participation Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Trial Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Drop Out</fullName>
    </customValue>
    <customValue>
        <fullName>Deceased</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Successfully Contacted</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Reach</fullName>
    </customValue>
    <customValue>
        <fullName>Contacted - Not Suitable</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Success</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress - Wash Out Period</fullName>
        <label>In Wash Out Period</label>
    </customValue>
    <customValue>
        <fullName>Ready to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Declined Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent After Screening</fullName>
    </customValue>
    <masterLabel>Participant Statuses</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_StudyDetailAboutStudyRemote.cls
@IsTest(IsParallel=false)
public class Test_StudyDetailAboutStudyRemote {
    @TestSetup
    static void init() {
        Test.startTest();
        TestData.loadTestData();
        TestData.createTCAcceptance();
        Test.stopTest();
    }
    @IsTest
    static void basePITest1() {
        TestData testData = new TestData();
        Account hcpAccount = [SELECT Id FROM Account WHERE Name = 'HCP Account'];
        List<Clinical_Trial_Profile__c> ctpList = [
            SELECT Id, CommunityTemplate__c
            FROM Clinical_Trial_Profile__c
            LIMIT 1
        ];
        ctpList[0].CommunityTemplate__c = 'Janssen';
        update ctpList;
        System.runAs(testData.piUser) {
            Test.startTest();
            StudyListViewController.getStudyTrialList(CommunityService.USER_MODE_PI);
            StudyDetailViewController.getTrialDetail(
                testData.ctp.Id,
                CommunityService.USER_MODE_PI
            );
            StudyDetailAboutStudyRemote.setTrialAcceptedForPI(testData.ctp.Id, null, null);
            StudyDetailAboutStudyRemote.getDocuments(
                CommunityService.USER_MODE_PI,
                testData.ctp.Id
            );
            AccountSettingsController.getInitData(CommunityService.USER_MODE_HCP);
            AccountSettingsController.changeEmail('new@emil.com', CommunityService.USER_MODE_HCP);
            AccountSettingsController.changePassword('Dd231324d13', 'Dd231324d13', '11111');
            ClinicProfileRemote.getClinicProfileData(hcpAccount.Id);
            CommunityFacadeRemote.getCommunityData();
            CommunityFacadeRemote.changeMode(CommunityService.USER_MODE_PI, null, null, null);
        }
        Test.stopTest();
    }
    @IsTest
    static void basePITest2() {
        TestData testData = new TestData();
        Account hcpAccount = [SELECT Id FROM Account WHERE Name = 'HCP Account'];
        List<Clinical_Trial_Profile__c> ctpList = [
            SELECT Id, CommunityTemplate__c
            FROM Clinical_Trial_Profile__c
            LIMIT 1
        ];
        ctpList[0].CommunityTemplate__c = 'Janssen';
        update ctpList;
        testData.ss.Override_PI_Referral_Status__c = 'On Hold';
        update testData.ss;
        Resource__c docPtRes = new Resource__c(
            Content_Type__c = 'Study_Document',
            Description__c = 'testBehavior',
            document_type__c = 'Document',
            Title__c = 'TestRes'
        );
        insert docPtRes;
        Res_study__c resDocStudy = new Res_study__c(
            Active_After_Days__c = 0.00,
            Active_On_Status__c = PEStatusState.PE_STATUS_ENROLLMENT_SUCCESS,
            Clinical_Trial_Profile__c = testData.ctp.Id,
            Expires_After_Days__c = 5,
            Expires_On_Status__c = PEStatusState.PE_STATUS_TREATMENT_PERIOD_STARTED,
            Notify_On_Availability__c = true,
            Resource__c = docPtRes.Id,
            Visible_In_Alumni__c = false,
            Visible_To_Delegates__c = true,
            Visible_To_Participant__c = true,
            Visible_To_PI__c = true
        );
        insert resDocStudy;
        System.runAs(testData.piUser) {
            Test.startTest();
            StudyDetailAboutStudyRemote.setTrialAcceptedForPI(
                testData.ctp.Id,
                null,
                testData.ss.Id
            );
            StudyDetailAboutStudyRemote.getDocuments(
                CommunityService.USER_MODE_PI,
                testData.ctp.Id
            );
        }
        Test.stopTest();
    }

    @IsTest
    static void basePITest3() {
        TestData testData = new TestData();
        Account hcpAccount = [SELECT Id FROM Account WHERE Name = 'HCP Account'];
        List<Clinical_Trial_Profile__c> ctpList = [
            SELECT Id, CommunityTemplate__c
            FROM Clinical_Trial_Profile__c
            LIMIT 1
        ];
        ctpList[0].CommunityTemplate__c = 'Janssen';
        update ctpList;

        testData.ss.Override_PI_Referral_Status__c = 'On Hold';
        update testData.ss;
        Resource__c docPtRes = new Resource__c(
            Content_Type__c = 'Study_Document',
            Description__c = 'testBehavior',
            document_type__c = 'Document',
            Title__c = 'TestRes'
        );
        insert docPtRes;
        Res_study__c resDocStudy = new Res_study__c(
            Active_After_Days__c = 0.00,
            Active_On_Status__c = PEStatusState.PE_STATUS_ENROLLMENT_SUCCESS,
            Clinical_Trial_Profile__c = testData.ctp.Id,
            Expires_After_Days__c = 5,
            Expires_On_Status__c = PEStatusState.PE_STATUS_TREATMENT_PERIOD_STARTED,
            Notify_On_Availability__c = true,
            Resource__c = docPtRes.Id,
            Visible_In_Alumni__c = false,
            Visible_To_Delegates__c = true,
            Visible_To_Participant__c = true,
            Visible_To_PI__c = true
        );
        ContentVersion contentVersion = new ContentVersion(
            LanguageCode__c = 'en_US',
            Title = 'en_US',
            PathOnClient = 'Irregular verbs.pdf',
            VersionData = EncodingUtil.base64Decode('fdsgg5465w')
        );
        insert contentVersion;
        insert resDocStudy;
        Id docId = [
            SELECT Id, ContentDocumentId
            FROM ContentVersion
            WHERE Title = 'en_US'
            LIMIT 1
        ]
        .ContentDocumentId;
        ContentDocumentLink contentDocumentLink = new ContentDocumentLink(
            ContentDocumentId = docId,
            LinkedEntityId = docPtRes.Id
        );
        insert contentDocumentLink;
        Test.startTest();
        System.runAs(testData.piUser) {
            StudyDetailAboutStudyRemote.setTrialAcceptedForPI(
                testData.ctp.Id,
                null,
                testData.ss.Id
            );
            StudyDetailAboutStudyRemote.getDocuments(
                CommunityService.USER_MODE_PI,
                testData.ctp.Id
            );
        }
        Test.stopTest();
    }
    @IsTest
    static void basePITest4() {
        TestData testData = new TestData();
        Account hcpAccount = [SELECT Id FROM Account WHERE Name = 'HCP Account'];
        List<Clinical_Trial_Profile__c> ctpList = [
            SELECT Id, CommunityTemplate__c
            FROM Clinical_Trial_Profile__c
            LIMIT 1
        ];
        ctpList[0].CommunityTemplate__c = 'Janssen';
        update ctpList;

        testData.ss.Override_PI_Referral_Status__c = 'On Hold';
        update testData.ss;
        Test.startTest();
        System.runAs(testData.piUser) {
            StudyDetailAboutStudyRemote.setTrialAcceptedForPI(testData.ctp.Id, null, null);
        }
        Test.stopTest();
    }
}