force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Visit_Result_Type_Sharing__c/Visit_Result_Type_Sharing__c.object-meta.xml
<CustomObject>
    <label>Visit Result Type Sharing</label>
    <nameField>
        <label>Visit Result Type Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Result Type Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Result_Type_Sharing__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Visit Result Type Sharings</relationshipLabel>
    <relationshipName>Visit_Result_Type_Sharings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VisitResultTypeSharingBatchDeletion.cls
global class VisitResultTypeSharingBatchDeletion implements Database.Batchable<sObject>{
	private String ctpId;
    global VisitResultTypeSharingBatchDeletion(String ctpId){
        this.ctpId = ctpId;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        /*List<Visit_Result_Type_Sharing__c> visitResTypeSharingLst = CTPDeletionHelper.getVisitResultTypeSharings(ctpId);
        return Database.getQueryLocator([SELECT Id, Name FROM Visit_Result_Type_Sharing__c WHERE Id IN :visitResTypeSharingLst]);*/
        return Database.getQueryLocator([SELECT Id, Name, Clinical_Trial_Profile__c FROM Visit_Result_Type_Sharing__c 
                                         WHERE Clinical_Trial_Profile__c =:ctpId]); 
    }
    
    global void execute(Database.BatchableContext BC, List<Visit_Result_Type_Sharing__c> visitResTypeSharingLst){
        delete visitResTypeSharingLst;
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}