force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Is_Program__c.field-meta.xml
<CustomField>
    <fullName>Is_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Program</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Participant_Workflow_Final_Step__c.field-meta.xml
<CustomField>
    <fullName>Participant_Workflow_Final_Step__c</fullName>
    <label>Participant Workflow Final Step</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrollment</fullName>
                <default>true</default>
                <label>Enrollment</label>
            </value>
            <value>
                <fullName>Randomization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status_Milestone_Available__c.field-meta.xml
<CustomField>
    <fullName>Status_Milestone_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status/Milestone Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Schedule_Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Visit_Schedule_Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Schedule Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Motivational_Message__c/Motivational_Message__c.object-meta.xml
<CustomObject>
    <label>Motivational Message</label>
    <nameField>
        <displayFormat>MM-{0000}</displayFormat>
        <label>Motivational Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Motivational Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Motivational_Message__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Motivational Messages</relationshipLabel>
    <relationshipName>Motivational_Messages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/Participant_Enrollment_Status_History__c.object-meta.xml
<CustomObject>

    <label>Participant Enrollment Status History</label>
    <nameField>
        <displayFormat>PESH-{0000000}</displayFormat>
        <label>Participant Enrollment Status History Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollment Status History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Participant_Enrollment_Status_History__c/fields/ParticipantEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ParticipantEnrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Participant Enrollment Status History</relationshipLabel>
    <relationshipName>Participant_Enrollment_Status_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Participant Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Participant_Statuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/Patient_Visit__c.object-meta.xml
<CustomObject>
    <label>Patient Visit</label>
    <nameField>
        <displayFormat>PV-{000000}</displayFormat>
        <label>Patient Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Visit__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/visits/objects/Patient_Visit__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/visits/objects/Patient_Visit__c/fields/Visit_Number__c.field-meta.xml
<CustomField>
    <fullName>Visit_Number__c</fullName>
    <label>Visit Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Study_status_desc_and_motivational_msg__mdt/Study_status_desc_and_motivational_msg__mdt.object-meta.xml
<CustomObject>
    <label>Study status desc and motivational msg</label>
    <pluralLabel>Study status descs and motivational msgs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Study_status_desc_and_motivational_msg__mdt/fields/Motivational_message__c.field-meta.xml
<CustomField>
    <fullName>Motivational_message__c</fullName>
    <label>Motivational message</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_status_desc_and_motivational_msg__mdt/fields/PER_Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>PER_Participant_Status__c</fullName>
    <label>PER Participant Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Motivational_Message__c.field-meta.xml
<CustomField>
    <fullName>Motivational_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Motivational Message</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Patient_Portal_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Portal_Name__c</fullName>
    <label>Patient Portal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Description__c.field-meta.xml
<CustomField>
    <fullName>Visit_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Visit Description</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Visit_Number__c.field-meta.xml
<CustomField>
    <fullName>Visit_Number__c</fullName>
    <label>SDH Visit Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Participant_Statuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Failed Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Failed Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded from Referring</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Success</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-Up Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Participation Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Trial Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Drop Out</fullName>
    </customValue>
    <customValue>
        <fullName>Deceased</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Successfully Contacted</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Reach</fullName>
    </customValue>
    <customValue>
        <fullName>Contacted - Not Suitable</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Success</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress - Wash Out Period</fullName>
        <label>In Wash Out Period</label>
    </customValue>
    <customValue>
        <fullName>Ready to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Declined Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent After Screening</fullName>
    </customValue>
    <masterLabel>Participant Statuses</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ppProgressBarUtility.cls
public without sharing class ppProgressBarUtility {
    public class parentWrapper{
        @AuraEnabled
        public list<progressWrapper> progressWrapperList;   
        @AuraEnabled
        public String message; 
        @AuraEnabled
        public String messageDesc;
        @AuraEnabled
        public String journeyLink;     
        @AuraEnabled
        public Integer currentStatusVal;
        @AuraEnabled
        public Boolean isEvent;  
    }
    
    public class progressWrapper{
        @AuraEnabled
        public String title;
        @AuraEnabled
        public String description;   
        @AuraEnabled
        public Integer stepVal;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public Datetime statusDate; 
        @AuraEnabled
        public String recordId;   
    }
    @AuraEnabled
    public static parentWrapper generateProgressBar(String peId){
        parentWrapper pw = new parentWrapper();
        Participant_Enrollment__c pe = [select id,Participant_Status__c,Clinical_Trial_Profile__r.Participant_Workflow_Final_Step__c,Clinical_Trial_Profile__r.Is_Program__c,
                Clinical_Trial_Profile__r.Visit_Schedule_Is_Available__c,Clinical_Trial_Profile__r.Status_Milestone_Available__c,Clinical_Trial_Profile__c,
                (select id,Status__c, Date__c FROM Participant_Enrollment_Status_History__r order by Date__c asc) 
                FROM Participant_Enrollment__c where id=:peId];
        if([select count() FROM Study_status_desc_and_motivational_msg__mdt where PER_Participant_Status__c =:pe.Participant_Status__c]==0){
            return null;
        }
        Boolean isProgram = pe.Clinical_Trial_Profile__r.Is_Program__c;

        if(isProgram && pe.Clinical_Trial_Profile__r.Visit_Schedule_Is_Available__c){
            pw =generateVisitData(peId,pw, isProgram,true,pe);
        }
        else if((!isProgram) && pe.Clinical_Trial_Profile__r.Visit_Schedule_Is_Available__c && pe.Clinical_Trial_Profile__r.Status_Milestone_Available__c){
            //left status/milestone and right is visit
            pw =generateVisitData(peId, pw, isProgram,false,pe);
        }
        else if((!isProgram) && pe.Clinical_Trial_Profile__r.Visit_Schedule_Is_Available__c && (!pe.Clinical_Trial_Profile__r.Status_Milestone_Available__c)){
            pw =generateVisitData(peId,pw, isProgram,true,pe);
        }
        else if((!isProgram) && pe.Clinical_Trial_Profile__r.Status_Milestone_Available__c && (!pe.Clinical_Trial_Profile__r.Visit_Schedule_Is_Available__c)){
            pw = generateStatusBar(pe);
        }
        else{
            return null;
        }
        return pw;
    }
        
    @AuraEnabled
    public static parentWrapper generateData(){
        parentWrapper pw = new parentWrapper();
        pw.progressWrapperList = new list<progressWrapper>(); 
        integer currentSt = 13; //use mods to get this math.mod(7,5) or =5 if greater then 5; might not be used
        Integer count = 1; 
        Integer multiplier = -1;
        for(integer i = 1; i<=20 ; i++){
            progressWrapper prW = new progressWrapper();
            prW.title = i+': Title of treatment period';
            prW.description = 'Brief description of what occurs and what is expected during treatment period. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam. Ut enim ad minim veniam. Charcters: 200';
            if(i == currentSt){
                multiplier = 1;
                count = 0;
            }
            prW.stepVal = count*multiplier;
            count++;
            
            pw.progressWrapperList.add(prW);
        }
        pw.message = 'This message of treatment period. Lorem Ipsum has been the industrys standard dummy. Characters: 100';
        pw.journeyLink = 'test';
        pw.currentStatusVal = currentSt;
        return pw;
    }

    public static parentWrapper generateVisitData(String peId, parentWrapper pw, Boolean isProgram, Boolean setMotivationMsg, Participant_Enrollment__c pe){
        List<Patient_Visit__c> patientVisits = [select Id,Visit__r.Visit_Description__c, Visit__r.Motivational_Message__c,Visit__r.Patient_Portal_Name__c ,Completed_Date__c,Status__c 
                    from Patient_Visit__c where Participant_Enrollment__c =:peId  order by Visit_Number__c ,Visit__r.Visit_Number__c]; 
        
        pw.isEvent = isProgram;
        Integer count = 1; 
        Integer multiplier = -1;
        if(!patientVisits.isEmpty()){
            pw.progressWrapperList = new list<progressWrapper>(); 
            Boolean upComingVisit = false;
            for( Integer i=0; i<patientVisits.size(); i++){
                Patient_Visit__c patientVisit = patientVisits[i];
                progressWrapper prW = new progressWrapper();
                prW.title = patientVisit.Visit__r.Patient_Portal_Name__c;
                prW.description = patientVisit.Visit__r.Visit_Description__c;      
                prW.status = (patientVisit.Status__c == 'Missed' ? 'UNAVAILABLE' : (patientVisit.Status__c == 'Completed' ? 'COMPLETED' : 'FUTURE'));
                prW.statusDate = patientVisit.Completed_Date__c;
                if(((patientVisit.Status__c != 'Completed' && patientVisit.Status__c != 'Missed' ) || (patientVisits.size()-1 == i))
                 && (!upComingVisit)){
                    upComingVisit = true;
                    pw.currentStatusVal = count;                    
                    pw.message = ( setMotivationMsg ? patientVisit.Visit__r.Motivational_message__c : pw.message);
                    multiplier = 1;
                    count = 0;
                    prW.status = (patientVisit.Completed_Date__c == null && patientVisit.Status__c != 'Completed' && patientVisit.Status__c != 'Missed' ? 'UPCOMING' : prW.status );
                }
                if(pw.isEvent){
                    prW.recordId = patientVisit.Id;
                }
                prW.stepVal = count*multiplier;
                
                count++;                
                pw.progressWrapperList.add(prW);
            }
        }
        if(patientVisits.isEmpty() && setMotivationMsg){
            pw = null;
        }
        if(!setMotivationMsg){
            for(Study_status_desc_and_motivational_msg__mdt statusConfig : [select id,MasterLabel,Status_order__c,PER_Participant_Status__c FROM Study_status_desc_and_motivational_msg__mdt where PER_Participant_Status__c =:pe.Participant_Status__c]){
                pw.message =statusConfig.MasterLabel;
            } 
            for(Study_status_description_motivation__c studyDescConfig : [SELECT Status_Description__c FROM Study_status_description_motivation__c WHERE Study__c  =: pe.Clinical_Trial_Profile__c and Status_Name__c =:pe.Participant_Status__c]){
                pw.messageDesc = studyDescConfig.Status_Description__c;
            }
        }
        return pw;
    }

    public static parentWrapper generateStatusBar(Participant_Enrollment__c pe ){
        Map<string,Study_status_description_motivation__c> statusConfigMap = new Map<string,Study_status_description_motivation__c>();
        integer configCount = 0;
        for(Study_status_description_motivation__c studyDescConfig : [SELECT Status_Name__c,Study__c,Status_Description__c,Status_Motivational_Message__c FROM Study_status_description_motivation__c WHERE Study__c  =: pe.Clinical_Trial_Profile__c]){
            statusConfigMap.put(studyDescConfig.Status_Name__c,studyDescConfig);
            configCount++;
        }
        if(configCount==0){
            return null;
        }
        parentWrapper pw = new parentWrapper();
        pw.progressWrapperList = new list<progressWrapper>(); 
        Integer count = 1; 
        Integer multiplier = -1;
        Map<String,Datetime> peshDateMap = new Map<String,Datetime>();
        for(Participant_Enrollment_Status_History__c pesh : pe.Participant_Enrollment_Status_History__r){
            peshDateMap.put(pesh.Status__c,pesh.Date__c);
        }
        for(Study_status_desc_and_motivational_msg__mdt statusConfig : [select id,MasterLabel,Status_order__c,PER_Participant_Status__c FROM Study_status_desc_and_motivational_msg__mdt where Status_order__c>2 order by Status_order__c  asc]){
            if((statusConfig.MasterLabel == 'Randomization' || statusConfig.MasterLabel == 'Enrollment') && pe.Clinical_Trial_Profile__r.Participant_Workflow_Final_Step__c != statusConfig.MasterLabel){
                continue;
            }
            progressWrapper prW = new progressWrapper();
            prW.title = statusConfig.MasterLabel;
            if(statusConfigMap.containsKey(statusConfig.PER_Participant_Status__c))
                prW.description = statusConfigMap.get(statusConfig.PER_Participant_Status__c).Status_Description__c;
            prW.status = 'FUTURE';
            if(statusConfig.PER_Participant_Status__c == pe.Participant_Status__c){
                pw.currentStatusVal = count;                    
                if(statusConfigMap.containsKey(statusConfig.PER_Participant_Status__c))
                    pw.message = statusConfigMap.get(statusConfig.PER_Participant_Status__c).Status_Motivational_Message__c;
                multiplier = 1;
                count = 0;
                prW.status = 'IN PROGRESS';
            }
            prW.stepVal = count*multiplier;
            
            if(prW.stepVal<0){
                prW.status = 'COMPLETED';
                if(peshDateMap.containsKey(pe.Participant_Status__c)){
                    prW.statusDate = peshDateMap.get(pe.Participant_Status__c);
                }
            }
            count++;                
            pw.progressWrapperList.add(prW);
        }
        pw.journeyLink = ''; 
        return pw;
    }

    @AuraEnabled
    public static String updatePatientVisit(String patientVisitId){
        try {
            PatientVisit pv = new PatientVisit();
            return pv.updatePV(patientVisitId);
        } catch (Exception ex) {
            return 'false';
        }

        
    }

    public without sharing class PatientVisit { 
        public  String updatePV(String patientVisitId){
            try {
                Patient_Visit__c patientVisit = new Patient_Visit__c();
                patientVisit.Id = patientVisitId;
                patientVisit.Completed_Date__c = Date.today();
                patientVisit.Status__c = 'Completed';
                update patientVisit;
                return 'true';
            } catch (Exception ex) {
                return 'false';
            }
            
        }
    }    
}