force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Override_Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_Recruitment_Status__c</fullName>
    <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
    <label>Override Recruitment Status</label>

    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actively Enrolling</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>No_Longer_Enrolling</fullName>
                <label>No Longer Enrolling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Trial_Match_Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Trial_Match_Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables the trial matcher for participant</description>
    <label>Trial Match Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/trial-match/objects/Trial_Match__c/Trial_Match__c.object-meta.xml
<CustomObject>
    <label>Trial Match</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Trial Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trial_Match__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Trial Matches</relationshipLabel>
    <relationshipName>Trial_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trial_Match__c/fields/Is_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Is_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/trial-match/objects/Trial_Match__c/fields/Is_User_notified__c.field-meta.xml
<CustomField>
    <fullName>Is_User_notified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is User notified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/trial-match/objects/Trial_Match__c/fields/Matching_Details__c.field-meta.xml
<CustomField>
    <fullName>Matching_Details__c</fullName>
    <label>Matching Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/trial-match/objects/Trial_Match__c/fields/Matching_Score__c.field-meta.xml
<CustomField>
    <fullName>Matching_Score__c</fullName>
    <label>Matching Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trial_Match__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Trial Matches</relationshipLabel>
    <relationshipName>Trial_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/trial-match/objects/Trial_Match__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_Batch_TrialMatchNotify.cls
@IsTest
private class Test_Batch_TrialMatchNotify {
	@IsTest
    static void batchTrialMatch_test() {
        TestData.loadTestData();
        TestData testData = new TestData();
        testData.ctp.Trial_Match_Is_Available__c = true;
        testData.ctp.Override_Recruitment_Status__c = 'Actively Enrolling';
        Test.startTest();
        update testData.ctp;
        Trial_Match__c tm = new Trial_Match__c(
            Clinical_Trial_Profile__c = testData.ctp.id,
            Is_Eligible__c = true,
            Matched_Date__c = Datetime.now().dateGmt(),
            Matching_Details__c = 'Sample Matching Details',
            Matching_Score__c = 77,
            Is_User_notified__c = False,
            Participant_Enrollment__c = testData.pe.id,
            Passed__c = false,
            Therapeutic_Area__c = 'Therapeutic Area Sample test data'
        );
        insert tm;
        Database.executeBatch(new Batch_TrialMatchNotify());
        Test.stopTest();
    }

}