force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/CommunityTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommunityTemplate__c</fullName>
    <label>Community Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>IQVIA Patient Portal</label>
            </value>
            <value>
                <fullName>GSK</fullName>
                <label>GSK Pan Oncology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Patient_Portal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Patient_Portal_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Patient Portal Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Days_After_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Days_After_Enrolled__c</fullName>
    <formula>TODAY()  -  Enrolled_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days After Enrolled</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Days_Since_Last_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Last_Status_Change__c</fullName>
    <description>Number of days since &quot;Participant Status Last Changed Date&quot; has been updated.</description>
    <formula>FLOOR(NOW() - Participant_Status_Last_Changed_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Last Status Change</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Is_Midpoint__c.field-meta.xml
<CustomField>
    <fullName>Is_Midpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Midpoint</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Reminder_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reminder Schedule</label>
    <referenceTo>Reminder_Schedule__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SurveyL</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Trial_Survey__c.field-meta.xml
<CustomField>
    <fullName>Trial_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trial Survey</label>
    <referenceTo>Trial_Survey__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/Trial_Survey__c.object-meta.xml
<CustomObject>
    <label>Trial Survey</label>
    <nameField>
        <displayFormat>TS-{000}</displayFormat>
        <label>Trial Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trial_Survey__c/fields/Active_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Active_After_Days__c</fullName>
    <description>Days</description>
    <label>Number of Days Active after Enrollment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Active_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_On_Status__c</fullName>
    <label>Active on status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Referral Sent to PI</fullName>
            </value>
            <value>
                <fullName>Referral Accepted</fullName>
            </value>
            <value>
                <fullName>Contact Attempt In Progress</fullName>
            </value>
            <value>
                <fullName>Contact Successful</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Complete</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Trial Surveys</relationshipLabel>
    <relationshipName>Trial_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Expires_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Expires_After_Days__c</fullName>
    <description>Task expires</description>
    <label>Expires after (days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Is_Midpoint__c.field-meta.xml
<CustomField>
    <fullName>Is_Midpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Survey tasks will expire when the Participants status is changed to: Drop Out, Trial Complete or Participation Complete</inlineHelpText>
    <label>Expire in Alumni View</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Reminder_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reminder Schedule</label>
    <referenceTo>Reminder_Schedule__c</referenceTo>
    <relationshipLabel>Trial Surveys</relationshipLabel>
    <relationshipName>Trial_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Trial Surveys</relationshipLabel>
    <relationshipName>Trial_Surveys</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey_end_date__c.field-meta.xml
<CustomField>
    <fullName>Survey_end_date__c</fullName>
    <label>Survey end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey_start_date__c.field-meta.xml
<CustomField>
    <fullName>Survey_start_date__c</fullName>
    <label>Survey start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/scheduled-batch-implementation/classes/Batch_PSECreateInvitation.cls
/**
 * Created by Igor Malyuta on 29.05.2019.
 */

public without sharing class Batch_PSECreateInvitation extends Batch_ScheduledAbstract {
    public Database.QueryLocator start(Database.BatchableContext param1) {
        List<Trial_Survey__c> trialSurveys = [
            SELECT Clinical_Trial_Profile__c
            FROM Trial_Survey__c
            WHERE
                (Active_On_Status__c != NULL
                AND Clinical_Trial_Profile__r.Patient_Portal_Enabled__c = TRUE)
                OR (Survey_start_date__c != NULL 
                AND Survey_start_date__c <= TOMORROW 
                AND Survey_end_date__c != NULL
                AND Survey_end_date__c > today
                )
        ];

        Set<Id> ctpSet = new Set<Id>();
        for (Trial_Survey__c ts : trialSurveys){
            ctpSet.add(ts.Clinical_Trial_Profile__c);
        }
            

        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    Clinical_Trial_Profile__c,
                    Clinical_Trial_Profile__r.CommunityTemplate__c,
                    Days_After_Enrolled__c,
                    Participant_Contact__c,
                    Days_Since_Last_Status_Change__c,
                    Participant_Status__c
                FROM Participant_Enrollment__c
                WHERE
                    Clinical_Trial_Profile__c IN :ctpSet
                    AND Participant_Contact__c NOT IN (SELECT ContactId FROM User WHERE IsActive = FALSE) // changed the query to fetch the record for Minor Participants also as the dont have user record. 
            ]
        );
    }

    public void execute(
        Database.BatchableContext param1,
        List<Participant_Enrollment__c> enrollments
    ) {
        List<Trial_Survey__c> trialSurveys = [
            SELECT
                Id,
                Clinical_Trial_Profile__c,
                Survey__c,
                Survey__r.Name,
                Active_After_Days__c,
                Active_On_Status__c,
                Expires_After_Days__c,
                Is_Midpoint__c,
                Reminder_Schedule__c,
                Whose_response_needed__c
            FROM Trial_Survey__c
            WHERE
                Clinical_Trial_Profile__c IN (
                    SELECT Clinical_Trial_Profile__c
                    FROM Participant_Enrollment__c
                    WHERE Id IN :enrollments
                )
                AND Survey__r.ActiveVersionId != NULL
        ];

        Map<Id, String> trialWhoseResponse = new Map<Id, String>();
        Map<Id, List<Trial_Survey__c>> ctpToTSMap = new Map<Id, List<Trial_Survey__c>>();
        for (Trial_Survey__c t : trialSurveys) {
            trialWhoseResponse.put(t.Id, t.Whose_response_needed__c);

            List<Trial_Survey__c> tsList = ctpToTSMap.get(t.Clinical_Trial_Profile__c);
            if (tsList == null) {
                tsList = new List<Trial_Survey__c>();
                ctpToTSMap.put(t.Clinical_Trial_Profile__c, tsList);
            }
            tsList.add(t);
        }

        Map<String, Id> communitiesMap = CommunityService.getCommunityIdsMap();
        Map<Id, String> networkByPE = new Map<Id, String>();
        for (Participant_Enrollment__c pe : enrollments) {
            String communityName = CommunityTemplateService.getTemplate(
                    pe.Clinical_Trial_Profile__r.CommunityTemplate__c
                )
                .communityName;
            networkByPE.put(pe.Id, communitiesMap.get(communityName));
        }

        Map<String, SurveyInvitation> invitationMap = getInvitationMap(enrollments);
        List<SurveyInvitation> newInvitations = new List<SurveyInvitation>();
        for (Participant_Enrollment__c pe : enrollments) {
            List<Trial_Survey__c> surveys = ctpToTSMap.get(pe.Clinical_Trial_Profile__c);
            if (surveys != null) {
                for (Trial_Survey__c ts : surveys) {
                    if (ts.Active_On_Status__c == pe.Participant_Status__c && ts.Active_After_Days__c <= pe.Days_Since_Last_Status_Change__c) {
                        if (
                            ts.Is_Midpoint__c &&
                            PEStatusState.PE_STATUS_GROUP_COMPLETE.contains(
                                pe.Participant_Status__c
                            )
                        )
                            continue;
                        String key = '' + pe.Id + ts.Id;
                        if (invitationMap.get(key) == null) {
                            newInvitations.add(
                                SurveyService.getInstance()
                                    .generateInvitation(ts, pe.Id, networkByPE.get(pe.Id))
                            );
                        }
                    }
                }
            }
        }

        insert newInvitations;
        Map<Id, String> invitationsVisible = new Map<Id, String>();
        for (SurveyInvitation inv : newInvitations) {
            invitationsVisible.put(inv.Id, trialWhoseResponse.get(inv.Trial_Survey__c));
        }

        TaskService.getInstance().createSurveyTasks(invitationsVisible);
    }

    private Map<String, SurveyInvitation> getInvitationMap(
        List<Participant_Enrollment__c> enrollments
    ) {
        List<SurveyInvitation> surveyInvitation = [
            SELECT Id, Participant_Enrollment__c, Trial_Survey__c
            FROM SurveyInvitation
            WHERE Participant_Enrollment__c IN :enrollments
        ];

        Map<String, SurveyInvitation> invitationMap = new Map<String, SurveyInvitation>();
        for (SurveyInvitation inv : surveyInvitation) {
            invitationMap.put('' + inv.Participant_Enrollment__c + inv.Trial_Survey__c, inv);
        }
        return invitationMap;
    }

    public override Type getType() {
        return Batch_PSECreateInvitation.class;
    }

    public override String getBatchDescription() {
        return 'This job create Survey Tasks from time-based Trial Survey templates on Clinical Trial Profile';
    }

    public override String getRecommendedIntervalMode() {
        return Batch_ScheduledAbstract.INTERVAL_HOURS;
    }

    public override Integer getRecommendedRelaunchInterval() {
        return 2;
    }
}