force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>HCP Enrollments</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Closure__c/Study_Closure__c.object-meta.xml
<CustomObject>
    <label>Study Closure</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Study Closure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Closures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Closure__c/fields/Clinical_Trial_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Clinical Trial Profile Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HCPEnrollmentBatchDeletion.cls
global class HCPEnrollmentBatchDeletion implements Database.Batchable<sObject>, Database.Stateful{
    private String ctpId;
    private Boolean isStudyToDelete = false;
    private Set<Id> hcpEnrollmentIds = new Set<Id>();
    
    global HCPEnrollmentBatchDeletion(String ctpId){
        this.ctpId = ctpId;
    }
    global HCPEnrollmentBatchDeletion(String ctpId, Boolean isStudyToDelete){
        this.ctpId = ctpId;
        this.isStudyToDelete = isStudyToDelete;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query='SELECT Id, Name from HCP_Enrollment__c where Clinical_Trial_Profile__c = :ctpId';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC,List<HCP_Enrollment__c> hcpEnrollLst){
    
        if(isStudyToDelete) {
            delete hcpEnrollLst;
        } else {
        
           hcpEnrollmentIds.addAll((new Map<Id, HCP_Enrollment__c>(
               hcpEnrollLst
           )).keySet());
        }
    }
    global void finish(Database.BatchableContext BC){
        
        if(isStudyToDelete == false) {
        
            List<Study_Closure__c> studyClosureProcessList = [
                SELECT Id FROM Study_Closure__c WHERE Clinical_Trial_Profile_Id__c = :ctpId LIMIT 1
            ];
            if(studyClosureProcessList.isEmpty() == false) {
                
                List<ContentVersion> contentVersions =new List<ContentVersion>();
                contentVersions.add(Batch_SCParticipantEnrollment.constructCsvFile(
                    ctpId, 'HCP Enrollment', hcpEnrollmentIds
                ));
                
                Batch_SCParticipantEnrollment.insertContentVersions(studyClosureProcessList[0].Id, contentVersions);
            }
        }   
    }
}