force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Patient_Portal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Patient_Portal_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Patient Portal Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Televisit_Vendor_is_Available__c.field-meta.xml
<CustomField>
    <fullName>Televisit_Vendor_is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Televisit Vendor is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Invited_To_PP_Date__c.field-meta.xml
<CustomField>
        <fullName>Invited_To_PP_Date__c</fullName>
        <label>Invited To PP Date</label>
        <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Override_PI_Referral_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_PI_Referral_Status__c</fullName>
    <label>PI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Accepted (Admin)</fullName>
                <isActive>false</isActive>
                <label>Accepted (Admin)</label>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Active (Admin)</fullName>
                <isActive>false</isActive>
                <label>Active (Admin)</label>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
                <isActive>false</isActive>
                <label>Deactivated (Admin)</label>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
                <isActive>false</isActive>
                <label>Declined (Acceptance)</label>
            </value>
            <value>
                <fullName>No Response</fullName>
                <isActive>false</isActive>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
                <isActive>false</isActive>
                <label>Non-Responsive (Admin)</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
                <isActive>false</isActive>
                <label>On Hold (Admin)</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site_Activation_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Activation_Status__c</fullName>
    <label>Site Activation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Activated (Admin)</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
                <default>true</default>
                <label>Deactivated</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/Televisit__c.object-meta.xml
<CustomObject>
    <label>Televisit</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Televisit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Televisits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Call will be ended after the planned duration time</inlineHelpText>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>15 minutes</fullName>
            </value>
            <value>
                <fullName>30 minutes</fullName>
            </value>
            <value>
                <fullName>45 minutes</fullName>
            </value>
            <value>
                <fullName>60 minutes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Televisits</relationshipLabel>
    <relationshipName>Televisits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Visit Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Visit_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_End_Date_Time__c</fullName>
    <label>Visit End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/Televisit_Attendee__c.object-meta.xml
<CustomObject>
    <label>Televisit Attendee</label>
    <nameField>
        <label>Televisit Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Televisit Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit_Attendee__c/fields/Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Type__c</fullName>
    <label>Attendee Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Lastname__c.field-meta.xml
<CustomField>
    <fullName>Lastname__c</fullName>
    <label>Lastname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Televisit__c.field-meta.xml
<CustomField>
    <fullName>Televisit__c</fullName>
    <label>Televisit</label>
    <referenceTo>Televisit__c</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TelevisitVendorSettings__c/TelevisitVendorSettings__c.object-meta.xml
<CustomObject>
    <label>TelevisitVendorSettings</label>
    <nameField>
        <displayFormat>TVS-{0000}</displayFormat>
        <label>TelevisitVendorSetting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TelevisitVendorSettings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TelevisitVendorSettings__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>TelevisitVendorSettings</relationshipLabel>
    <relationshipName>TelevisitVendorSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/tele-visits/classes/ParticipantTelevisitRemote.cls
public without sharing class ParticipantTelevisitRemote {
    public static Map<Id,Participant_Enrollment__c> perMapForMultiRole = New Map<Id,Participant_Enrollment__c>();
    @AuraEnabled
    public static televisitWrapper getParticipantTelevisits(List<Id> joinbuttonids){
        try {
            Id userId;
            String timezonechanges;
            Boolean delegatecheck = false;
            participantservice.participantstate pstate = ((participantservice) classfactory.newinstance(participantservice.class)).getState(); 
            String ctpId;
            if(pstate != null && pstate.pe != null){
                ctpId = pstate.pe.Clinical_Trial_Profile__c;
            }
            user u = [Select id,contactid,TimeZoneSidKey from User where id =: UserInfo.getUserId()];
            userId = u.Id;
            timezonechanges = u.TimeZoneSidKey;
            Boolean isDelegate = pstate.isDelegate;
            String query = 'Select Televisit__r.Id, Televisit__r.Meeting_URL__c,Televisit__r.Title__c,Televisit__r.Status__c,Televisit__r.Duration__c,Televisit__r.Visit_Date_Time__c,Televisit__r.Visit_End_Date_Time__c,Televisit__r.Participant_Enrollment__r.Study_Site__c, Televisit__r.Participant_Enrollment__r.Study_Site__r.Site_Activation_Status__c, Televisit__r.Participant_Enrollment__r.Study_Site__r.Override_PI_Referral_Status__c from Televisit_Attendee__c';
            if(ctpId != null && ctpId != ''){
                String peId = pstate.pe.Id;
                Participant_Enrollment__c currentPER =  new Participant_Enrollment__c(Id=peId);
                List<Participant_Enrollment__c> allPERList =  new List<Participant_Enrollment__c>();
                allPERList.Add(currentPER);
                if(!isDelegate){
                    //participant View
                    query += '  where Televisit__r.Participant_Enrollment__c = :peId AND Televisit__r.Participant_Enrollment__r.Clinical_Trial_Profile__r.Patient_Portal_Enabled__c = true AND Televisit__r.Participant_Enrollment__r.Invited_To_PP_Date__c != null order by Televisit__r.Visit_Date_Time__c desc';
                }else{
                    //Delegate switched to participant View
                    if(ParticipantContext.getCurrentContact() != null){ // Participant contact
                        List<Participant_Enrollment__c> pastEnrollments  = ContactService.getPastEnrollments(
                            ParticipantContext.getCurrentContact().Id
                        );
                        //Check If participant has past study - if yes then it is half Alumni case.
                        if(pastEnrollments.size() > 0){
                            allPERList.AddAll(pastEnrollments);
                        }
                    }
                    query += '  where Televisit__r.Participant_Enrollment__c = :allPERList AND Televisit__r.Participant_Enrollment__r.Clinical_Trial_Profile__r.Patient_Portal_Enabled__c = true order by Televisit__r.Visit_Date_Time__c desc';
                }     
            }else{ 
                delegatecheck = true;
                String contactId;
                //Added for PEH-13732
                Boolean minorAlumni = false;
                if(isDelegate){
                    contactId = ParticipantContext.getCurrentParticipant().Contact__c ;
                    //Added for PEH-13732
                    if(ParticipantContext.getCurrentUser() == null){
                        contactId = pstate.currentContactId;
                        minorAlumni = true;
                    }
                }else{
                    contactId = pstate.currentContactId;
                }
                //query += '  where Contact__c =:contactId order by Televisit__r.Visit_Date_Time__c desc';
                
                //Added for PEH-13732
                if(minorAlumni){
                    query += '  where Televisit__r.Participant_Enrollment__r.Participant_Contact__c =:contactId AND Televisit__r.Participant_Enrollment__r.Clinical_Trial_Profile__r.Patient_Portal_Enabled__c = true order by Televisit__r.Visit_Date_Time__c desc';
                }else{
                    if(isDelegate){
                        //Delegate Switch to Participant View.
                        query += '  where Contact__c =:contactId AND Televisit__r.Participant_Enrollment__r.Clinical_Trial_Profile__r.Patient_Portal_Enabled__c = true order by Televisit__r.Visit_Date_Time__c desc';
                    }else{
                        //Delegate self view or Multi Role(self View) for all non Invited study or full alumni. 
                        //Get PER record if Delegate is also a participant.
                        contact currentContact = ParticipantContext.getCurrentContact();
                        perMapForMultiRole = ParticipantEnrollmentService.getPerMapByContactId(currentContact.Id);
                        query += '  where Contact__c =:contactId AND Televisit__r.Participant_Enrollment__r.Clinical_Trial_Profile__r.Patient_Portal_Enabled__c = true order by Televisit__r.Visit_Date_Time__c desc';
                    }
                    
                }
            }
            List<Televisit_Attendee__c> televisitattendeesdata = Database.query(query);
            List<Televisit_Attendee__c> televisitattendeeList;
            if(televisitattendeesdata != null && televisitattendeesdata.size() > 0){
                televisitattendeeList =  filteringtelevisits(televisitattendeesdata);
            }else{
                televisitattendeeList = televisitattendeesdata;
            }                                                    
            Set<Id> televisitIdSet = new Set<Id>();
            televisitWrapper  tw = new televisitWrapper();
            if(televisitattendeeList != null && !televisitattendeeList.isempty()){
                Map<id,upcomingTelevisits> upcomingTelevisitmap = new Map<id,upcomingTelevisits>();
                Map<id,pastTelevisits> pastTelevisitsmap = new Map<id,pastTelevisits>();
                for(Televisit_Attendee__c attendee:televisitattendeeList){
                    televisitIdSet.add(attendee.Televisit__r.Id);
                    if(attendee.Televisit__r.Status__c != 'Cancelled' && attendee.Televisit__r.Status__c != 'Completed' &&
                       attendee.Televisit__r.Visit_End_Date_Time__c >= system.now() &&
                       attendee.Televisit__r.Participant_Enrollment__r.Study_Site__r.Site_Activation_Status__c != 'Deactivated (Admin)'&&
                       attendee.Televisit__r.Participant_Enrollment__r.Study_Site__r.Site_Activation_Status__c != 'Deactivated' &&
                       attendee.Televisit__r.Participant_Enrollment__r.Study_Site__r.Override_PI_Referral_Status__c == 'Accepted' &&
                       attendee.Televisit__r.Participant_Enrollment__r.Study_Site__r.Site_Activation_Status__c != null ){
                           upcomingTelevisits upcomingTelevisit = new upcomingTelevisits();
                           upcomingTelevisit.televisitId = attendee.Televisit__r.Id;
                           upcomingTelevisit.title = attendee.Televisit__r.Title__c;
                           upcomingTelevisit.televisitdate = attendee.Televisit__r.Visit_Date_Time__c;
                           upcomingTelevisit.televisitduration = attendee.Televisit__r.Duration__c.split(' ')[0] + ' '+System.Label.Minutesinshort;
                           upcomingTelevisit.televisitmettingurl = attendee.Televisit__r.Meeting_URL__c;
                           if(joinbuttonids.contains(attendee.Televisit__r.Id) /*&& !isDelegate*/){
                               upcomingTelevisit.showjoinbutton = true;
                           }else{
                               upcomingTelevisit.showjoinbutton = false;
                           }
                           upcomingTelevisitmap.put(attendee.Televisit__r.Id,upcomingTelevisit);
                       }else if(attendee.Televisit__r.Visit_End_Date_Time__c < system.now() || 
                                attendee.Televisit__r.Status__c == 'Cancelled'){
                                    pastTelevisits pastTelevisit = new pastTelevisits();
                                    pastTelevisit.title = attendee.Televisit__r.Title__c;
                                    pastTelevisit.televisitdate = attendee.Televisit__r.Visit_Date_Time__c;
                                    pastTelevisit.televisitduration = attendee.Televisit__r.Duration__c;
                                    pastTelevisit.televisitId = attendee.Televisit__r.Id;
                                    if(attendee.Televisit__r.Status__c == 'Cancelled'){
                                        pastTelevisit.status = 'Canceled';
                                        pastTelevisit.iscancelledone = true;
                                    }
                                    pastTelevisitsmap.put(attendee.Televisit__r.Id,pastTelevisit);
                                }                                       
                }
                List<Televisit__c> televisitList = [Select id,(select id,Attendee_Type__c,Firstname__c,Televisit__c,Lastname__c,CreatedBy.Name  from Televisit_Attendee__r) from Televisit__c 
                                                    where Id IN : televisitIdSet order by Visit_Date_Time__c,Duration__c asc];
                List<Televisit_Attendee__c> attendeelist = new List<Televisit_Attendee__c>();
                if(televisitList != null && !televisitList.isempty()){
                    for(Televisit__c televisit: televisitList){
                        attendeelist.addAll(televisit.Televisit_Attendee__r);
                    }
                }
                Map<Id,List<televisitattendeeWrapper>> upcomingattendeesmap = new Map<Id,List<televisitattendeeWrapper>>();
                Map<Id,List<televisitattendeeWrapper>> pastattendeesmap = new Map<Id,List<televisitattendeeWrapper>>();
                
                for(Televisit_Attendee__c ta:attendeelist){
                    televisitattendeeWrapper taw = new televisitattendeeWrapper();
                    taw.firstname = ta.Firstname__c;
                    taw.lastname = ta.Lastname__c;
                    taw.attendeeType = ta.Attendee_Type__c;
                    if(pastTelevisitsmap.containskey(ta.Televisit__c)){
                        if(pastattendeesmap.containskey(ta.Televisit__c)){
                            pastattendeesmap.get(ta.Televisit__c).add(taw);
                        }else{                        
                            pastattendeesmap.put(ta.Televisit__c,new List<televisitattendeeWrapper> {taw});
                        }
                    }else if(upcomingTelevisitmap.containskey(ta.Televisit__c)){
                        if(upcomingattendeesmap.containskey(ta.Televisit__c)){
                            upcomingattendeesmap.get(ta.Televisit__c).add(taw);
                        }else{                        
                            upcomingattendeesmap.put(ta.Televisit__c,new List<televisitattendeeWrapper> {taw});
                        }
                    }
                    
                }
                List<upcomingTelevisits> finalupcomingTelevisitslist = new List<upcomingTelevisits>();
                List<pastTelevisits> finalpastTelevisitslist = new List<pastTelevisits>();
                for(Id i:upcomingattendeesmap.keyset()){
                    upcomingTelevisits ut = new upcomingTelevisits();
                    ut = upcomingTelevisitmap.get(i);
                    ut.relatedAttendees = upcomingattendeesmap.get(i);
                    finalupcomingTelevisitslist.add(ut);
                }
                for(Id i:pastTelevisitsmap.keyset()){
                    pastTelevisits pt = new pastTelevisits();
                    pt = pastTelevisitsmap.get(i);
                    pt.relatedAttendees = pastattendeesmap.get(i);
                    finalpastTelevisitslist.add(pt);
                }
                tw.televisitupcomingList = finalupcomingTelevisitslist;
                tw.televisitpastList = finalpastTelevisitslist;
                tw.showDefault = 'upcoming';
                tw.tz = timezonechanges;
                tw.isdelegate = delegatecheck;
                return tw;
            }
            tw.televisitupcomingList = new List<upcomingTelevisits>();
            tw.televisitpastList = new List<pastTelevisits>();
            tw.showDefault = 'upcoming';
            tw.tz = timezonechanges;
            tw.isdelegate = delegatecheck;
            return tw;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Televisit_Attendee__c> filteringtelevisits(List<Televisit_Attendee__c> attendeesList){
        try {
            List<Televisit_Attendee__c> filteredTelevisits = new List<Televisit_Attendee__c>();
            Set<Id> studySiteIds = new Set<Id>();
            for (Televisit_Attendee__c telattendeeObj : attendeesList) {
                studySiteIds.add(telattendeeObj.Televisit__r.Participant_Enrollment__r.Study_Site__c);
            }
            Map<Id, Study_Site__c> ssMap = new Map<Id, Study_Site__c>(
                [
                    SELECT Id
                    FROM Study_Site__c
                    WHERE
                        Id IN (
                            SELECT Study_Site__c
                            FROM TelevisitVendorSettings__c
                            WHERE
                                isEnable__c = TRUE
                                AND Study_Site__r.Clinical_Trial_Profile__r.Televisit_Vendor_is_Available__c = TRUE
                                AND Study_Site__c = :studySiteIds 
                        )
                ]
            );
            for (Televisit_Attendee__c telattendeeObj : attendeesList) {
                //if participat has multi role and not invited to studies, skip the Televisit.
                Id perId = telattendeeObj?.Televisit__r?.Participant_Enrollment__c;
                if(perMapForMultiRole.containsKey(perId) && perMapForMultiRole.get(perId).Invited_To_PP_Date__c == null){
                    continue;
                }
                if (
                    ssMap.size() > 0 &&
                    ssMap.containsKey(telattendeeObj.Televisit__r.Participant_Enrollment__r.Study_Site__c)
                ) {
                    filteredTelevisits.add(telattendeeObj);
                }
            }
            return  filteredTelevisits;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    public class upcomingTelevisits{
        @AuraEnabled public string title;
        @AuraEnabled public datetime televisitdate;
        @AuraEnabled public string televisitduration;
        @AuraEnabled public id televisitId;
        @AuraEnabled public string televisitmettingurl;
        @AuraEnabled public boolean showjoinbutton;
        @AuraEnabled public List<televisitattendeeWrapper> relatedAttendees;
    }
    public class pastTelevisits{
        @AuraEnabled public string title;
        @AuraEnabled public datetime televisitdate;
        @AuraEnabled public string televisitduration;
        @AuraEnabled public string status;
        @AuraEnabled public id televisitId;
        @AuraEnabled public boolean iscancelledone = false;
        @AuraEnabled public List<televisitattendeeWrapper> relatedAttendees;
    }
    public class televisitWrapper{
        @AuraEnabled public List<upcomingTelevisits> televisitupcomingList;
        @AuraEnabled public List<pastTelevisits> televisitpastList;
        @AuraEnabled public string showDefault;
        @AuraEnabled public string tz;
        @AuraEnabled public boolean isdelegate;
    }
    public class televisitattendeeWrapper{
        @AuraEnabled public string firstname;
        @AuraEnabled public string lastname;
        @AuraEnabled public string attendeeType;
        @AuraEnabled public boolean organiger = false;
    }
}