force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <description>QI assigned unique ID for a study</description>
    <externalId>true</externalId>
    <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
    <label>Protocol ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Title__c.field-meta.xml
<CustomField>
    <fullName>Study_Title__c</fullName>
    <description>Title of the Study</description>
    <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
    <label>Study Title</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Synch_with_TMDH__c.field-meta.xml
<CustomField>
    <fullName>Synch_with_TMDH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TMDH Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Icon_Details__c/Icon_Details__c.object-meta.xml
<CustomObject>
    <description>icon description</description>
    <label>Icon Details</label>
    <nameField>
        <label>Icon Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Icons Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Icon_Details__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Icons Details</relationshipLabel>
    <relationshipName>Icons_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/visits/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>SDH Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Visit_Plan__c.field-meta.xml
<CustomField>
    <fullName>Visit_Plan__c</fullName>
    <label>Visit Plan</label>
    <referenceTo>Visit_Plan__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Plan__c/Visit_Plan__c.object-meta.xml
<CustomObject>
    <label>Visit Plan</label>
    <nameField>
        <label>Visit Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Visit Plans</relationshipLabel>
    <relationshipName>Visit_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/tests/classes/Test_CTPSelector.cls
@IsTest
public with sharing class Test_CTPSelector {

    @TestSetup
    static void setup() {
        Visit_Plan__c visitPlan = new Visit_Plan__c(Name = 'Test 0');
        insert visitPlan;

        Clinical_Trial_Profile__c ctpList = (new Clinical_Trial_Profile__c(Protocol_ID__c = '11111111111', Study_Title__c = 'test',
                Visit_Plan__c = visitPlan.Id, Synch_with_TMDH__c = true));
        insert ctpList;

        List<Visit__c> visits = new List<Visit__c>();
        for (Integer i = 0; i < 2; i++) {
            visits.add(new Visit__c(Name = 'Test -' + i, Visit_Plan__c = visitPlan.Id));
        }
        insert visits;

        List<Icon_Details__c> iconDetails = new List<Icon_Details__c>();
        for (Integer i = 0; i < 2; i++) {
            iconDetails.add(new Icon_Details__c(Name = 'Test -' + i, Visit_Plan__c = visitPlan.Id, Label__c = 'test'));
        }
        insert iconDetails;
    }

    @IsTest
    static void getVisitsByCtp() {
        Clinical_Trial_Profile__c ctp = getCtp();
        Visit_Plan__c visitPlan = getVisitPlan(ctp.Id);
        CTPSelector selector = new CTPSelector();

        List<Visit__c> visits =
                selector.getVisitsByCtpId(visitPlan.Id);
        System.assertEquals(2, visits.size());
    }

    @IsTest
    static void getCtpById() {
        CTPSelector selector = new CTPSelector();
        Id ctpId = getCtp().Id;
        List<Clinical_Trial_Profile__c> ctp = selector.getCtpById(ctpId);
        System.assertEquals(1, ctp.size());
    }

    private static Clinical_Trial_Profile__c getCtp() {
        return [SELECT Id, Visit_Plan__c FROM Clinical_Trial_Profile__c LIMIT 1];
    }

    private static Visit_Plan__c getVisitPlan(Id ctpId) {
        return [
                SELECT Id
                FROM Visit_Plan__c
                WHERE Id IN (SELECT Visit_Plan__c FROM Clinical_Trial_Profile__c WHERE Id = :ctpId)
                LIMIT 1
        ];
    }

    @IsTest
    static void getIconDetailsByVisitPlanInCTP_test() {
        CTPSelector selector = new CTPSelector();
        Clinical_Trial_Profile__c ctp = getCtp();
        List<Icon_Details__c> iconDetails = selector.getIconDetailsByVisitPlanInCTP(ctp.Visit_Plan__c);
        System.assertEquals(2, iconDetails.size());
    }
}