force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resource_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Resource_Notifications__c</fullName>
    <label>Resource Notifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Days_After_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Days_After_Enrolled__c</fullName>
    <formula>TODAY()  -  Enrolled_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days After Enrolled</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value on this field is place holder for IQVIA outreach consent for email which will later be copied on to contact fields</description>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/Res_study__c.object-meta.xml
<CustomObject>
    <label>Study Resource</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Resource Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Res_study__c/fields/Active_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Active_After_Days__c</fullName>
    <label>Active After Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Active_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_On_Status__c</fullName>
    <label>Active On Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <inlineHelpText>master detail</inlineHelpText>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Resource</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Expires_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Expires_After_Days__c</fullName>
    <label>Number of Days Before Document Expires</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Expires_On_Status__c.field-meta.xml
<CustomField>
    <fullName>Expires_On_Status__c</fullName>
    <label>Expires On Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Active_On_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Participant_Statuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Notify_On_Availability__c.field-meta.xml
<CustomField>
    <fullName>Notify_On_Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notify On Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>Only Study Specific Resource can be added.</errorMessage>
        <filterItems>
            <field>Resource__c.Content_Class__c</field>
            <operation>equals</operation>
            <value>Study-Specific</value>
        </filterItems>
        <filterItems>
            <field>Resource__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Study Document</value>
        </filterItems>
        <filterItems>
            <field>Resource__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Relevant Link</value>
        </filterItems>
        <infoMessage>Only Study Specific Resource can be added.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Study Resources</relationshipLabel>
    <relationshipName>Study</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_In_Alumni__c.field-meta.xml
<CustomField>
    <fullName>Visible_In_Alumni__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible In Alumni</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_To_Delegates__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Delegates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Delegates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_Participant__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object contains Video/Articles</description>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/resources/objects/Resource__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Study_Document</fullName>
                <label>Study Document</label>
            </value>
            <value>
                <fullName>Relevant_Link</fullName>
                <label>Relevant Link</label>
            </value>
            <value>
                <fullName>Submitted_Articles</fullName>
                <label>Submitted Articles</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Resource__c/recordTypes/Study_Document.recordType-meta.xml
<RecordType>
    <fullName>Study_Document</fullName>
    <active>true</active>
    <label>Study Document</label>
</RecordType>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Approved_Lng__c.field-meta.xml
<CustomField>
    <fullName>Approved_Lng__c</fullName>
    <label>Approved Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Participant_Statuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Failed Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Failed Review</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded from Referring</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Eligibility Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Success</fullName>
    </customValue>
    <customValue>
        <fullName>Enrollment Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Follow-Up Period Started</fullName>
    </customValue>
    <customValue>
        <fullName>Participation Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Trial Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Drop Out</fullName>
    </customValue>
    <customValue>
        <fullName>Deceased</fullName>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
    </customValue>
    <customValue>
        <fullName>Successfully Contacted</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Attempted</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Reach</fullName>
    </customValue>
    <customValue>
        <fullName>Contacted - Not Suitable</fullName>
    </customValue>
    <customValue>
        <fullName>Screening Passed</fullName>
    </customValue>
    <customValue>
        <fullName>Unable to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Success</fullName>
    </customValue>
    <customValue>
        <fullName>Randomization Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Screening In Progress - Wash Out Period</fullName>
        <label>In Wash Out Period</label>
    </customValue>
    <customValue>
        <fullName>Ready to Screen</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Declined Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrew Consent After Screening</fullName>
    </customValue>
    <masterLabel>Participant Statuses</masterLabel>
</GlobalValueSet>

force-app/main/scheduled-batch/classes/Batch_CreateSummaryNotifications.cls
/**
 * Created by Igor Malyuta on 11.09.2019.
 */

public without sharing class Batch_CreateSummaryNotifications extends Batch_ScheduledAbstract{

    public Database.QueryLocator start(Database.BatchableContext param1) {
        return Database.getQueryLocator([
                SELECT
                        Active_After_Days__c,
                        Active_On_Status__c,
                        Clinical_Trial_Profile__c,
                        Expires_After_Days__c,
                        Expires_On_Status__c,
                        Id,
                        Notify_On_Availability__c,
                        Resource__c,
                        Resource__r.Language__c,
                        Visible_In_Alumni__c,
                        Visible_To_Delegates__c,
                        Visible_To_Participant__c
                FROM Res_study__c
                WHERE Notify_On_Availability__c = TRUE
                AND Visible_To_Participant__c = TRUE
                AND Resource__r.Content_Type__c = 'Study_Document'
        ]);
    }

    public void execute(Database.BatchableContext param1, List<Res_study__c> resStudies) {
        Map<Id, List<Res_study__c>> resStudyByCtp = new Map<Id, List<Res_study__c>>();
        Set<String> resLangs = new Set<String>();
        for(Res_study__c res : resStudies) {
            if(!resStudyByCtp.containsKey(res.Clinical_Trial_Profile__c)) {
                resStudyByCtp.put(res.Clinical_Trial_Profile__c, new List<Res_study__c>());
            }
            resStudyByCtp.get(res.Clinical_Trial_Profile__c).add(res);
            resLangs.add(res.Resource__r.Language__c);
        }

        List<Participant_Enrollment__c> enrollment = [
                SELECT
                        Id,
                        Clinical_Trial_Profile__c,
                        Days_After_Enrolled__c,
                        Participant_Contact__c,
                        Participant_Contact__r.Language__c,
                        Participant_Contact__r.Participant_Opt_In_Status_Emails__c,
                        Participant_Contact__r.Resource_Notifications__c,
                        Participant_Status__c
                FROM Participant_Enrollment__c
                WHERE Clinical_Trial_Profile__c IN: resStudyByCtp.keySet()
                AND Study_Site__r.Approved_Lng__c IN: resLangs
        ];

        List<Contact> contactToNotify = new List<Contact>();
        for(Participant_Enrollment__c pe : enrollment) {
            List<Contact> peContacts = new List<Contact>();
            peContacts.add(pe.Participant_Contact__r);
            peContacts.addAll(PatientDelegateService.getDelegateContacts(pe.Participant_Contact__c));

            for(Res_study__c res : resStudyByCtp.get(pe.Clinical_Trial_Profile__c)) {
                for(Contact contact : peContacts) {
                    Boolean isDelegate = pe.Participant_Contact__c != contact.Id;
                    if(StudyResourceVisibilityService.isResourceVisibleForPE(res, pe, isDelegate)) {
                        if(needNotify(contact, res.Resource__c)) contactToNotify.add(contact);
                    }
                }
            }
        }

        if(!contactToNotify.isEmpty()) {
            SendEmailToParticipant.sendPlainSummaryNotifications(contactToNotify, SendEmailToParticipant.PATIENT_PLAIN_SUMMARY);
            update contactToNotify;
        }
    }

    public override Type getType() {
        return Batch_CreateSummaryNotifications.class;
    }

    private Boolean needNotify(Contact contact, Id resourceId) {
        Boolean notify = false;
        if(contact.Resource_Notifications__c == null) {
            contact.Resource_Notifications__c = resourceId;
            notify = true;
        } else {
            List<String> resourceIds = contact.Resource_Notifications__c.split(';');
            if(!resourceIds.contains(resourceId)) {
                contact.Resource_Notifications__c += ';' + resourceId;
                notify = true;
            }
        }

        return notify;
    }
}