force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions__c/Terms_And_Conditions__c.object-meta.xml
<CustomObject>
    <label>Terms And Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms And Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions_Acceptance__c/Terms_And_Conditions_Acceptance__c.object-meta.xml
<CustomObject>

    <label>Terms And Conditions Acceptance</label>
    <nameField>
        <displayFormat>TCA-{000000}</displayFormat>
        <label>Terms And Conditions Acceptance Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions Acceptance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions_Acceptance__c/fields/Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Accepted Date</label>

    <type>DateTime</type>
</CustomField>

force-app/main/terms-and-conditions/objects/Terms_And_Conditions_Acceptance__c/fields/Terms_And_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_And_Conditions__c</fullName>
    <label>Terms And Conditions</label>
    <referenceTo>Terms_And_Conditions__c</referenceTo>
    <relationshipLabel>Terms And Conditions Acceptance</relationshipLabel>
    <relationshipName>Terms_And_Conditions_Acceptance</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/terms-and-conditions/classes/TermsAndConditionsRemote.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class TermsAndConditionsRemote {
    class TCData {
        Terms_And_Conditions__c tc;
        Datetime acceptedDate;
        Boolean isAccepted;
        Clinical_Trial_Profile__c trial;
    }

    @AuraEnabled
    public static String getPortalTcData(Boolean useDefaultCommunity) {
        try {
            return JSON.serialize(getTCData(TermsAndConditions.getPortalTC(useDefaultCommunity)));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    @AuraEnabled
    public static String getTrialTcData(Id ctpId) {
        try {
            TCData tcData = getTCData(TermsAndConditions.getTrialTC(ctpId));
            tcData.trial = StudyTrialService.getFullTrial(ctpId);
            return JSON.serialize(tcData);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    @AuraEnabled
    public static string generatePDF(Id ppId){
        Id contId;
        string retUrl;

        try{
            ContentDocumentLink cdl = new ContentDocumentLink();
            ContentDistribution contDist = new ContentDistribution();
            cdl = [SELECT Id,ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: ppId];
          // con = [SELECT Id, Title FROM ContentDocument WHERE Id =: cdl.ContentDocumentId];
           contId = cdl.ContentDocumentId;
           contDist = [Select Id,ContentDownloadUrl from ContentDistribution  where ContentDocumentId =: cdl.ContentDocumentId ];
           retUrl = contDist.ContentDownloadUrl;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
        /*string retUrl = URL.getOrgDomainUrl().toExternalForm() + 
                        '/sfc/servlet.shepherd/document/download/'+ contId +'?operationContext=S1';*/
        return retUrl;
    }

    @AuraEnabled
    public static String getTC(String code, String languageCode, Boolean useDefaultCommunity) {
        System.debug('useDefaultCommunity: '+useDefaultCommunity);
        try {
            TCData tcData = new TCData();
            if (code == 'PrivacyPolicy') {
                tcData.tc = TermsAndConditions.getOrgDefaultPrivacyTC(useDefaultCommunity);
            } else if (code == 'CookiePolicy') {
                tcData.tc = TermsAndConditions.getCookieTC(useDefaultCommunity);
            } else {
                tcData.tc = TermsAndConditions.getTC(
                    TermsAndConditions.getOrgDefaultTCbyCode(code),
                    languageCode,
                    useDefaultCommunity
                );
            }
            return JSON.serialize(tcData);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    @AuraEnabled
    public static void acceptTC(Id tcId) {
        try {
            TermsAndConditions.acceptTC(tcId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    @auraEnabled
    public static String getCommunityName() {
        String communityName = TranslateHelper.getLabelValue(
            UserContext.getTemplateProperty('CommunityBrandName')
        );
        communityName = communityName.replace('<i>', '');
        communityName = communityName.replace('</i>', '');
        return communityName;
    }
    private static TCData getTCData(Terms_And_Conditions__c tc) {
        TCData tcData = new TCData();
        if (tc != null) {
            tcData.tc = tc;
            Terms_And_Conditions_Acceptance__c tca = TermsAndConditions.getTCA(tc.Id);
            tcData.isAccepted = tca != null;
            if (tca != null)
                tcData.acceptedDate = tca.Accepted_Date__c;
        }
        return tcData;
    }
}