force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Link_to_Pre_screening__c.field-meta.xml
<CustomField>
    <fullName>Link_to_Pre_screening__c</fullName>
    <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires pre-screening.</inlineHelpText>
    <label>Link to Pre-screening</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Logged_Out_Days_Notification__c.field-meta.xml
<CustomField>
    <fullName>Logged_Out_Days_Notification__c</fullName>
    <label>Logged Out Days Notification</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/NCT_Number__c.field-meta.xml
<CustomField>
    <fullName>NCT_Number__c</fullName>
    <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
    <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
    <label>NCT Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Override_Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Override_Recruitment_Status__c</fullName>
    <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
    <label>Override Recruitment Status</label>

    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actively Enrolling</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>No_Longer_Enrolling</fullName>
                <label>No Longer Enrolling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Participating_in_Digital_Recruitment__c.field-meta.xml
<CustomField>
    <fullName>Participating_in_Digital_Recruitment__c</fullName>
    <label>Participating in Digital Recruitment</label>

    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Y_N_Unknown</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Participating_in_Patient_Portal__c.field-meta.xml
<CustomField>
    <fullName>Participating_in_Patient_Portal__c</fullName>
    <label>Participating in Patient Portal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Participating_in_Rocket_Referral__c.field-meta.xml
<CustomField>
    <fullName>Participating_in_Rocket_Referral__c</fullName>
    <label>Participating in Rocket Referral</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Participating_in_Digital_Recruitment__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Y_N_Unknown</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <description>QI assigned unique ID for a study</description>
    <externalId>true</externalId>
    <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
    <label>Protocol ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Shareback_Availability_Timing__c.field-meta.xml
<CustomField>
    <fullName>Shareback_Availability_Timing__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Show visit result after # completed visits</description>
    <label>Shareback Availability Timing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Shareback_Settings_On_Participant_Level__c.field-meta.xml
<CustomField>
    <fullName>Shareback_Settings_On_Participant_Level__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shareback Settings On Participant Level</description>
    <label>Shareback Settings On Participant Level</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
<!--    <trackHistory>true</trackHistory>-->
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Title__c.field-meta.xml
<CustomField>
    <fullName>Study_Title__c</fullName>
    <description>Title of the Study</description>
    <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
    <label>Study Title</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Suppress_Participant_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Participant_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, no emails will be sent to participants for this study.</inlineHelpText>
    <label>Suppress Participant Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Synch_with_TMDH__c.field-meta.xml
<CustomField>
    <fullName>Synch_with_TMDH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TMDH Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Data_Shareback__c.field-meta.xml
<CustomField>
    <fullName>Visit_Data_Shareback__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Data Shareback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Site__c.field-meta.xml
<CustomField>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value on this field is place holder for IQVIA outreach consent for email which will later be copied on to contact fields</description>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>

    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reminder_Schedule__c/Reminder_Schedule__c.object-meta.xml
<CustomObject>
    <label>Reminder Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Reminder Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reminder Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reminder_Schedule__c/fields/First_Reminder_day__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder_day__c</fullName>
    <inlineHelpText>Define how many days should pass before 1st reminder email is sent to a Participant in case Survey Task is still pending</inlineHelpText>
    <label>First Reminder day</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reminder_Schedule__c/fields/Second_Reminder_day__c.field-meta.xml
<CustomField>
    <fullName>Second_Reminder_day__c</fullName>
    <inlineHelpText>Define how many days should pass before the Final reminder email is sent to a Participant in case Survey Task is still pending</inlineHelpText>
    <label>Second Reminder day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reminder_Schedule__c/fields/Use_Final_Template__c.field-meta.xml
<CustomField>
    <fullName>Use_Final_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if sending only 1 reminder and you want to use the final reminder email.</inlineHelpText>
    <label>Use Final Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Protocol_ID__c.field-meta.xml
<CustomField>
    <fullName>Protocol_ID__c</fullName>
    <formula>Clinical_Trial_Profile__r.Protocol_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Clinical Trial Profile&#39;s Protocol Id</inlineHelpText>
    <label>Protocol ID</label>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Suppress_Participant_Emails__c.field-meta.xml
<CustomField>
    <fullName>Suppress_Participant_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, no emails will be sent to participants for this study site.</inlineHelpText>
    <label>Suppress Participant Emails</label>

    <type>Checkbox</type>
</CustomField>

force-app/unpackaged/main/default/globalValueSets/Y_N_Unknown.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>Yes, No, Unknown</description>
    <masterLabel>Y/N/Unknown</masterLabel>
</GlobalValueSet>

force-app/main/tests/classes/Test_Batch_PatientTaskReminder.cls
/**
 * Created by Olga Skrynnikova on 10/23/2019.
 */
@IsTest
public with sharing class Test_Batch_PatientTaskReminder {
    @IsTest
    static void testBatchExecute() {
        initData();
        Participant_Enrollment__c pe = [SELECT Id, Participant_Contact__c FROM Participant_Enrollment__c];
        List<Task> tskList = new List<Task>();
        User user = [
                SELECT
                        Id,
                        ContactId,
                        Contact.Participant_Opt_In_Status_Emails__c
                FROM User
                WHERE ContactId = : pe.Participant_Contact__c
        ];
        Task tsk = new Task(
                Subject = 'Test Name',
                Task_Type__c = 'Not Selected',
                Reminder_Date__c = Datetime.now(),
                Status = 'Open',
                ReminderDateTime = Datetime.now(),
                OwnerId = user.Id
        );
        tskList.add(tsk);

        Contact conList = [SELECT Id, Participant_Opt_In_Status_Emails__c, Email FROM Contact WHERE Email = 'MaxJames@mail.com'];
        conList.Participant_Opt_In_Status_Emails__c = true;
        update conList;


        Test.startTest();
        upsert tsk;
        List<Task> tasks = [
                SELECT Id,
                        Description,
                        OwnerId,
                        Subject,
                        Start_Date__c,
                        Task_Type__c,
                        ReminderDateTime,
                        Reminder_Date__c,
                        Reminder_Schedule__c,
                        Reminder_Schedule__r.First_Reminder_day__c,
                        Reminder_Schedule__r.Second_Reminder_day__c,
                        Reminder_Schedule__r.Use_Final_Template__c,
                        Visible_For__c,
                        WhatId,
                        WhoId
                FROM Task
                WHERE ReminderDateTime <= :Datetime.now()
                AND Is_Reminder_Sent__c = FALSE
                AND Status IN:TaskService.TASK_STATUS_GROUP_AVAILABLE
        ];
        new Batch_PatientTaskReminder().execute(null, tasks);
        Test.stopTest();

        List<Task> taskList = [SELECT Id, Subject, Task_Type__c, WhoId, Reminder_Date__c FROM Task];
        System.assertEquals(2, taskList.size());

    }

    static void initData() {
        List<Account> accounts = new List<Account>();
        Account participantsAccount = new Account(
                Name = 'Participant'
        );
        accounts.add(participantsAccount);
        Account piAccount = new Account(
                Name = 'PI Account'
        );
        accounts.add(piAccount);
        Account studySiteAccount = new Account(
                Name = 'Study Site Account',
                BillingCountryCode = 'US'
        );
        accounts.add(studySiteAccount);
        insert accounts;

        List<Contact> contacts = new List<Contact>();
        Contact piContact = new Contact(
                FirstName = 'PI',
                LastName = 'PI',
                Email = 'pi@emil.com',
                AccountId = piAccount.Id
        );
        contacts.add(piContact);
        insert contacts;

        List<Clinical_Trial_Profile__c> studies = new List<Clinical_Trial_Profile__c>();
        studies.add(new Clinical_Trial_Profile__c(
                Protocol_ID__c = 'CTP1',
                Override_Recruitment_Status__c = 'Actively Enrolling',
                NCT_Number__c = 'NCT99999999',
                Link_to_Pre_screening__c = 'some link',
                Study_Title__c = 'Some Title',
                Study_Code_Name__c = 'Some Code Name',
                Suppress_Participant_Emails__c = false,
                Participating_in_Digital_Recruitment__c = 'YES',
                Participating_in_Rocket_Referral__c = 'YES',
                Participating_in_Patient_Portal__c = 'Yes',
                Shareback_Settings_On_Participant_Level__c = true,
                Shareback_Availability_Timing__c = 1,
                Visit_Data_Shareback__c = true,
                Synch_with_TMDH__c = true,
                Logged_Out_Days_Notification__c = 12
        ));
        insert studies;

        List<Study_Site__c> studySites = new List<Study_Site__c>();
        studySites.add(new Study_Site__c(
                Principal_Investigator__c = piContact.Id,
                Clinical_Trial_Profile__c = studies[0].Id,
                Override_PI_Referral_Status__c = StudySiteService.PI_S_INVITATION_SENT,
                Site__c = studySiteAccount.Id,
                Study_Site_Type__c = 'Traditional',
                Suppress_Participant_Emails__c = false,
                Study_Site_Number__c = 'SS1'
        ));
        insert studySites;

        Participant__c participant = new Participant__c(
                First_Name__c = 'Max',
                Last_Name__c = 'James',
                Birth_Year__c = '1985',
                Mailing_Country_Code__c = 'US',
                Mailing_State_Code__c = 'NY',
                Email__c = 'MaxJames@mail.com'
        );
        insert participant;

        insert new Participant_Enrollment__c(
                Participant__c = participant.Id,
                Screening_ID__c = 'PE1',
                Study_Site__c = studySites[0].Id
        );
    }

}