force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Integration_Biomarker__c/Integration_Biomarker__c.object-meta.xml
<CustomObject>
    <label>Integration Biomarker</label>
    <nameField>
        <displayFormat>IB-{00000000}</displayFormat>
        <label>Integration Biomarker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Biomarkers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Closure__c/Participant_Closure__c.object-meta.xml
<CustomObject>
    <label>Participant Closure</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>PER Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participant Closure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Closure__c/fields/Study_Closure__c.field-meta.xml
<CustomField>
    <fullName>Study_Closure__c</fullName>
    <label>Study Closure</label>
    <referenceTo>Study_Closure__c</referenceTo>
    <relationshipLabel>Participant Closure</relationshipLabel>
    <relationshipName>Participant_Closure</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RH_Biomarker__c/RH_Biomarker__c.object-meta.xml
<CustomObject>
    <label>Biomarker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Biomarkers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RH_Biomarker__c/fields/Integration_Biomarker__c.field-meta.xml
<CustomField>
    <fullName>Integration_Biomarker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integration Biomarker</label>
    <referenceTo>Integration_Biomarker__c</referenceTo>
    <relationshipLabel>Biomarkers</relationshipLabel>
    <relationshipName>Biomarkers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RH_Biomarker__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Biomarkers</relationshipLabel>
    <relationshipName>Biomarkers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Closure__c/Study_Closure__c.object-meta.xml
<CustomObject>
    <label>Study Closure</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Study Closure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Closures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Closure__c/fields/Clinical_Trial_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Clinical Trial Profile Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_Closure__c/fields/Only_Selected_Participants__c.field-meta.xml
<CustomField>
    <fullName>Only_Selected_Participants__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Only Selected Participants</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IntegrationBioMarkerFileBatchDeletion.cls
global class IntegrationBioMarkerFileBatchDeletion implements Database.Batchable<sObject>, Database.Stateful{
    private String ctpId;
    private Boolean isStudyToDelete = false;
    private Set<Id> contentDocumentIds = new Set<Id>();
    private Set<String> RefIds = new Set<String>();
    private Boolean onlySelectedPart = false;
    
    global IntegrationBioMarkerFileBatchDeletion(String ctpId){
        this.ctpId = ctpId;
    }
    global IntegrationBioMarkerFileBatchDeletion(String ctpId, Boolean isStudyToDelete){
        this.ctpId = ctpId;
        this.isStudyToDelete = isStudyToDelete;
    }
    public class BatchControlException extends Exception{}
    global Database.QueryLocator start(Database.BatchableContext BC){
        List<Study_Closure__c> studyClosureList = [
                SELECT Id,Only_Selected_Participants__c FROM Study_Closure__c WHERE Clinical_Trial_Profile_Id__c = :ctpId LIMIT 1
            ];
        if(studyClosureList.isEmpty() == false){
              if(studyClosureList[0].Only_Selected_Participants__c){
                    onlySelectedPart = true;
                    List<Participant_Closure__c> partClosureList = [Select Name from Participant_Closure__c ];
                    for(Participant_Closure__c pc:partClosureList){
                        RefIds.add(pc.Name);
                    }
              }else{ onlySelectedPart = false;}
         }else{
                throw new BatchControlException('Please check the studyclosure record created or not for the study.');
         }
        String query = 'SELECT Id FROM Participant_Enrollment__c ';
        if(String.isNotBlank(ctpId)) {
            query += 'WHERE Clinical_Trial_Profile__c = :ctpId';
             if(onlySelectedPart){
                     query += ' AND Name IN:RefIds';
                }
        } else {
            query += 'LIMIT 0';
        }
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Participant_Enrollment__c> enrollmentList){
    
        Set<Id> integrationBioMarkerIds = new Set<Id>();
        List<ContentDocumentLink> cdl = new List<ContentDocumentLink>();
        List<Id> cdIds = new List<Id>();
        for(RH_Biomarker__c bioMarker : [
            SELECT Id, Integration_Biomarker__c 
            FROM RH_Biomarker__c 
            WHERE Participant_Enrollment__c IN :enrollmentList AND Integration_Biomarker__c != null
        ]){
            
            integrationBioMarkerIds.add(bioMarker.Integration_Biomarker__c);
        }
        cdl = [SELECT ContentDocumentId,Id,LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN:integrationBioMarkerIds];
        
        if(cdl.isEmpty() == false){
            for(ContentDocumentLink  cd:cdl){
                cdIds.add(cd.ContentDocumentId);
            } 
         } 
        if(isStudyToDelete) {
            delete [SELECT Id FROM ContentDocument WHERE ID IN : cdIds];
        } else {
        
           contentDocumentIds.addAll((new Map<Id, ContentDocument>(
               [SELECT Id FROM ContentDocument WHERE ID IN : cdIds]
           )).keySet());
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
        if(isStudyToDelete == false) {
        
            List<Study_Closure__c> studyClosureProcessList = [
                SELECT Id FROM Study_Closure__c WHERE Clinical_Trial_Profile_Id__c = :ctpId LIMIT 1
            ];
            if(studyClosureProcessList.isEmpty() == false) {
                
                List<ContentVersion> contentVersions =new List<ContentVersion>();
                contentVersions.add(Batch_SCParticipantEnrollment.constructCsvFile(
                    ctpId, 'Integration BioMarker Files', contentDocumentIds
                ));
                
                Batch_SCParticipantEnrollment.insertContentVersions(studyClosureProcessList[0].Id, contentVersions);
            }
        }   
    }
}