force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/CommunityTemplate__c.field-meta.xml
<CustomField>
    <fullName>CommunityTemplate__c</fullName>
    <label>Community Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>IQVIA Patient Portal</label>
            </value>
            <value>
                <fullName>GSK</fullName>
                <label>GSK Pan Oncology</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Delayed_No_Of_Days__c.field-meta.xml
<CustomField>
    <fullName>Delayed_No_Of_Days__c</fullName>
    <label>Delayed No.Of Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/E_Consent_Configuration__c.field-meta.xml
<CustomField>
    <fullName>E_Consent_Configuration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E-Consent Configuration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/ECOA_Is_Avaialble__c.field-meta.xml
<CustomField>
    <fullName>ECOA_Is_Avaialble__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECOA Is Avaialble</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Enrolled_Or_Randomized_Consent_Available__c.field-meta.xml
<CustomField>
    <fullName>Enrolled_Or_Randomized_Consent_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enrolled Or Randomized Consent Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/IQVIA_Outreach__c.field-meta.xml
<CustomField>
    <fullName>IQVIA_Outreach__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IQVIA Outreach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Is_Program__c.field-meta.xml
<CustomField>
    <fullName>Is_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Program</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Medical_Vendor_is_Available__c.field-meta.xml
<CustomField>
    <fullName>Medical_Vendor_is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Medical Vendor is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Payment_Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Payment_Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Received_Until_Consent_Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Received_Until_Consent_Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Received Until Consent Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Relevant_Links_Are_Available__c.field-meta.xml
<CustomField>
    <fullName>Relevant_Links_Are_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Relevant Links Are Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status_Milestone_Available__c.field-meta.xml
<CustomField>
    <fullName>Status_Milestone_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status/Milestone Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Documents_Are_Available__c.field-meta.xml
<CustomField>
    <fullName>Study_Documents_Are_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Study Documents Are Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_GUID__c.field-meta.xml
<CustomField>
    <fullName>Study_GUID__c</fullName>
    <label>Study GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Version_GUID__c.field-meta.xml
<CustomField>
    <fullName>Study_Version_GUID__c</fullName>
    <label>Study Version GUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Tasks_Are_Available__c.field-meta.xml
<CustomField>
    <fullName>Tasks_Are_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tasks Are Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Televisit_Vendor_is_Available__c.field-meta.xml
<CustomField>
    <fullName>Televisit_Vendor_is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Televisit Vendor is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Travel_Vendor_Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Travel_Vendor_Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Travel Vendor Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Trial_Match_Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Trial_Match_Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enables the trial matcher for participant</description>
    <label>Trial Match Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Video_And_Articles_Are_Available__c.field-meta.xml
<CustomField>
    <fullName>Video_And_Articles_Are_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Video And Articles Are Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Schedule_Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Visit_Schedule_Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Schedule Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visits_are_Available__c.field-meta.xml
<CustomField>
    <fullName>Visits_are_Available__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Visits are Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/StudySiteVisitPlan__c/StudySiteVisitPlan__c.object-meta.xml
<CustomObject>
    <label>StudySiteVisitPlan</label>
    <nameField>
        <displayFormat>SSVP-{0000000}</displayFormat>
        <label>StudySiteVisitPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StudySiteVisitPlans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/StudySiteVisitPlan__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>StudySiteVisitPlans</relationshipLabel>
    <relationshipName>StudySiteVisitPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/backend-ctp-setup/classes/StudyConfigurationRemote.cls
/**
 * Created by Nargiz Mamedova on 12/9/2019.
 */

public with sharing class StudyConfigurationRemote {
    public static final String FEATURE_STUDY_CONFIGURATION = 'Toggle_Feature_Delta';

    public class InitData {
        @AuraEnabled
        public Clinical_Trial_Profile__c ctp;
        @AuraEnabled
        public String user_has_permission = 'no perm';
        @AuraEnabled
        public Boolean noVisitPlansMessage = false;
    }

    @AuraEnabled
    public static InitData getInitData(Id ctpId) {
        InitData initData = new InitData();
        try {
            initData.ctp = [
                SELECT
                    Id,
                    Visit_Schedule_Is_Available__c,
                    Is_Program__c,
                    Study_Documents_Are_Available__c,
                    Video_And_Articles_Are_Available__c,
                    Tasks_Are_Available__c,
                    Travel_Vendor_Is_Available__c,
                    Trial_Match_Is_Available__c,
                    Relevant_Links_Are_Available__c,
                    Received_Until_Consent_Is_Available__c,
                	Delayed_No_Of_Days__c,
                    Enrolled_Or_Randomized_Consent_Available__c,
                    Payment_Is_Available__c,
                    Medical_Vendor_is_Available__c,
                    ECOA_Is_Avaialble__c,
                    Study_GUID__c,
                    Study_Version_GUID__c,
                    Visits_are_Available__c,
                    Televisit_Vendor_is_Available__c, //Televisit
                    IQVIA_Outreach__c,
                    E_Consent_Configuration__c,
                    Status_Milestone_Available__c,
                    CommunityTemplate__c
                FROM Clinical_Trial_Profile__c
                WHERE Id = :ctpId
            ];
            initData.user_has_permission = GetPermissions.getViewMode(FEATURE_STUDY_CONFIGURATION);
            List<Study_Site__c> allSSList = [
                SELECT Id, (SELECT Id FROM StudySiteVisitPlans__r)
                FROM Study_Site__c
                WHERE Clinical_Trial_Profile__c = :ctpId
            ];
            for (Study_Site__c ss : allSSList)
                if (ss.StudySiteVisitPlans__r.isEmpty())
                    initData.noVisitPlansMessage = true;
            return initData;
        } catch (Exception e) {
            return (InitData) AuraHelper.throwException(e);
        }
    }

    @AuraEnabled
    public static void saveChanges(Clinical_Trial_Profile__c ctp) {
        try {
            update ctp;
        } catch (Exception e) {
            AuraHelper.throwException(e);
        }
    }
}