force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Payment_Vendor__c/Payment_Vendor__c.object-meta.xml
<CustomObject>
    <label>Payment Vendor</label>
    <nameField>
        <label>Payment Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Vendor__c/fields/Link_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Link_Vendor__c</fullName>
    <label>Link Vendor</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/backend-ctp-setup/classes/tests/Test_PaymentVendorPanelRemote.cls
/**
 * Created by Nargiz Mamedova on 1/17/2020.
 */

@IsTest
private with sharing class Test_PaymentVendorPanelRemote {
    @TestSetup
    static void init(){
        TestData.loadTestData();
    }

    @IsTest
    static void getItems_test(){
        Clinical_Trial_Profile__c ctp=[Select Id from Clinical_Trial_Profile__c limit 1];
        Test.startTest();
        PaymentVendorPanelRemote.InitData initData = PaymentVendorPanelRemote.getInitData(ctp.Id);
        PaymentVendorPanelRemote.getItems(JSON.serialize(initData.searchResponse.studySiteItems), JSON.serialize(initData.filter), JSON.serialize(new PaginationData(15)));
        Test.stopTest();
    }

    @IsTest
    static void selectAllInColumn_test(){
        Clinical_Trial_Profile__c ctp=[Select Id from Clinical_Trial_Profile__c limit 1];
        Payment_Vendor__c paymentVendor = new Payment_Vendor__c(Name = 'Qiwi', Link_Vendor__c = 'link 1');
        insert paymentVendor;

        Test.startTest();
        PaymentVendorPanelRemote.InitData initData = PaymentVendorPanelRemote.getInitData(ctp.Id);
        PaymentVendorPanelRemote.selectAllInColumn(paymentVendor.Id, true, JSON.serialize(initData.filter), JSON.serialize(new PaginationData(15)), JSON.serialize(initData.searchResponse.studySiteItems));
        Test.stopTest();
    }

    @IsTest
    static void clearAllInColumn_test(){
        Clinical_Trial_Profile__c ctp=[Select Id from Clinical_Trial_Profile__c limit 1];
        Payment_Vendor__c paymentVendor = new Payment_Vendor__c(Name = 'Qiwi', Link_Vendor__c = 'link 1');
        insert paymentVendor;

        Test.startTest();
        PaymentVendorPanelRemote.InitData initData = PaymentVendorPanelRemote.getInitData(ctp.Id);
        System.debug(JSON.serializePretty(initData.searchResponse.studySiteItems));
        PaymentVendorPanelRemote.selectAllInColumn(paymentVendor.Id, false, JSON.serialize(initData.filter), JSON.serialize(new PaginationData(15)), JSON.serialize(initData.searchResponse.studySiteItems));
        Test.stopTest();
    }

    @IsTest
    static void getInitDataWithException_test() {
        Boolean isExceptionThrown = false;
        Test.startTest();
        try {
            PaymentVendorPanelRemote.getInitData(null);
        } catch (Exception e) {
            isExceptionThrown = true;
            System.assert(e.getTypeName() == 'System.AuraHandledException');
        }
        Test.stopTest();
        System.assert(true, isExceptionThrown);
    }
}