force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Workflow_Step__mdt/Participant_Workflow_Step__mdt.object-meta.xml
<CustomObject>
    <label>Participant Workflow Step</label>
    <pluralLabel>Participant Workflow Steps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Participant_Workflow_Step__mdt/fields/Name_Label__c.field-meta.xml
<CustomField>
    <fullName>Name_Label__c</fullName>
    <label>Name Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParticipantWorkflowService.cls
/**
 * Created by Andrii Kryvolap.
 */

public without sharing class ParticipantWorkflowService {

    public static ParticipantWorkflowWrapper prepareParticipantWorkflow(Clinical_Trial_Profile__c ctp, Participant_Enrollment__c pe){
        ParticipantWorkflowWrapper wrapper = new ParticipantWorkflowWrapper();
        wrapper.steps = new List<ParticipantWorkflowService.ParticipantWorkflowStepWrapper>();
        List<Participant_Workflow_Step__mdt> steps = [SELECT Condition__c, Name_Label__c FROM Participant_Workflow_Step_mdt ORDER By Order__c ASC];
        for(Participant_Workflow_Step__mdt step : steps){
            if(step.Condition__c == null || step.Condition__c =='' || ConditionCheckerService.checkConditionForObject(step.Condition__c, ctp)){
                ParticipantWorkflowStepWrapper stepWrapper = new ParticipantWorkflowStepWrapper();
                stepWrapper.title = step.Name_Label__c;
                stepWrapper.status = step.Name_Label__c + ' status';
                wrapper.steps.add(stepWrapper);
            }
        }
        if(!wrapper.steps.isEmpty()){
            wrapper.currentStep = wrapper.steps[0];
        }
        return wrapper;
    }



    public class ParticipantWorkflowWrapper{
        @AuraEnabled public List<ParticipantWorkflowStepWrapper> steps;
        @AuraEnabled public ParticipantWorkflowStepWrapper currentStep;
    }

    public class ParticipantWorkflowStepWrapper{
        @AuraEnabled public String title;
        @AuraEnabled public String status;
    }

}