force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Patient_Portal_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Patient_Portal_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Patient Portal Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/messaging/objects/Notification__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <description>store the id of task record.</description>
    <label>Task Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Topic</label>
    <referenceTo>Topic__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/messaging/objects/Notification__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <label>WhatId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Opt_In_Status_Emails__c.field-meta.xml
<CustomField>
    <fullName>Participant_Opt_In_Status_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Value on this field is place holder for IQVIA outreach consent for email which will later be copied on to contact fields</description>
    <label>Opt In Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Referral_Source__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source__c</fullName>
    <description>HCP/Physician Participant Referral Source</description>
    <inlineHelpText>HCP/Physician Participant Referral Source</inlineHelpText>
    <label>Referral Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>HCP Prescreen Log</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>ePR</fullName>
            </value>
            <value>
                <fullName>ACOE</fullName>
            </value>
            <value>
                <fullName>3rd_Party</fullName>
                <label>3rd Party</label>
            </value>
            <value>
                <fullName>Autocruitment</fullName>
            </value>
            <value>
                <fullName>23andMe</fullName>
            </value>
            <value>
                <fullName>IQVIA registry</fullName>
            </value>
            <value>
			 <fullName>Ciitizen</fullName>
                </value>
            <value>
                <fullName>MassiveBio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/Therapeutic_Area_Patient__c.object-meta.xml
<CustomObject>
    <label>Therapeutic Area Patient</label>
    <nameField>
        <displayFormat>TAP - {00000000}</displayFormat>
        <label>Therapeutic Area Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Therapeutic Area Patients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Condition_Of_Interest_Order__c.field-meta.xml
<CustomField>
    <fullName>Condition_Of_Interest_Order__c</fullName>
    <label>Condition Of Interest Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Therapeutic Areas</relationshipLabel>
    <relationshipName>Therapeutic_Area_Patients</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Therapeutic Area Patients</relationshipLabel>
    <relationshipName>Therapeutic_Area_Patients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <displayFormat>TOPIC-{0000}</displayFormat>
        <label>Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Topic__c/fields/TopicId__c.field-meta.xml
<CustomField>
    <fullName>TopicId__c</fullName>
    <label>TopicId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/messaging/classes/Test_NotificationService.cls
/**
 * Created by Olga Skrynnikova on 12/10/2019.
 */

@IsTest
private class Test_NotificationService {
    @TestSetup
    static void init() {
        Test.startTest();
        TestData.loadTestData();
        TestData.createTCAcceptance();

        Test.stopTest();
    }

    @IsTest
    static void test_checkHCPNotificationType() {
        Test.startTest();
        TestData testData = new TestData();
        testData.pe.Participant_Status__c = PEStatusState.PE_STATUS_REFERRAL_ACCEPTED;
        NotificationService.checkHCPNotificationType(testData.pe, false);

        testData.pe.Participant_Status__c = PEStatusState.PE_STATUS_REFERRAL_DECLINED;
        NotificationService.checkHCPNotificationType(testData.pe, false);

        testData.pe.Participant_Status__c = PEStatusState.PE_STATUS_REFERRAL_ON_HOLD;
        NotificationService.checkHCPNotificationType(testData.pe, false);
        Test.stopTest();
    }

    @IsTest
    static void test_checkPatientNotificationType() {
        Test.startTest();
        TestData testData = new TestData();
        testData.pe.Participant_Status__c = PEStatusState.PE_STATUS_REFERRAL_ACCEPTED;
        NotificationService.checkPatientNotificationType(testData.pe, false);

        testData.pe.Participant_Status__c = PEStatusState.PE_STATUS_REFERRAL_DECLINED;
        NotificationService.checkPatientNotificationType(testData.pe, false);

        testData.pe.Participant_Status__c = PEStatusState.PE_STATUS_REFERRAL_ON_HOLD;
        NotificationService.checkPatientNotificationType(testData.pe, false);

        Test.stopTest();
    }

    @IsTest
    static void test_checkPatientNotificationVTType() {
        Test.startTest();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = [
            SELECT
                Id,
                Participant_Status__c,
                Referral_Source__c,
                Clinical_Trial_Profile__r.Patient_Portal_Enabled__c
            FROM Participant_Enrollment__c
            WHERE Id = :testData.pe.Id
        ];
        pe.Referral_Source__c = 'HCP';

        pe.Participant_Status__c = PEStatusState.PE_STATUS_REFERRAL_ACCEPTED;
        NotificationService.checkPatientNotificationVTType(pe);

        pe.Participant_Status__c = PEStatusState.PE_STATUS_REFERRAL_DECLINED;
        NotificationService.checkPatientNotificationVTType(pe);

        pe.Participant_Status__c = PEStatusState.PE_STATUS_REFERRAL_ON_HOLD;
        NotificationService.checkPatientNotificationVTType(pe);

        pe.Clinical_Trial_Profile__r.Patient_Portal_Enabled__c = true;
        pe.Participant_Status__c = PEStatusState.PE_STATUS_ENROLLMENT_SUCCESS;
        NotificationService.checkPatientNotificationVTType(pe);
        Test.stopTest();
    }
    @IsTest
    static void test_checkPatientNotificationVT() {
        Test.startTest();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = [
            SELECT
                Id,
                Participant_Status__c,
                Referral_Source__c,
                Clinical_Trial_Profile__r.Patient_Portal_Enabled__c
            FROM Participant_Enrollment__c
            WHERE Id = :testData.pe.Id
        ];
        pe.Referral_Source__c = 'HCP';

        pe.Participant_Status__c = PEStatusState.PE_STATUS_RECEIVED;
        update pe;
        NotificationService.checkPatientNotificationVTType(pe);
        Test.stopTest();
    }

    @IsTest
    static void test_checkPatientNotificationVTT() {
        Test.startTest();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = [
            SELECT
                Id,
                Participant_Status__c,
                Referral_Source__c,
                Clinical_Trial_Profile__r.Patient_Portal_Enabled__c
            FROM Participant_Enrollment__c
            WHERE Id = :testData.pe.Id
        ];
        pe.Referral_Source__c = 'ePR';

        pe.Participant_Status__c = PEStatusState.PE_STATUS_RECEIVED;
        update pe;
        NotificationService.checkPatientNotificationVTType(pe);
        Test.stopTest();
    }

    @IsTest
    static void test_getTopicOrCreateNew() {
        Test.startTest();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = [
            SELECT
                Id,
                Participant_Status__c,
                Referral_Source__c,
                Clinical_Trial_Profile__r.Patient_Portal_Enabled__c
            FROM Participant_Enrollment__c
            WHERE Id = :testData.pe.Id
        ];

        Topic__c topic = NotificationService.getTopicOrCreateNew(null);
        Test.stopTest();
    }

    @IsTest
    static void test_getTopicListOrCreateNewByCOI() {
        Test.startTest();
        Account account = (Account) TestDataFactory.getSObject(
            Account.getSObjectType(),
            new Map<String, Object>{ 'Name' => CommunityService.COMMUNITY_PARTICIPANT_ACCOUNT_NAME }
        );
        Participant__c participant = (Participant__c) TestDataFactory.getSObject(
            Participant__c.getSObjectType()
        );
        Therapeutic_Area__c ta = (Therapeutic_Area__c) TestDataFactory.getSObject(
            Therapeutic_Area__c.getSObjectType()
        );
        insert new List<SObject>{ account, participant, ta };

        Therapeutic_Area_Patient__c tap = (Therapeutic_Area_Patient__c) TestDataFactory.getSObject(
            Therapeutic_Area_Patient__c.getSObjectType(),
            new Map<String, Object>{
                'Participant__c' => participant.Id,
                'Therapeutic_Area__c' => ta.Id,
                'Condition_Of_Interest_Order__c' => 0
            }
        );

        List<Therapeutic_Area_Patient__c> tapList = new List<Therapeutic_Area_Patient__c>();
        tapList.add(tap);
        List<Topic__c> res = NotificationService.getTopicListOrCreateNewByCOI(tapList);
        Test.stopTest();
    }
    @isTest
    static void test_getTopicListOrCreateNew() {
        Test.startTest();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = [
            SELECT Id, Clinical_Trial_Profile__c
            FROM Participant_Enrollment__c
            WHERE Id = :testData.pe.Id
        ];

        Clinical_Trial_Profile__c ct = [
            SELECT Id, Therapeutic_Area__c
            FROM Clinical_Trial_Profile__c
            WHERE Id = :pe.Clinical_Trial_Profile__c
        ];

        List<Clinical_Trial_Profile__c> ctpList = new List<Clinical_Trial_Profile__c>();
        ctpList.add(ct);

        List<Topic__c> topics = NotificationService.getTopicListOrCreateNew(ctpList);
        Test.stopTest();
    }
    @isTest
    static void test_getTopicListOrCreateNewByCTPId() {
        Test.startTest();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = [
            SELECT Id, Clinical_Trial_Profile__c
            FROM Participant_Enrollment__c
            WHERE Id = :testData.pe.Id
        ];

        Clinical_Trial_Profile__c ct = [
            SELECT Id, Therapeutic_Area__c
            FROM Clinical_Trial_Profile__c
            WHERE Id = :pe.Clinical_Trial_Profile__c
        ];

        List<Clinical_Trial_Profile__c> ctpList = new List<Clinical_Trial_Profile__c>();
        ctpList.add(ct);

        List<Topic__c> topics = NotificationService.getTopicListOrCreateNewByCTPId(ctpList);
        Test.stopTest();
    }

    @isTest
    static void test_sendNotifications_v1() {
        Test.startTest();
        TestData testData = new TestData();
        Contact piContact = [
            SELECT Id, Email, Language__c, Phone
            FROM Contact
            WHERE Id = :testData.pe.Participant_Contact__c
        ];
        piContact.Language__c = 'en_US';
        piContact.Phone = '+77777777777';
        piContact.Participant_Opt_In_Status_Emails__c = true;

        List<Contact> contacts = new List<Contact>();
        contacts.add(piContact);
        update contacts;

        Task task = new Task();
        task.Subject = 'test';
        task.Reminder_Date__c = Datetime.now();
        task.ReminderDateTime = Datetime.now();
        task.Activity_Datetime__c = Datetime.now().addDays(1);
        task.OwnerId = testData.participantUser.Id;
        task.Visible_For__c = 'Delegates';

        insert task;

        List<Notification__c> notifications = new List<Notification__c>();
        notifications.add(
            new Notification__c(
                Notification_Type__c = 'Message_to_HCP_Patient_Accepted_Type',
                Recipient__c = testData.pe.Participant_Contact__c,
                WhatId__c = testData.pe.Id,
                StartDate__c = Date.today(),
                Task_Id__c = task.Id
            )
        );

        insert notifications;

        try {
            NotificationService.sendNotifications(notifications);
        } catch (Exception e) {
        }

        Test.stopTest();
    }

    @isTest
    static void test_sendNotifications_v2() {
        Test.startTest();
        TestData testData = new TestData();
        Contact piContact = [
            SELECT Id, Email, Language__c, Phone
            FROM Contact
            WHERE Id = :testData.pe.Participant_Contact__c
        ];
        piContact.Language__c = 'en_US';
        piContact.Phone = '+77777777777';

        List<Contact> contacts = new List<Contact>();
        contacts.add(piContact);
        update contacts;

        Task task = new Task();
        task.Subject = 'test';
        task.Reminder_Date__c = Datetime.now();
        task.ReminderDateTime = Datetime.now();
        task.Activity_Datetime__c = Datetime.now().addDays(1);
        task.OwnerId = testData.participantUser.Id;
        task.Visible_For__c = 'Delegates';

        insert task;

        Topic__c topic = new Topic__c();
        topic.TopicId__c = 'rga134';

        insert topic;

        List<Notification__c> notifications = new List<Notification__c>();
        notifications.add(
            new Notification__c(
                Notification_Type__c = 'Message_to_PI_Access_Level_Changed_Type',
                WhatId__c = piContact.Id,
                Task_Id__c = task.Id,
                Topic__c = topic.Id,
                Recipient__c = testData.pe.Participant_Contact__c
            )
        );
        insert notifications;

        try {
            NotificationService.sendNotifications(notifications);
        } catch (Exception e) {
        }

        Test.stopTest();
    }

    @isTest
    static void test_sendNotification_v3() {
        Test.startTest();
        TestData testData = new TestData();
        Contact piContact = [
            SELECT Id, Email, Language__c, Phone
            FROM Contact
            WHERE Id = :testData.pe.Participant_Contact__c
        ];
        piContact.Language__c = 'en_US';
        piContact.Phone = '+77777777777';

        List<Contact> contacts = new List<Contact>();
        contacts.add(piContact);
        update contacts;

        Task task = new Task();
        task.Subject = 'test';
        task.Reminder_Date__c = Datetime.now();
        task.ReminderDateTime = Datetime.now();
        task.Activity_Datetime__c = Datetime.now().addDays(1);
        task.OwnerId = testData.participantUser.Id;
        task.Visible_For__c = 'Delegates';

        insert task;

        Topic__c topic = new Topic__c();
        topic.TopicId__c = 'rga134';

        insert topic;

        List<Notification__c> notifications = new List<Notification__c>();
        notifications.add(
            new Notification__c(
                Notification_Type__c = 'Message_To_PT_New_Message_Type',
                WhatId__c = testData.pe.Id,
                Task_Id__c = task.Id,
                Topic__c = topic.Id
            )
        );
        insert notifications;

        try {
            NotificationService.sendNotifications(notifications);
        } catch (Exception e) {
        }

        Test.stopTest();
    }

    @isTest
    static void test_sendNotifications_v4() {
        Test.startTest();
        TestData testData = new TestData();
        Contact piContact = [
            SELECT Id, Email, Language__c, Phone, Participant_Opt_In_Status_SMS__c
            FROM Contact
            WHERE Id = :testData.pe.Participant_Contact__c
        ];
        piContact.Language__c = 'en_US';
        piContact.Phone = '+77777777777';
        piContact.Participant_Opt_In_Status_SMS__c = true;

        update piContact;

        Task task = new Task();
        task.Subject = 'test';
        task.Reminder_Date__c = Datetime.now();
        task.ReminderDateTime = Datetime.now();
        task.Activity_Datetime__c = Datetime.now().addDays(1);
        task.OwnerId = testData.participantUser.Id;
        task.Visible_For__c = 'Delegates';
        insert task;

        Clinical_Trial_Profile__c ctP = [
            SELECT Id, Suppress_Participant_Emails__c
            FROM Clinical_Trial_Profile__c
            WHERE Id = :testData.ctp.Id
        ];
        ctP.Suppress_Participant_Emails__c = false;
        update ctP;

        List<Notification__c> notifications = new List<Notification__c>();
        notifications.add(
            new Notification__c(
                Notification_Type__c = 'Message_to_PT_COI_Ctp_Start_Enroll_Type',
                Recipient__c = testData.piContact.Id,
                WhatId__c = testData.ctp.Id,
                StartDate__c = Date.today(),
                Task_Id__c = task.Id
            )
        );
        insert notifications;

        try {
            NotificationService.sendNotifications(notifications);
        } catch (Exception e) {
        }

        Test.stopTest();
    }

    @isTest
    static void test_sendNotifications_v5() {
        Test.startTest();
        TestData testdat = new TestData();
        Contact piContact = [
            SELECT Id, Email, Language__c, Phone
            FROM Contact
            WHERE Email = 'pi@emil.com'
        ];
        piContact.Language__c = 'en_US';
        piContact.Phone = '+77777777777';

        List<Contact> contacts = new List<Contact>();
        contacts.add(piContact);
        update contacts;

        List<Notification__c> notifications = new List<Notification__c>();
        notifications.add(
            new Notification__c(
                Notification_Type__c = NotificationCatalog.MESSAGE_TO_PT_DATA_AVAILABLE_TYPE,
                Recipient__c = piContact.Id,
                WhatId__c = testdat.pe.Id,
                StartDate__c = Date.today()
            )
        );

        insert notifications;
        try {
            NotificationService.sendNotifications(notifications);
        } catch (Exception e) {
        }

        Test.stopTest();
    }

    @isTest
    static void test_sendNotifications_v6() {
        Test.startTest();
        TestData testdat = new TestData();
        Contact piContact = [
            SELECT
                Id,
                Email,
                Language__c,
                Phone,
                UserCommunityIsDelegate__c,
                Participant_Opt_In_Status_Emails__c
            FROM Contact
            WHERE Id = :testdat.pe.Participant_Contact__c
        ];
        piContact.Language__c = 'en_US';
        piContact.Phone = '+77777777777';
        piContact.UserCommunityIsDelegate__c = false;
        piContact.Participant_Opt_In_Status_Emails__c = true;

        List<Contact> contacts = new List<Contact>();
        contacts.add(piContact);
        update contacts;

        Study_Site__c s = [
            SELECT Id, Suppress_Participant_Emails__c
            FROM Study_Site__c
            WHERE id = :testdat.pe.Study_Site__r.Id
        ];
        s.Suppress_Participant_Emails__c = false;
        update s;

        Task task = new Task();
        task.Subject = 'test';
        task.Reminder_Date__c = Datetime.now();
        task.ReminderDateTime = Datetime.now();
        task.Activity_Datetime__c = Datetime.now().addDays(1);
        task.OwnerId = testDat.participantUser.Id;
        task.Visible_For__c = 'Delegates';
        insert task;

        List<Notification__c> notifications = new List<Notification__c>();
        notifications.add(
            new Notification__c(
                Notification_Type__c = NotificationCatalog.MESSAGE_TO_PT_DATA_AVAILABLE_TYPE,
                Recipient__c = piContact.Id,
                WhatId__c = testdat.pe.Id,
                Task_Id__c = task.Id,
                StartDate__c = Date.today()
            )
        );

        insert notifications;
        try {
            NotificationService.sendNotifications(notifications);
        } catch (Exception e) {
        }

        Test.stopTest();
    }
}