force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Relevant_Links_Are_Available__c.field-meta.xml
<CustomField>
    <fullName>Relevant_Links_Are_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Relevant Links Are Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Documents_Are_Available__c.field-meta.xml
<CustomField>
    <fullName>Study_Documents_Are_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Study Documents Are Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Video_And_Articles_Are_Available__c.field-meta.xml
<CustomField>
    <fullName>Video_And_Articles_Are_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Video And Articles Are Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/Res_study__c.object-meta.xml
<CustomObject>
    <label>Study Resource</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Resource Study Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/resources/objects/Res_study__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <inlineHelpText>master detail</inlineHelpText>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Resource</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Expires_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Expires_After_Days__c</fullName>
    <label>Number of Days Before Document Expires</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>Only Study Specific Resource can be added.</errorMessage>
        <filterItems>
            <field>Resource__c.Content_Class__c</field>
            <operation>equals</operation>
            <value>Study-Specific</value>
        </filterItems>
        <filterItems>
            <field>Resource__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Study Document</value>
        </filterItems>
        <filterItems>
            <field>Resource__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Relevant Link</value>
        </filterItems>
        <infoMessage>Only Study Specific Resource can be added.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Study Resources</relationshipLabel>
    <relationshipName>Study</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_In_Alumni__c.field-meta.xml
<CustomField>
    <fullName>Visible_In_Alumni__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible In Alumni</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Res_study__c/fields/Visible_To_Delegates__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Delegates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Delegates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_Participant__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Participant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To Participant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_PI__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_PI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To PI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Res_study__c/fields/Visible_To_RP__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_RP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible To RP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/resources/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object contains Video/Articles</description>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Resources Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/resources/objects/Resource__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Study_Document</fullName>
                <label>Study Document</label>
            </value>
            <value>
                <fullName>Relevant_Link</fullName>
                <label>Relevant Link</label>
            </value>
            <value>
                <fullName>Submitted_Articles</fullName>
                <label>Submitted Articles</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Resource__c/fields/Countries__c.field-meta.xml
<CustomField>
    <fullName>Countries__c</fullName>
    <label>Countries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Resource__c/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/resources/objects/Resource__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
<!--                <fullName>Helpful Links</fullName>-->
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
<!--                <label>Helpful Links</label>-->
            </value>
            <value>
                <fullName>Patient advocacy groups</fullName>
            </value>
            <value>
                <fullName>Articles for caregivers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/Therapeutic_Area__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Therapeutic Area</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Therapeutic Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapeutic Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Therapeutic Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Therapeutic_Area__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Therapeutic Area</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Conditions of Interests</relationshipLabel>
    <relationshipName>Therapeutic_Areas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COI</fullName>
            </value>
            <value>
                <fullName>TA</fullName>
            </value>
            <value>
                <fullName>3dPartyCOI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Assignment__c/Therapeutic_Area_Assignment__c.object-meta.xml
<CustomObject>
    <description>Object for relation between Resource and Therapeutic Area</description>
    <label>Therapeutic Area Assignment</label>
    <nameField>
        <displayFormat>TAA - {0000000}</displayFormat>
        <label>Therapeutic Area Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Therapeutic Area Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area_Assignment__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Therapeutic Area Assignments</relationshipLabel>
    <relationshipName>Therapeutic_Area_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Assignment__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Therapeutic Area Assignments</relationshipLabel>
    <relationshipName>Therapeutic_Area_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/Therapeutic_Area_Patient__c.object-meta.xml
<CustomObject>
    <label>Therapeutic Area Patient</label>
    <nameField>
        <displayFormat>TAP - {00000000}</displayFormat>
        <label>Therapeutic Area Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Therapeutic Area Patients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Therapeutic Areas</relationshipLabel>
    <relationshipName>Therapeutic_Area_Patients</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Therapeutic_Area_Patient__c/fields/Therapeutic_Area__c.field-meta.xml
<CustomField>
    <fullName>Therapeutic_Area__c</fullName>
    <label>Therapeutic Area</label>
    <referenceTo>Therapeutic_Area__c</referenceTo>
    <relationshipLabel>Therapeutic Area Patients</relationshipLabel>
    <relationshipName>Therapeutic_Area_Patients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/community-pages-pp/home-page/classes/RelevantLinksRemote.cls
/**
 * Created by Nargiz Mamedova on 12/13/2019.
 */

public without sharing class RelevantLinksRemote {
    public class InitData {
        @AuraEnabled
        public Boolean linksAvailable = false;
        @AuraEnabled
        public List<LinksWrapper> linksWrappers = new List<LinksWrapper>();
    }

    public class InitDataNew {
        @AuraEnabled
        public Boolean linksAvailable = false;

        @AuraEnabled
        public Boolean relevantLinksAreAvailable = false;
        @AuraEnabled
        public Boolean studyDocumentsAreAvailable = false;
        @AuraEnabled
        public Boolean videoAndArticlesAreAvailable = false;
        @AuraEnabled
        public List<ResourceService.ResourceWrapper> resources = new List<ResourceService.ResourceWrapper>();
        @AuraEnabled
        public Boolean isDelegate = false;
        @AuraEnabled
        public string participantStateValue;
    }

    public class LinksWrapper {
        @AuraEnabled
        public LabelValueItem type;
        @AuraEnabled
        public List<ResourceService.ResourceWrapper> resources = new List<ResourceService.ResourceWrapper>();
    }

    @AuraEnabled
    public static InitData getInitData() {
        try {
            String contentType = ResourceService.RESOURCE_TYPE_RELEVANT_LINK;
            List<Id> COIsOfParticipant = new List<Id>();
            InitData initData = new InitData();

            ParticipantService.ParticipantState ps = ParticipantService.getInstance().getState();
            List<Participant_Enrollment__c> enrollments = getEnrollments(ps);
            List<String> preferredLanguages = ContactService.getPreferredLanguages();

            List<Therapeutic_Area_Patient__c> therapeuticAreaPatients = [
                SELECT Id, Therapeutic_Area__c
                FROM Therapeutic_Area_Patient__c
                WHERE Participant__c = :ps.participant.Id
            ];
            for (Therapeutic_Area_Patient__c tap : therapeuticAreaPatients)
                COIsOfParticipant.add(tap.Therapeutic_Area__c);

            List<Resource__c> resourcesVisibleForParticipant = getStudySpecificResources(
                contentType,
                enrollments,
                preferredLanguages,
                COIsOfParticipant,
                ps.isDelegate
            );
            if (ps.value == ParticipantService.ParticipantStates.ALUMNI) {
                resourcesVisibleForParticipant.addAll(
                    getCOIResources(contentType, COIsOfParticipant, preferredLanguages)
                );
                if (!resourcesVisibleForParticipant.isEmpty())
                    initData.linksAvailable = true;
            } else {
                if (enrollments.size() > 0)
                    initData.linksAvailable = true;
            }

            TranslateHelper.translate(resourcesVisibleForParticipant);
            List<LabelValueItem> typeLabelValues = getTranslatedTypes(
                Resource__c.Type__c.getDescribe().getPicklistValues()
            );
            for (LabelValueItem t : typeLabelValues) {
                LinksWrapper lw = new LinksWrapper();
                for (Resource__c res : resourcesVisibleForParticipant) {
                    if (res.Type__c.equals(t.value)) {
                        lw.resources.add(new ResourceService.ResourceWrapper(res));
                    }
                }

                if (!lw.resources.isEmpty()) {
                    lw.type = t;
                    lw.resources = ResourceService.sortResourcesByCOI(lw.resources);
                    initData.linksWrappers.add(lw);
                }
            }

            if (initData.linksAvailable && initData.linksWrappers.isEmpty()) {
                LinksWrapper lw = new LinksWrapper();
                lw.type = new LabelValueItem(
                    TranslateHelper.getPickListLabel(Resource__c.Type__c, 'Relevant Links'),
                    'Relevant Links'
                );
                initData.linksWrappers.add(lw);
            }

            return initData;
        } catch (Exception e) {
            return (InitData) AuraHelper.throwException(e);
        }
    }

    @AuraEnabled
    public static InitDataNew getInitDataNew() {
        try {
            String contentType = ResourceService.RESOURCE_TYPE_RELEVANT_LINK;
            List<Id> COIsOfParticipant = new List<Id>();
            InitDataNew initDataNew = new InitDataNew();

            ParticipantService.ParticipantState ps = ParticipantService.getInstance().getState();
            List<Participant_Enrollment__c> enrollments = getEnrollments(ps);
            List<String> preferredLanguages = ContactService.getPreferredLanguages();

            //getting ctp value from ParticipantState for ctp toggles
            initDataNew.relevantLinksAreAvailable = ps.ctp.Relevant_Links_Are_Available__c;
            initDataNew.studyDocumentsAreAvailable = ps.ctp.Study_Documents_Are_Available__c;
            initDataNew.videoAndArticlesAreAvailable = ps.ctp.Video_And_Articles_Are_Available__c;
            initDataNew.isDelegate = ps.isDelegate;
            initDataNew.participantStateValue = String.valueOf(ps.value);

            List<Therapeutic_Area_Patient__c> therapeuticAreaPatients = [
                SELECT Id, Therapeutic_Area__c
                FROM Therapeutic_Area_Patient__c
                WHERE Participant__c = :ps.participant.Id
            ];
            for (Therapeutic_Area_Patient__c tap : therapeuticAreaPatients)
                COIsOfParticipant.add(tap.Therapeutic_Area__c);

            List<Resource__c> resourcesVisibleForParticipant = new List<Resource__c>();
            if (
                (ps.value != ParticipantService.ParticipantStates.ALUMNI &&
                initDataNew.relevantLinksAreAvailable) ||
                ps.value == ParticipantService.ParticipantStates.ALUMNI
            ) {
                //study specific relevant links
                resourcesVisibleForParticipant = getStudySpecificResources(
                    contentType,
                    enrollments,
                    preferredLanguages,
                    COIsOfParticipant,
                    ps.isDelegate
                );
            }

            if (
                (ps.value == ParticipantService.ParticipantStates.ALUMNI &&
                ps.isDelegate == false) || !initDataNew.relevantLinksAreAvailable
            ) {
                //platform level relevant links
                resourcesVisibleForParticipant.addAll(
                    getCOIResources(contentType, COIsOfParticipant, preferredLanguages)
                );
                if (!resourcesVisibleForParticipant.isEmpty())
                    initDataNew.linksAvailable = true;
            } else {
                if (enrollments.size() > 0)
                    initDataNew.linksAvailable = true;
            }

            TranslateHelper.translate(resourcesVisibleForParticipant);
            List<LabelValueItem> typeLabelValues = getTranslatedTypes(
                Resource__c.Type__c.getDescribe().getPicklistValues()
            );

            for (Resource__c res : resourcesVisibleForParticipant) {
                ResourceService.ResourceWrapper rw = new ResourceService.ResourceWrapper(res);
                initDataNew.resources.add(rw);
            }

            initDataNew.resources = ResourceService.sortResourcesByCOI(initDataNew.resources);
            return initDataNew;
        } catch (Exception e) {
            return (InitDataNew) AuraHelper.throwException(e);
        }
    }

    private static List<Resource__c> getStudySpecificResources(
        String contentType,
        List<Participant_Enrollment__c> enrollments,
        List<String> preferredLanguages,
        List<Id> coiIds,
        Boolean isDelegate
    ) {
        List<Resource__c> resourcesVisibleForParticipant = new List<Resource__c>();
        List<Id> ctpIds = new List<Id>();
        for (Participant_Enrollment__c pe : enrollments)
            ctpIds.add(pe.Clinical_Trial_Profile__c);

        if (ctpIds != null && ctpIds.size() > 0) {
            List<Res_study__c> resStudies = [
                SELECT
                    Id,
                    Clinical_Trial_Profile__c,
                    Resource__c,
                    Resource__r.URL__c,
                    Resource__r.Title__c,
                    Resource__r.Type__c,
                    Resource__r.Content_Type__c,
                    Resource__r.Countries__c,
                    Resource__r.Languages__c,
                    Visible_To_Participant__c,
                    Visible_To_Delegates__c,
                    Visible_To_PI__c,
                    Visible_To_RP__c,
                    Visible_In_Alumni__c,
                    Expires_After_Days__c,
                    Expires_On_Status__c,
                    Active_On_Status__c,
                    Active_After_Days__c
                FROM Res_study__c
                WHERE
                    Clinical_Trial_Profile__c IN :ctpIds
                    AND Resource__r.Content_Type__c = :contentType
            ];

            List<Id> resourceIdsVisibleForParticipant = new List<Id>();
            for (Res_study__c rs : resStudies) {
                for (Participant_Enrollment__c pe : enrollments) {
                    if (
                        rs.Clinical_Trial_Profile__c == pe.Clinical_Trial_Profile__c &&
                        StudyResourceVisibilityService.isResourceVisibleForPE(
                            rs,
                            pe,
                            preferredLanguages,
                            CommunityService.getUserContact().userCommunityMode__c,
                            isDelegate
                        )
                    ) {
                        resourceIdsVisibleForParticipant.add(rs.Resource__c);
                    }
                }
            }

            resourcesVisibleForParticipant = [
                SELECT
                    Id,
                    Title__c,
                    Type__c,
                    URL__c,
                    description__c,
                    CreatedDate,
                    (
                        SELECT Id, Therapeutic_Area__c
                        FROM Therapeutic_Area_Assignments__r
                        WHERE Therapeutic_Area__c IN :coiIds
                    )
                FROM Resource__c
                WHERE Id IN :resourceIdsVisibleForParticipant
                ORDER BY CreatedDate DESC
            ];
        }
        return resourcesVisibleForParticipant;
    }

    private static Set<Resource__c> getCOIResources(
        String contentType,
        List<Id> coiIds,
        List<String> preferredLanguages
    ) {
        Set<Resource__c> coiResources = new Set<Resource__c>();
        List<Id> resWithResStudyIds = new List<Id>();
        List<Id> taaResIds = new List<Id>();
        List<Id> coiResIds = new List<Id>();

        List<Therapeutic_Area_Assignment__c> taAssignments = [
            SELECT Resource__c
            FROM Therapeutic_Area_Assignment__c
            WHERE Therapeutic_Area__c IN :coiIds
        ];
        for (Therapeutic_Area_Assignment__c taa : taAssignments)
            taaResIds.add(taa.Resource__c);

        List<Res_study__c> resStudies = [
            SELECT Id, Resource__c
            FROM Res_study__c
            WHERE Resource__c IN :taaResIds AND Resource__r.Content_Type__c = :contentType
        ];
        for (Res_study__c rs : resStudies)
            resWithResStudyIds.add(rs.Resource__c);

        for (Id res : taaResIds) {
            if (!resWithResStudyIds.contains(res))
                coiResIds.add(res);
        }

        List<Resource__c> resources = [
            SELECT
                Id,
                Title__c,
                Type__c,
                URL__c,
                Languages__c,
                description__c,
                (
                    SELECT Id, Therapeutic_Area__c
                    FROM Therapeutic_Area_Assignments__r
                    WHERE Therapeutic_Area__c IN :coiIds
                )
            FROM Resource__c
            WHERE Id IN :coiResIds AND Content_Type__c = :contentType
            ORDER BY CreatedDate DESC
        ];

        for (Resource__c res : resources) {
            for (String lang : preferredLanguages) {
                if (res.Languages__c.contains(lang))
                    coiResources.add(res);
            }
        }
        return coiResources;
    }

    private static List<Participant_Enrollment__c> getEnrollments(
        ParticipantService.ParticipantState participantState
    ) {
        List<Participant_Enrollment__c> enrollments = new List<Participant_Enrollment__c>();
        if (participantState.value == ParticipantService.ParticipantStates.ALUMNI) {
            Id currentContactId = CommunityService.getInstance().getCurrentContactId();
            if (participantState.isDelegate)
                currentContactId = PatientDelegateService.getParticipantByDelegateContactId(
                        currentContactId
                    )
                    .Contact__c;

            List<Id> peIds = PatientDelegateService.getPastPEIdsForContact(currentContactId);
            if (peIds != null) {
                enrollments = [
                    SELECT
                        Id,
                        Days_After_Enrolled__c,
                        Participant_Status__c,
                        Clinical_Trial_Profile__c,
                        Clinical_Trial_Profile__r.Relevant_Links_Are_Available__c,
                        Study_Site__r.Approved_Lng__c,
                        Study_Site__r.Site__r.BillingCountryCode
                    FROM Participant_Enrollment__c
                    WHERE
                        Id IN :peIds
                        AND Clinical_Trial_Profile__r.Relevant_Links_Are_Available__c = TRUE
                ];
            }
        } else {
            enrollments = new List<Participant_Enrollment__c>();
            if (participantState.ctp.Relevant_Links_Are_Available__c)
                enrollments.add(participantState.pe);
        }
        return enrollments;
    }

    private static List<LabelValueItem> getTranslatedTypes(List<PicklistEntry> types) {
        List<LabelValueItem> translatedTypes = new List<LabelValueItem>();
        for (PicklistEntry t : types) {
            if (!t.getValue().equals('None'))
                translatedTypes.add(new LabelValueItem(t.getLabel(), t.getValue()));
        }
        return translatedTypes;
    }
}