force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Enable_for_Call_Center_Support__c.field-meta.xml
<CustomField>
    <fullName>Enable_for_Call_Center_Support__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enable for Call Center Support</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Status__c</fullName>
    <inlineHelpText>field populated from Data Factory</inlineHelpText>
    <label>CTMS Recruitment Status</label>
<!--    <trackHistory>true</trackHistory>-->
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed Follow-up / In Analysis</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Enrolling</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Open to Enrollment</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Closed to Enrollment</fullName>
            </value>
            <value>
                <fullName>Closed Follow Up / In Analysis</fullName>
                <isActive>false</isActive>
                <label>Closed Follow Up / In Analysis</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
                <isActive>false</isActive>
                <label>Proposed</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Staff__c/Site_Staff__c.object-meta.xml
<CustomObject>
    <description>Used to connect Contacts with Study Sites to represent a Principal Investigator&#39;s team</description>

    <label>Site Staff</label>
    <nameField>
        <displayFormat>Staff #{0000}</displayFormat>
        <label>Site Staff</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Staff__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; Study_Site__r.Clinical_Trial_Profile__c,  Study_Site__r.Clinical_Trial_Profile__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clinical Trial Profile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact__c</fullName>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staff&#39;s Study Sites</relationshipLabel>
    <relationshipName>PI_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <formula>if(is_Site_and_Staff_Same_Country__c == false,  HYPERLINK(&quot;/&quot;&amp; Id , Name ) , &apos;-&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Staff</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Site Staff</relationshipLabel>
    <relationshipName>Site_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Enable_for_Call_Center_Support__c.field-meta.xml
<CustomField>
    <fullName>Enable_for_Call_Center_Support__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable for Call Center Support</label>
    <type>Checkbox</type> 
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Recruitment_Status__c.field-meta.xml
<CustomField>
    <fullName>Recruitment_Status__c</fullName>
    <label>CTMS Recruitment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved for SSV</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Conditional Selected</fullName>
            </value>
            <value>
                <fullName>Contacted (Feasibility)</fullName>
            </value>
            <value>
                <fullName>Contacted (Site ID)</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>Enrollment Closed</fullName>
            </value>
            <value>
                <fullName>Enrollment On Hold</fullName>
            </value>
            <value>
                <fullName>Enrollment Open</fullName>
            </value>
            <value>
                <fullName>Essential Documents in place</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Interested (Feasibility)</fullName>
            </value>
            <value>
                <fullName>Interested (Site ID)</fullName>
            </value>
            <value>
                <fullName>Non-responder (Feasibility)</fullName>
            </value>
            <value>
                <fullName>Non-responder (Site ID)</fullName>
            </value>
            <value>
                <fullName>Not Interested (Feasibility)</fullName>
            </value>
            <value>
                <fullName>Not Interested (Site ID)</fullName>
            </value>
            <value>
                <fullName>Not Selected</fullName>
            </value>
            <value>
                <fullName>Null</fullName>
            </value>
            <value>
                <fullName>Permanently Closed</fullName>
            </value>
            <value>
                <fullName>Prematurely Closed</fullName>
            </value>
            <value>
                <fullName>Preselected</fullName>
            </value>
            <value>
                <fullName>Ready for Initiation</fullName>
            </value>
            <value>
                <fullName>Regulatory Green Light</fullName>
            </value>
            <value>
                <fullName>Regulatory Initiation</fullName>
            </value>
            <value>
                <fullName>Rejected for SSV</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Targeted</fullName>
            </value>
            <value>
                <fullName>Unsure (Feasibility)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to study site delegate</description>
    <label>Site Staff</label>
    <referenceTo>Site_Staff__c</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Study_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Study_Site_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Study Site Number</label>
    <length>255</length>
<!--    <trackHistory>true</trackHistory>-->
    <type>Text</type>
</CustomField>

force-app/main/community-pages-cc/classes/SiteListPageRemote.cls
public without sharing class SiteListPageRemote {
    public class SiteWrapper {
        @AuraEnabled
        public String studyName;
        @AuraEnabled
        public String siteNumber;
        @AuraEnabled
        public String siteName;
        @AuraEnabled
        public String country;
        @AuraEnabled
        public String piName;
        @AuraEnabled
        public String phoneNumber;
        @AuraEnabled
        public String primaryContact;
        @AuraEnabled
        public String siteStatus;
    }
    public class PaginatedSiteWrapper {
        @AuraEnabled
        public List<SiteWrapper> sites;
        @AuraEnabled
        public PaginationData paginationData;
    }
    public static final List<String> SS_TABLE_FIELDS = new List<String>{
        'Clinical_Trial_Profile__r.Name',
        'Study_Site_Number__c',
        'Name',
        'Site_Staff__r.Site_Contact__r.MailingCountry',
        'Principal_Investigator__r.Name',
        'Site_Staff__r.Site_Contact__r.Phone',
        'Site_Staff__r.Site_Contact__r.Name',
        'Recruitment_Status__c'
    };

    public static final String DEFAULT_FILTER = 'Enable_for_Call_Center_Support__c = true AND Clinical_Trial_Profile__r.Enable_for_Call_Center_Support__c = true';

    @AuraEnabled
    public static PaginatedSiteWrapper getSearchResults(
        String searchOption,
        String searchText,
        String sortType
    ) {
        PaginatedSiteWrapper paginatedWrapper = new PaginatedSiteWrapper();
        List<Study_Site__c> siteQueryResult;
        String filterText = '';

        paginatedWrapper.paginationData = new PaginationData(100);
        paginatedWrapper.sites = new List<SiteWrapper>();

        switch on searchOption {
            when 'Principal_Investigator__r.Name' {
                filterText +=
                    DEFAULT_FILTER +
                    ' AND Principal_Investigator__r.Name LIKE ' +
                    '\'%' +
                    String.escapeSingleQuotes(searchText) +
                    '%\'';
            }
            when 'Name' {
                filterText +=
                    DEFAULT_FILTER +
                    ' AND Name LIKE ' +
                    '\'%' +
                    String.escapeSingleQuotes(searchText) +
                    '%\'';
            }
            when else {
                filterText +=
                    DEFAULT_FILTER +
                    ' AND ' +
                    searchOption +
                    ' =' +
                    String.escapeSingleQuotes(searchText);
            }
        }
        try {
            System.debug(filterText);
            //Apply pagination
            Integer recordCount = Database.countQuery(
                'SELECT COUNT() FROM Study_Site__c WHERE ' + filterText
            );

            paginatedWrapper.paginationData.setRecordsCount(recordCount);

            Integer limitvalue = paginatedWrapper.paginationData.pageRecordsCount;
            Integer currentpage = paginatedWrapper.paginationData.currentPage;
            Integer size = currentpage - 1;
            Integer offsetvalue = size * limitvalue;
            //Get query results from DatabaseService
            siteQueryResult = DatabaseService.query(
                SS_TABLE_FIELDS,
                Study_Site__c.getSObjectType(),
                filterText,
                sortType,
                limitvalue,
                offsetvalue
            );

            if (!siteQueryResult.isEmpty()) {
                //Apply translation
                TranslateHelper.translate(siteQueryResult);
                //Transform into wrapper
                paginatedWrapper.sites = wrapperTransformation(siteQueryResult);
            }
            return paginatedWrapper;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static List<SiteWrapper> wrapperTransformation(List<Study_Site__c> siteList) {
        List<SiteWrapper> wrapperList = new List<SiteWrapper>();
        for (Study_Site__c site : siteList) {
            SiteWrapper wrapper = new SiteWrapper();
            wrapper.country = site.Site_Staff__r.Site_Contact__r.MailingCountry;
            wrapper.phoneNumber = site.Site_Staff__r.Site_Contact__r.Phone;
            wrapper.piName = site.Principal_Investigator__r.Name;
            wrapper.primaryContact = site.Site_Staff__r.Site_Contact__r.Name;
            wrapper.siteName = site.Name;
            wrapper.siteNumber = site.Study_Site_Number__c;
            wrapper.siteStatus = site.Recruitment_Status__c;
            wrapper.studyName = site.Clinical_Trial_Profile__r.Name;
            wrapperList.add(wrapper);
        }
        return wrapperList;
    }
}