force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/trial-match/objects/Trial_Match__c/Trial_Match__c.object-meta.xml
<CustomObject>
    <label>Trial Match</label>
    <nameField>
        <displayFormat>TM-{000000}</displayFormat>
        <label>Trial Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trial_Match__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Trial Matches</relationshipLabel>
    <relationshipName>Trial_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/trial-match/classes/TrialMatchPageRemote.cls
/**
 * Created by Sravani Dasari
 */
public without sharing class TrialMatchPageRemote {
    static Id peId;
    @AuraEnabled
    public static TrialMatchContainer getMatchCTPs(String urlid) {
        if (urlid != null)
            peId = Id.valueOf(urlid);
        else
            peId = ParticipantContext.getCurrentPEId();
        try {
            TrialMatchHelper helper = (TrialMatchHelper) ClassFactory.newInstance(
                TrialMatchHelper.class
            );
            TrialMatchContainer trialMatchContainer = helper.getInitTrialMatchContainer(
                peId
            );
            return trialMatchContainer;
        } catch (Exception e) {
            return (TrialMatchContainer) AuraHelper.throwException(e);
        }
    }

    public class TrialMatchContainer {
        @AuraEnabled
        public List<TrialMatchCTP> trialmatchctps;
        @AuraEnabled
        public Id partenrollid;

        public TrialMatchContainer() {
            this.trialmatchctps = new List<TrialMatchPageRemote.TrialMatchCTP>();
            partenrollid = peId;
        }
    }

    public class TrialMatchCTP {
        @AuraEnabled
        public Clinical_Trial_Profile__c ctp;
        @AuraEnabled
        public Trial_Match__c trm;
        @AuraEnabled
        public Boolean isEnrollingCTP;
        @AuraEnabled
        public String ctpid;
        @AuraEnabled
        public String TherapeuticArea;
        @AuraEnabled
        public String StudyCodeName;
        @AuraEnabled
        public String OfficialTitle;
        @AuraEnabled
        public String matchDate;
        @AuraEnabled
        public String NCTId;
        @AuraEnabled
        public Date matchedDate;
    }
}