force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Enrollments</relationshipLabel>
    <relationshipName>Participant_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reminder_Schedule__c/Reminder_Schedule__c.object-meta.xml
<CustomObject>
    <label>Reminder Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Reminder Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reminder Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyInvitation/fields/ExpireDateTime__c.field-meta.xml
<CustomField>
    <fullName>ExpireDateTime__c</fullName>
    <label>ExpireDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Is_End_Date_Visible__c.field-meta.xml
<CustomField>
    <fullName>Is_End_Date_Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to display a survey due date in task list available at home page and task page</inlineHelpText>
    <label>Is End Date Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Is_Expired__c.field-meta.xml
<CustomField>
    <fullName>Is_Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Is_Midpoint__c.field-meta.xml
<CustomField>
    <fullName>Is_Midpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Midpoint</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/IsTrialSurvey__c.field-meta.xml
<CustomField>
    <fullName>IsTrialSurvey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTrialSurvey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Reminder_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reminder Schedule</label>
    <referenceTo>Reminder_Schedule__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/ReminderDateTime__c.field-meta.xml
<CustomField>
    <fullName>ReminderDateTime__c</fullName>
    <label>ReminderDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SurveyL</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyInvitation/fields/Trial_Survey__c.field-meta.xml
<CustomField>
    <fullName>Trial_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trial Survey</label>
    <referenceTo>Trial_Survey__c</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/Trial_Survey__c.object-meta.xml
<CustomObject>
    <label>Trial Survey</label>
    <nameField>
        <displayFormat>TS-{000}</displayFormat>
        <label>Trial Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trial_Survey__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Trial Surveys</relationshipLabel>
    <relationshipName>Trial_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Display_in_UI__c.field-meta.xml
<CustomField>
    <fullName>Display_in_UI__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>By checking this, Survey due date will be displayed to users.</inlineHelpText>
    <label>Display date in UI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Expires_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Expires_After_Days__c</fullName>
    <description>Task expires</description>
    <label>Expires after (days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Is_Midpoint__c.field-meta.xml
<CustomField>
    <fullName>Is_Midpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Survey tasks will expire when the Participants status is changed to: Drop Out, Trial Complete or Participation Complete</inlineHelpText>
    <label>Expire in Alumni View</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Is_Recurrence_Survey__c.field-meta.xml
<CustomField>
    <fullName>Is_Recurrence_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Recurrence Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Recurrence_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Frequency__c</fullName>
    <label>Recurrence Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Reminder_in_days_before_the_end_date__c.field-meta.xml
<CustomField>
    <fullName>Reminder_in_days_before_the_end_date__c</fullName>
    <description>Days</description>
    <label>Reminder(in days) before the end date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Reminder_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reminder Schedule</label>
    <referenceTo>Reminder_Schedule__c</referenceTo>
    <relationshipLabel>Trial Surveys</relationshipLabel>
    <relationshipName>Trial_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Trial Surveys</relationshipLabel>
    <relationshipName>Trial_Surveys</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trial_Survey__c/fields/Survey_end_date__c.field-meta.xml
<CustomField>
    <fullName>Survey_end_date__c</fullName>
    <label>Survey end date</label>
    <type>Date</type>
</CustomField>

force-app/main/tasks/classes/SurveyService.cls
/**
 * Created by Igor Malyuta on 15.05.2019.
 */

public without sharing class SurveyService {
    public class SurveyException extends Exception {
    }

    public static final String SURVEY_RESPONSE_PATIENT_ONLY = 'Patient only';
    public static final String SURVEY_RESPONSE_EACH_DELEGATE = 'Each Delegate';
    public static final String SURVEY_RESPONSE_PATIENT_ANY_DELEGATE = 'Patient or any Delegate';
    public static final String SURVEY_RESPONSE_ANY_DELEGATE = 'Any Delegate';
    public static final String SURVEY_RESPONSE_PATIENT_EACH_DELEGATE = 'Patient and each Delegate';

    public static final Map<String, String> SURVEY_VISIBLE = new Map<String, String>{
        SURVEY_RESPONSE_PATIENT_ONLY => TaskService.TASK_VISIBILITY_OWNER,
        SURVEY_RESPONSE_EACH_DELEGATE => TaskService.TASK_VISIBILITY_OWNER,
        SURVEY_RESPONSE_PATIENT_ANY_DELEGATE => TaskService.TASK_VISIBILITY_ALL,
        SURVEY_RESPONSE_ANY_DELEGATE => TaskService.TASK_VISIBILITY_DELEGATES,
        SURVEY_RESPONSE_PATIENT_EACH_DELEGATE => TaskService.TASK_VISIBILITY_OWNER
    };

    public class SurveyWrapper {
        public String name;
        public String url;
        public String studyCodeName;

        public SurveyWrapper(String name, String url, String studyCodeName) {
            this.name = name;
            this.url = url;
            this.studyCodeName = studyCodeName;
        }
    }

    private static SurveyService instance;

    public static SurveyService getInstance() {
        if (instance == null)
            instance = new SurveyService();
        return instance;
    }

    public static void setMock(StubProvider mock) {
        instance = (SurveyService) Test.createStub(SurveyService.class, mock);
    }

    public SurveyWrapper getSurveyWrapper(Id invitationId) {
        try {
            SurveyInvitation invitation = [
                SELECT
                    InvitationLink,
                    Survey.Name,
                    Participant_Enrollment__r.Clinical_Trial_Profile__r.Study_Code_Name__c
                FROM SurveyInvitation
                WHERE Id = :invitationId
            ];

            return new SurveyWrapper(
                invitation.Survey.Name,
                invitation.InvitationLink,
                invitation.Participant_Enrollment__r.Clinical_Trial_Profile__r.Study_Code_Name__c
            );
        } catch (Exception e) {
            throw new SurveyService.SurveyException(e.getCause() + '\n' + e.getMessage());
        }
    }

    public SurveyInvitation generateInvitation(
        Trial_Survey__c ts,
        Id peId,
        Id communityId,
        Date partDate,
        TimeZone usertz
    ) {
        SurveyInvitation invitation = new SurveyInvitation(
            CommunityId = communityId,
            Is_Midpoint__c = ts.Is_Midpoint__c,
            Name = ts.Survey__r.Name + ':TS:' + ts.Id,
            Participant_Enrollment__c = peId,
            Reminder_Schedule__c = ts.Reminder_Schedule__c,
            SurveyId = ts.Survey__c,
            Survey__c = ts.Survey__c,
            Trial_Survey__c = ts.Id,
            IsTrialSurvey__c = true,
            Is_End_Date_Visible__c = ts.Display_in_UI__c
        );

        Date today;
        if (partDate != null) {
            today = partDate;
        } else {
            today = System.today();
        }
        Date endDate = today;
        Time eodTime = Time.newInstance(23, 59, 0, 0);
        if (ts.Is_Recurrence_Survey__c) {
            if (ts.Recurrence_Frequency__c == 'Weekly') {
                endDate = today.addDays(6);
            } else if (ts.Recurrence_Frequency__c == 'Monthly') {
                endDate = today.addMonths(1).addDays(-1);
            } else if (ts.Recurrence_Frequency__c == 'Yearly') {
                endDate = today.addYears(1).addDays(-1);
            }
            if (ts.Survey_end_date__c != null && endDate > ts.Survey_end_date__c) {
                endDate = ts.Survey_end_date__c;
            }
        } else {
            if (ts.Expires_After_Days__c != null) {
                endDate = today.addDays((Integer) ts.Expires_After_Days__c);
            } else {
                endDate = ts.Survey_end_date__c;
            }
        }
        Integer days;
        Date reminderDate;
        Time remTime;
        if (ts.Reminder_in_days_before_the_end_date__c != null) {
            days = Integer.valueOf(ts.Reminder_in_days_before_the_end_date__c);
            reminderDate = endDate.addDays(-days);
            remTime = Time.newInstance(9, 30, 0, 0);
        }

        Integer offsetSeconds = 0;
        if (userTZ != null) {
            offsetSeconds = userTZ.getOffset(endDate) / 1000;
        }
        Datetime expiry = Datetime.newInstanceGmt(endDate, eodTime).addSeconds(-offsetSeconds);
        invitation.ExpireDateTime__c = expiry;
        if (reminderDate != null && reminderDate >= today) {
            Datetime reminderDatetime = Datetime.newInstanceGmt(reminderDate, remTime)
                .addSeconds(-offsetSeconds);
            invitation.ReminderDateTime__c = reminderDatetime;
        }

        return invitation;
    }

    public SurveyInvitation generateInvitation(
        Survey survey,
        Reminder_Schedule__c schedule,
        Integer expiresAfterDays,
        Boolean isMidpoint,
        Id peId,
        Id communityId
    ) {
        SurveyInvitation invitation = new SurveyInvitation(
            CommunityId = communityId,
            Is_Midpoint__c = isMidpoint,
            Name = survey.Name + ':PE:' + peId,
            Participant_Enrollment__c = peId,
            SurveyId = survey.Id,
            Survey__c = survey.Id
        );

        if (schedule != null)
            invitation.Reminder_Schedule__c = schedule.Id;

        if (expiresAfterDays != null) {
            Date today = System.today().addDays(expiresAfterDays);
            Datetime expiry = Datetime.newInstance(today.year(), today.month(), today.day());
            invitation.ExpireDateTime__c = expiry;
        }

        return invitation;
    }

    public Id getSurveyInvitationId(String surveyId, String participantContactId) {
        List<SurveyInvitation> invitation = [
            SELECT Id
            FROM SurveyInvitation
            WHERE
                SurveyId = :surveyId
                AND Participant_Enrollment__r.Participant_Contact__c = :participantContactId
        ];
        if (invitation.isEmpty())
            return '';

        return invitation.get(0).Id;
    }

    public Boolean isInvitationExpired(Id invitationId) {
        return isInvitationsExpired(new List<Id>{ invitationId }).get(invitationId);
    }

    public Map<Id, Boolean> isInvitationsExpired(List<Id> invitationIds) {
        List<SurveyInvitation> invitations = [
            SELECT ExpireDateTime__c, Is_Expired__c
            FROM SurveyInvitation
            WHERE Id IN :invitationIds
        ];
        Map<Id, Boolean> invitationStateById = new Map<Id, Boolean>();
        for (SurveyInvitation inv : invitations) {
            invitationStateById.put(
                inv.Id,
                (inv.Is_Expired__c || inv.ExpireDateTime__c <= Datetime.now())
            );
        }
        return invitationStateById;
    }

    public Boolean expireInvitation(List<Id> invitationIds) {
        for (Id invId : invitationIds) {
            if (invId == null || invId.getSobjectType() != SurveyInvitation.getSObjectType()) {
                return false;
            }
        }

        List<SurveyInvitation> invitations = [
            SELECT Id, Is_Expired__c, InviteExpiryDateTime
            FROM SurveyInvitation
            WHERE Id IN :invitationIds
        ];

        if (!invitations.isEmpty()) {
            for (SurveyInvitation inv : invitations) {
                inv.Is_Expired__c = true;
                if (inv.InviteExpiryDateTime != null)
                    inv.InviteExpiryDateTime = null;
            }

            update invitations;

            List<Task> tasksForExpire = [
                SELECT Id, Status
                FROM Task
                WHERE Survey_Invitation__c IN :invitationIds
            ];
            for (Task t : tasksForExpire)
                t.Status = TaskService.TASK_STATUS_EXPIRED;

            update tasksForExpire;

            return true;
        }

        return false;
    }
}