force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Media_outreach_Provider__c.field-meta.xml
<CustomField>
    <fullName>Media_outreach_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Outreach Contact</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clinical_Trial_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserCommunityIsDelegate__c.field-meta.xml
<CustomField>
    <fullName>UserCommunityIsDelegate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Community Is Delegate</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/Media_Outreach__c.object-meta.xml
<CustomObject>
    <description>To provides the ability to support PI team members requesting assistance with site recruitment activities, such as placing an advertising orders and viewing the status of their previous and current requests.</description>
    <label>Media Outreach</label>
    <nameField>
        <displayFormat>RQ-{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Outreachs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Media_Outreach__c/fields/Alternate_Email_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email_Phone_Number__c</fullName>
    <label>Alternate Email/Phone Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <label>Study Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Media_Type__c.field-meta.xml
<CustomField>
    <fullName>Media_Type__c</fullName>
    <label>Media Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Preferred_contact_method__c.field-meta.xml
<CustomField>
    <fullName>Preferred_contact_method__c</fullName>
    <label>Preferred Contact Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Requested_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_End_Date__c</fullName>
    <label>Requested End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Study_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To capture the study Name.</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Media Outreachs</relationshipLabel>
    <relationshipName>Media_Outreachs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Media_Outreach__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Media Outreachs</relationshipLabel>
    <relationshipName>Media_Outreachs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/Site_Staff__c.object-meta.xml
<CustomObject>
    <description>Used to connect Contacts with Study Sites to represent a Principal Investigator&#39;s team</description>

    <label>Site Staff</label>
    <nameField>
        <displayFormat>Staff #{0000}</displayFormat>
        <label>Site Staff</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Staff__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp; Study_Site__r.Clinical_Trial_Profile__c,  Study_Site__r.Clinical_Trial_Profile__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clinical Trial Profile</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site_Staff__c/fields/Delegate_Level__c.field-meta.xml
<CustomField>
    <fullName>Delegate_Level__c</fullName>
    <label>Delegate Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Study_Site__r.Principal_Investigator__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Site_Contact__c</fullName>
    <label>Site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Staff&#39;s Study Sites</relationshipLabel>
    <relationshipName>PI_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <formula>if(is_Site_and_Staff_Same_Country__c == false,  HYPERLINK(&quot;/&quot;&amp; Id , Name ) , &apos;-&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Staff</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Staff__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Site Staff</relationshipLabel>
    <relationshipName>Site_Staff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Site_Staff__c.field-meta.xml
<CustomField>
    <fullName>Site_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to study site delegate</description>
    <label>Site Staff</label>
    <referenceTo>Site_Staff__c</referenceTo>
    <relationshipLabel>Study Sites</relationshipLabel>
    <relationshipName>Study_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Study_Site_Phone__c.field-meta.xml
<CustomField>
    <fullName>Study_Site_Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Phone number referenced in the email for Virtual Trial Participants</inlineHelpText>
    <label>Study Site Phone</label>

    <type>Phone</type>
</CustomField>

force-app/main/default/classes/NewMediaOutReach.cls
/**
*  @Name: newMediaOutReach
*  @Description - This class helps to create new media outReach and 
load the data from logged in community
*  @Author : Vicky
*  @created  2020-05-22
* @version 48.0   
*/
public with sharing class NewMediaOutReach {
    
    public static String REQUESTED_VAL = Label.Requested;
    
    public  static Id studyContactId;
    public  static String lstvalsite;
    public  static string lstvalstudy;
    public  static  List<Study_Site__c> studyDataLast;
   
    public class CommunityPreferred {
        @AuraEnabled public string preEmail;
        @AuraEnabled public string prePhone;
        @AuraEnabled public string studyName;
        
        public CommunityPreferred(){
        }  
    }  
    /**   
* @Author: Vicky
* @name: getstudyType
* @CreateDate: 2020-05-25
* @Description: To Pass the phone from study site and email from logged in community user on component.
**/
    @AuraEnabled
    public static string getstudyType(string site) {
        List<Study_Site__c> studylst = new List<Study_Site__c>();
        Integer limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows();

        Contact userContact = CommunityService.getUserContact();
        studyContactId = userContact.Id;

        if((String.isNotBlank(site))){
            Study_Site__c siteId =[SELECT id,Name,Study_Site_Phone__c FROM Study_Site__c WHERE Name =:site LIMIT 1];
            lstvalsite = siteId.Study_Site_Phone__c;
            }
            
        Contact con=[SELECT id,name,Email,Phone from Contact where Id =:studyContactId LIMIT 1];
        CommunityPreferred commm = new CommunityPreferred();
        
        commm.prePhone = lstvalsite;
        commm.preEmail = con.Email;
        
       return JSON.serialize(commm);
        
    }
    /**   
* @Author: Vicky
* @name: getstudyData
* @CreateDate: 2020-05-25
* @Description: To Pass the list of study.
**/
    
   @AuraEnabled
    public static List<NewMediaOutReach.CommunityPreferred> getstudyData(string dataStudy) {
        List<NewMediaOutReach.CommunityPreferred> result = new List<NewMediaOutReach.CommunityPreferred>();
        NewMediaOutReach.CommunityPreferred studyPoistion;
        Clinical_Trial_Profile__c ctpdata;
        Id studyContactId;
        Contact userContact = CommunityService.getUserContact();
        
        studyContactId = userContact.Id;
        Contact con =[SELECT id,UserCommunityIsDelegate__c FROM Contact WHERE Id =:studyContactId LIMIT 1];
        Integer limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows();
        
        //for PI 
        
        if((String.isNotBlank(dataStudy))){
            ctpdata =[SELECT id,Study_Code_Name__c,Name from Clinical_Trial_Profile__c WHERE Study_Code_Name__c =:dataStudy LIMIT 1];
        }
        if(studyContactId != null && con.UserCommunityIsDelegate__c == false){
            if(ctpdata != null){
                studyDataLast =[SELECT id,Site__r.Name,Clinical_Trial_Profile__r.Study_Code_Name__c,Name FROM Study_Site__c WHERE Clinical_Trial_Profile__c =:ctpdata.Id AND Principal_Investigator__c =:studyContactId LIMIT :limitRows];
                for(Study_Site__c sc: studyDataLast){
                    studyPoistion = new NewMediaOutReach.CommunityPreferred();
                    studyPoistion.studyName = sc.Name;
                    result.add(studyPoistion);
                }
            }
        }
        //for PI staff
        if(studyContactId != null && con.UserCommunityIsDelegate__c == true ){
            if(ctpdata != null){
                List<id> studySiteIds = new List<Id>();
                List<Site_Staff__c> sitestaffDetails = [SELECT id,Delegate_Level__c,Study_Site__r.Clinical_Trial_Profile__c,Study_Site__r.Clinical_Trial_Profile__r.Media_outreach_Provider__c,Study_Site__c,Site_Contact__c FROM Site_Staff__c where Site_Contact__c =:studyContactId AND Study_Site__r.Clinical_Trial_Profile__r.Media_outreach_Provider__c != null  AND Study_Site__r.Clinical_Trial_Profile__c =:ctpdata.id LIMIT :limitRows];
                for(Site_Staff__c sitestaff: sitestaffDetails) {
                    studySiteIds.add(sitestaff.Study_Site__c);
                } 
                if(!studySiteIds.isEmpty()){
                    studyDataLast =[SELECT id,Site__r.Name,Clinical_Trial_Profile__r.Study_Code_Name__c,Name FROM Study_Site__c WHERE id in: studySiteIds LIMIT :limitRows];
                    for(Study_Site__c sc: studyDataLast){
                        studyPoistion = new NewMediaOutReach.CommunityPreferred();
                        studyPoistion.studyName = sc.Name;
                        result.add(studyPoistion);
                    }
                }
            }
        }
        return result;
        
    } 
 /**   
* @Author: Vicky
* @name: getstudyData
* @CreateDate: 2020-05-25
* @Description: To fetch the Media outreach Provider not null.
**/
    @AuraEnabled
    public static List<Clinical_Trial_Profile__c> getstudyContact() {
        Integer limitRows = Limits.getLimitQueryRows() - Limits.getQueryRows();
        Id studyContactId;
        List<Clinical_Trial_Profile__c> clinicalTrialLst = new List<Clinical_Trial_Profile__c>(); 
        List<Study_Site__c> studylst = new List<Study_Site__c>(); 
        List<Site_Staff__c> siteStaff = new List<Site_Staff__c>();
        Contact con;
        set<Id> ctpIds = new set<Id>();
        Contact userContact = CommunityService.getUserContact();
        
        studyContactId = userContact.Id;
        system.System.debug('studyContactId??'+studyContactId);
        con =[SELECT id,UserCommunityIsDelegate__c FROM Contact WHERE Id =:studyContactId LIMIT 1];
       
        if(studyContactId != null && con.UserCommunityIsDelegate__c == false){
        studylst =[SELECT id,Name,Clinical_Trial_Profile__r.Media_outreach_Provider__c,Clinical_Trial_Profile__c,Clinical_Trial_Profile__r.Study_Code_Name__c,Principal_Investigator__c FROM Study_Site__c WHERE Principal_Investigator__c =:studyContactId AND Clinical_Trial_Profile__r.Media_outreach_Provider__c != null LIMIT :limitRows];
        }

        if(studyContactId != null && con.UserCommunityIsDelegate__c == true ){
       siteStaff =[SELECT id,Delegate_Level__c,Study_Site__r.Clinical_Trial_Profile__c,Study_Site__r.Clinical_Trial_Profile__r.Media_outreach_Provider__c,Study_Site__c,Site_Contact__c FROM Site_Staff__c where Site_Contact__c =:studyContactId AND Study_Site__r.Clinical_Trial_Profile__r.Media_outreach_Provider__c != null LIMIT :limitRows];
        }

        if(studylst.size()>0){
          for(Study_Site__c st: studylst){
              ctpIds.add(st.Clinical_Trial_Profile__c);
          }
        }
        if(siteStaff.size()>0){
          for(Site_Staff__c ss: siteStaff){
              ctpIds.add(ss.Study_Site__r.Clinical_Trial_Profile__c);
          }
        }
        if(!ctpIds.isEmpty()){
           clinicalTrialLst =[SELECT id,Study_Code_Name__c,Name from Clinical_Trial_Profile__c WHERE Id =:ctpIds LIMIT :limitRows];
        }
        
        return clinicalTrialLst;
        
    }
    /**   
* @Author: Vicky
* @name: getPickListValues
* @CreateDate: 2020-05-29
* @Description: To fetch the Media type value from media outreach object.
**/
    
    @AuraEnabled
    public static Map<String, String> getPickListValues(String obj, String str) {
        Map<String, String> options = new Map<String, String>(); 
        Schema.DescribeFieldResult plistvalues = Schema.getGlobalDescribe().get(obj).getDescribe().fields.getMap().get(str).getDescribe();
        
        for(PicklistEntry ent:plistvalues.getpicklistvalues())
        {
            options.put(ent.getValue(),ent.getLabel());
        }
        return options;
    }
    
    /**   
* @Author: Vicky
* @name: getPickListValues
* @CreateDate: 2020-05-29
* @Description: To create media outreach data.
**/
    
    @AuraEnabled
    public static void inviteNewMedia(string study,string site,String prefferedtype,string actualemailPhone, List<String> media,string startdt,string enddt,string notes){
       try{
            Clinical_Trial_Profile__c ctpLstdata;
            Study_Site__c siteId;
            Account accLst;
            if(study != '' || study != null){
                ctpLstdata =[SELECT id,Study_Code_Name__c,Name,Media_outreach_Provider__c from Clinical_Trial_Profile__c WHERE Study_Code_Name__c =:study LIMIT 1];
                }
                 if(ctpLstdata != null && (site != '' || site != null)){
                siteId =[SELECT id,Site__c,Name,Principal_Investigator__c,Principal_Investigator__r.FirstName,Principal_Investigator__r.LastName from Study_Site__c WHERE Clinical_Trial_Profile__c =:ctpLstdata.Id AND Name =:site LIMIT 1];
                 }
            if(siteId.Site__c != null){
                accLst =[SELECT id,name FROM Account where Id =:siteId.Site__c LIMIT 1];
            }
            List<Media_Outreach__c> medialst = new List<Media_Outreach__c>();
            string typeval;
            Media_Outreach__c mediaOut = new Media_Outreach__c();
            if(media.size()>0){
                for(Integer i =0; i<media.size(); i++){
                    if(i==0){
                        typeval = media[i];
                    }
                    if(i>0){
                        typeval = typeval+';'+ media[i];  
                    }
                } 
            }
            mediaOut.Clinical_Trial_Profile__c = ctpLstdata.Study_Code_Name__c;
            mediaOut.Study_Name__c = siteId.Id;
           // mediaOut.Study_Site__c = accLst.Id;
            mediaOut.Media_Type__c =  typeval;
            mediaOut.Preferred_contact_method__c = prefferedtype;
            mediaOut.Alternate_Email_Phone_Number__c = actualemailPhone;
            mediaOut.Status__c = REQUESTED_VAL;
            if(startdt!= ''){
                mediaOut.Requested_Start_Date__c = Date.valueOf(startdt);
            }
            if(enddt!= ''){
                mediaOut.Requested_End_Date__c = Date.valueOf(enddt);
            }
            medialst.add(mediaOut);
            
            if(medialst.size()>0){
                insert medialst;
            }
            //Task Creation
            if(medialst.size()>0)
            {
              if(ctpLstdata.Media_outreach_Provider__c !=null )
              {
                Task tsk = new Task();
                tsk.ActivityDate=System.today().addDays(3);
                tsk.OwnerId =ctpLstdata.Media_outreach_Provider__c;
                tsk.Priority ='Normal';
                tsk.Status ='Open';
                tsk.WhatId=medialst[0].Id;
                tsk.Subject='New media outreach request from PI' + '  ' +siteId.Principal_Investigator__r.FirstName + ' ' + siteId.Principal_Investigator__r.LastName;
                Insert tsk;
              } 
                   
            }
            if(String.isNotBlank(notes)) {
                
                ContentNote objCntNote = new ContentNote();
                objCntNote.Title = notes;
                insert objCntNote;  
                
                ContentDocumentLink objCntDocLink = new ContentDocumentLink();
                objCntDocLink.LinkedEntityId = medialst[0].Id;
                objCntDocLink.ContentDocumentId = objCntNote.Id;
                insert objCntDocLink;
            }
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    
    
}