force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Shareback_Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Shareback_Availability_Status__c</fullName>
    <label>Shareback Availability Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Shareback_Availability_Timing__c.field-meta.xml
<CustomField>
    <fullName>Shareback_Availability_Timing__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Show visit result after # completed visits</description>
    <label>Shareback Availability Timing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Visit_Data_Shareback__c.field-meta.xml
<CustomField>
    <fullName>Visit_Data_Shareback__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Data Shareback</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Visit_Results_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Visit_Results_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Results Opt In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Mailing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Country Code</label>
    <length>2</length>

    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Study_Enrollment__c/Participant_Study_Enrollment__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Participant Study Enrollment</label>
    <nameField>
        <displayFormat>PSE{00000000}</displayFormat>
        <label>Participant Study Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Study Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Study</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Participant Study Enrollments</relationshipLabel>
    <relationshipName>Participant_Study_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Participant Study Enrollments</relationshipLabel>
    <relationshipName>Participant_Study_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Study Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>Participant_Study_Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Participant Study Enrollments</relationshipLabel>
    <relationshipName>Participant_Study_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/Patient_Visit__c.object-meta.xml
<CustomObject>
    <label>Patient Visit</label>
    <nameField>
        <displayFormat>PV-{000000}</displayFormat>
        <label>Patient Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Visit__c/fields/Participant_Study_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Study_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Study Enrollment</label>
    <referenceTo>Participant_Study_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/visits/objects/Patient_Visit__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Principal_Investigator__c.field-meta.xml
<CustomField>
    <fullName>Principal_Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PI&#39;s Study Sites</relationshipLabel>
    <relationshipName>Study_Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/fields/Visit_Results_Sharing__c.field-meta.xml
<CustomField>
    <fullName>Visit_Results_Sharing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visit Results Sharing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Result__c/Visit_Result__c.object-meta.xml
<CustomObject>
    <label>Visit_Result</label>
    <nameField>
        <displayFormat>VR-{0000000}</displayFormat>
        <label>Visit_Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit_Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Result__c/fields/Actual_Value__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value__c</fullName>
    <label>Actual Result</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Max_Value__c</fullName>
    <label>Max Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/visits/objects/Visit_Result__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Min_Value__c.field-meta.xml
<CustomField>
    <fullName>Min_Value__c</fullName>
    <label>Min Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Patient_Visit__c.field-meta.xml
<CustomField>
    <fullName>Patient_Visit__c</fullName>
    <label>Patient Visit</label>
    <referenceTo>Patient_Visit__c</referenceTo>
    <relationshipLabel>Visit_Results</relationshipLabel>
    <relationshipName>Visit_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Result_Type__c.field-meta.xml
<CustomField>
    <fullName>Result_Type__c</fullName>
    <description>.</description>
    <label>Result Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Result_Type_Sharing__c/Visit_Result_Type_Sharing__c.object-meta.xml
<CustomObject>
    <label>Visit Result Type Sharing</label>
    <nameField>
        <label>Visit Result Type Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Result Type Sharings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Result_Type_Sharing__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Visit Result Type Sharings</relationshipLabel>
    <relationshipName>Visit_Result_Type_Sharings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Result_Type_Sharing__c/fields/Sharing_Countries__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Countries__c</fullName>
    <label>Sharing Countries</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VisitResultSharingService.cls
/**
 * Created by Igor Malyuta on 24.06.2019.
 */

public without sharing class VisitResultSharingService {

    public static List<Visit_Result__c> processResults(List<Visit_Result__c> visitResults) {
        List<Visit_Result__c> visitResultList = [
                SELECT
                        Actual_Value__c,
                        Max_Value__c,
                        Measurement__c,
                        Min_Value__c,
                        Patient_Visit__c,
                        Patient_Visit__r.Participant_Study_Enrollment__c,
                        Patient_Visit__r.Participant_Study_Enrollment__r.Clinical_Trial_Profile__c,
                        Patient_Visit__r.Participant_Study_Enrollment__r.Participant_Contact__r.Visit_Results_Opt_In__c,
                        Patient_Visit__r.Participant_Study_Enrollment__r.Participant__r.Mailing_Country_Code__c,
                        Patient_Visit__r.Participant_Study_Enrollment__r.Study_Site__r.Visit_Results_Sharing__c,
                        Patient_Visit__r.Participant_Study_Enrollment__r.Status__c,
                        Patient_Visit__r.Visit__c,
                        Patient_Visit__r.Visit__r.Order__c,
                        Result_Type__c
                FROM Visit_Result__c
                WHERE Id IN:visitResults
        ];

        Set<Id> ctpIds = new Set<Id>();
        for (Visit_Result__c vr : visitResultList) {
            ctpIds.add(vr.Patient_Visit__r.Participant_Study_Enrollment__r.Clinical_Trial_Profile__c);
        }

        Map<Id, Clinical_Trial_Profile__c> trialProfileMap = new Map<Id, Clinical_Trial_Profile__c>([
                SELECT
                        Id,
                        Shareback_Availability_Status__c,
                        Shareback_Availability_Timing__c,
                        Visit_Data_Shareback__c, (
                        SELECT Id, Type__c, Sharing_Countries__c
                        FROM Visit_Result_Type_Sharings__r
                )
                FROM Clinical_Trial_Profile__c
                WHERE Id IN:ctpIds
        ]);

        List<Visit_Result__c> filteredResults = new List<Visit_Result__c>();
        for (Visit_Result__c result : visitResultList) {
            Participant_Study_Enrollment__c pse = result.Patient_Visit__r.Participant_Study_Enrollment__r;
            Clinical_Trial_Profile__c ctp = trialProfileMap.get(pse.Clinical_Trial_Profile__c);

            if (!ctp.Visit_Data_Shareback__c || !pse.Study_Site__r.Visit_Results_Sharing__c
                    || !pse.Participant_Contact__r.Visit_Results_Opt_In__c) continue;
            if (result.Patient_Visit__r.Visit__r.Order__c <= ctp.Shareback_Availability_Timing__c) continue;
            if (!ctp.Shareback_Availability_Status__c.contains(pse.Status__c)) continue;

            for(Visit_Result_Type_Sharing__c resultTypeSharing : ctp.Visit_Result_Type_Sharings__r) {
                if(resultTypeSharing.Type__c == result.Result_Type__c) {
                    if(resultTypeSharing.Sharing_Countries__c == 'All' ||
                            resultTypeSharing.Sharing_Countries__c.contains(pse.Participant__r.Mailing_Country_Code__c)) {
                        filteredResults.add(result);
                        break;
                    }
                }
            }
        }

        return filteredResults;
    }
}