force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/Study_Incentive_Plan__c.object-meta.xml
<CustomObject>
    <label>Study Incentive Plan</label>
    <nameField>
        <displayFormat>SIP-{000000}</displayFormat>
        <label>Study Incentive Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Incentive Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/incentive-program/objects/Study_Incentive_Plan__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>Study Incentive Plans</relationshipLabel>
    <relationshipName>Study_Incentive_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StudyIncentivePlanBatchDeletion.cls
global class StudyIncentivePlanBatchDeletion implements Database.Batchable<sObject>{
	private String ctpId;
    global StudyIncentivePlanBatchDeletion(String ctpId){
        this.ctpId = ctpId;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        /*List<Study_Incentive_Plan__c> studIncPlanLst = CTPDeletionHelper.getStudyIncentivePlans(ctpId);
        return Database.getQueryLocator([SELECT Id, Name FROM Study_Incentive_Plan__c WHERE Id IN :studIncPlanLst]);*/
        return Database.getQueryLocator([SELECT Id, Name, Clinical_Trial_Profile__c FROM Study_Incentive_Plan__c 
                                         WHERE Clinical_Trial_Profile__c = :ctpId]); 
    }
    
    global void execute(Database.BatchableContext BC, List<Study_Incentive_Plan__c> studIncPlanLst){
        delete studIncPlanLst;
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}