force-app/main/default/objects/Clinical_Trial_Profile__c/Clinical_Trial_Profile__c.object-meta.xml
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>
 

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Clinical_Trial_Profile__c/fields/Study_Code_Name__c.field-meta.xml
<CustomField>
    <fullName>Study_Code_Name__c</fullName>
    <label>Study Code Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HCP_Enrollment__c/HCP_Enrollment__c.object-meta.xml
<CustomObject>
    <description>HCP Enrollment</description>

    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>

        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HCP_Enrollment__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipLabel>HCP Enrollments</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/HCP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HCP_Contact__c</fullName>
    <label>HCP Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HCP&#39;s Study Sites</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>HCP Status per clinical trial by PI</description>
    <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
    <label>HCP Status</label>

    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invitation Sent</fullName>
            </value>
            <value>
                <fullName>On Hold (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Declined (Acceptance)</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Admin)</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending</fullName>
            </value>
            <value>
                <fullName>Activation Pending Orientation</fullName>
            </value>
            <value>
                <fullName>Declined (Approval)</fullName>
            </value>
            <value>
                <fullName>On Hold (Approval)</fullName>
            </value>
            <value>
                <fullName>Declined (Activation)</fullName>
            </value>
            <value>
                <fullName>On Hold (Activation)</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Activated (Admin)</fullName>
            </value>
            <value>
                <fullName>On Hold (Admin)</fullName>
            </value>
            <value>
                <fullName>Declined (Admin)</fullName>
            </value>
            <value>
                <fullName>Deactivated (Admin)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HCP_Enrollment__c/fields/Study_Site__c.field-meta.xml
<CustomField>
    <fullName>Study_Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Hospital of rainbow</description>
    <label>Study Site</label>
    <referenceTo>Study_Site__c</referenceTo>
    <relationshipLabel>Referring HCPs</relationshipLabel>
    <relationshipName>HCP_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Site__c/Study_Site__c.object-meta.xml
<CustomObject>
    <!--compactLayoutAssignment>Study_Site</compactLayoutAssignment-->
    <description>Study Site Profile</description>

    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>

        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Site__c/fields/Clinical_Trial_Profile__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Trial_Profile__c</fullName>
    <description>Connects the study site to the primary study that it relates to</description>
    <label>Clinical Trial Profile</label>
    <referenceTo>Clinical_Trial_Profile__c</referenceTo>
    <relationshipName>Study_Site_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>

    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MyReferringClinicsController.cls
/**
 * Created by D.Yasinskyi on 30.03.2018
 */
public without sharing class MyReferringClinicsController {

    private static List<Account> getAccounts(Set<Id> accountIds) {
        return [
                SELECT Id, Name, BillingStreet, BillingState, BillingPostalCode, BillingCity, Phone
                FROM Account
                WHERE Id IN :accountIds
        ];
    }

    private static MyReferringClinicsController.HCPEnrollmentWrapper createEnrollmentWrapper(HCP_Enrollment__c hcpEnrollment){
        Map<String, StudyActions.Action> actionsMap = new StudyActionsPI(hcpEnrollment).actions;
        MyReferringClinicsController.HCPEnrollmentWrapper wrapper = new MyReferringClinicsController.HCPEnrollmentWrapper();
        wrapper.status = CommunityService.getConvertedStatus(hcpEnrollment.Status__c);
        wrapper.statusLabel = TranslateHelper.getPickListLabel(HCP_Enrollment__c.Status__c,hcpEnrollment.Status__c);
        wrapper.enrollment = hcpEnrollment;

        Map<String, String> actionToStatusesMap = HCPEnrollmentService.HCP_CHANGE_STATUS_MAP.get(hcpEnrollment.Status__c);
        if(actionToStatusesMap != null){
            for(String actionId : actionToStatusesMap.keySet()) {
                wrapper.buttonList.add(actionsMap.get(actionId));
            }
        }
        return wrapper;
    }
    @AuraEnabled
    public static String getInitData(String trialId, String ssId){
        InitData initData = new InitData();
        initData.ssId = null;
        initData.trialId = null;
        initData.filterData.statusOptions = getInitStatusOptions();
        try {
            Set<Id> trialIds = new Set<Id>();
            List<Study_Site__c> studySites;
            studySites = StudySiteService.getStudySitesForPI();
            Map<Id, List<Study_Site__c>> studyMap = new Map<Id, List<Study_Site__c>>();
            Map<String, String> studySiteMap = new Map<String, String>();
            initData.filterData.studyPickList = new List<LabelValueItem>{
                    new LabelValueItem(Label.PG_MRRL_L_All_studies, null)
            };
            for (Integer i = 0, j = studySites.size(); i < j; i++) {
                if (studyMap.containsKey(studySites[i].Clinical_Trial_Profile__c)) {
                    studyMap.get(studySites[i].Clinical_Trial_Profile__c).add(studySites[i]);
                } else {
                    studyMap.put(studySites[i].Clinical_Trial_Profile__c, new List<Study_Site__c>{
                            studySites[i]
                    });
                    initData.filterData.studyPickList.add(new LabelValueItem(studySites[i].Clinical_Trial_Profile__r.Study_Code_Name__c, studySites[i].Clinical_Trial_Profile__c));
                }
                studySiteMap.put(studySites[i].Id, studySites[i].Clinical_Trial_Profile__c);
            }
            if (trialId != null) {
                studySites = studyMap.get(trialId);
            }
            initData.filterData.studySitePickList = new List<LabelValueItem>{
                    new LabelValueItem(Label.PG_Report_L_All_study_sites, null)
            };
            if (ssId == null) {
                for (Study_Site__c studySite : studySites) {
                    trialIds.add(studySite.Clinical_Trial_Profile__c);
                    initData.filterData.studySitePickList.add(new LabelValueItem(studySite.Name, studySite.Id));
                }
                initData.filteredReferringClinics = getInitDataEnrollments(HCPEnrollmentService.getEnrollmentsForPIByTrialIds(
                        trialIds, new List<String>{
                                HCPEnrollmentService.HCP_S_INVITATION_SENT
                        }
                ));
            } else {
                initData.filteredReferringClinics = getInitDataEnrollments(HCPEnrollmentService.getEnrollmentsForPIByStudySiteId(ssId));
                List<Study_Site__c> ssForStudy = studyMap.get(studySiteMap.get(ssId));
                initData.ssId = ssId;
                initData.filterData.ssId = ssId;
                trialId = ssForStudy[0].Clinical_Trial_Profile__c;
                for (Integer i = 0; i < ssForStudy.size(); i++) {
                    initData.filterData.studySitePickList.add(new LabelValueItem(ssForStudy[i].Name, ssForStudy[i].Id));
                }
            }
            if (trialId != null) {
                initData.trialId = trialId;
                initData.filterData.trialId = trialId;
            }


        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
        return JSON.serialize(initData);
    }

    private static List<MyReferringClinicsController.ClinicWrapper> getInitDataEnrollments(List<HCP_Enrollment__c> enrollments) {
        List<MyReferringClinicsController.ClinicWrapper> result = new List<MyReferringClinicsController.ClinicWrapper>();
        Map<Id, List<HCP_Enrollment__c>> clinicEnrolmentMap = new Map<Id, List<HCP_Enrollment__c>>();
        for (HCP_Enrollment__c enroll :enrollments) {
            if (!clinicEnrolmentMap.containsKey(enroll.HCP_Contact__r.AccountId)) {
                clinicEnrolmentMap.put(enroll.HCP_Contact__r.AccountId, new List<HCP_Enrollment__c>());
            }
            clinicEnrolmentMap.get(enroll.HCP_Contact__r.AccountId).add(enroll);
        }

        for (Account acc : getAccounts(clinicEnrolmentMap.keySet())) {
            result.add(new ClinicWrapper(acc, clinicEnrolmentMap.get(acc.Id)));
        }

        return result;
    }
    public static List<LabelValueItem> getInitStatusOptions(){
        List<LabelValueItem> enrollmentStatusOptions = new List<LabelValueItem>();
        for (Schema.PicklistEntry ple : HCP_Enrollment__c.Status__c.getDescribe().getPicklistValues()) {
            if(HCPEnrollmentService.HCP_E_S_INVISIBLE_ON_STUDY_SITE_P.contains(ple.getValue())) continue;
            enrollmentStatusOptions.add(new LabelValueItem(ple.getLabel(),ple.getValue()));
        }
        return enrollmentStatusOptions;
    }

    public class ClinicWrapper {
        public Account clinic;
        public List<MyReferringClinicsController.HCPEnrollmentWrapper> enrollments = new List<MyReferringClinicsController.HCPEnrollmentWrapper>();

        public ClinicWrapper(Account clinic, List<HCP_Enrollment__c> enrollments) {
            this.clinic = clinic;
            if(enrollments != null){
                for(HCP_Enrollment__c enrollment : enrollments){
                    this.enrollments.add(createEnrollmentWrapper(enrollment));
                }
            }
        }
    }

    public class  HCPEnrollmentWrapper {
        HCP_Enrollment__c enrollment;
        String status;
        String statusLabel;
        List<StudyActions.Action> buttonList = new List<StudyActions.Action>();
    }
    public class InitData{
        FilterData filterData;
        SortData sortData;
        PaginationData paginationData;
        public List<MyReferringClinicsController.ClinicWrapper> filteredReferringClinics;
        public String trialId;
        public String ssId;
        public InitData(){
            filteredReferringClinics = new List<MyReferringClinicsController.ClinicWrapper>();
            filterData = new FilterData();
            sortData = new SortData();
            PaginationData = new PaginationData();
        }
    }
    public class FilterData {
        public String searchText = '';
        public String searchTextPlaceholder = Label.PG_MRZ_L_Search_for_a_referring_clinic;
        public String statusFilter = '';
        public List<LabelValueItem> statusOptions = new List<LabelValueItem>();
        public String statusFilterPlaceholder = Label.PG_MRZ_L_Provider_Status;
        public String trialId;
        public List<LabelValueItem> studyPickList = new List<LabelValueItem>();
        public String ssId;
        public List<LabelValueItem> studySitePickList = new List<LabelValueItem>();

    }
    public class SortData{
        public String sortType;
        public List<LabelValueItem> sortVariants;
        public SortData(){
            sortVariants = new List<LabelValueItem>{
                    new LabelValueItem(Label.PG_MRZ_L_Last_Added, 'CreatedDate DESC'),
                    new LabelValueItem(Label.PG_MRZ_L_Last_Modified, 'LastModifiedDate DESC'),
                    new LabelValueItem(Label.PG_MRZ_L_Alphabetical_A_Z, 'Name ASC'),
                    new LabelValueItem(Label.PG_MRZ_L_Alphabetical_Z_A, 'Name DESC')
            };
            sortType = 'CreatedDate DESC';
        }
    }

}