force-app/main/default/objects/Batch_Notification__c/Batch_Notification__c.object-meta.xml
<CustomObject>
    <label>Batch Notification</label>
    <nameField>
        <label>Batch Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Notification__c/fields/Recipient_Ids__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Ids__c</fullName>
    <label>Recipient Ids</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Notification__c/fields/Time_Zone_Date__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone_Date__c</fullName>
    <label>Time Zone Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Test_EmailForPendingReferrals.cls
@isTest
public class Test_EmailForPendingReferrals {
    
    @TestSetup
    static void init() {
        Test.startTest();
        TestData.loadTestData();
        TestData.createTCAcceptance();
        Test.stopTest();
    }
    @isTest
    private static void Test_sendMails(){
        
        TestData testData = new TestData();
        Batch_Notification__c notification = new Batch_Notification__c();
        
        notification.Recipient_Ids__c = [SELECT Id,ContactId FROM User WHERE Id =:testData.piUser.Id][0].ContactId;
        notification.Time_Zone_Date__c = DateTime.now();
        insert notification;
        EmailForPendingReferrals.sendMails(new List<Batch_Notification__c>{notification});
        
    }
}