force-app/main/default/objects/Integration_VisitResult__c/Integration_VisitResult__c.object-meta.xml
<CustomObject>
    <label>Integration VisitResult</label>
    <nameField>
        <label>Integration VisitResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration VisitResult</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_VisitResult__c/fields/MD5__c.field-meta.xml
<CustomField>
    <fullName>MD5__c</fullName>
    <label>MD5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/NRIND__c.field-meta.xml
<CustomField>
    <fullName>NRIND__c</fullName>
    <label>NRIND</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/STNRHI__c.field-meta.xml
<CustomField>
    <fullName>STNRHI__c</fullName>
    <label>STNRHI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/integration/objects/Integration_VisitResult__c/fields/STNRLO__c.field-meta.xml
<CustomField>
    <fullName>STNRLO__c</fullName>
    <label>STNRLO</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/STRESN__c.field-meta.xml
<CustomField>
    <fullName>STRESN__c</fullName>
    <label>STRESN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_VisitResult__c/fields/STRESU__c.field-meta.xml
<CustomField>
    <fullName>STRESU__c</fullName>
    <label>STRESU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/TESTCD__c.field-meta.xml
<CustomField>
    <fullName>TESTCD__c</fullName>
    <label>TESTCD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/VISIT__c.field-meta.xml
<CustomField>
    <fullName>VISIT__c</fullName>
    <label>VISIT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_VisitResult__c/fields/Vital_or_Lab__c.field-meta.xml
<CustomField>
    <fullName>Vital_or_Lab__c</fullName>
    <label>Vital_or_Lab</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vital</fullName>
            </value>
            <value>
                <fullName>Lab</fullName>
            </value>
            <value>
                <fullName>Biomarker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/VSDTC__c.field-meta.xml
<CustomField>
    <fullName>VSDTC__c</fullName>
    <label>VSDTC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/Work_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Status__c</fullName>
    <label>Work Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/visits/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>SDH Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/integration/batches/classes/Batch_IntegrationVisitResultProcess.cls
/**
 * Created by user on 23-Jul-19.
 */ 

public without sharing class Batch_IntegrationVisitResultProcess implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [
                SELECT
                    Id,
                    OwnerId,
                    IsDeleted,
                    Name,
                    CreatedDate,
                    CreatedById,
                    LastModifiedDate,
                    LastModifiedById,
                    SystemModstamp,
                    External_Key__c,
                    IsDeletedInSDH__c,
                    MD5__c,
                    NRIND__c,
                    STNRHI__c,
                    STNRLO__c,
                    STRESN__c,
                    STRESU__c,
                    STUDYID__c,
                    TESTCD__c,
                    USUBJID__c,
                    VISITNUM__c,
                    VISIT__c,
                    VSDTC__c,
                    Vital_or_Lab__c,
                    Work_Status__c
                FROM Integration_VisitResult__c
                WHERE Processed__c = FALSE
            ]
        );
    }

    public void execute(Database.BatchableContext param1, List<SObject> scope) {
        ((IntegrationVisitResultService) ClassFactory.newInstance(
                IntegrationVisitResultService.class
            ))
            .updateVisitResults(scope);
    }

    public void finish(Database.BatchableContext param1) {
    }
}