force-app/main/default/objects/Integration_VisitResult__c/Integration_VisitResult__c.object-meta.xml
<CustomObject>
    <label>Integration VisitResult</label>
    <nameField>
        <label>Integration VisitResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration VisitResult</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_VisitResult__c/fields/STNRHI__c.field-meta.xml
<CustomField>
    <fullName>STNRHI__c</fullName>
    <label>STNRHI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/TESTCD__c.field-meta.xml
<CustomField>
    <fullName>TESTCD__c</fullName>
    <label>TESTCD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/VISIT__c.field-meta.xml
<CustomField>
    <fullName>VISIT__c</fullName>
    <label>VISIT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_VisitResult__c/fields/Vital_or_Lab__c.field-meta.xml
<CustomField>
    <fullName>Vital_or_Lab__c</fullName>
    <label>Vital_or_Lab</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vital</fullName>
            </value>
            <value>
                <fullName>Lab</fullName>
            </value>
            <value>
                <fullName>Biomarker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/VSDTC__c.field-meta.xml
<CustomField>
    <fullName>VSDTC__c</fullName>
    <label>VSDTC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Participant_Study_Enrollment__c/Participant_Study_Enrollment__c.object-meta.xml
<CustomObject>
    <!--enableLicensing>false</enableLicensing-->
    <label>Participant Study Enrollment</label>
    <nameField>
        <displayFormat>PSE{00000000}</displayFormat>
        <label>Participant Study Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Study Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Study_Enrollment__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <formula>Study_ID__c + &quot;~&quot; + Study_Site__r.Study_Site_Number__c + &quot;~&quot; + Screening_ID__c</formula>
    <label>External Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/Patient_Visit__c.object-meta.xml
<CustomObject>
    <label>Patient Visit</label>
    <nameField>
        <displayFormat>PV-{000000}</displayFormat>
        <label>Patient Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Visit__c/fields/Participant_Study_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Study_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Study Enrollment</label>
    <referenceTo>Participant_Study_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/visits/objects/Patient_Visit__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/visits/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>SDH Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Result__c/Visit_Result__c.object-meta.xml
<CustomObject>
    <label>Visit_Result</label>
    <nameField>
        <displayFormat>VR-{0000000}</displayFormat>
        <label>Visit_Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit_Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Result__c/fields/Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Max_Value__c</fullName>
    <label>Max Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Patient_Visit__c.field-meta.xml
<CustomField>
    <fullName>Patient_Visit__c</fullName>
    <label>Patient Visit</label>
    <referenceTo>Patient_Visit__c</referenceTo>
    <relationshipLabel>Visit_Results</relationshipLabel>
    <relationshipName>Visit_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/recordTypes/Vital.recordType-meta.xml
<RecordType>
    <fullName>Vital</fullName>
    <active>true</active>
    <label>Vital</label>
</RecordType>

force-app/main/tests/classes/Test_IntegrationVisitResultHandler.cls
/**
 * Created by Denis Z on 09-Jul-19.
 */

@IsTest
private class Test_IntegrationVisitResultHandler {

    @TestSetup
    static void setup() {
        Account acc = new Account();
        acc.Name = CommunityService.COMMUNITY_PARTICIPANT_ACCOUNT_NAME;
        insert acc;
        ParticipantEnrollmentFactory.createParticipantEnrollmentRecords('1','2','3');
        List<Participant_Study_Enrollment__c> pseList = [
                SELECT  Id,
                        External_Key__c
                FROM    Participant_Study_Enrollment__c
                WHERE   External_Key__c = '1~2~3'
        ];
        Patient_Visit__c visit = new Patient_Visit__c();
        visit.Name = 'New Visit';
        visit.Completed_Date__c = Date.today();
        visit.Participant_Study_Enrollment__c = pseList[0].Id;
        insert visit;
    }

    @IsTest
    static void visitResultsUpdateTest() {
        Test.startTest();
        Integration_VisitResult__c externalVisitResult = new Integration_VisitResult__c();
        externalVisitResult.USUBJID__c = '1~2~3';
        externalVisitResult.VISIT__c = 'New Visit';
        externalVisitResult.VSDTC__c = Date.today();
        externalVisitResult.TESTCD__c = 'RBC';
        externalVisitResult.Vital_or_Lab__c = 'Vital';
        externalVisitResult.STNRHI__c = 10;
        externalVisitResult.STUDYID__c = '10';
        externalVisitResult.IsDeletedInSDH__c = 'N';
        insert externalVisitResult;
        IntegrationVisitResultTriggerHandler.updateVisitResults(new List<Integration_VisitResult__c> {externalVisitResult});
        System.assertEquals(10, [SELECT Max_Value__c FROM Visit_Result__c][0].Max_Value__c);
        externalVisitResult = new Integration_VisitResult__c();
        externalVisitResult.USUBJID__c = '1~2~3';
        externalVisitResult.VISIT__c = 'New Visit';
        externalVisitResult.VSDTC__c = Date.today();
        externalVisitResult.TESTCD__c = 'RBC';
        externalVisitResult.Vital_or_Lab__c = 'Vital';
        externalVisitResult.STNRHI__c = 11;
        externalVisitResult.STUDYID__c = '10';
        externalVisitResult.IsDeletedInSDH__c = 'N';
        insert externalVisitResult;
        IntegrationVisitResultTriggerHandler.updateVisitResults(new List<Integration_VisitResult__c> {externalVisitResult});
        System.assertEquals(1, [SELECT COUNT() FROM Visit_Result__c]);
        externalVisitResult = new Integration_VisitResult__c();
        externalVisitResult.USUBJID__c = '1~2~3';
        externalVisitResult.VISIT__c = 'New Visit';
        externalVisitResult.VSDTC__c = Date.today();
        externalVisitResult.TESTCD__c = 'RBC';
        externalVisitResult.Vital_or_Lab__c = 'Vital';
        externalVisitResult.STNRHI__c = 11;
        externalVisitResult.STUDYID__c = '10';
        externalVisitResult.IsDeletedInSDH__c = 'Y';
        insert externalVisitResult;
        IntegrationVisitResultTriggerHandler.updateVisitResults(new List<Integration_VisitResult__c> {externalVisitResult});
        System.assertEquals(0, [SELECT COUNT() FROM Visit_Result__c]);
        Test.stopTest();
    }

}