force-app/main/default/objects/Integration_VisitResult__c/Integration_VisitResult__c.object-meta.xml
<CustomObject>
    <label>Integration VisitResult</label>
    <nameField>
        <label>Integration VisitResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration VisitResult</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_VisitResult__c/fields/STNRHI__c.field-meta.xml
<CustomField>
    <fullName>STNRHI__c</fullName>
    <label>STNRHI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/integration/objects/Integration_VisitResult__c/fields/STNRLO__c.field-meta.xml
<CustomField>
    <fullName>STNRLO__c</fullName>
    <label>STNRLO</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/STRESN__c.field-meta.xml
<CustomField>
    <fullName>STRESN__c</fullName>
    <label>STRESN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_VisitResult__c/fields/STRESU__c.field-meta.xml
<CustomField>
    <fullName>STRESU__c</fullName>
    <label>STRESU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/TESTCD__c.field-meta.xml
<CustomField>
    <fullName>TESTCD__c</fullName>
    <label>TESTCD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/VISIT__c.field-meta.xml
<CustomField>
    <fullName>VISIT__c</fullName>
    <label>VISIT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/integration/objects/Integration_VisitResult__c/fields/Vital_or_Lab__c.field-meta.xml
<CustomField>
    <fullName>Vital_or_Lab__c</fullName>
    <label>Vital_or_Lab</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vital</fullName>
            </value>
            <value>
                <fullName>Lab</fullName>
            </value>
            <value>
                <fullName>Biomarker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/VSDTC__c.field-meta.xml
<CustomField>
    <fullName>VSDTC__c</fullName>
    <label>VSDTC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Integration_VisitResult__c/fields/Work_Status__c.field-meta.xml
<CustomField>
    <fullName>Work_Status__c</fullName>
    <label>Work Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <formula>Study_ID__c + &quot;~&quot; + Study_Site__r.Study_Site_Number__c + &quot;~&quot; + Screening_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/Patient_Visit__c.object-meta.xml
<CustomObject>
    <label>Patient Visit</label>
    <nameField>
        <displayFormat>PV-{000000}</displayFormat>
        <label>Patient Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Visit__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Visit__c/fields/SDH_Key__c.field-meta.xml
<CustomField>
    <fullName>SDH_Key__c</fullName>
    <externalId>true</externalId>
    <label>SDH Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/visits/objects/Patient_Visit__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Patient Visits</relationshipLabel>
    <relationshipName>Patient_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/visits/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>SDH Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Result__c/Visit_Result__c.object-meta.xml
<CustomObject>
    <label>Visit_Result</label>
    <nameField>
        <displayFormat>VR-{0000000}</displayFormat>
        <label>Visit_Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit_Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Result__c/fields/Actual_Value__c.field-meta.xml
<CustomField>
    <fullName>Actual_Value__c</fullName>
    <label>Actual Result</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Max_Value__c</fullName>
    <label>Max Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/visits/objects/Visit_Result__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Min_Value__c.field-meta.xml
<CustomField>
    <fullName>Min_Value__c</fullName>
    <label>Min Value</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Patient_Visit__c.field-meta.xml
<CustomField>
    <fullName>Patient_Visit__c</fullName>
    <label>Patient Visit</label>
    <referenceTo>Patient_Visit__c</referenceTo>
    <relationshipLabel>Visit_Results</relationshipLabel>
    <relationshipName>Visit_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit_Result__c/fields/Result_Type__c.field-meta.xml
<CustomField>
    <fullName>Result_Type__c</fullName>
    <description>.</description>
    <label>Result Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/visits/objects/Visit_Result__c/recordTypes/Biomarker.recordType-meta.xml
<RecordType>
    <fullName>Biomarker</fullName>
    <active>true</active>
    <label>Biomarker</label>
</RecordType>

force-app/main/default/objects/Visit_Result__c/recordTypes/Lab.recordType-meta.xml
<RecordType>
    <fullName>Lab</fullName>
    <active>true</active>
    <label>Lab</label>
</RecordType>

force-app/main/default/objects/Visit_Result__c/recordTypes/Vital.recordType-meta.xml
<RecordType>
    <fullName>Vital</fullName>
    <active>true</active>
    <label>Vital</label>
</RecordType>

force-app/main/visits/objects/Visit_Result_TypeM__mdt/Visit_Result_TypeM__mdt.object-meta.xml
<CustomObject>
    <label>Visit Result Type</label>
    <pluralLabel>Visit Result Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Visit_Result_TypeM__mdt/fields/Visit_Result_Code__c.field-meta.xml
<CustomField>
    <fullName>Visit_Result_Code__c</fullName>
    <label>Visit Result Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/integration/classes/IntegrationVisitResultService.cls
/**
 * Created by Dmytro Pokutnii
 */
public with sharing class IntegrationVisitResultService {

    Map<String, Id> recordTypeIdsByNames;
    Map<String,Visit_Result_TypeM__mdt> resultTypesByCodes;

    public IntegrationVisitResultService() {
        this.recordTypeIdsByNames = this.getRecordTypeMap();
        this.resultTypesByCodes = this.getVisitResultTypesMap();
    }

    public void updateVisitResults(List<Integration_VisitResult__c> iResults){
        //If USUBJID, STUDYID, VISIT, VSDTC AND TESTCD ARE PRIMARY KEYS Exclude record if blank or NULL

        Set<String> externalKeys = this.getKeys(iResults);
        Map<String, Patient_Visit__c> visitsByExternalIds = this.getPatientVisitsMap(externalKeys);
        Map<String, Visit_Result__c> resultsByExternalIds = this.getVisitResultsMap(externalKeys);

        List<Visit_Result__c> newResults = new List<Visit_Result__c>();
        List<Visit_Result__c> resultsToDelete = new List<Visit_Result__c>();
        List<Visit_Result__c> resultsToUpdate = new List<Visit_Result__c>();

        for(Integration_VisitResult__c iResult : iResults){
            String codeResult = iResult.TESTCD__c.toUpperCase();
            if (resultTypesByCodes.containsKey(codeResult)) {
                String visitKey = iResult.USUBJID__c + iResult.VISIT__c + iResult.VSDTC__c;
                String key = visitKey + resultTypesByCodes.get(codeResult).DeveloperName;

                if(resultsByExternalIds.containsKey(key)){
                    Visit_Result__c result = resultsByExternalIds.get(key);
                    if(iResult.IsDeletedInSDH__c == 'N') {
                        resultsToUpdate.add(this.populateVisitResult(result, visitKey, iResult));
                    } else {
                        resultsToDelete.add(result);
                    }
                } else if(visitsByExternalIds.containsKey(visitKey)){
                    newResults.add(this.createNewResult(visitsByExternalIds.get(visitKey), visitKey, iResult));
                }
            }
        }

        update resultsToUpdate;
        delete resultsToDelete;
        insert newResults;
        update iResults;
    }

    private Visit_Result__c createNewResult(Patient_Visit__c visit, String externalId, Integration_VisitResult__c iResult){
        Visit_Result__c result = this.populateVisitResult(new Visit_Result__c(), externalId, iResult);
        result.Patient_Visit__c = visit.Id;
        return result;
    }

    private Map<String,Id> getRecordTypeMap(){
        return new Map<String, Id>{
                'Lab' => SchemaUtil.getRecordTypeIdByName('Lab', Visit_Result__c.getSObjectType()),
                'Vital' => SchemaUtil.getRecordTypeIdByName('Vital', Visit_Result__c.getSObjectType()),
                'Biomarker' => SchemaUtil.getRecordTypeIdByName('Biomarker', Visit_Result__c.getSObjectType())
        };
    }

    private Set<String> getKeys(List<Integration_VisitResult__c> results){

        Set<String> externalKeys = new Set<String>();
        for(Integration_VisitResult__c visitResult : results){
            visitResult.Work_Status__c = 'Failed';
            if(visitResult.USUBJID__c != null
                    && visitResult.STUDYID__c != null
                    && visitResult.VISIT__c != null
                    && visitResult.VSDTC__c != null
                    && visitResult.TESTCD__c != null){
                externalKeys.add(visitResult.USUBJID__c + visitResult.VISIT__c + visitResult.VSDTC__c);
            }
        }
        return externalKeys;
    }

    private Map<String,Visit_Result_TypeM__mdt> getVisitResultTypesMap(){

        List<Visit_Result_TypeM__mdt> resultTypes = [
                SELECT
                        DeveloperName,
                        Visit_Result_Code__c
                FROM    Visit_Result_TypeM__mdt
        ];
        Map<String,Visit_Result_TypeM__mdt> resultTypeMap = new Map<String,Visit_Result_TypeM__mdt>();
        for(Visit_Result_TypeM__mdt resultType : resultTypes){
            if(resultType.Visit_Result_Code__c != null) {
                for (String code : resultType.Visit_Result_Code__c.split(';')) {
                    resultTypeMap.put(code.toUpperCase(), resultType);
                }
            }
        }
        return resultTypeMap;
    }

    private Visit_Result__c populateVisitResult(Visit_Result__c result, String externalKey, Integration_VisitResult__c integrationVisitResult){

        result.Actual_Value__c = integrationVisitResult.STRESN__c;
        result.Max_Value__c = integrationVisitResult.STNRHI__c;
        result.Measurement__c = integrationVisitResult.STRESU__c;
        result.Min_Value__c = integrationVisitResult.STNRLO__c;
        result.RecordTypeId = this.recordTypeIdsByNames.get(integrationVisitResult.Vital_or_Lab__c);
        result.SDH_Key__c = externalKey;
        if(resultTypesByCodes.containsKey(integrationVisitResult.TESTCD__c.toUpperCase())){
            result.Result_Type__c = resultTypesByCodes.get(integrationVisitResult.TESTCD__c.toUpperCase()).DeveloperName;
        }
        integrationVisitResult.Work_Status__c = 'Success';
        integrationVisitResult.Processed__c = true;

        return result;
    }

    private Map<String, Visit_Result__c> getVisitResultsMap(Set<String> externalKeys){

        List<Visit_Result__c> visitResults = [
                SELECT
                        Id,
                        Actual_Value__c,
                        Max_Value__c,
                        Min_Value__c,
                        Measurement__c,
                        Result_Type__c,
                        Patient_Visit__r.Participant_Enrollment__r.External_Key__c,
                        Patient_Visit__r.Name,
                        Patient_Visit__r.Completed_Date__c,
                        SDH_Key__c
                FROM    Visit_Result__c
                WHERE   SDH_Key__c IN :externalKeys
        ];
        Map<String, Visit_Result__c> resultMap = new Map<String, Visit_Result__c>();
        for(Visit_Result__c result : visitResults){
            resultMap.put(result.SDH_Key__c + result.Result_Type__c, result);
        }
        return resultMap;
    }

    private Map<String, Patient_Visit__c> getPatientVisitsMap(Set<String> externalKeys){

        List<Patient_Visit__c> visits = [
                SELECT
                        Id,
                        Name,
                        Participant_Enrollment__r.External_Key__c,
                        Completed_Date__c,
                        SDH_Key__c
                FROM    Patient_Visit__c
                WHERE   SDH_Key__c IN : externalKeys
        ];
        Map<String, Patient_Visit__c> visitMap = new Map<String, Patient_Visit__c>();
        for(Patient_Visit__c visit : visits){
            visitMap.put(visit.SDH_Key__c, visit);
        }
        return visitMap;
    }
}