force-app/main/default/objects/Translation__c/Translation__c.object-meta.xml
<CustomObject>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Translation__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TranslationTriggerHandler.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class TranslationTriggerHandler {
    
    // Handlers: -------------------------------------------------------------------------------------------------------
    
    public class CheckFieldsConsistencyHandler extends TriggerHandler{
        
        public override void beforeInsert(List<SObject> newList) {
            checkFieldsConsistency(newList);
        }
        
        public override void beforeUpdate(List<SObject> newList, Map<Id, SObject> oldMap) {
            checkFieldsConsistency(newList);
        }
    }
    
    // Logic: ----------------------------------------------------------------------------------------------------------
    
    @TestVisible
    private static void checkFieldsConsistency(List<Translation__c> newList){
        List<DisplayType> supportedTypes = new List<DisplayType>{
                DisplayType.STRING,
                DisplayType.TEXTAREA
        };
        List<String> supportedLanguages = new List<String>();
        List<PicklistEntry> picklistEntries = User.LanguageLocaleKey.getDescribe().getPicklistValues();
        for (Schema.PicklistEntry picklistEntry : picklistEntries) supportedLanguages.add(picklistEntry.getValue());
    
        for (Translation__c translation : newList) {
            try {
                if(String.isEmpty(translation.Value__c)){
                    translation.Value__c.addError('Field: "' + Translation__c.Value__c + '" can not be empty');
                }
                Id recordId = Id.valueOf(translation.Record_Id__c);
                translation.Record_Id__c = recordId + '';
                translation.Object_Name__c = recordId.getSobjectType() + '';
                SObjectField sObjectField = recordId.getSobjectType().getDescribe().fields.getMap().get(translation.Field_Name__c);
                if (sObjectField == null) {
                    translation.Field_Name__c.addError('Field: "' + translation.Field_Name__c + '" not found for object: ' + recordId.getSobjectType());
                }else if(!supportedTypes.contains(sObjectField.getDescribe().getType())){
                    translation.Field_Name__c.addError('Unsupported field type. Only string fields are supported. Field type: ' + sObjectField.getDescribe().getType());
                }else if(sObjectField.getDescribe().isCalculated()){
                    translation.Field_Name__c.addError('Formula field not supported for translation');
                }
                translation.Field_Name__c = translation.Field_Name__c.toLowerCase();
                if(!supportedLanguages.contains(translation.Language__c)){
                    translation.Language__c.addError('Unsupported language, code: ' + translation.Language__c);
                }
            } catch (Exception e) {
                translation.Record_Id__c.addError(e.getMessage());
            }
        }
    }

}