force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit__c/Televisit__c.object-meta.xml
<CustomObject>
    <label>Televisit</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Televisit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Televisits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Call will be ended after the planned duration time</inlineHelpText>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>15 minutes</fullName>
            </value>
            <value>
                <fullName>30 minutes</fullName>
            </value>
            <value>
                <fullName>45 minutes</fullName>
            </value>
            <value>
                <fullName>60 minutes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Televisits</relationshipLabel>
    <relationshipName>Televisits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <label>Visit Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Visit_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_End_Date_Time__c</fullName>
    <label>Visit End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Visit_Link_Activation_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Link_Activation_End_Time__c</fullName>
    <formula>Visit_End_Date_Time__c  + ( (IF( ISBLANK(TEXT(Participant_Enrollment__r.Study_Site__r.Banner_Dispose_Offset_Time__c)) , 0 , VALUE(TEXT(Participant_Enrollment__r.Study_Site__r.Banner_Dispose_Offset_Time__c))))
/ 1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visit Link Activation End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Visit_Link_Activation_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Link_Activation_Start_Time__c</fullName>
    <formula>Visit_Date_Time__c  - (  Participant_Enrollment__r.Clinical_Trial_Profile__r.Banner_Display_Offset_Time__c /  1440)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Visit Link Activation Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/Televisit_Attendee__c.object-meta.xml
<CustomObject>
    <label>Televisit Attendee</label>
    <nameField>
        <label>Televisit Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Televisit Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit_Attendee__c/fields/Televisit__c.field-meta.xml
<CustomField>
    <fullName>Televisit__c</fullName>
    <label>Televisit</label>
    <referenceTo>Televisit__c</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TelevisitMeetBannerController.cls
public without sharing class TelevisitMeetBannerController {
    @AuraEnabled
    public static String getSessionId() {
        return UserInfo.getSessionId();
    }
    @AuraEnabled
    public static String getVisits() {
        Datetime currentDateTime = Datetime.now();
        Datetime next24HoursDateTime = Datetime.now().addHours(24);
        List<Televisit_Attendee__c > allVisitis = [select Televisit__r.Id,Televisit__r.Title__c,Televisit__r.Visit_Date_Time__c,
                    Televisit__r.Visit_Link_Activation_End_Time__c,Televisit__r.Visit_Link_Activation_Start_Time__c,Televisit__r.Meeting_URL__c,
                    Televisit__r.Participant_Enrollment__r.Participant_Name__c,Televisit__r.Duration__c,Televisit__r.Visit_End_Date_Time__c
                    from Televisit_Attendee__c where User__c  =:UserInfo.getUserId() and Televisit__r.Visit_Link_Activation_End_Time__c >=:currentDateTime 
                    and Televisit__r.Visit_Link_Activation_End_Time__c <=:next24HoursDateTime 
                    and Televisit__r.Status__c = 'Scheduled'];

        return JSON.serialize(allVisitis);
    }
    @AuraEnabled
    public static String getUserTimeZoneOffset() {
        TimeZone tzone = UserInfo.getTimeZone();
        //Milliseconds to Day
        //return String.valueOf(tzone.getOffset(DateTime.now()) / (1000 * 3600 * 24.0));
        return String.valueOf(tzone);
    }
}