force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Participant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
    <relationshipName>PE_Participant_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit__c/Televisit__c.object-meta.xml
<CustomObject>
    <label>Televisit</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Televisit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Televisits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>Call will be ended after the planned duration time</inlineHelpText>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>15 minutes</fullName>
            </value>
            <value>
                <fullName>30 minutes</fullName>
            </value>
            <value>
                <fullName>45 minutes</fullName>
            </value>
            <value>
                <fullName>60 minutes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Participant_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Participant_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Televisits</relationshipLabel>
    <relationshipName>Televisits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/Televisit_Attendee__c.object-meta.xml
<CustomObject>
    <label>Televisit Attendee</label>
    <nameField>
        <label>Televisit Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Televisit Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Televisit_Attendee__c/fields/Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Type__c</fullName>
    <label>Attendee Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Televisit_Attendee__c/fields/Televisit__c.field-meta.xml
<CustomField>
    <fullName>Televisit__c</fullName>
    <label>Televisit</label>
    <referenceTo>Televisit__c</referenceTo>
    <relationshipLabel>Televisit Attendee</relationshipLabel>
    <relationshipName>Televisit_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/tests/classes/Test_TelevisitAttendeeTriggerHandler.cls
@IsTest
public class Test_TelevisitAttendeeTriggerHandler {
    @IsTest
    static void taskTest()
    {
        TestData.loadTestData();
        TestData testData = new TestData();
        Televisit_Attendee__c taObj = new Televisit_Attendee__c();
                Televisit_Attendee__c taObj1 = new Televisit_Attendee__c();

        Televisit__c televisitRecord = new Televisit__c();
        televisitRecord.Title__c = 'title';
        televisitRecord.Duration__c='15 minutes';
        televisitRecord.Status__c='Scheduled';
        televisitRecord.Participant_Enrollment__c = testData.pe.Id;
        insert televisitRecord;
        taObj.Attendee_Type__c='Participant';
        taObj.Televisit__c = televisitRecord.Id;
        taObj.Contact__c =  testData.pe.Participant_Contact__c;
        insert taObj;
        taObj1.Attendee_Type__c='PI';
        taObj1.Televisit__c = televisitRecord.Id;
        taObj1.Contact__c =  testData.pe.Participant_Contact__c;
        insert taObj1;
                        Televisit_Attendee__c taObj2 = new Televisit_Attendee__c();
         taObj2.Attendee_Type__c='PI';
        taObj2.Televisit__c = televisitRecord.Id;
        taObj2.Contact__c =  testData.pe.Participant_Contact__c;
        insert taObj2;
delete taObj2;
        TelevisitAttendeeTriggerHandler.ManageAttendees manageAttendee = new TelevisitAttendeeTriggerHandler.ManageAttendees();
        manageAttendee.afterDelete(new List<Televisit_Attendee__c>{taObj,taObj1,taObj2});
        manageAttendee.afterInsert(new List<Televisit_Attendee__c>{taObj,taObj1});
        TelevisitAttendeeTriggerHandler.TelevisitEventTrigger teTrigger = new TelevisitAttendeeTriggerHandler.TelevisitEventTrigger();
        teTrigger.afterInsert(new List<Televisit_Attendee__c>{taObj,taObj1});
        TelevisitAttendeeTriggerHandler.TelevisitAttendeeTrigger taTrigger = new TelevisitAttendeeTriggerHandler.TelevisitAttendeeTrigger();
        taTrigger.afterDelete(new List<Televisit_Attendee__c>{taObj,taObj1,taObj2});
                taTrigger.afterInsert(new List<Televisit_Attendee__c>{taObj,taObj1});

        
    }
}