force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Permit_IQVIA_to_contact_about_study__c.field-meta.xml
<CustomField>
    <fullName>Permit_IQVIA_to_contact_about_study__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked when share the above information with IQVIA and its affiliates checkbox is checked in the front end</inlineHelpText>
    <label>Permit personal information storage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Permit_Mail_Email_contact_for_this_study__c.field-meta.xml
<CustomField>
    <fullName>Permit_Mail_Email_contact_for_this_study__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permit Mail-Email contact for this study</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Permit_SMS_Text_for_this_study__c.field-meta.xml
<CustomField>
    <fullName>Permit_SMS_Text_for_this_study__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permit SMS/Text for this study</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Permit_Voice_Text_contact_for_this_study__c.field-meta.xml
<CustomField>
    <fullName>Permit_Voice_Text_contact_for_this_study__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permit voice call for this study</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Email_Consent_Time__c.field-meta.xml
<CustomField>
    <fullName>Study_Email_Consent_Time__c</fullName>
    <label>Study Email Consent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_Phone_Consent_Time__c.field-meta.xml
<CustomField>
    <fullName>Study_Phone_Consent_Time__c</fullName>
    <label>Study Phone Consent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_PI_Storage_Consent_Time__c.field-meta.xml
<CustomField>
    <fullName>Study_PI_Storage_Consent_Time__c</fullName>
    <label>Study PI Storage Consent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Study_SMS_Consent_Time__c.field-meta.xml
<CustomField>
    <fullName>Study_SMS_Consent_Time__c</fullName>
    <label>Study SMS Consent Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/tests/classes/Batch_UpdatetimestampsforexistingPERTest.cls
@isTest
public with sharing class Batch_UpdatetimestampsforexistingPERTest {
    @isTest
    public static void test(){
        TestData.loadTestData();
        TestData testData = new TestData();
        Participant_Enrollment__c pe = new Participant_Enrollment__c();
        pe.id = testData.pe.Id;
        pe.Permit_Mail_Email_contact_for_this_study__c = true;
        pe.Permit_Voice_Text_contact_for_this_study__c = true;
        pe.Permit_SMS_Text_for_this_study__c = true;
        pe.Permit_IQVIA_to_contact_about_study__c = true;
        pe.Study_Email_Consent_Time__c = null;
        pe.Study_Phone_Consent_Time__c = null;
        pe.Study_SMS_Consent_Time__c = null;
        pe.Study_PI_Storage_Consent_Time__c = null;
        TriggerHandlerExecutor.bypassHandler(ParticipantEnrollmentTriggerHandler.StudyConsentTimestamps.class);
        update pe;
        Participant_Enrollment__History[] ah =  [Select ParentId, Field, OldValue, NewValue from Participant_Enrollment__History where ParentId = :pe.Id limit 200];
        system.debug('++++++++'+ah.size());
        Batch_UpdatetimestampsforexistingPER batch = new Batch_UpdatetimestampsforexistingPER();
        database.executeBatch(batch, 200);
    }
}