force-app/main/default/objects/Participant_Enrollment__c/Participant_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Participant Profile</description>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment__c/fields/Informed_Consent__c.field-meta.xml
<CustomField>
    <fullName>Informed_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Did the Potential Participant provide informed consent?</inlineHelpText>
    <label>Informed Consent</label>

    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Last_Status_Changed_Notes__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Changed_Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Status Changed Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Non_Enrollment_Reason__c.field-meta.xml
<CustomField>
    <fullName>Non_Enrollment_Reason__c</fullName>
    <label>Non-Enrollment Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Participant_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Site No Longer Accepting Referrals</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Meet Pre-Screening Eligibility</fullName>
            </value>
            <value>
                <fullName>Declined Practitioner</fullName>
            </value>
            <value>
                <fullName>PI Decision</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Show For Initial Visit</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Sign Consent</fullName>
            </value>
            <value>
                <fullName>Failed Inclusion/Exclusion Criteria</fullName>
            </value>
            <value>
                <fullName>Patient Declined</fullName>
            </value>
            <value>
                <fullName>Visit Out Of Window</fullName>
            </value>
            <value>
                <fullName>Patient Decision</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Ready to Schedule</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Transportation Issues</fullName>
            </value>
            <value>
                <fullName>Childcare Issues</fullName>
            </value>
            <value>
                <fullName>Participant Not Interested</fullName>
            </value>
            <value>
                <fullName>Did Not Meet Inclusion/Exclusion Criteria</fullName>
            </value>
            <value>
                <fullName>Did Not Attend Appointment</fullName>
            </value>
            <value>
                <fullName>Left a Message</fullName>
            </value>
            <value>
                <fullName>Protocol Concerns</fullName>
            </value>
            <value>
                <fullName>Inadequate Documentation</fullName>
            </value>
            <value>
                <fullName>Does Not Meet Eligibility Criteria</fullName>
            </value>
            <value>
                <fullName>Could not schedule visit</fullName>
                <isActive>false</isActive>
                <label>Could not schedule visit</label>
            </value>
            <value>
                <fullName>Declined or Withdrew Consent</fullName>
                <isActive>false</isActive>
                <label>Declined or Withdrew Consent</label>
            </value>
            <value>
                <fullName>Did not respond to contact attempts</fullName>
                <isActive>false</isActive>
                <label>Did not respond to contact attempts</label>
            </value>
            <value>
                <fullName>Failed screening / does not qualify</fullName>
                <isActive>false</isActive>
                <label>Failed screening / does not qualify</label>
            </value>
            <value>
                <fullName>No longer interested</fullName>
                <isActive>false</isActive>
                <label>No longer interested</label>
            </value>
            <value>
                <fullName>No show for scheduled visit</fullName>
                <isActive>false</isActive>
                <label>No show for scheduled visit</label>
            </value>
            <value>
                <fullName>Not eligible</fullName>
                <isActive>false</isActive>
                <label>Not eligible</label>
            </value>
            <value>
                <fullName>Not willing to sign informed consent</fullName>
                <isActive>false</isActive>
                <label>Not willing to sign informed consent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status__c</fullName>
    <description>HCP/Physician Participant Participant Status</description>
    <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
    <label>Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Failed Referral</fullName>
            </value>
            <value>
                <fullName>Failed Review</fullName>
            </value>
            <value>
                <fullName>Excluded from Referring</fullName>
            </value>
            <value>
                <fullName>Eligibility Passed</fullName>
            </value>
            <value>
                <fullName>Eligibility Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress</fullName>
            </value>
            <value>
                <fullName>Screening Failed</fullName>
            </value>
            <value>
                <fullName>Enrollment Success</fullName>
            </value>
            <value>
                <fullName>Enrollment Failed</fullName>
            </value>
            <value>
                <fullName>Treatment Period Started</fullName>
            </value>
            <value>
                <fullName>Follow-Up Period Started</fullName>
            </value>
            <value>
                <fullName>Participation Complete</fullName>
            </value>
            <value>
                <fullName>Trial Complete</fullName>
            </value>
            <value>
                <fullName>Drop Out</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Successfully Contacted</fullName>
            </value>
            <value>
                <fullName>Contact Attempted</fullName>
            </value>
            <value>
                <fullName>Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Contacted - Not Suitable</fullName>
            </value>
            <value>
                <fullName>Screening Passed</fullName>
            </value>
            <value>
                <fullName>Unable to Screen</fullName>
            </value>
            <value>
                <fullName>Randomization Success</fullName>
            </value>
            <value>
                <fullName>Randomization Failed</fullName>
            </value>
            <value>
                <fullName>Screening In Progress - Wash Out Period</fullName>
                <label>In Wash Out Period</label>
            </value>
            <value>
                <fullName>Ready to Screen</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent</fullName>
            </value>
            <value>
                <fullName>Declined Consent</fullName>
            </value>
            <value>
                <fullName>Withdrew Consent After Screening</fullName>
            </value>
            <value>
                <fullName>Declined Final Consent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant_Enrollment__c/fields/Participant_Status_Last_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Participant_Status_Last_Changed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Participant Status Last Changed Date</label>

    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/Participant_Enrollment_Status_History__c.object-meta.xml
<CustomObject>

    <label>Participant Enrollment Status History</label>
    <nameField>
        <displayFormat>PESH-{0000000}</displayFormat>
        <label>Participant Enrollment Status History Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollment Status History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/NewStatus__c.field-meta.xml
<CustomField>
    <fullName>NewStatus__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NewStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant_Enrollment_Status_History__c/fields/Non_Enrollment_Reason__c.field-meta.xml
<CustomField>
    <fullName>Non_Enrollment_Reason__c</fullName>
    <label>Non-Enrollment Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Site No Longer Accepting Referrals</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Meet Pre-Screening Eligibility</fullName>
            </value>
            <value>
                <fullName>Declined Practitioner</fullName>
            </value>
            <value>
                <fullName>PI Decision</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Show For Initial Visit</fullName>
            </value>
            <value>
                <fullName>Didn&apos;t Sign Consent</fullName>
            </value>
            <value>
                <fullName>Failed Inclusion/Exclusion Criteria</fullName>
            </value>
            <value>
                <fullName>Patient Declined</fullName>
            </value>
            <value>
                <fullName>Visit Out Of Window</fullName>
            </value>
            <value>
                <fullName>Patient Decision</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Ready to Schedule</fullName>
            </value>
            <value>
                <fullName>Call Back</fullName>
            </value>
            <value>
                <fullName>Transportation Issues</fullName>
            </value>
            <value>
                <fullName>Childcare Issues</fullName>
            </value>
            <value>
                <fullName>Participant Not Interested</fullName>
            </value>
            <value>
                <fullName>Did Not Meet Inclusion/Exclusion Criteria</fullName>
            </value>
            <value>
                <fullName>Did Not Attend Appointment</fullName>
            </value>
            <value>
                <fullName>Left a Message</fullName>
            </value>
            <value>
                <fullName>Protocol Concerns</fullName>
            </value>
            <value>
                <fullName>Inadequate Documentation</fullName>
            </value>
            <value>
                <fullName>Does Not Meet Eligibility Criteria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Participant_Enrollment_Status_History__c/fields/ParticipantEnrollment__c.field-meta.xml
<CustomField>
    <fullName>ParticipantEnrollment__c</fullName>
    <label>Participant Enrollment</label>
    <referenceTo>Participant_Enrollment__c</referenceTo>
    <relationshipLabel>Participant Enrollment Status History</relationshipLabel>
    <relationshipName>Participant_Enrollment_Status_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/triggers-implementation/classes/ParticipantEnrollmentSHTriggerHandler.cls
/**
 * Created by Kryvolap
 */

public without sharing class ParticipantEnrollmentSHTriggerHandler {

    //Handlers----------------------------------------------------------------------------------------------------------
    public class SendPESHToEPR extends TriggerHandler {

        public override void afterInsert(List<SObject> newList) {
            sendToEPR(newList);
        }
    }

    public class UpdatePEHandler extends TriggerHandler {

        public override void beforeInsert(List<SObject> newList) {
            updateEnrollmentStatus((List<Participant_Enrollment_Status_History__c>) newList);
        }
    }

    //Logic-------------------------------------------------------------------------------------------------------------
    private static void sendToEPR(List<Participant_Enrollment_Status_History__c> newList) {
        List<Id> ids = new List<Id>();
        for (Participant_Enrollment_Status_History__c obj : newList) {
            ids.add(obj.Id);
        }
        IntegrationService.sendPESHToEPRAsync(ids);
    }

    @TestVisible
    private static void updateEnrollmentStatus(List<Participant_Enrollment_Status_History__c> histories) {
        Set<Id> peIds = new Set<Id>();
        Map<Id, List<Participant_Enrollment_Status_History__c>> peToHistories =
                new Map<Id, List<Participant_Enrollment_Status_History__c>>();

        for (Participant_Enrollment_Status_History__c history : histories) {
            if(history.NewStatus__c == PEStatusState.PE_STATUS_REFERRAL_SENT_TO_PI) continue;

            Id peId = history.ParticipantEnrollment__c;
            peIds.add(peId);

            if (!peToHistories.containsKey(peId)) {
                peToHistories.put(peId, new List<Participant_Enrollment_Status_History__c>());
            }
            peToHistories.get(peId).add(history);
        }

        List<Participant_Enrollment__c> enrollments = [
                SELECT Id,
                        Informed_Consent__c,
                        Last_Status_Changed_Notes__c,
                        Non_Enrollment_Reason__c,
                        Participant_Status__c,
                        Participant_Status_Last_Changed_Date__c
                FROM Participant_Enrollment__c
                WHERE Id IN:peIds
        ];
        for (Participant_Enrollment__c pe : enrollments) {
            String largerStatus = pe.Participant_Status__c;
            Integer largerStatusValue = PEStatusState.PE_ORDERED_STATUSES.get(largerStatus);
            for (Participant_Enrollment_Status_History__c history : peToHistories.get(pe.Id)) {
                Integer historyStatusValue = PEStatusState.PE_ORDERED_STATUSES.get(history.NewStatus__c);
                if (largerStatusValue != Math.max(largerStatusValue, historyStatusValue)) {
                    largerStatus = history.NewStatus__c;
                    largerStatusValue = historyStatusValue;

                    pe.Last_Status_Changed_Notes__c = history.Notes__c;
                    pe.Non_Enrollment_Reason__c = history.Reason__c;
                    pe.Participant_Status_Last_Changed_Date__c = history.Date__c;
                }
            }
            pe.Participant_Status__c = largerStatus;
            if(largerStatus == PEStatusState.PE_STATUS_ENROLLMENT_SUCCESS) pe.Informed_Consent__c = true;
        }

        update enrollments;
    }
}